### ISSUE TITLE
cfcr/k8s - uaa oidc

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#100]
### Expected behavior

As a Cf operator, I expect to log in to K8S dashboard using my UAA account

### Observed behavior

As a Cf operator, I currently log in and act with instead of a shared admin token

### Affected release

Reproduced on version 33.0

### references
- https://medium.com/@mrbobbytables/kubernetes-day-2-operations-authn-authz-with-oidc-and-a-little-help-from-keycloak-de4ea1bdbbe

**Comment by obeyler** [comment]
issue on cfcr-24
https://github.com/cloudfoundry-incubator/kubo-release/issues/275

**Comment by poblin-orange** [comment]
cfcr 25 merged in v37
