### ISSUE TITLE
k8s based implementation (daemon set) for static routing

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1004]
### Expected behavior

* As a paas-templates paas-templates maintainer
* In order to 
  - have a robust way to apply tcp static route on an instance group
* I need 
  - a bosh release capturing the scripts required to add / remove routes based on lifecycle.

### Observed behavior
As of v48
- the networking bosh release exist, but has issues
- the generic scripting bosh release is used in paas-templates, but diverging implementations per deployment, causing hidden issues (route not cleaned at monit stop time, preventing following monit start) 

### Affected releases

* x.y
* earlier versions

**Comment by ogrand** [comment]
**TODO**
- [x] Create bosh release networking
- [x] Replace old networkink bosh release and scripting release with new bosh release

**Comment by poblin-orange** [comment]
Consider using k8s daemonset for k8s level host routing preparation
see https://github.com/jkwong888/k8s-add-static-routes

**Comment by gberche-orange** [comment]
Discussed during backlog review the risk of circular dependencies preventing the K8S cluster from starting if the node host routing isn't effective (e.g. jcr/harbor, dns recursion, ...)

**Comment by poblin-orange** [comment]
fixed on 00-core-connectivity by https://github.com/orange-cloudfoundry/paas-templates-private/pull/1850
