### ISSUE TITLE
Per platform Osb-cmdb metadata field to service providers

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1007]
### Expected behavior

* As a 3rd party osb service provider 
* In order to distinguish service instances receives from distinct osb-cmdb instances (e.g. integration/preprod/prod)
* I need a metadata field to distinguish them
   * such as `x-osb-cmdb.annotations.brokered_service_cmdb_url` with the osb-cmdb broker url which is unique among all platforms (as exposed on the intranet)

### Observed behavior

The ` x-osb-cmdb.annotations.brokered_services_client_name` is configured to be consistent among  integration/preprod/prod environments (for service providers relying on it programmatically)

/CC @gcordierOrange 

### Affected releases

* 49.0.1
* earlier versions

**Comment by gberche-orange** [comment]
@poblin-orange any other alternative suggestion to the cmdb broker url (which might create confusion to service consummers and increase its exposure whereas only service providers should use it) ?

/CC @mlesaout

**Comment by gberche-orange** [comment]
Alternatives to metadata:
* distinct service providers broker endpoints by Osb-cmdb environment (integration, preprod, prod)
* distinct service providers broker credentials by Osb-cmdb environment (integration, preprod, prod)

**Comment by poblin-orange** [comment]
osbcmdb ops should require at least different credentials for (integration/preprod/prod). @CDallosto-orange @gcordierOrange
