### ISSUE TITLE
bosh nats cert rotation

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#102]
### Expected behavior
As a platform operator, knowing that bosh nats certs are valid for 1 year, i want to be able to rotate the certs in a reliable way

### references
- https://github.com/cloudfoundry/docs-bosh/pull/540
- #84

**Comment by gberche-orange** [comment]
NATS TLS should be introduced in v34, so planned expiration for 1st platform should happen in sep 2019

**Comment by poblin-orange** [comment]
final doc is in bosh.io https://bosh.io/docs/nats-ca-rotation/
