### ISSUE TITLE
mysql shared not accepting more connexions

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1021]
### Expected behavior

* As a paas-templates operator | marketplace user
* In order to connect to the shared instance 
* I need to have more open file limit

### Observed behavior
Error in log : 
```
{"timestamp":"1606208296.228882074","source":"/var/vcap/packages/switchboard/bin/switchboard","message":"/var/vcap/packages/switchboard/bin/switchboard.Error accepting client connection","log_level":2,"data":{"error":"accept tcp 0.0.0.0:3306: accept4: too many open files"}}
```
### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
many TIME_WAIT on proxy switch board vms.
raised ulimit to 4K
=> reaching scalability limits

**Comment by CDallosto-orange** [comment]
manually raised ulimit nofile to 4K 3306 for all user (*)

**Comment by gcordierOrange** [comment]
https://community.pivotal.io/s/article/pivotal-application-services-internal-mysql-proxy-reports-error-too-many-open-files?language=en_US

**Comment by CDallosto-orange** [comment]
The limit is overloaded in `/var/vcap/jobs/proxy/bin/switchboard_ctl` => ulimit -n 3000
Manually raised to 6000

**Comment by gberche-orange** [comment]
Bump to 8000 file descriptors in production in branch `feature-extend-mysql-osb-proxy-limit` was integrated in 3d6441e3a5a12f7907453462dce78bd30b61bb4d in branch #893 from orange-cloudfoundry/feature-clean-ocb-services
