### ISSUE TITLE
micro-depls/docker-bosh-cli update failure

### ISSUE THREAD

**Issue by amoussa2589** [orange-cloudfoundry/paas-templates#1023]
### Expected behavior

* As a paas-templates operator paas-templates author 
* In order to modify the public key to access to the docker-boshcli integration plateform
* I need to launch deploy-docker-bosh-cli without error

### Observed behavior
 Error: 'docker-cli is not running after update. Review logs for failed jobs: ops_portal

### Affected releases

* 49.0.0
* earlier versions

**Comment by poblin-orange** [comment]
docker process leaks prevents proper bosh stop ?

**Comment by poblin-orange** [comment]
root cause is https://github.com/orange-cloudfoundry/paas-templates/issues/879
