### ISSUE TITLE
Loki label-based log database

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1027]
### Expected behavior

* As a paas-templates operator
* In order to correlate metrics with logs entries per time/labels
* In order to store control plane logs (as a workaround for logsearch scalability issue)
* I need a label-based log database such as loki

### Observed behavior
 
ELK/Log search (full-text search indexing) 
* provide full-text search suiteable for searching from an observed symptom (e.g. a stack trace/error content)
* does not yet provide support for correlating prometheus-based labels (time, labels)

### Affected releases

* 49.x
* earlier versions

### References

https://grafana.com/oss/loki/
https://github.com/grafana/loki

Prometheus & open metrics session at CfSummit EU 2020
  * Video: https://www.youtube.com/watch?v=9sQvVfgBykU 
  * Slides: https://static.sched.com/hosted_files/cfeu2020/25/Observability%20with%20Prometheus%20and%20beyond.pdf
  * Transcript: https://static.sched.com/hosted_files/cfeu2020/d4/Text_Transcript_WLBR-9821.pdf 

https://www.infracloud.io/blogs/grafana-loki-log-monitoring-alerting
https://www.scaleway.com/en/docs/use-loki-to-manage-k8s-application-logs/

**Comment by poblin-orange** [comment]
considering workload to bump logsearch (bionic compat issue), raising this priority, might fit ops team for scalable ops logs management

**Comment by gberche-orange** [comment]
Reopening as https://github.com/orange-cloudfoundry/paas-templates-private/pull/901 did not resolve all tasks

**Comment by poblin-orange** [comment]
54. loki activated with promtail, collecting vm logs with syslog and k8s logs with promtail
closing
