### ISSUE TITLE
Add redis client to docker bosh-cli

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1028]
### Expected behavior

* As a paas-templates operator | paas-templates author | paas-templates maintainer
* In order to connect to a redis instane
* I need to have redis-cli command

### Observed behavior
 No client available
Add v6 cli, if possible

### Affected releases

* 48.0
* earlier versions

**Comment by gcordierOrange** [comment]
v6 cli seems work with the v5 redis deployment.

**Comment by ogrand** [comment]
Done in docker-bosh-cli for v50
