### ISSUE TITLE
mysql service - Lacks HA for switchboard proxies (SPOF)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#103]
### Expected behavior
As on operator, I'd expect no SPOF on the marketplace mysql access layer

### Observed behavior
Only a single switchboard proxy is used. Miss a ha mechanism:
- iaas level loadbalancer to the 2 switchbord, exclusive mode (no sync between the switchboard, this could result in different "master" galera vm used)
- keep alived vrrp mechnism, so a single VIP is served by the 2 switchboard. see https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/docs/keepalived.md

### Affected release
Reproduced on version 33

**Comment by poblin-orange** [comment]
TODO: check if same spof between diego and bbs db in master-depls/cloudfoundry-datastore

**Comment by regismarg** [comment]
vip with vrrp between vms ?
start with service shared

**Comment by poblin-orange** [comment]
Note: on flexible engine, the openstack loadbalancer.
vrrp can be used on shared p-mysql
vrrp is hard to set on COAB services (no bosh pam for vrrp vip)
alternate solution: use bosh-dns

**Comment by JCL38-ORANGE** [comment]
Merged in v43.
