### ISSUE TITLE
Remove vault certificates from coab instances

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1035]
### Expected behavior

* As a paas-templates operator
* In order to manage distribution certificates maintenability
* I need to remove unused certs

### Observed behavior

When creating coab instances from each type (redis, mysql, rabitmq, mongodb...), I see that unused `vault-ca` and `vault-tls` are generated.
 
### Affected releases

* all

### Traces and logs
```
- 2021-10-09: /bosh-coab/t_4ac682f4-b260-43a8-86eb-bc364f3a5747/vault-ca
- 2021-10-09: /bosh-coab/t_4ac682f4-b260-43a8-86eb-bc364f3a5747/vault-tls
- 2021-10-14: /bosh-coab/m_aef1e89d-cb6b-4a3e-b1e0-4fa911b50592/vault-ca
- 2021-10-14: /bosh-coab/m_aef1e89d-cb6b-4a3e-b1e0-4fa911b50592/vault-tls
- 2021-05-05: /bosh-coab/r_79678d9a-9b91-47ef-bf1e-6abc3c88ecfe/vault-ca
- 2021-05-05: /bosh-coab/r_79678d9a-9b91-47ef-bf1e-6abc3c88ecfe/vault-tls
...
```

**Comment by JCL38-ORANGE** [comment]
They are used by shield embedded in order to crypt/uncrypt backups.
