### ISSUE TITLE
coab rabbit and redis metrics not collected

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#1036]
### Expected behavior

* As a paas-templates operator
* In order to have a dashboard for monitoring rabbit coab
* I need to collect metrics from rabbit coab

### Observed behavior
No metrics are collected, but rabbit exporter are deployed with the service.
 
### Affected releases

* 48.0.2

**Comment by JCL38-ORANGE** [comment]
it will be delivered in v50
