### ISSUE TITLE
multi-region dedicated rabbitmq

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1038]
### Expected behavior

* As a marketplace user
* In order to 
  * support HA rabbitmq in the marketplace
* I need 
  * a new extended rabbitmq service 

### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
closed because duplicate of https://github.com/orange-cloudfoundry/paas-templates/issues/1088
