### ISSUE TITLE
Paas-templates access layer refactoring

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1039]
# Paas-templates acces layer refactoring 
  
## K8s updated migration status

**Legend:**
**I** : k8s feature installed (but not used)
**A** : k8s feature activated
**D** : bosh feature deactivated

| feature                    | Cluster | INT     | v50  | v51  | v52 | v53  | PR  |
| -------------------- | ------- | ------ | ----- | ---- | ---- | ---- | ---- |
| rancher-ui               | gitops  | A        | I/A   | A      | A    | A     |
| stratos                    | gitops  | A        | I/A   | A      | A    | A     |
| bosh ops-relay        |            | A        | A     | D      | D    | D     |
| metallb private vips | core     | I         | -      | I/A    | A     | A     | [705](https://github.com/orange-cloudfoundry/paas-templates-private/pull/705) |
| metallb public vips   | core    | I         | -      | I/A    | A     | A     | [695](https://github.com/orange-cloudfoundry/paas-templates-private/pull/695) |
| traefik 2 sni for ops  | core    | A        | -      | I/A #1097 #1078  | A  |  A  | [634](https://github.com/orange-cloudfoundry/paas-templates-private/pull/634) [572](https://github.com/orange-cloudfoundry/paas-templates-private/pull/572)  |
| intranet squid k8s   | core     | I         | -      | I/A     | A    | A     | [623](https://github.com/orange-cloudfoundry/paas-templates-private/pull/623) [700](https://github.com/orange-cloudfoundry/paas-templates-private/pull/700)|
| internet squid k8s   | core     | I         | -      | I/A     | A    | A     | [704](https://github.com/orange-cloudfoundry/paas-templates-private/pull/704) |
| jcr k8s                     | core     |  A      | -      | I/A     | A/D | A  | [582](https://github.com/orange-cloudfoundry/paas-templates-private/pull/582)  [680](https://github.com/orange-cloudfoundry/paas-templates-private/pull/680) [697](https://github.com/orange-cloudfoundry/paas-templates-private/pull/697) |
| gitlab k8s                | ci         | A         | -      | I/A    | A/D | A  | [620](https://github.com/orange-cloudfoundry/paas-templates-private/pull/620)  [681](https://github.com/orange-cloudfoundry/paas-templates-private/pull/681) |
| - k8s coa  repo        |            | A         | -      | I/A    | A    | A   | 
| - k8s secrets repo    |            | A         | -      | I/A    | A    | A   |
| - k8s template repo |            | github | -      | I/A    | A    | A   |
| minio k8s                | ci         | A         | -      | I/A   | A/D | A   | [648](https://github.com/orange-cloudfoundry/paas-templates-private/pull/648) [627](https://github.com/orange-cloudfoundry/paas-templates-private/pull/627) [674](https://github.com/orange-cloudfoundry/paas-templates-private/pull/674) |
| concourse k8s         | ci         | I          | -      | I/A    | A     | A   | [626](https://github.com/orange-cloudfoundry/paas-templates-private/pull/626)  |
| openldap k8s          | ci         | A         | -      | I/A    | A    | A    | [621](https://github.com/orange-cloudfoundry/paas-templates-private/pull/621) [698](https://github.com/orange-cloudfoundry/paas-templates-private/pull/698)  |

https://docs.google.com/spreadsheets/d/1a9qcc4H1orZlUdRsdgNwRCOYwh46GmoruAI5OeG73rM/edit#gid=0

**paas-templates update to switch:**

- option 1: refactor all url dns with credhub secrets
  - ok with bosh
  - ko with cf apps / terraform 
  
- option 2: with individuals feature branche ? => too complex to apply by ops teams

- option 3: with default code to template, and profile to reenable bosh legacy => (Most convenient, but risky / ops team 

- option 4 (chosen): with activation profile per product activation

install 51
    bump bosh releases
    bump concourse 7.1.x
    bump stemcells
    create target k8s deployments

post-install 51
  - **51-switch-to-k8s-traefik** (pré requis, permet le routage SNI vers les autres composants)
  - **51-switch-to-k8s-openldap** (ldif à réimporter)
  - **51-switch-internet-proxy**
  - **51-switch-intranet-proxy**
  - **51-switch-to-k8s-minio** (change coa-config). bosh errand to copy legacy datas
  - **51-switch-to-k8s-jcr**  (change coa-config). no data (cache)
  - **51-switch-to-k8s-jcr-for-docker-k3s**
  - **51-switch-to-k8s-gitlab** (change coa-config/coab secrets), must import secrets repo snapshot (concourse paused, coab read-only)
  - **54-switch-to-k8s-concourse**

## Context  
  
> What is the issue that we're seeing that is motivating this decision or change?  
  
*   SPOF on relay vms (singletons, no vrrp). Downtimes during upgrades, impact limited by upgrade being orchestrated by upgrade pipeline
    *   control plane (HTTP/HTTPS, gRPC HTTP/2)
        *   inbound
            *   wildcard http(s) domains (pki certs)
                *   api
                *   ops
                *   osb
            *   ssh: docker bosh cli access
            *   internal traffic to internal components accessed through a public intranet url (ops domain)
                *   jcr (docker registry has same hostname as ui)
                *   gitlab
                *   minio s3 (public https / private internal.paas http or https)
                *   brokers COAB (api relay)
        *   outbound http proxy
            *   intranet relay
            *   internet relay

*   data plane ==> out of scope ? different additional requirements:
        *   latency impact
        *   capacity management / volume ...
        *   additional protocols: 
            *   tls, sni routing
            *   tcp

  *   protocol limitations with current fixed DNS (wildcard) entries and use of standard TCP ports (80/443)
      *   no http 2 / grpc
        *   k8s api not exposable through gorouters.
        *   k8s => rancher-ui (behind gorouter)
*   https offload is shared/centralized (gorouter)
    *   +: no dissemination/duplicated configuration of intranet FQDN certs
    *   \-: weak security: missing end to end encrypted communication (end to end tls) ?
*   inconsistent technical architecture across Iaas infrastructures
    *   openstack. VPC and peering
        *   peering on VPC GIN
        *   static route 10.xx.xx => VPC Paas (pattern DMZ)
        *   no double NIC required / possible
    *   issue with VPC Peering with VRRP (eg: Kermit =>  OSB mysql shared)
    *   unable to use HWS load balancer (holding external VIPs)
    *   not same architecture as vsphere 
        *   (double NIC, 1 NIC GIN, 1 NIC privée)

  *   K8s transformation
    *   cloud provider (plugin openstack, loadbalancer)
        *   **service type LoadBalancer** \=> crée à la volée un loadbalancer Openstack (Octavia ?)
            *   \+ intégration
            *   \- 1 load balancer per service
            *   \- maturity. community on openstack cloud provider / Huawei openstack cloud provider
            *   \- would need nsx-t plugin for vsphere / brmc
        *   not installed / qualified on bosh k8s deployments (S&W K8S / k3s)
    *   metallb:
        *   équivalent keep alived
        *   configuration  pool, vips
        *   ha
        *   +
            *   higher density/smaller footprint
            *   ips saving
            *   HA across AZs with BGP support (brmc compatible, metalikaas => vpshere ? openstack ?)
        *   \-
            *   vertical scaling: not loadbalancing (only HA)
            *   openstack: allowed\_adress\_pair specific configuration. Openstack CPI allow one single ip.
                *   need to patch the openstack cpi, to allow 192.168.116.0/24 (instead of 192.168.116.15)
            *   HA across AZ requires multi-az k8s cluster (openstack ok, vpshere brmc => requires a VPN)
                *   risk on storage: etcd muti-az, latency. On k3s, possible to use a mysql galera backend (mysql extended).
        *   granular transformation k8S
            *   3 / 2 centralized k8s
            *   k8s (k3s) specialized
                *   access layer
                *   cf
                *   concourse ?

## Decision  
  
> What is the change that we're proposing and/or doing?  
  
*   inbound access layer / vips managed by a dedicated k8s
    *   instead of haproxy / dedicated vm
    *   centralize access layer on micro-depls
        *   ops relay
            *   including docker cli relay
        *   osb relay
        *   api (cloudfoundry)
*   introduce a top level ingress / TLS offload mechanism
    *   ingress k8s (TLS termination, or SNI routing). traefik / nginx /istio
        *   routes
        *   default routes (transient)
            *   ops-router (nats / route registar)
                *   with X-FORWARD\_PROTO (so backend)
                *   with X\_FORWARDED\_FOR
                *   with proxy protocol so that gorouter propagates source IP adress in XFF

*   phase 0: api. haproxy offload ssl (modif XFF, XFP)    => http 80 gorouter
*   phase 0 bis (non fait) haproxy offload ssl (modif XFF, XFP) => client https, split brain local pour aiguiller le backend vers gorouter => https 443 gorouter
*   phase 1:                                              haproxy TCP    => https 443 gorouter (offload). problème: perte d'ip source (gorouter voit l'ip du haproxy)
*   phase 2 (actuel): haproxy mode proxy protocol TCP  => 443 Host: original FQDN  gorouter (config proxy entrant), go router peut récupérer l'ip source

  *   change proposé

*   **VIP (metallb) => service typeLoadBalancer d'un ingress (traefik 2/istio/... selon les capacité fonctionelles)**
    *    \=> 443 offload SSL => backend (Service External)   ===> backend (api k8s)
    *   \=> 443  => offload SSL & HTTP routing & XFF & XFP ==> backend (80/443)
    *   \=> 443 SNI & **proxy protocol labelling**                ==> backend (443)              
    *   **\=> (default si pas de route kubernetes) ==> gorouter (config proxy entrant), go router peut récupérer l'ip source (permet d'accéder aux vms legacy route registrar)**

  *   possibilité de cohabitation de 2 ingress controller sur 1 cluster
    *   1 vip pour traefik
        *  service: type: LoadBalancer
    *   1 vip pour istio
        *  service type: loadBalancer
    
*   outbound acces layer managed by k8s

## Consequences  
  
> What becomes easier or more difficult to do because of this change?  
  
Easier:  
  
More Difficult:  
* must support smooth migration from existing pf (without downtime breaking circular dependencies among PF components)  
* need to have intranet interco relay in micro-depls  

*   "blue green" pattern:
    *   with new VIP
    *   DNS switch (Di@ANE) for ops traffic
    *   pbs
        *   IP address shortage (openstack FE. 10 ip, mutualiser inbound/outbound)
            *   1 ip par vip (api/ops/osb). recorded in DI@NE
            *   \+ vm metallb (2 ou 3).

**Comment by poblin-orange** [comment]
All COA profile swiches have been set in v51.0.3.
v52 will clean legacy bosh deployments, and remove switch profiles
