### ISSUE TITLE
rancher-ui integration and hardening (micro-depls-bosh-generated/jobs/run-errand-00-core-connectivity-k8s-rancher-registration fails)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1045]
### Expected behavior

* As a paas-templates operator
* In order to 
  * reduce manuel install step to wire rancher-ui with paas-templates control plane k8s clusters
* I need 
  * [ ] an automation for k8s clusters registration in the rancher-ui
  * [ ] automated ops role assignement (ideally based on master-depls/openldap admin role ?)  
  * [ ] paas-templates helm repo mirror registration in rancher-ui
  * [ ] leverage rancher cross-cutting feature on paas-templates control plane k8s clusters ?
    * [ ] logging (rancher built in banzai cloud)
    * [ ] monitoring (rancher built in prometheus grafana integration)
  * [ ] clarify and fix rancher internet (proxy/no proxy configuration)
    * [ ]  wrt to helm chart icons rendering in rancher ui (ok on local, ko when looking on imported k8s cluster in cluster explorer)
    * [ ] multiple no proxy syntax
      * see https://github.com/orange-cloudfoundry/paas-templates-private/blob/develop/shared-operators/k3s/rancher/35-install-rancher-ui-operators.yml#L61
  * [ ] federate with micro-depls/jcr helm repo mirror
  * [ ] federate with micro-depls/jcr docker repo mirror

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
Focusing rancher on analytics/dashboarding for control plane of multiple k8s clusters (but dashboards not data services such as strimzi)

The configuration and provisionning use-cases (helm chart installations) are 
* in conflicts with flucd reconcialiation approach, 
* brings tight coupling/dependency
* technically difficult to automate: rancher charts requires rancher terraform

**Comment by poblin-orange** [comment]
as of v54, rancher and 00-gitop-management are removed
