### ISSUE TITLE
token-authentication requirements for gitoperations

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1046]
### Expected behavior

* As a paas-templates operator / author
* In order to 
  * be able to use github as a paas-template hosting git repo
* I need 
  * an evolution to token/ssh key for git access
    * [ ] from COA 
    * [ ] from coab   

### reference

- github message: 

```
Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.


```

### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
I think we can replace Password with Personal Access Token, and it does not require changes on COA side.

**Comment by poblin-orange** [comment]
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
