### ISSUE TITLE
No alerts are throw for rabbitMq shared

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1051]
### Expected behavior

* As a paas-templates operator 
* In order to monitor the RabbitMQ shared instance
* I need to have an alert with alertmanager

### Observed behavior
No alert for shared (alerts are well throw for coab rabbitmq)

All the alerts are describe here 
https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/rabbitmq_alerts/templates/rabbitmq.alerts.yml
The shared instance does not match the job filter : **job=~".*rabbitmq.*"** because the job is **cf-rabbit** for the shared instance

### Affected releases

* 48.0
* earlier versions

**Comment by JCL38-ORANGE** [comment]
it will be delivered in v50
