### ISSUE TITLE
Redis extended does not support canary update

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1052]
### Expected behavior

* As a paas-templates operator
* In order to upgrade a redis extended deployment 
* I need to have the deployment ok after upgrade

### Observed behavior
 The deployment is KO, without an elected master

### Affected releases

* 49
* earlier versions

### constat
En partant d’un environnement stable et en lançant le recreate du déploiement, on constate bien la mise à jours séquentiel des vms

Lors de l’arrêt de la vm master (vm1), le système bascule bien vers le slave (vm2) qui a été élu nouveau master.
Lors du démarrage de vm1, il arrive en tant que master, mais le système lui dit qu’il y un autre master (vm2), donc il cherche ca chercher à se synchroniser. Et là c’est le drame !! Le canary update a déjà déclenché l’arrêt de vm2 donc vm1 n’arrivera jamais à se synchroniser avec vm2 qui est en cours d’arrêt.
Lors du démarrage de vm2, il arrive en tant que slave, donc il va chercher à se resynchroniser avec vm1, mais qui n’est pas master, donc on se retrouve avec 2 nœuds qui sont à la fois master / slave l’un de l’autre
La relance des 2 sentinels ne change rien

**Comment by poblin-orange** [comment]
Suggested fix:
- ensure bosh manifest uses serial=true to avoid concurrent redis vms updates
- add a post-start script
  - with a tempo so the redis node has enough time to resync
  - ideally, check resync is ok before terminating post-start script https://github.com/orange-cloudfoundry/generic-scripting-release/blob/master/jobs/scripting/spec#L15


Hot fix possible with generic scritping release 
Eventually, this should be built in the bosh release.

**Comment by poblin-orange** [comment]
workaround status;
-  bosh recreate ok
- unexpected vm restart keeps the cluster ok, but gets unmanageable with bosh ... (issue probably existing on non HA dedicated redis)

**Comment by JCL38-ORANGE** [comment]
correction available https://github.com/orange-cloudfoundry/redis-orange/releases/tag/v3.2
it will be delivered v50.0.2 as part of the distribution.
a branch based on v49.0.2 is available for OPS team
