### ISSUE TITLE
gorouter 0.210.0 /go1.15 ssl validation issue

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1053]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to 
* I need 

### Observed behavior

- master-dels/ops-routing uaa acces KO (Http 503)
- shield acces KO (Http 526)

### reference
- https://app.slack.com/client/T02FL4A1X/C01ABMVNE9E/thread/C2U7KA7M4-1610121124.075500

### Affected releases

* x.y
* earlier versions

**Comment by ogrand** [comment]
go 1.15 => The deprecated, legacy behavior of treating the CommonName field on X.509 certificates as a host name when no Subject Alternative Names are present is now disabled by default.
It can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable.

**Comment by obeyler** [comment]
Replace all certificate inside K8S* previously  generated by certmanager by the certificate *.k8s-xxx generated by pki
