### ISSUE TITLE
rabbitmq 3.8

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1066]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to
  * have upstream support for rabbitmq 
* I need 
  * to offer rabbitmq 3.8 in the marketplace

### references
- https://www.rabbitmq.com/versions.html
- https://github.com/pivotal-cf/cf-rabbitmq-release/releases
- https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq/#installing-the-chart
- https://www.rabbitmq.com/kubernetes/operator/using-operator.html
- https://www.rabbitmq.com/blog/2020/11/17/rabbitmq-kubernetes-operator-reaches-1-0/

### Affected releases

* v48 or v49
* earlier versions

**Comment by JCL38-ORANGE** [comment]
rabbitmq 3.8 is available both in shared and dedicated services

**Comment by gberche-orange** [comment]
closing as it was fixed in v48 or v49
