### ISSUE TITLE
removing stable/incubator helm repo breaks rundeck and metabase

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1077]
### Expected behavior

* As a paas-templates  author
* In order to 
  * be able to run existing k8s helm deployments 
* I need
  * a way to workaround stable/incubator depreciation warning in helm kubectl bosh release see # following https://helm.sh/blog/helm-hub-moving-to-artifact-hub/
     * helm repos are now read-only not accepting fixed

### Observed behavior

broken bosh/helm kubectl broken:
- master-depls/rundeck
  - incubator/rundeck 
- master-depls/metabase
  -  stable/kafka-manager
  - stable/oauth2-proxy see https://github.com/oauth2-proxy/oauth2-proxy/issues/930
 
### Affected releases

* 50.0.0 (pre RC)

**Comment by obeyler** [comment]
for metabase a workaround is to use not official helm repo: https://github.com/pmint93/helm-charts

**Comment by gberche-orange** [comment]
status: helm CLI option to force the deployment despite its deprecated flags still enable

**Comment by poblin-orange** [comment]
rundeck remove in v52.
should not use legacy helm repo anymore
