### ISSUE TITLE
No log in logsearch's  kibana for specific user

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#108]
### Expected behavior
See log into logsearch's kibana (both for paas-users and paas-ops)

### Observed behavior
No log even if I'm log as my admin account, 
but I can see log if I'm log as cf admin account.

<!-- 
### Affected release
paas template 33

**Comment by gberche-orange** [comment]
* Same after recreating accounts that don't work 
* Same observed with some user accounts

**Comment by aveyrenc** [comment]
Logs are filtered on the fly by a Kibana plugin based on your Cloud Foundry permissions. Please verify that your user has sufficient permissions on the specific org/space.

To see Ops logs, you must be part of system domain.

**Comment by obeyler** [comment]
The problem occured  even for an admin
