### ISSUE TITLE
vsphere iaas type - Adding new datastore to cloud config

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1086]
### Expected behavior

* As a paas-templates operator | paas-templates author | paas-templates maintainer
* In order to increase the resilience on datastore fault
* I need to have more than one datastore into the cloud config

### Observed behavior
Only One datastore.
The cloud provider vsphere would give more than one DS, we want use it into our deployment. For example, deploy galera node on different DS.

### Affected releases

* 49
* earlier versions

**Comment by gcordierOrange** [comment]
use case :

1. A DS for making wmotion storage (maintenance op or crash)
2. Using more than one DS to slip deployment on different DS

**Comment by poblin-orange** [comment]
Will rather leverage a new vsphere cluster, with its own datastore (leveraging rack level locality of the datastore)
see #1318
