### ISSUE TITLE
cf-rabbit extended (HA) dedicated service 

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1088]
### Expected behavior

* As a marketplace user
* In order to prevent me from failures (network loss, room loss) 
* I need an extended (HA) cf-rabbit dedicated service

### Observed behavior
the current dedicated cf-rabbit service doesn't prevent from room or network failure  

### Availability
- v51 / initial service
- v52 / prod ready  service

**Comment by gcordierOrange** [comment]
About the need to have the both proxy ip send by the broker.
When we look into cf-rabbitmq-multitenant-broker-release, we see that de structure of the broker support an array of hostname.

**Comment by JCL38-ORANGE** [comment]
it will be delivered in v51.
