### ISSUE TITLE
Issues encountered during tag v33.0.0 bootstraping

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#109]
### Expected behavior

No bootstrap issue ;-)

### Observed behavior
- [x] **Step1 : Solve zlib1g-dev and ruby package mis installation**
    
  At step 7, we encounter some errors related to the fact that ruby and zlib1g-dev package that were not installed on the Ubuntu bootstrap VM. But it seems that package installation of ruby was done during Step1. We did not notice any error in logs during the apt-get install. Need to be confirmed.

- [x] **Step 8: Concourse 3.8 deployment error**

     We encounter errors during Concourse in deployment:
    Error during concourse-micro deployment: Job worker not found in concourse 3.8.0

    => cd ~/bosh/template/bootstrap/tools && ./bootstrap.sh : change the version of concourse 3.14.1 (instead of 3.8.0)

     uploadBoshReleases() {

    ....

    uploadRelease "https://bosh.io/d/github.com/concourse/concourse?v=3.14.1" "concourse" "3.14.1"

### Affected release

Reproduced on version 33.0.0

**Comment by gberche-orange** [comment]
@aurelienbouleau please clarify step 9

**Comment by aurelienbouleau** [comment]
Updated My comment as I think it was a mistake for Step9. Sorry.

**Comment by ogrand** [comment]
Fixed in paas-template v35.0.0
