### ISSUE TITLE
Instance and persistent disk on different availability-zone

### ISSUE THREAD

**Issue by shoudusse** [orange-cloudfoundry/paas-templates#111]
### Expected behavior
It should not be possible to create an instance and the attached disk on a different AZ if the IaaS can't support it.

### Observed behavior
When using Flexible Engine IaaS, BOSH may create the instance and the disk on different AZ.
Then BOSH can't attach the disk 

### Traces and logs
```
Task 84357 | 08:31:51 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Timed out waiting for Volume `a7d1efae-0e27-434c-9101-4e216694cc1d' to be in-use' in 'attach_disk' CPI method
```

* [x ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by shoudusse** [comment]
The Openstack CPI has a parameter to tune this: [openstack.ignore_server_availability_zone](https://bosh.io/jobs/openstack_cpi?source=github.com/cloudfoundry-incubator/bosh-openstack-cpi-release&version=24#p=openstack.ignore_server_availability_zone)

**Comment by shoudusse** [comment]
Maybe a duplicate of #47

**Comment by poblin-orange** [comment]
which version of paas-templates and deployments ? as of v33, the iaas-type config should prevent this with appropriate openstack cpi configuration.
