### ISSUE TITLE
resurrector off feature not synchronized with service instance deployment 

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1113]
### Expected behavior

* As a paas-templates operator 
* In order to avoid problem during vpn operation or fail
* I need to have resurrector disabled on extended deployment

### Observed behavior
Resurector is enabled on this kind of deployments

The root-deployment level script `deploy.sh` (which restores the resurrector disabling flag) script is not launched since one month.

### Required fix

* [ ] apply persistently the disabling of resurrector on the extended deployment (e.g. schedule it into a concourse pipeline)

### Affected releases

* 49
* earlier versions

**Comment by ogrand** [comment]
* Workaround with concourse pipeline to trigger `deploy.sh` script for v51
* Next to look for COAB resolution
