### ISSUE TITLE
rate limiting on COA bosh release precompilation 

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1116]
### Expected behavior

* As a paas-templates operator 
* In order to 
  *  keep a reasonable usage of vms and api usage
  * avoid hitting IAAS level API rate limits returning 429? errors
* I need 
 *  the precompilation pipeline by root-deployment paralellism to be configurable

### Observed behavior
 
On master-depls, all precomilation launch in //, inducing a huge load on:
- minio s3
- bosh master director
- iaas api (// concurrent stemcell update)

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
same issue while bumping stemcell (bionic 0.24 on integration env).

bosh-master saturated (cant log-bosh on it).

```
bosh/df0a66e8-3598-47ec-931f-8c60c1efba09:~# netstat -na |grep 25555 | wc -l
62

```

**Comment by gberche-orange** [comment]
Status during backlog review:
* reproduced on customer site
* @o-orand would you mind creating an upstream issue on a coa repo ?

**Comment by o-orand** [comment]
This will be part of [COA 5.2.x releases](https://github.com/orange-cloudfoundry/cf-ops-automation/releases/)
