### ISSUE TITLE
Ingress routing looses source IP address

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#112]
### Expected behavior

HTTP/HTTPS workload should properly receive source IP address of HTTP clients in the X-Forwarded header

### Observed behavior

HTTP/HTTPS workload currently receive source IP address of our ingress routing layer instead

### Affected release

Reproduced on version 33.0

### references:
- https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
- https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-send-proxy-v2-ssl-cn
- 

### Suggested fix

Our current ingress routing layer (which is composed of the following stages) is not properly propagating source IP address to HTTP workload (by enrichiring the HTTP X-forwarded-for header):
    
For application and operations HTTP workloads:
   * User facing IP address is served by the "interco relay" bosh deployment (both for intranet and internet) which apply L4 load balancing using the haproxy-bosh-release on tcp mode
   * TLS termination is performed by the "rps" bosh deployment using the haproxy-bosh-release in http mode
   * Gorouter receive HTTP traffic and load balance to HTTP/HTTPS backends

For API workloads:
   * User facing IP address is served by the "interco relay" bosh deployment (both for intranet and internet) which apply L4 load balancing using the haproxy-bosh-release on itcp mode
   * TLS termination is performed by the CF bosh deployment using the routing-release (using gorouter)

The [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) extension over TCP, enables L4 TCP load balancers to propagate source IP addresses to backends. 

We should enable PROXY procotol in our different ingres TCP stages

For application and operations HTTP workloads:
   * "interco relay" bosh deployment 
      * enable PROXY protocol to backends "send-proxy-v2" in  the [tcp_backend_config](https://bosh.io/jobs/haproxy?source=github.com/cloudfoundry-community/haproxy-boshrelease&version=9.3.0#p%3dha_proxy.tcp_backend_config)
   * TLS termination is performed by the "rps" bosh deployment using the haproxy-bosh-release in http mode
      * enforce PROXY protocol on listeners: [accept_proxy](https://bosh.io/jobs/haproxy?source=github.com/cloudfoundry-community/haproxy-boshrelease&version=9.3.0#p%3dha_proxy.accept_proxy)=true which will implicitly impact the x-forwarded-for header use the IP received from PROXY protocol
   * Gorouter receive HTTP traffic and load balance to HTTP/HTTPS backends
       
For API workloads:
   * "interco relay" bosh deployment:
      * enable PROXY protocol to backends "send-proxy-v2" in  the [tcp_backend_config](https://bosh.io/jobs/haproxy?source=github.com/cloudfoundry-community/haproxy-boshrelease&version=9.3.0#p%3dha_proxy.tcp_backend_config)
   * In the CF bosh deployment using the routing-release (using gorouter)
      * enforce PROXY protocol in [enable_proxy](https://bosh.io/jobs/gorouter?source=github.com/cloudfoundry-incubator/cf-routing-release&version=0.180.0#p%3drouter.enable_proxy) property, see [related doc](https://github.com/cloudfoundry/gorouter/blob/master/README.md#enabling-apps-to-detect-the-requestors-ip-address-uing-proxy-protocol)

In the future, Iaas load balancers could be configured to enable the PROXY protocol, we need to clarify how to enable these
   * For openstack, see https://github.com/terraform-providers/terraform-provider-openstack/pull/375

**Comment by gberche-orange** [comment]
Actually the tcp_backend_config clause of the haproxy bsoh release does not end up on the "server" line, so dedicated support needs to be added into the release.

**Comment by poblin-orange** [comment]
with haproxy 9.4.1, we can leverage the property tcp_backend_config to configure default values for servers:

```
      properties:
        ha_proxy:
...
          disable_http: true
          log_level: debug
          tcp:
          - name: cf-api-https
            port: 443
            backend_servers:
            - cf-deployment-routers #bosh-dns alias to cf/routers instances
          tcp_backend_config: |
            default-server send-proxy  

```

**Comment by poblin-orange** [comment]
proxy protocol between relay and go routers status:
- [X] cf api - v40
- [X ] apps - v40
- [ ] ops
- [ ] osb
- [ ] isolations segment intranet 2

**Comment by gberche-orange** [comment]
In v41, ops traffic is sending proxy protocol except ssh traffic as sshd is not yet supporting proxy protocol. See related resources below:
* [proxy protocol specifications](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) section `6. Validation` describes that sshd properly fails fast when proxy protocol is used:

>   - SSH :
    - openssh 3.9p1    : abort                   => pass/optimal
* some alternative sshd such as [Apache mina sshd java implementation](https://mina.apache.org/sshd-project/) are planning proxy protocol impl, see related https://issues.apache.org/jira/browse/SSHD-656

A potential future improvement could be to colocate [mmproxy](https://github.com/cloudflare/mmproxy) with sshd (on bosh-cli bosh deployment), 
> mmproxy sits near the application, receives the proxy-protocol enabled connections from the load balancer, spoofs the client IP addresses, and sends traffic directly to the application. From application point of view the traffic look identically like it would have originated from the remote client.

/CC @poblin-orange 
More details in https://blog.cloudflare.com/mmproxy-creative-way-of-preserving-client-ips-in-spectrum/

**Comment by poblin-orange** [comment]
@gberche-orange to workaround the proxy isue, tcp relay for ssh is implemented separaly with envoy. see #356. Maybe an architecture refactoring could do (direct ops interco relay on docker-bosh-cli bastion vm).

**Comment by gberche-orange** [comment]
For the records, during application of v41, the following symptoms were observed when the `intranet-interco-relay` was deployed before the `ops-routing` deployment:

* firefox reports  `SSL_ERROR_RECORD_OVERFLOW_ALERT` on api url
* curl and open_ssl report record overflow
```
openssl s_client -connect ops-portal.${api-domain}:443 
CONNECTED(00000003)
139738843017664:error:140943FE:SSL routines:ssl3_read_bytes:tlsv1 alert record overflow:../ssl/record/rec_layer_s3.c:1399:SSL alert number 22
```
* the ops-routing-router gorouter servers display the following traces in `/var/vcap/sys/log/gorouter/gorouter.stderr.log`:

```
2019/08/13 14:47:40 http: TLS handshake error from 192.168.99.30:40506: tls: oversized record received with length 22617
2019/08/13 14:47:41 http: TLS handshake error from 192.168.99.30:40518: tls: oversized record received with length 22617
```

The resolution was to deploy `ops-routing` before the `intranet-interco-relay`. The traces displayed correspond to protocol mismatch , see related https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt section "6. Validation" which describes similar protocol mismatch handled by different middleware

**Comment by poblin-orange** [comment]
closing, after confirmation that x-fowarded-for is correct on isolation-segment-2.
