### ISSUE TITLE
Prebuild stratos ui (AOT) as to speed up browser load time

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#113]
### Expected behavior

Stratos console to load quickly in browser.

This requires AOT (Ahead Of Time) compilation prior to the cf-push, see https://github.com/cloudfoundry-incubator/stratos/tree/v2-master/deploy/cloud-foundry#pre-building-the-ui

However, the pre-cf-push.sh COA containers currently lack the nodejs/npm prereqs to perform this build. This is likely we'd need a custom concourse pipeline to build stratos binaries.

Note that asking for prebuilt binaries to the stratos team may not help, as we probably need to include orange branding changes prior to triggering AOT.

### Observed behavior

It takes 15+s to load.

### Affected release

Reproduced on version 34.0

**Comment by gberche-orange** [comment]
It's possible that the AOT build would be added to the cf staging time build process which would then avoid the need of a custom concourse pipeline. See related slack exchange at https://cloudfoundry.slack.com/archives/C80EP4Y57/p1536756672000100?thread_ts=1536700835.000100&cid=C80EP4Y57

**Comment by gberche-orange** [comment]
Related stratos feature suggestion at https://github.com/cloudfoundry-incubator/stratos/issues/3144

**Comment by shoudusse** [comment]
nodejs/npm prereqs are now installed at the pre-cfpush step. And the pre-build is done.
Is it a good solution for you?
