### ISSUE TITLE
crossplane for marketplace services

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1134]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to
  * offer managed services on top of k8s control plane and dataplane
  * offer public cloud services with k8s control plane
  * bridge existing OSB client platforms with on the shelf public cloud services/k8s operators
  * also support native k8S client platforms (openshift/rancher )
* I need 
  *  a solution / framework to construct / extend for marketplace management

### References
cross plane for service offering construction

https://dev.to/sahillakhwani/building-custom-control-planes-using-crossplane-404f

crossplane and k8s clusterAPI:

- https://thenewstack.io/kubernetes-is-not-just-about-containers-its-about-the-api/
- https://github.com/crossplane-contrib/provider-capi crossplane provider for kubernetes-sigs Cluster API 
- https://danielmangum.com/posts/crossplane-infrastructure-llvm/

cross plane integration with existing terraform plugins:
- https://githubmemory.com/repo/crossplane-contrib/provider-terraform-vsphere 
- https://github.com/crossplane-contrib/terraform-provider-gen : crossplane provider codegenerator from terraform provider
- https://blog.crossplane.io/adding-vmware-support-to-crossplane-using-terraform/

cross plane provider for using helm charts:
- https://github.com/crossplane-contrib/provider-helm
   - https://github.com/crossplane/crossplane/blob/master/design/one-pager-helm-provider.md

crossplane for OSB API
- https://kb.vshn.ch/app-catalog/explanations/crossplane_service_broker.html
- https://github.com/vshn/crossplane-service-broker
   - https://github.com/vshn/crossplane-service-broker/releases
   - Still specific service binder with impl for redis and mysql. See https://github.com/vshn/crossplane-service-broker/blob/5558d15049c601b4edf29e6627d6767a3c7a354f/pkg/crossplane/services.go#L69-L79
- https://github.com/vshn/swisscom-service-broker
   - https://github.com/vshn/swisscom-service-broker/releases
crossplane and openshift / OLM
- https://containerjournal.com/topics/container-management/ibm-throws-weight-behind-crossplane-project/
- https://blog.crossplane.io/crossplane-openshift-operator-cloud-native-services/
- https://next.redhat.com/2021/03/31/crossplane-as-an-abstraction-platform-to-manage-and-deploy-service-operators/
- https://github.com/redhat-et/crossplane-quay

crossplane SDK for defining compositions using DSLs in general programming languages including java 
- https://github.com/crossplane-contrib/crossplane-cdk8s

crossplane support for remote consumption from distinct K8S cluster
- https://github.com/crossplane-contrib/agent 
   - https://github.com/crossplane/crossplane/blob/7d942fd/design/design-doc-agent.md

terraform support 
- https://github.com/crossplane-contrib/provider-terraform
- https://github.com/crossplane/terrajet
   - https://github.com/crossplane/crossplane/blob/master/design/design-doc-terrajet.md

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
Use cases for the spike
* service composition with service plans
   * which workload ?
      * redis 
         * bitnami helm chart
      * hello world ?
      * other ?
   * user facing UX
      * osb api
         * [ ] interoperator gotemplate
         * [ ] validated by osb cf-based smoke tests CronJob
      * native K8S CR
         * which test validation ?
 
Design:
* Crossplane helm provider

Steps:
* [ ] Update cross plane to latest version

**Comment by gberche-orange** [comment]
Learnings from the spike:
- too early to include crossplane as our main composition layer:
   - authoring is complex with patches
   - operations is complex with XRC, XR, MR objects to watch
   - scalability limits (concurrency bottlenecks https://github.com/crossplane-contrib/provider-kubernetes/issues/32 
https://github.com/crossplane-contrib/provider-helm/issues/125
   - still small community
- promising features for services yet to explore and hook/glue up 
   - composition revisions https://crossplane.io/docs/v1.6/guides/composition-revisions.html

To be revisited with
- for public cloud consumptions use-cases
- future availability of wider providers through terrajet providers
- scability improvements
