### ISSUE TITLE
v50 upgrade destroys cf internal org content

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1154]
### Expected behavior

* As a paas-templates operator 
* In order to 
  * not loose the cf org content
* I need 
  * a solution to preserve content, despite paas-templates refactoring from COA ops-depls terraform to embedded master-depls/cf/terraform 

### Observed behavior
 
Installing v50 in integration
- terraform refactoring has side effects
- deletes the cf org when triggering COA ops-depls terraform apply (losing all spaces/org content)
- master-depls/cf/terraform errand creates a brand now cf org

See full [status Aprl 8th, 2021 spreadsheet](https://docs.google.com/spreadsheets/d/1O75-TY7p6ffxsoR3jcZmktWx1QAGwRqbfPwo9VWx6j8/edit#gid=0)

### Workaround
manual steps to avoid org loss.

- before applying COA ops depls terraform apply
  - clone the secrets repo
  - cd ops-depls/cloudfoundry/terraform-config
  - terraform state list |grep org|grep internal
  - terraform state delete xxx
  - git commit + git pull --rebase + git push the terraform state
- check COA ops depls terraform plan (org should not be listed as "to delete")
- trigger COA ops depls terraform

For master-depls/cf
- bosh ssh into the terraform vm
```
bosh -d cf ssh terraform
cd /var/vcap/store/terraform-apply
terraform plan
terraform state list
terraform import the existing cf org
git add / git commit the state.json file
```
 

### Affected releases

* 50.0.0
* earlier versions

**Comment by o-orand** [comment]
After some investigations, `internal org` is not managed by terraform on prod, nor on preprod environments
