### ISSUE TITLE
k8s core-connectivity openstack:  bosh recreate loses arp vip connectivity, resulting in deadlock

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1161]
### Expected behavior

* As a paas-templates operator
* In order to 
  * update stemcell / or bosh recreate safely the micro-depls/00-core-connectivity-k8s on openstack
* I need 
  * a robust recreate path 

### Observed behavior
- bosh recreate
 - stops and recreate vms one by one
 - we see the metallb mechanism move vips to other vms while vm is recreating
 - but the openstack allow address pair is a post-deploy, only applied at the end. So we progressivly lose all inbound connectivity
 - when all vm are recreated, the post-deploy (based on k8s openstack-client image) starts, but k8s is unable to pull image
   - as of v51.0.0, it tries to reach 00-ci-k8s jcr, or micro-depls/jcr, both unreachable as core-connectivity cluster is unreachable  

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
Solution:
- immediate workaround: use openstack cli to set allowed adress pair 192.168.16.0/24 on 00-core-connectivity vms
- evolution: convert the post-deploy to post-start script (wich would authorize arp for each vm on the fly) 
- evolution: configure core-connectivity containderd mirroring to use corporate docker proxy / or inter http proxy to break the cyclic dependency

**Comment by gberche-orange** [comment]
This problem still reproduces on v52 on openstack despites the DaemonSet which assigns the allowed address pair. Still observing Image pull backoff error following a bosh recreate of the K8S core-connectivity deployment (as part of the secret rotation on Orange FE-int lab environment)

Suspecting remaining chicken-an-egg/circular dependency between core-connectivity and jcr deployment.

Manually worked-around by configuring the DaemonSet to directly point to corporate docker repository proxy:
* Log using bosh `admin` credentials (available in shared/secrets.yml  bosh.admin.password
* log-bosh to bosh-micro and core-connectivity deployment
* bosh ssh to core-connectivity deployment and sudo -i
* k9s
* in namespace `openstack-init-daemonset` edit `openstack-init` DaemonSet: add the corporate docker repository proxy FQDN as a prefix of the 2 images such as `image:fqdn/rancher/pause:3.1"
