### ISSUE TITLE
concourse 7.1 memory leak

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1179]
### Expected behavior

* As a paas-templates operator
* In order to 
  * ensure smooth operation 
* I need 
  * no memory leaks no control plane components

### Observed behavior
- on 51.0.1, with concourse 7.1, we observe linear memory consumption on the web instance groups
 
### Affected releases

* 51.0.1

### workaround
- restarting web instance monit jobs resets memory usage

```
bosh -d concourse restart web
```

**Comment by o-orand** [comment]
Closed, this is a duplicate of #1193
