### ISSUE TITLE
Remove Orange OCB specifics from paas-templates

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#118]
### Expected behavior

Paas-templates needs to be shared with the opensource community (see #65), without being polluted with Orange specifics. Company specifics should instead be maintained in feature branches, possibly shared among environment (as to ensure parity across environments), see https://github.com/orange-cloudfoundry/cf-ops-automation/issues/62

### Observed behavior

Orange OCB specifics are still in paas-templates in particular:
* specific networks
* specific prometheus alertmanager escalation rules

### Affected release

Reproduced on version 34.0

**Comment by poblin-orange** [comment]
delivered in 36.0.0
