### ISSUE TITLE
CredhubExporterScrapeTooOld - alert and scrape update are not coherent

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1181]
### Expected behavior

* As a paas-templates operator
* In order to monitor efficiently the plateform
* I need to have less false alarm

### Observed behavior
The alert  CredhubExporterScrapeTooOld  is not coherent between scrape update
We send an alert after 1 hour but the scrape update interval is set to 6 hours
change the alert to be coherent between the alert and the update => we send an alert after 6 hours

### Affected releases

* 50

**Comment by ogrand** [comment]
Incoherent scraping is resolved with `prometheus 26.5.0` release bumped with `paas-template 51.0.6`
