### ISSUE TITLE
Tune upgrade pipeline for Coab

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1191]
### Expected behavior

* As a paas-templates operator
* In order to automate COAB upgrade process
* I need to have additional jobs in upgrade pipeline

Here some details about expected steps:
  - [ ] ensure models are upgraded with manual approval
  - [ ] unpause latest created services (one per service type) with manual approval
  - [ ] process remaining deployments, either:
    - 2 steps, each steps holding 50% of deployments
   **and/or**
    -  unpause all COAB jobs on maintenance period start and pause all COAB jobs on maintenance period stop (8pm -> 8 am)
   
### Observed behavior
Currently, we there is only no specific job releated to COAB. So we need manual operations to perform an upgrade.
 
### Affected releases
* v51and earlier versions

**Comment by o-orand** [comment]
Does it match your expectation @CDallosto-orange  ?

**Comment by CDallosto-orange** [comment]
> Does it match your expectation @CDallosto-orange ?

it meets all my expectations, I can't wait :-)

**Comment by CDallosto-orange** [comment]
Can you divide `manual-step-xx-upgrade-remaining-root-deployments` in following steps ?
- Unpause coab skeletons
- Unpause last one created coab instances (to be sure there are not in production) (one by type)
- Unpause Shared services
- Unpause 50% of coab instances
- Unpause 50% of coab instances
