### ISSUE TITLE
Remove remaining COA dependency to image with no tag (latest)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1203]
### Expected behavior

* As a paas-templates operator |
* In order to 
 * have predictable load on corporate dockerhub registry proxy 
* I need 
 * to always use image with a specified version/sha1 (and never latest)

### Observed behavior

High load notified from corporate registry teams for images:
- teliaoss/github-pr-resource (298 k downloads) https://hub.docker.com/layers/teliaoss/github-pr-resource/v0.23.0/images/sha256-40b2a459ad46efe61c8eb86e8088eb7fed8da720e685ebf139d72108afcd37c5?context=explore
- cftoolsmiths/cron-resource (207 k downloads) https://hub.docker.com/r/cftoolsmiths/cron-resource/tags
- olhtbr/metadata-resource (77 k downloads)  https://hub.docker.com/r/olhtbr/metadata-resource/tags?page=1&ordering=last_updated
 
 
### references
- https://github.com/orange-cloudfoundry/paas-templates/issues/97

### Affected releases

* 51.x
* earlier versions

**Comment by o-orand** [comment]
teliaoss/github-pr-resource is only used by 2 pipelines:
 - [X] micro-depls(release-mgmt-github) 
 - [ ] ops-depls(osb-cmdb-pipeline) (@gberche-orange could you have a look ?)
Others need COA evolution, and should be included in next major release (52, or 53)
