### ISSUE TITLE
credhub export / import incompatibility. v32 => v33 upgrade

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#122]
### Expected behavior
As a platform operator, upgrading a v32 to a v33, i expect to be able to reimport all my existing master-depls to micro-depls/credhub-ba

### Observed behavior

Getting errors while importing
```
Import complete.
Successfully set: 491
Failed to set: 6
Credential '/bosh-master/cf/diego_ssh_proxy_host_key' at index 243 could not be set: The request includes an unrecognized parameter 'public_key_fingerprint'. Please update or remove this parameter and retry your request.
Credential '/micro-bosh/concourse-micro/worker_key' at index 358 could not be set: The request includes an unrecognized parameter 'public_key_fingerprint'. Please update or remove this parameter and retry your request.
Credential '/micro-bosh/concourse-micro/tsa_host_key' at index 359 could not be set: The request includes an unrecognized parameter 'public_key_fingerprint'. Please update or remove this parameter and retry your request.
Credential '/cf/diego_ssh_proxy_host_key' at index 430 could not be set: The request includes an unrecognized parameter 'public_key_fingerprint'. Please update or remove this parameter and retry your request.
Credential '/bosh-ops/concourse-dev/worker_key' at index 474 could not be set: The request includes an unrecognized parameter 'public_key_fingerprint'. Please update or remove this parameter and retry your request.
Credential '/bosh-ops/concourse-dev/tsa_host_key' at index 475 could not be set: The request includes an unrecognized parameter 'public_key_fingerprint'. Please update or remove this parameter and retry your request.`
```

**Comment by poblin-orange** [comment]
bosh release versions:
master-depls/credhub  1.7.1
micro-depls/credhub-ha, 1.9.3

**Comment by shoudusse** [comment]
It's a credhub related bug.
If you try to export / import datas (even from / to the same credhub) you will have an error for all `ssh` and `user` type credentials.
The error concern fields that can be automaticaly retrieved.
- `public_key_fingerprint` for `ssh` type
- `password_hash` for `user` type

A workaround can be to delete all these fields from the export file as credhub will automaticaly retrieve them.

**Comment by shoudusse** [comment]
Issue opened on credhub project:
https://github.com/cloudfoundry-incubator/credhub/issues/47

**Comment by shoudusse** [comment]
Upstream bug has been fixed here: https://github.com/cloudfoundry-incubator/credhub-cli/commit/c3c89bdb728dee8ff0e650c8b2a1975c03340e7a

**Comment by poblin-orange** [comment]
fixed upstream
