### ISSUE TITLE
cf-apps use internet-proxy for smoke-tests broker requests

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1240]
### Expected behavior

* As a paas-templates operator
* In order to avoid internal requests emitted to `internet-proxy`
* I need brokers api requests don't use `internet-proxy`

### Observed behavior

Production environment, version 50

When checking `internet-proxy` access logs, we saw `502` http errors with request to <cf_api_fqdn>, maybe generated by brokers smoke tests:

```
coa-cf-mysql-broker.<cf_api_fqdn>
coa-cf-mysql-extended-broker.<cf_api_fqdn>
coa-mongodb-broker.<cf_api_fqdn>
coa-redis-extended-broker.<cf_api_fqdn>
intranet-proxy-sec-group-broker-filter.<cf_api_fqdn>
```

### Affected releases

* 51.0.6
* earlier versions

**Comment by gberche-orange** [comment]
Not reproducing on openstack lab environment, within core-connectivity k3s in the internet-proxy/internet-proxy pod

```
root@internet-proxy-7b5555b4d7-65z45:/# ls -al /var/log/squid/access.log
-rw-r----- 1 proxy proxy 147490 Nov 15 09:56 /var/log/squid/access.log
root@internet-proxy-7b5555b4d7-65z45:/# cat /var/log/squid/access.log | grep -i coa
root@internet-proxy-7b5555b4d7-65z45:/# date
Mon Nov 15 09:56:39 UTC 2021
```

**Comment by JCL38-ORANGE** [comment]
to be checked on v52/BRMC-INT

**Comment by gberche-orange** [comment]
Expected to be closed by removing dns recursors in pr https://github.com/orange-cloudfoundry/paas-templates-private/pull/972

>  Delete dns-recursor (use bosh-dns only in /etc/resolv.conf) for
>     remote-r2-depls
>     remote-r3-depls
>     micro-depls
>     ops-depls
>     master-depls
>
