### ISSUE TITLE
mysql shared/dedicated - updating the plan does not unlock the exceeded quota

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#1246]
### Expected behavior

* As a paas-templates user
* In order to 
* I need 

### Observed behavior

During control plane upgrade (v51) a customer exceeded his quota and updating his plan did not release the quota
 
### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
broker table holding the quota value was not updated by cf update-service for that particuler case.
