### ISSUE TITLE
redis extended - access to service interrupted during vpn update

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#1248]
### Expected behavior

* As a paas-templates user
* In order to 
* I need 

### Observed behavior

incident during the vpn update of version 51

- vpn r1: the master (r1) becomes slave and the app sees it in readonly
- vpn r2: the slave (r1) becomes master again and the app accesses it again (after 30 minutes)
- vpn r3: the master (r1) goes back to slave and a manual action (cf restart) is necessary to restore the service (cut of 3 hours)
  - why did the master become a slave when r3 was inaccessible?

- The client only uses the r1 proxy in the binding (not the second proxy)
- configuration of the pool in question? (duration of connections, + check of the connection)
- instruction had been given to set a tcp keep-alive to 300 (workaround of the NSX-T micro-cut "bug"). Can be linked?

 
### Affected releases

* 50.0.6
* 51.0.3
* earlier versions

**Comment by poblin-orange** [comment]
dev support needed to check correct redis configuration

**Comment by poblin-orange** [comment]
architecture: redis extended is fronted with haproxy bosh release (tcp mode, with a configuration ):

- https://redis.io/topics/clients#client-timeouts (default version 5).
- redis bosh release keeps default timeout parameter
- haproxy bosh release with default timeout parametre

**Comment by poblin-orange** [comment]
Client architecture: Spring Data Redis with lettuce. No explicit connection pool set.

references for connection pooling set up:
https://www.docs4dev.com/javadoc/en/org/springframework/spring-aop/5.2.9.RELEASE/org/springframework/aop/target/CommonsPool2TargetSource.html
https://docs.spring.io/spring-data/redis/docs/2.3.9.RELEASE/reference/html/#redis:connectors:connection

**Comment by JCL38-ORANGE** [comment]
It will be delivered on v52.
