### ISSUE TITLE
coab smoke tests failure - service provisionning timeout 

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1251]
### Expected behavior

* As a paas-templates operator 
* In order to have confidence no regressions were introduced in a release
 * I need to have green smoke tests 

### Observed behavior

coab smoke tests fail on `cf create-service` 

coab broker slow response from OSB provisionning triggers timeouts from cloudfoundry (maybe initial git clone delays taking the OSB create / http PUT request)

```
$ cf create-service mariadb-dedicated medium cf-mysql-smoketest-1628152566 -b p-coab-cf-mysql -c params.json
Creating service instance cf-mysql-smoketest-1628152566 in org service-sandbox / space coa-cf-mysql-smoke-tests as admin...
Unexpected Response
Response code: 504
CC code:       0
CC error code: 
Request ID:    25b68827-980f-4533-7476-119113268381::a118ca53-18f8-490d-b7ef-2228c698f6d8
Description:   {
  "description": "The request to the service broker timed out",
  "error_code": "CF-HttpClientTimeout",
  "code": 10001,
  "http": {
    "uri": "https://coa-cf-mysql-broker.<api_domain>/v2/service_instances/78480445-4bd7-4467-9ece-484674f19d5b?accepts_incomplete=true",
    "method": "PUT"
  }
}

```
 
### Affected releases

* 51.0.6

**Comment by poblin-orange** [comment]
successfull workaround with a tempo between broker cf push, and smoke tests launch

**Comment by gberche-orange** [comment]
@poblin-orange and @ogrand collected coab broker app diagnostic traces in private etherpad named `FE-INT-DEBUG`

`
2021-08-05T08:37:12.57+0000 [RTR/1] OUT coa-cf-mysql-broker.redacted-domain.org - [2021-08-05T08:36:12.56568118    5Z] "PUT /v2/service_instances/78480445-4bd7-4467-9ece-484674f19d5b?accepts_incomplete=true HTTP/1.1" 499 1285 22 "-" "HTTPClient/1.0 (2.8.3, ruby 2.7.2 (2020-10-01))" "192.168.35.69:36742" "192.168.35.79:61058" x_forwarded_for:"192.168.35.69" x_forwarded_    proto:"https" vcap_request_id:"ef2ad755-739a-4e5d-5615-2a021fda6166" response_time:60.004000 gorouter_time:0.000805 app_id:"cfb6    ae09-7e31-440b-8349-69b769bcf6e1" app_index:"0" x_cf_routererror:"endpoint_failure" x_b3_traceid:"03c4705c262a2c2c" x_b3_spanid:    "03c4705c262a2c2c" x_b3_parentspanid:"-" b3:"03c4705c262a2c2c-03c4705c262a2c2c"
`

From https://github.com/cloudfoundry/gorouter

> The value of the <code>X-Cf-Routererror</code> header can be one of the following:
> 
> 
> Value | Description
> -- | --
> [...]
> endpoint_failure | The registered endpoint for the desired route failed to handle the request.
> 

This seems to indicate the gorouter fronting the master-depls/cf is failing to obtain the http response after 60 seconds, whereas its [request_timeout_in_seconds](https://github.com/cloudfoundry/routing-release/blob/2e1cc8b89df0b569102489f7eda159107094fc9f/jobs/gorouter/spec#L337-L344) property is configured with the default 900s value.

> request_timeout_in_seconds:
>     description: |
>       This configures a "request timeout" and a "backend idle timeout".
>       Requests from router to backend endpoints that are longer than this duration will be canceled and logged as
>       `backend-request-timeout` errors. In addition, TCP connections between router and backend endpoints that
>       are idle for longer than this duration will be closed. Related properties: `router.max_idle_connections`
>       and `router.keep_alive_probe_interval`.
>     default: 900

The capi [cc.broker_client_timeout_seconds](https://github.com/cloudfoundry/capi-release/blob/789849795d7530aaaeb274bd0484aef498b8feb9/jobs/cloud_controller_ng/spec#L802-L804) is also configured to its default value (60s), explaining CC http client timeout

>   cc.broker_client_timeout_seconds:
>     default: 60
>     description: "For requests to service brokers, this is the HTTP (open and read) timeout setting."
> 

Alternative fixes:
* Coab optimizations to reduce sync response latency:
   * Eager git clone: https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/421
   * Replace pooled git clones with deep FS copies of a single git clone: https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/422
* Reduce size of git repos (paas-templates and paas-secrets) to speed up git clones

**Comment by gberche-orange** [comment]
@poblin-orange experiment with git repo prefetching at application startup (plus async pool refilling) shows a 50% reduction in provisionning response time on a paas-templates environment which is not under load and a single provisionning request: from 15s CSR to 7 s.

On a heavy loaded paas-templates environment where the service instance provisionning are failing on timeout, I observed a constant provisionning time for 1 concurrent request with 7s.

However, the risk on a highly loaded paas-templates environment (e.g. during wip-reset triggering many parallel git clones) with coab now performing 2 git clones at start up (templates+secrets) is:
* increase coab downtime during upgrades (coab app reaching start timeout)
   * coab app start run into [start timeout](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#timeout). Currently capped at cc.maximum_health_check_timeout=180. Observed `Started BoshBrokerApplication in 62.488 seconds (JVM running for 63.348)` 
* increased load on gitlab servers (each coab app restart triggering 2 git clones)

**Comment by poblin-orange** [comment]
@gberche-orange if we ensure cf push rolling upgrade is active for coab-depls, this should be ok. We also have other possible improvement (51 switch to k8s gitlab, secrets squashing, paas-templates coab instance branch squashing). Id rather avoid changing default cf timeout for the time being
