### ISSUE TITLE
Bosh deployment template dir naming consistency

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1252]
### Expected behavior

* As a paas-templates operator 
* In order to reduce cognitive complexity
* I need have a consistent naming across deployment subdirectory. So `template` dir should be renamed to `bosh-deployment-config`

### Observed behavior
For instances, concourse pipeline definitions are located in `concourse-pipeline-config`, whereas bosh deployment definitions are located in `template`
```
micro-depls/release-mgmt-github
└── concourse-pipeline-config
    ├── pipeline-vars-tpl.yml
    ├── Readme.md
    └── release-mgmt-github.yml
micro-depls/bosh-master
├── deployment-dependencies-openstack-hws.yml
├── deployment-dependencies-vsphere.yml
├── deployment-dependencies.yml
└── template
```
 
### Affected releases

* v51 and earlier versions

**Comment by poblin-orange** [comment]
impact on coab-depls might induce too much complexity wrt to maintability gain

**Comment by o-orand** [comment]
To ease implementation and reduce backward compatibility work on COA side:
* Paas templates - version N
   - [ ] first step, rename `template` to `bosh-deployment-config` and create a symlink   **/!\ This may not be compliant with COAB**
* Paas templates - version N+1
   - [ ] second step, upgrade COA to support only `bosh-deployment-config` and remove symlink
