### ISSUE TITLE
cf service access deactivated during update for extended services

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#1254]
### Expected behavior

* As a paas-templates operator
* In order to 
* I need 

### Observed behavior

During the update, cf service access are deactivated for extended services.
 
### Affected releases

* 51
* earlier versions

**Comment by JCL38-ORANGE** [comment]
solved with https://github.com/orange-cloudfoundry/paas-templates/issues/1118 in v52
