### ISSUE TITLE
prometheus alerting on concourse stalled workers

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1264]
### Expected behavior

* As a paas-templates operator 
* In order to 
  * detect stalled workers (which do silent non triggering of concourse job) 
* I need 

### Solution outline
Add a prometheus alert based on these metrics:
```
concourse_workers_registered{bosh_deployment="concourse",instance="192.168.116.161:9176",job="concourse",state="stalled"}
```

### Screenshots
![image](https://user-images.githubusercontent.com/18172904/149156572-ab21f92f-3142-4a21-a4f0-7948d28d55db.png)

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
Alternative UX:
* the following web nodes are reporting a positive number of stalled workers. Please identify stalled workers using `fly workers` command and purge them using `prune-worker -a`
```
concourse_workers_registered{bosh_deployment="concourse", bosh_job="web", exported_bosh_deployment="concourse", instance="192.168.116.160:9176", job="concourse", state="stalled"}
2
concourse_workers_registered{bosh_deployment="concourse", bosh_job="web", exported_bosh_deployment="concourse", instance="192.168.116.161:9176", job="concourse", state="stalled"}
0
concourse_workers_registered{bosh_deployment="concourse", bosh_job="web", exported_bosh_deployment="concourse", instance="192.168.116.162:9176", job="concourse", state="stalled"}
0
```
* At least one concourse web node reported a positive number of stalled worker: {}. Please identify stalled workers using `fly workers` command and purge them using `prune-worker -a`
2


Second approach seems more actionnable.
