### ISSUE TITLE
Bosh director coab capacity/tuning issues

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1267]
### Expected behavior

* As a paas-templates operator
* In order to support operations
* I need bosh director to not run out of resources

### Observed behavior
 
* bosh health manager process keep failing on bosh director REST api calls (restarted by monit)
* some bosh workers and director processes keep failing on db connection reset or lack available DB connections

Bosh health manager symptom
```
I, [2021-09-02T08:52:27.834174 #7506]  INFO : HealthMonitor shutting down...
F, [2021-09-02T08:52:27.838375 #7506] FATAL : undefined method `uri' for #<EventMachine::HttpClient:0x00007f559013d818>
F, [2021-09-02T08:52:27.838493 #7506] FATAL : /var/vcap/data/packages/health_monitor/f7d1f7d39e63df0d8785fd69d515655a27561af9/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/director.rb:36:in `get_deployment_instances'
/var/vcap/data/packages/health_monitor/f7d1f7d39e63df0d8785fd69d515655a27561af9/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:171:in `block in fetch_deployments'
/var/vcap/data/packages/health_monitor/f7d1f7d39e63df0d8785fd69d515655a27561af9/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:165:in `each'
/var/vcap/data/packages/health_monitor/f7d1f7d39e63df0d8785fd69d515655a27561af9/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:165:in `fetch_deployments'
/var/vcap/data/packages/health_monitor/f7d1f7d39e63df0d8785fd69d515655a27561af9/gem_home/ruby/2.6.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:121:in `block in poll_director'
```

Bosh director symptoms
```
E, [2021-09-01T08:37:11.585008 #4528] [] ERROR -- Director: PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.: (conn: 46976014361840) SELECT NULL
E, [2021-09-01T08:37:11.621374 #4528] [] ERROR -- DirectorWorker: 2021-09-01T08:37:11+0000: [Worker(worker_9)] Job Bosh::Director::Jobs::DBJob (id=27040800) (queue=urgent) FAILED (0 prior attempts) with Sequel::DatabaseConnectionError: PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections

E, [2021-09-01T08:37:11.621513 #4528] [] ERROR -- DirectorWorker: 2021-09-01T08:37:11+0000: [Worker(worker_9)] Job Bosh::Director::Jobs::DBJob (id=27040800) (queue=urgent) FAILED permanently because of 1 consecutive failures
```
and 
```
2021-09-02 09:08:05 GMT FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

### root causes

* potentially too high call rate to bosh
* lack of bosh director tuning

### possible fixes

* [ ] director tuning
   * [ ] get best practices and cf summit tuning guides
   * [ ] db sizing
   * [ ] system max open files

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
reference anynines bosh at scale https://blog.anynines.com/beyond-1000-bosh-deployments/#So_how_did_we_tackle_this

**Comment by JCL38-ORANGE** [comment]
actions performed at short term => purge queued bosh tasks never completed by director

**Comment by ogrand** [comment]
Workaround to stop `prometheus queued retrieve vm-stats` tasks which consume cpu

```
for task in $(bosh tasks | grep "queued" | grep "prometheus" | awk '{print $1}') ; do bosh cancel-task ${task} ; done
```

**Comment by ogrand** [comment]
Increase postgres connexions pool
https://bosh.io/jobs/postgres-10?source=github.com/cloudfoundry/bosh&version=271.8.0#p%3dpostgres.max_connections

```
    postgres:
      adapter: postgres
      additional_databases:
      - uaa
      database: bosh
      max_connections: 300
```

**Comment by gberche-orange** [comment]
<details>
<summary>bosh rest API statistics collected by @ogrand </summary> show important traffic from prometheus bosh exporter

```
    213 prometheus  GET /api metrics
  20767 prometheus  GET /deployments
    228 prometheus  GET /metrics
 413732 prometheus  GET /tasks

   1450 127.0.0.1 GET /configs
 368542 127.0.0.1 GET /deployments
    194 127.0.0.1 GET /info
  88193 127.0.0.1 POST /events

      2 concourse GET /deployment configs
    366 concourse GET /deployments
    272 concourse GET /info
      8 concourse GET /locks
    195 concourse GET /releases
  24228 concourse GET /tasks
      2 concourse POST /cleanup
      6 concourse POST /configs
     42 concourse POST /deployments
     38 concourse POST /releases

   8543 others GET /deployments
      2 others GET /info
  30448 others GET /tasks
```
</details>

Could be useful to try to reduce the director rest API load. 

The vmware vendor versions seems to include alternative exporters to the open source community exporter, not yet clear whether they are also shared with the opensource community
https://docs.pivotal.io/healthwatch/2-1/architecture.html
https://docs.pivotal.io/healthwatch/2-1/metrics.html

**Comment by gberche-orange** [comment]
Thanks @benjaminguttmann-avtq  for having pointed us to an alternative approach by email:

BOSH Health monitor is a component that listens to and responds to events (Heartbeats & Alerts) on the message bus (NATS) from bosh agents. 

HM receives for each job an associated heart beat event with the following metrics attached

https://github.com/cloudfoundry/bosh/blob/83813f6323c07d49a3af62fcff8e6a94209fadfc/src/bosh-monitor/lib/bosh/monitor/events/heartbeat.rb#L94-L109

>       def populate_metrics
>         add_metric('system.load.1m', @load[0]) if @load.is_a?(Array)
>         add_metric('system.cpu.user', @cpu['user'])
>         add_metric('system.cpu.sys', @cpu['sys'])
>         add_metric('system.cpu.wait', @cpu['wait'])
>         add_metric('system.mem.percent', @mem['percent'])
>         add_metric('system.mem.kb', @mem['kb'])
>         add_metric('system.swap.percent', @swap['percent'])
>         add_metric('system.swap.kb', @swap['kb'])
>         add_metric('system.disk.system.percent', @system_disk['percent'])
>         add_metric('system.disk.system.inode_percent', @system_disk['inode_percent'])
>         add_metric('system.disk.ephemeral.percent', @ephemeral_disk['percent'])
>         add_metric('system.disk.ephemeral.inode_percent', @ephemeral_disk['inode_percent'])
>         add_metric('system.disk.persistent.percent', @persistent_disk['percent'])
>         add_metric('system.disk.persistent.inode_percent', @persistent_disk['inode_percent'])
>         add_metric('system.healthy', @job_state == 'running' ? 1 : 0)
>       end

Plugins within bosh health monitor export these metrics to other systems without querying the bosh api to collect status about bosh jobs, and the hence stacking up bosh tasks.

See more details into 
https://github.com/cloudfoundry/bosh/blob/83813f6323c07d49a3af62fcff8e6a94209fadfc/src/bosh-monitor/README.md

The built-in graphite hm plugin exports these metrics into a graphite format
https://github.com/cloudfoundry/bosh/blob/83813f6323c07d49a3af62fcff8e6a94209fadfc/src/bosh-monitor/lib/bosh/monitor/plugins/graphite.rb#L24-L36

The hm graphite plugin can be enabled in bosh director using the following ops file https://github.com/cloudfoundry/bosh-deployment/blob/master/hm/graphite.yml

A graphite exporter such as https://github.com/prometheus/graphite_exporter can then reexpose the bosh health event metrics in prometheus format.

The prometheus bosh release bundles the graphite exporter see https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-graphite.yml

Ferran shared associated config of the graphite exporter in https://github.com/bosh-prometheus/bosh_tsdb_exporter/issues/1#issuecomment-396103057

This is also documented into https://github.com/bosh-prometheus/bosh_exporter/blob/master/FAQ.md#how-can-i-get-bosh-metrics-without-the-above-caveats

> The downside of the above approaches is that you will NOT get the same level of metrics that this exporter reports and you cannot use the service discovery approach.

**Comment by poblin-orange** [comment]
v52 exporter refactoring should reduce bosh-coab load (1 single boxh exporter to get a shared inventory).

Next steps, prometheus scraping reduction/optim, to consider with prometheus k8s migration #1152

**Comment by poblin-orange** [comment]
waiting for feedback of bosh-coab usage with v52 in production

**Comment by o-orand** [comment]
Fine with 8cpu-32g
