### ISSUE TITLE
bosh-cli/k8s-admin tool to solve namespace stuck in "Terminating" state

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1270]
### Expected behavior

* As a paas-templates operator
* In order to 
  * unlock a namespace in deletion, and be able to repair / reconstruct the ns 
* I need 
  * a script enabling a "force delete" of a namespace, despite finalizer blocking

NB; this tooling should be used if no other solution possible see # for clean operators suppression/reinstall

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
Script doing it

```
$ cat remove_finalizer.sh 
set -eou pipefail
namespace=$1
if [ -z "$namespace" ]
then
  echo "This script requires a namespace argument input. None found. Exiting."
  exit 1
fi
kubectl get namespace $namespace -o json | jq '.spec = {"finalizers":[]}' > rknf_tmp.json
kubectl proxy &
sleep 5
curl -H "Content-Type: application/json" -X PUT --data-binary @rknf_tmp.json http://localhost:8001/api/v1/namespaces/$namespace/finalize
pkill -9 -f "kubectl proxy"
rm rknf_tmp.json

```

**Comment by poblin-orange** [comment]
include in admin scripts

**Comment by gberche-orange** [comment]
Included as `admin/delete-k8s-ns.sh` by  https://github.com/orange-cloudfoundry/paas-templates-private/pull/946
