### ISSUE TITLE
coab mysql deployment - FS full due to prometheus

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#1274]
### Expected behavior

* As a paas-templates operator | marketplace user 
* In order to monitor / supervise th database
* I need to have prometheus working

### Observed behavior
 Prometheus is not working, because /var/vcap/store is full
2 solutions :
- increase disk size
- reduce time retention (prometheus.storage.tsdb.retention.time)/ set size limit for data (prometheus.storage.tsdb.retention.size)

### Affected releases

* 52

**Comment by JCL38-ORANGE** [comment]
It will be delivered in v52.
