### ISSUE TITLE
k8s core-connectivity openstack: bosh recreate loses arp vip connectivity, resulting in deadlock (v52 on openstack)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1275]
### Expected behavior

* As a paas-templates operator
* In order to 
  * update stemcell / or bosh recreate safely the micro-depls/00-core-connectivity-k8s on openstack
* I need 
  * a robust recreate path 

### Observed behavior
- bosh recreate
 - stops and recreate vms one by one
 - we see the metallb mechanism move vips to other vms while vm is recreating
 - but the openstack allow address pair is a post-deploy, only applied at the end. So we progressivly lose all inbound connectivity
 - when all vm are recreated, the post-deploy (based on k8s openstack-client image) starts, but k8s is unable to pull image
   - as of v51.0.0, it tries to reach 00-ci-k8s jcr, or micro-depls/jcr, both unreachable as core-connectivity cluster is unreachable  
 
This is the same problem as described in https://github.com/orange-cloudfoundry/paas-templates/issues/1161 reproducing in v52

The workaround is to manually edit the openstack-init DaemonSet to go through corporate docker proxy. Full details at https://github.com/orange-cloudfoundry/paas-templates/issues/1161#issuecomment-918248155

### Possible approach

* [ ] on the openstack profile, directly use `corporate_internet.dockerhub_mirror_url` in DaemonSet instead of relying on the jcr set in k3s `/var/vcap/jobs/k3s-server/config/registries.yaml` as  `https://docker.jcr-k8s.<redacted-paas-templates-domain>`

### Affected releases

* 52.0.0
* earlier versions

**Comment by poblin-orange** [comment]
as of v52, for openstack, direct access to corporate docker registry has been set

**Comment by poblin-orange** [comment]
@o-orand contribute evolution on openstack cpi to enable setting allowed-addres-pair by disabling ip check.
Scripting patch has been provided for v53 (waiting for PR merge + release https://github.com/cloudfoundry/bosh-openstack-cpi-release/pull/243 )
