### ISSUE TITLE
Git pushes to gitlab-k8s transiently fail with "cannot lock ref" (during race conditions)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1281]
### Expected behavior

* As a paas-templates operator 
* In order to operate the platform
* I need git push to succeed

### Observed behavior
 
`git push` command are transiently observed to fail with message

`remote: error: cannot lock ref 'refs/heads/master': is at 2430f7b2edbf3489930f75bae7eeff0607a71b21 but expected 9faf77085529353355572e148fd6648c6be6a635`

This is suspected to be race conditions writing to gitlab-k8s.

This was observed from coab git pushes in https://github.com/orange-cloudfoundry/paas-templates/issues/1223

This was also observed from vsphere integration environment in the `master-depls/pipelines/master-depls-bosh-generated/jobs/approve-and-delete-disabled-deployments` pipeline as part of 52.0.1 upgrade process

### Workaround

For idempotent concourse job, retrigger a new job with the same inputs 

### Possible fixes

* [ ] Check whether COA built-in [git push retries could/should be applied](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/05c03f5a8970c869f1591d53796e6a5bdb7e4731/docs/reference_dataset/template_repository/shared-config.yml#L7-L12)

### Affected releases

* 52.0.1
* earlier versions

**Comment by o-orand** [comment]
Missing retries on push have been included in https://github.com/orange-cloudfoundry/cf-ops-automation/pull/379. Waiting for a new COA release (probably in [5.2.3](https://github.com/orange-cloudfoundry/cf-ops-automation/releases/tag/v5.2.3))

**Comment by gberche-orange** [comment]
Also reproduced on `coab-depls/pipelines/coab-depls-bosh-generated/jobs/cloud-config-and-runtime-config-for-coab-depls`
![image](https://user-images.githubusercontent.com/4748380/142024500-b952c982-640d-41e1-9ae1-9f7d3efbd7b7.png)

**Comment by o-orand** [comment]
This case seems not to be correctly handled by concourse 😞 A retry is already in place, but ineffective: https://github.com/orange-cloudfoundry/cf-ops-automation/blob/2d8bf9c1e1c094ee0727b5c229fea713b300d236/concourse/pipelines/template/bosh-pipeline.yml.erb#L632-L637. I'm not sure we can do better easily.

**Comment by gberche-orange** [comment]
> 
> This case seems not to be correctly handled by concourse 😞 A retry is already in place on out integration instance, but ineffective: https://github.com/orange-cloudfoundry/cf-ops-automation/blob/2d8bf9c1e1c094ee0727b5c229fea713b300d236/concourse/pipelines/template/bosh-pipeline.yml.erb#L632-L637. I'm not sure we can do better easily.

@o-orand It seems that the retry fix was not yet bundled into COA v5.2.2 used in paas-templates v52.x, explaining why a retry isn't yet observed, and keeping hope that concourse is indeed properly handling the retry ;-)

https://github.com/orange-cloudfoundry/cf-ops-automation/blob/7582628fad5b9c7fab29cbb31a787d5b728d924c/concourse/pipelines/template/bosh-pipeline.yml.erb#L598-L635

**Comment by o-orand** [comment]
Included in next COA release (5.30)
