### ISSUE TITLE
decommission riakcs

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#129]
### Expected behavior

As a platform operator, we should be able to leverage public s3 like OBOS or iaas provided s3 solution for on demand backup

### Observed behavior
we have a legacy riakcs s3 service as of v34. Used by db-dumper service

**Comment by poblin-orange** [comment]
NB: riakcs release is ko with xenial, stick to trusty as of v39

**Comment by poblin-orange** [comment]
related issues on iaas-level s3 offering
#191

**Comment by JCL38-ORANGE** [comment]
Included in v41
