### ISSUE TITLE
new ops-depls-recurrent-tasks/retrigger-failed-jobs interferes with orchestrated release upgrade

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1295]
### Expected behavior

* As a paas-templates operator 
* In order to deploy the v52 release 
* I need the orchestrated deployment process in the upgrade process to apply

### Observed behavior
 
Failed jobs, including bosh errands which are not paused by the upgrade process are re-triggered by the ops-depls-recurrent-tasks/retrigger-failed-jobs

As a result, this breaks the orchestrated deployment process by applying v52 errands earlier than expected

### Considered alternatives

* include errands in the release upgrade pause/unpause job
   * This is complex because
      * list of errands associated to a deployment requires logic to be extracted. This logic is missing from admin scripts
      * to prevent `retrigger-failed-jobs`from restarting errands at any time, this would require unpause errand right after the associated deployment gets executed, in other worlds orchestrating errands un pause
* pause the `ops-depls-recurrent-tasks/retrigger-failed-jobs` during upgrade process
   * right after the precompilation jobs end, in order to benefit from `retrigger-failed-jobs` during precompilation

### Affected releases

* 52.0.1
* earlier versions

**Comment by o-orand** [comment]
Instead of pausing `retrigger-failed-jobs` after precompilation, we pause during `pre-merge` step, so we will benefit retriggering a little bit longer. And unpause this job during `post-upgrade`.
For 52, we have to pause it during `pre-upgrade`, as the pipeline does not exist before. It will be fine with future releases.
