### ISSUE TITLE
CF CLI v8 bump

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1298]
### Expected behavior

* As a marketplace user 
* In order to use paas-templates osb smoke tests as living documentation with an up-to-date CF CLI version
* I need paas-templates osb smoke tests smoke tests to be using [CF CLI V8](https://github.com/cloudfoundry/cli/releases/tag/v8.0.0)

> 
In v8 the cf CLI has been switched to using v3 CAPI to make service relates requests, most commands now have a new flag called --wait since v3 services code create async jobs, if you want to still synchronously wait you can use the new flag to wait for the operation to complete.

* As a paas-templates maintainer
* In order to deploy CF apps and operate master-depls/cf with an up-to-date CF CLI
* I need 
   * COA pipelines to be using CF CLI V8
   * docker bosh cli to be using CF CLI V8

### Observed behavior

COA images and docker bosh cli are using Cf CLI v7
 
### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
Probably forced by usage crossplane and interoperator

**Comment by gberche-orange** [comment]
usage of async service binding through osb-cmdb is also dependent on #1360

**Comment by gberche-orange** [comment]
* cf cli v8 regression observed with multi broker registration, see https://github.com/cloudfoundry/cli/issues/2269
   * affects osb-reverse-proxy on openstack integration platform due to `feature-osb-brokers-refactoring` bringing the same `o-intranet-proxy-access` service offering with a distinct service broker
