### ISSUE TITLE
Unability to deploy bosh-ops

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#131]
### Expected behavior

As ops, I expect that bosh-ops deployment (whithin bosh-master) deploys at first glance.

### Observed behavior

Unability to deploy bosh-ops during bootstrap

### Affected release

Reproduced on version 34.0.0

### Traces and logs
Worker thread raised exception: bosh-ops/68810236-27dc-4b97-8906-285d95b6f1f2: Timed out sending 'get_state' to e812864b-34d0-4a1c-814e-ec1cd0f031e8 after 45 seconds - /var/vcap/data/packages/director/7ce324440ef15820ffe57216433724b98358c961/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/assembler.rb:129:in `rescue in block (4 levels) in current_states_by_instance'

### Proposed working workaround 

bosh delete-deployment and retrigger concourse job

**Comment by poblin-orange** [comment]
This symptom correspond to FE iaas issues wrt connectivity. If you can reproduce, should open an issue on Flexible Engine iaas.

**Comment by poblin-orange** [comment]
to reopen if issue reoccurs with s3
