### ISSUE TITLE
Bootstrap - Unability to deploy isolation-segment-internet

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#134]
### Expected behavior

As an OPS, I expect to be able to deploy isolation-segment-internet without error.

### Observed behavior

Due to dependency of cf-internet-rps to isolation-segment-internet, we followed the Releases Notes v29.3 but encounter some errors. Seems that a credhub value is missing.

### Affected release

Reproduced on version 34.0.0 during a bootstrap

### Traces and logs

``` Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'router'. Errors are:
    - Unable to render templates for job 'gorouter'. Errors are:
      - Failed to find variable '/bosh-master/isolation-segment-internet/router_ssl' from config server: HTTP Code '404', Error: 'Credential not found. Please validate your input and retry your request.'
      - Failed to find variable '/bosh-master/isolation-segment-internet/router_ssl' from config server: HTTP Code '404', Error: 'Credential not found. Please validate your input and retry your request.'
```

**Comment by poblin-orange** [comment]
reproduced on v34+. As master-depls/cf-internet-rp offload the ssl, there is no point in activating ssl on internet-isolation-segment go routers
