### ISSUE TITLE
Documentation - intranet-interco-relay job

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#135]
### Expected behavior

intranet-interco-relay deployed thanks to Concourse job.

### Observed behavior

Error during, the deployment due to the lack of documentation. Need to add the correct certificates within those foders:
secrets/shared/certs/ops-certs/certs/
secrets/master-depls/cf/api-certificates/api-certs/
secrets/master-depls/cf-rps/secrets/apps-certs/certs/

### Affected release

Reproduced on version 33

**Comment by poblin-orange** [comment]
- standardization on cert location in secrets shared/certs. (internal certs managed with) credhub
- tooling wrt json schema #107 study

**Comment by poblin-orange** [comment]
v35 added a standard location description for certificates
