### ISSUE TITLE
new shared cf-mysql hosted on R2

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1354]
### Expected behavior
* As a paas-templates operator
* In order to ensure a good SLA
* I need to have a new shared cf-mysql cluster hosted on R2

### Observed behavior
The current shared cf-mysql cluster is hosting too many services and faces with overload issues (ulimits, backups, ...)  

### References
See orange private etherpad cfp-design-sessions-2 section "07/10"

**Comment by JCL38-ORANGE** [comment]
Add a FQDN instead of IP as binding credentials (TLS with PKI CA DNS4CLOUD)
