### ISSUE TITLE
Bootstrap - Ops-depls pipelines jobs in error due to bad credentials

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#136]
### Expected behavior

As an ops, I expect to be able to deploy ops-depls at first launch.

### Observed behavior

All deployments (cloud-config-and-runtime, deploy.sh, check-terraform) failed with error :
```
Failed to authenticate with UAA

Requesting token via client credentials grant:
  UAA responded with non-successful status code '401' response '{"error":"unauthorized","error_description":"Bad credentials"}'

Exit code 1
```
We override the bosh-master/bosh-ops/secrets/secrets.yml inherited file content with the credhub password for bosh-ops and performed a bosh recreate on master-depls/bosh-ops , then retrigger concourse bosh-ops job, without success on ops-depls pipelines jobs.

### Affected release

Reproduced on version 34.0.0

**Comment by poblin-orange** [comment]
can you follow v34 release note, and ensure the concourse credentials have been updated with credhub get -n /bosh-master/bosh_ops/admin_password ?
