### ISSUE TITLE
paas-templates-x.y.z.-upgrade/jobs/reset-paas-templates-WIP-to-reference results in unchanged cf apps/pipelines failing with 'reference is not a tree'

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1367]
### Expected behavior

* As a paas-templates operator
* In order to deploy v52.0.3
* I need cf apps/bosh-deployments/paas-templates pipelines to be able to be retriggered/refreshed

#### Cf apps

All cf apps jobs without change since last paas-templates version fail fetching the paas-templates concourse resource with error 

```
Cloning into '/tmp/build/get'...
Could not find ref 03d8de843b31ae64f8d8f9c031773fec6625bf2d~127 in a shallow clone of depth 128
Reached depth threshold 127, falling back to deep clone...

[...]
reference is not a tree
``` 

#### Pipelines

Same problem for coa support for concourse pipelines

![image](https://user-images.githubusercontent.com/4748380/139076016-bf4cd8ac-7331-4f9b-a347-ae8147830527.png)
![image](https://user-images.githubusercontent.com/4748380/139076085-7d0fcb08-5c12-4ca2-8120-64c3bd7fb080.png)

### Root cause

Given reference-wip-merged  has the following history when scoped to path `paas-templates/`
* commit a
* v51.0.0 tag. commit b
* `WIP Reset Complete` commit d
* custom feature branch commit e

reference-wip-merged scans the following history when scoped to path `paas-templates/ops-depls/cf-apps-deployments/admin-ui`
* commit a
* `WIP Reset Complete` commit d

Concourse job `ops-depls/pipelines/ops-depls-cf-apps-generated/jobs/cf-push-admin-ui` is a commit a, and its concourse git resource `paas-template-admin-ui` has a last commit at commit d

When installing v52, reference-wip-merged gets reset to reference, then following history get scanned scoped to path `paas-templates/`
* commit a
* v51.0.0 tag. commit b
* v52.0.0 tag. commit c

then following history is available when scoped to path `paas-templates/ops-depls/cf-apps-deployments/admin-ui` for resource `paas-template-admin-ui`
* commit a

Then Concourse job `ops-depls/pipelines/ops-depls-cf-apps-generated/jobs/cf-push-admin-ui` always tries to fetch the last detected commit d, which is now missing

`WIP Reset Complete` commit is always present in any cf app because it updates a `.last-reset` file in each path

### Reference

https://github.com/orange-cloudfoundry/cf-ops-automation/issues/144
https://github.com/orange-cloudfoundry/paas-templates/issues/681

### Alternative fixes

* in v53: **coa adds scan of `paas-templates/meta-inf` to cf-app (or any file which changes at least on each paas-templates version)**
   * will provide a fix for https://github.com/orange-cloudfoundry/cf-ops-automation/issues/144 for paas-templates operators: each paas-templates release will trigger each cf app job at least at each release
* add a fake bump commit to all cf apps without recent changes
   * admin-ui
   * ops-depls-cf-apps-generated/jobs/cf-push-intranet-proxy-sec-broker

### Workaround by operators

* **retrigger `main/pipelines/sync-feature-branches/jobs/recreate-features-wip-merged-branch/`**
* manually disable all coa reset commit `WIP Reset Complete`
   * drawback: time consumming
* delete the concourse pipeline and manually retrigger `/main/pipelines/control-plane/jobs/load-generated-pipeline`. 
   * drawback: concourse job history is lost

Note: the workaround has been observed to be applied in production in v51

### Affected releases

* 52.0.3
* earlier versions

**Comment by JCL38-ORANGE** [comment]
appears also after a bosh recreate of concourse (control-plane pipeline/on-git-commit job)
workaround applied = retrigger main/pipelines/sync-feature-branches/jobs/recreate-features-wip-merged-branch/
