### ISSUE TITLE
dedicated instance prometheus gets metrics from other service instances - v51

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1385]
### Expected behavior

* As a paas-templates marketplace user
* In order to 
* I need 

### Observed behavior

Seems we get parasit metrics on embedded prometheus
Might cause https://github.com/orange-cloudfoundry/paas-templates/issues/1375 
### Affected releases

* 51.0.6, production
* should not impact 52 due to metrics collection refactoring
  * wont fix
  * or production hotfix on 51 ?

**Comment by JCL38-ORANGE** [comment]
Not reproduced in v52. Only self service instance metrics are retrieved (other are dropped, can be checked from GUI Status/Service Discovery)
