### ISSUE TITLE
support for vsphere as bosh Iaas

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#14]
### Expected behavior

Runner expect to be able to use paas-templates on premise with vsphere

### Observed behavior
only openstack supported

### Affected release

Reproduced on version 38

### solution outline
- [ ] adapt haproxy vrrp connnections (ie: logsearch ingestor)
- [x] adapt dhcp ip allocation (eg: compilation network, no dhcp on vsphere)
- [x] adapt floating ip usage (eg: internet interco relay, no floating ip on vsphere)
- [x] adapt cloud-config for vm_type, disk_type, network, az mapping to vsphere cpi
- [x]  adapt bosh directors with vpshere cpi operators from bosh-deployment
- [ ] adapt network and security group (nsx, terraform)

### references:
- https://www.terraform.io/docs/providers/vsphere/
VSAN) 
- https://aws.amazon.com/vmware/features/
- https://cloud.vmware.com/vmc-aws 
- http://www.vmware.com/go/try-vmc-aws-hol
- https://github.com/vmware/govmomi/blob/master/vcsim/README.md

**Comment by gberche-orange** [comment]
Useful inspiration in upcoming opensource terraform-based automation around PCF https://github.com/pivotal-cf/terraforming-vsphere (which is following the way of [production-ready](https://docs.pivotal.io/search?q=terraform+&product_name=Pivotal+Cloud+Foundry&product_version=2.2) support of [AWS/Azure/GCP Terraform in PCF](https://github.com/pivotal-cf?utf8=%E2%9C%93&q=terraform&type=&language=))

**Comment by poblin-orange** [comment]
first step relies on predefined static networks (no nsx / terraform)
