### ISSUE TITLE
k3s based k8s clusters SPOF (single master node + backing store)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1405]
### Expected behavior

* As a paas-templates maintainer
* In order to 
   * avoid failure/downtime of colocated k8s workloads relying 
      * on the K8s api 
         * k8s agents/kubelets 
         * custom resource controllers
      * on the k8s core dns
      * on the k8s metrics server
   * apply one-shot non retried K8S API calls with [helm-kubectl-boshrelease](https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease) and concourse
   * avoid circular dependencies and deadlock with cross-cluster K8S api calls such as
      * routing declaration in core-connectivity cluster
* I need a reliable/ha K8S API on some|all k8s clusters 

### Observed behavior
 
* [ ] k3s-boshrelease does not yet support multi-master https://github.com/orange-cloudfoundry/k3s-boshrelease/issues/6
   * [ ] ha [K8S backing store](https://kubernetes.io/docs/concepts/overview/components/#etcd) vs the current mysql single node process
   * [x] instanciate two k8s master nodes
   * [x] expose a vip for handling active/standby of k8s master

### Affected releases

* 52.x
* earlier versions

**Comment by gberche-orange** [comment]
@poblin-orange for a vip mechanism based on keepalived, a custom healthcheck might help a fast failover:
-  using a command based on kubectl cli such as
   - `kubectl describe cluster` suggested into [Check Tanzu Kubernetes Cluster Health](https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-AFAAD7D6-8EF9-41EC-A6FC-ACCD802E0787.html)
- e.g. a curl based command using the K8S api health check endpoints https://kubernetes.io/docs/reference/using-api/health-checks/

See https://github.com/cloudfoundry/haproxy-boshrelease/blob/fe301a9cb082324cc9933e1c9b06e371c955dc97/jobs/keepalived/spec#L22-L27
>   keepalived.healthcheck_name:
>     description: label displayed for the health check. Will appear in keepalive traces e.g. "Keepalived_vrrp[4558] VRRP_Script(check_haproxy) failed"
>     default: check_haproxy
>   keepalived.healthcheck_command:
>     description: when health check fails, this triggers a fail over. The default command checks the haproxy process is still alive.
>     default: killall -0 haproxy

**Comment by poblin-orange** [comment]
as of v53, k3s bosh release 20 support external vip for api. Combined with keepalived (haproxy bosh release), we can offer a single vip with n masters (applied on ops-depls/00-shared-services).

The current backing store (mysql, pxc bosh release) could be scaled with galera to avoid datastore spof. 
However the k3s kine bridge relies on sequential auto-increment id, which are not continuous with galera. see https://github.com/k3s-io/kine/issues/71

**Comment by poblin-orange** [comment]
v56. switch 00-shared-services to k3s embeded etcd
