### ISSUE TITLE
CF : Unauthorized access to subscribed service dashboard for p-mysql client

### ISSUE THREAD

**Issue by mickaelso** [orange-cloudfoundry/paas-templates#141]
### Expected behavior
Url Dashboard doesn't allow p-mysql client to connect cf mysql dashboard services

### Observed behavior
Http 500 error when accessed

### Affected release
v32

### Traces and logs
192.168.99.31 - - [25/Sep/2018:14:23:04 +0000] "GET /500?code=uLJ9tGZxuy&state=af3096d2fbc332f30d5c5797a3a6beed HTTP/1.1" 500 - 0.1419
I, [2018-09-25T14:23:19.228747 #21692]  INFO -- : Started GET "/manage/auth/cloudfoundry" for 192.168.35.80 at 2018-09-25 14:23:19 +0000
I, [2018-09-25T14:23:19.231361 #21692]  INFO -- omniauth: (cloudfoundry) Request phase initiated.
I, [2018-09-25T14:23:19.232304 #21692]  INFO -- omniauth: (cloudfoundry) Client: p-mysql auth_server: https://login.nd-cfapi.itn.ftgroup token_server: https://uaa.nd-cfapi.itn.ftgroup
I, [2018-09-25T14:23:19.233951 #21692]  INFO -- omniauth: (cloudfoundry) Redirect URI https://login.nd-cfapi.itn.ftgroup/oauth/authorize?client_id=p-mysql&response_type=code&redirect_uri=https%3A%2F%2Fp-mysql.nd-cfapi.itn.ftgroup%2Fmanage%2Fauth%2Fcloudfoundry%2Fcallback&state=9beedfc0a73c1ddff65c9554a91850e0&scope=cloud_controller_service_permissions.read+openid&nonce=9beedfc0a73c1ddff65c9554a91850e0

p-mysql is not configured into cf operators files for uaa synchronisation with credhub.
A manual synchronisation from the credhub to the uaa solve the problem and lead to a 401 error that prevent user from consulting his dashboard.

**Comment by poblin-orange** [comment]
fixed on v41
