### ISSUE TITLE
mongodb oplog file size must be increased in order to perform succesful backups (shared and dedicated)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1411]
### Expected behavior
* As a paas-templates operator
* In order to be confident with my platform
* I need to have succesful backups in case of recovery 

### Observed behavior
mongodb backups fails because oplog file size is too short
 
### Affected releases
v51/52

**Comment by CDallosto-orange** [comment]
Oplog-file-size configuration parameter is used to set the value during cluster creation.
To update the value inside the cluster, we have to set it in each node.
- Secondary nodes :
```sql
# Write activation
rs0:SECONDARY> rs.slaveOk()
```
- All nodes :
```sql
# Verify value
rs0:SECONDARY/PRIMARY> rs.printReplicationInfo()
configured oplog size: 256MB

# Set value (here : 8192MB)
rs0:SECONDARY/PRIMARY> db.adminCommand({replSetResizeOplog:1,size: 8192})

# Verify new value
rs0:SECONDARY/PRIMARY> rs.printReplicationInfo()
configured oplog size:   8192MB
```
