### ISSUE TITLE
validate.nginx.ingress.kubernetes.io x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1421]
### Expected behavior

* As a paas-templates operator
* In order to 
* I need 

### Observed behavior
 
upgrading nginx-ingress result in failure applying ingress:

```
kustomization/10-openldap.fluxcd

Ingress/openldap/phpldapadmin dry-run failed, reason: InternalError, error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": x509: certificate signed by unknown authority
revision

master/2d68ff569b6be8b8867bc896799a0af7e80ef39c
summary

01-ci-k8s.fe-int
```

### workaround

```
CA=$(kubectl -n ingress-nginx get secret ingress-nginx-admission -ojsonpath='{.data.ca}')
kubectl patch validatingwebhookconfigurations ingress-nginx-admission --type='json' -p='[{"op": "add", "path": "/webhooks/0/clientConfig/caBundle", "value":"'$CA'"}]'

```
see https://github.com/kubernetes/ingress-nginx/issues/5968#issuecomment-849772666

### root cause
the nginx-ingress helm chart was in failure state. The correct ca bundle is set as helm post-install, was not set as helm install was not successfull

see https://github.com/kubernetes/ingress-nginx/issues/5968#issuecomment-936047702

### Affected releases

* x.y
* earlier versions

**Comment by sbkg0002** [comment]
Some troubles here while upgrading from 3.23 > 4.0.9.

**Comment by gberche-orange** [comment]
Observed on 56.0.3 on 00-ha-datastore with 4.7.1

The corresponding source code of the Job to patch the admission webhook seems to be at
https://github.com/kubernetes/ingress-nginx/blame/helm-chart-4.7.1/charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
> {{- if and .Values.controller.admissionWebhooks.enabled .Values.controller.admissionWebhooks.patch.enabled (not .Values.controller.admissionWebhooks.certManager.enabled) -}}
> apiVersion: batch/v1
> kind: Job

No trace of the Job being run
