### ISSUE TITLE
ops tasks need to dynamically stop prometheus scrapping to bosh-directors

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1439]
### Expected behavior

* As a paas-templates operator
* In order to use available bosh director task processing capacity to perform cert rotation within a reasonable time
* I need to dynamically stop/start prometheus scrapping to selected bosh-director, when using k8s supervision cluster 
   * this would reduce bosh director api calls made by prometheus bosh exporter

### Observed behavior

Some ops tasks need to stop scrapping metrics from prometheus to bosh directors.
With bosh deployments, we used to stop `prometheus2` instances of the associated prometheus-exporter to achieve this.
We need a similar mecanism on `supervision` cluster to dynamically start/stop those scrappings.

### Affected releases

* 53 and earlier versions

**Comment by poblin-orange** [comment]
workaround;
- log-k8s, 00-supervision, namespace 00-flux-kustomization
- suspend fluxcd Kustomization (eg: 15-prometheus-coab).  <shift-t> Toggle suspend/resume on k9S
- delete ServiceMonitor bosh-exporter-service-monitor (this will disable prometheus scrape to bosh director. Will be recreated once fluxcd is unpaused)
