### ISSUE TITLE
logsearch apps service not indexing json payload (eg: spanId and traceId fields)

### ISSUE THREAD

**Issue by bfourtanier-orange** [orange-cloudfoundry/paas-templates#144]
### Expected behavior
As a microservices developer using Spring Cloud Sleuth in my apps and the logsearch service, I would expect to be able to search applicative logs in Kibana using spanId and traceId fields.

### Observed behavior
Searches using the (app.)spanId, (app.)traceId, x-b3-spanid, x-b3-traceId do not return any results. 

I am using a logback logstash encoder to produce a JSON output to my logs, as per the following logback config:

```xml
<appender name="JSON" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <!-- computes and adds a 'stack_hash' field on errors -->
            <provider class="net.logstash.logback.composite.loggingevent.StackHashJsonProvider">
                <exclusions>${STE_EXCLUSIONS}</exclusions>
            </provider>
            <!-- enriches the stack trace with unique hash -->
            <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
                <inlineHash>true</inlineHash>
                <exclusions>${STE_EXCLUSIONS}</exclusions>
            </throwableConverter>
            <customFields>{"@project":"${MD_PROJECT:--}","@type":"java"}</customFields>

        </encoder>
    </appender>
```
The CF log console still shows a JSON log output containing all the fields, including spanId, traceId, X-B3-TraceId, X-B3-SpanId.

**Comment by pismy** [comment]
See https://github.com/cloudfoundry-community/logsearch-boshrelease#common-customisations
?

**Comment by JCL38-ORANGE** [comment]
**05/07/2019 status** 
Not reproduced in production : log level is correctly parsed, (app.)spanId, (app.)traceId, x-b3-spanid, x-b3-traceId are searchable.
The good configuration at client side is available on cloud native burger tutorial. With this configuration, there is no issue on the production platform.
