### ISSUE TITLE
Spike argo-workflow for osb smoke tests

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1442]
### Expected behavior

* As a paas-templates maintainer
* In order to productively maintain smoke test infrastructure #1260
* I need a high level framework with functions to reuse

### Observed behavior
 
Extract from design session on 26/11/2020

- https://argoproj.github.io/argo/examples/
  - submit, cancel, see logs
  - parameters
  - retry
  - loops https://argoproj.github.io/argo/examples/#loops
  - exit handlers https://argoproj.github.io/argo/examples/#exit-handlers
    - sending notifications of workflow status (e.g., e-mail/Slack)
    - posting the pass/fail status to a webhook result (e.g. GitHub build result)
    - resubmitting or submitting another workflow
  - ide completion support https://argoproj.github.io/argo/ide-setup/
  - metrics exposed https://argoproj.github.io/argo/variables/#metrics
    - workflow.status
    - workflow.failures
    - For Workflow-level metrics: * workflow.duration
    - For Template-level metrics: * duration
- rbac https://argoproj.github.io/argo/workflow-rbac/
- cron workflows https://argoproj.github.io/argo/cron-workflows/
- https://argoproj.github.io/argo/workflow-pod-security-context/ workflows run as root by default, possibilit to run as non root and configure pod security context
  - https://argoproj.github.io/argo/workflow-requirements/ ability to only run unmodified workflow instances from templates
  - > As the administrator of the controller, you may want to limit which types of Workflows your users can run. Setting workflow restrictions allows you to ensure that Workflows comply with certain requirements. 
- https://argoproj.github.io/argo/rest-api/
  - https://raw.githubusercontent.com/argoproj/argo/master/api/openapi-spec/swagger.json
- https://argoproj.github.io/argo/cost-optimisation/
  - > S3 storage, vs PVs (depending on backing storage NFS vs EBS) and bandwidth costs
- https://argoproj.github.io/argo/architecture/
- UI
  - https://www.youtube.com/channel/UCOvYmppcbOPm1viN6ust3lA
    - https://youtu.be/TZgLkCFQ2tk?t=93 UI demo
    - https://github.com/orange-cloudfoundry/paas-templates/issues/1012

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
to check with https://github.com/orange-cloudfoundry/paas-templates-private/pull/1063
