### ISSUE TITLE
[Bootstrap] Associate Nat gateway floating ip 

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#145]
Error during step 4 deployment (terraform.sh)

Replace 
openstack floating ip set --port $(openstack port list -f value --noindent | grep **"192.168.20.2"** | awk '{print $1}') <natgw floating IP> 
by 
openstack floating ip set --port $(openstack port list -f value --noindent | grep **"192.168.20.2'"** | awk '{print $1}') <natgw floating IP>
<!-- 
### Affected release
v35.0.0

Reproduced on version x.y
 v30.0.0 to v35.0.0

**Comment by poblin-orange** [comment]
fixed in 35.0.1
