### ISSUE TITLE
all bosh jobs must be triggered by COA bump 

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1456]
### Expected behavior
* As a paas-templates operator
* In order to be confident with my platform
* I need all bosh jobs be triggered by COA bump

### Observed behavior
deploy-00-core-connectivity-k8s, deploy-k8s-jcr, deploy-k8s-gitlab are not triggered by the COA upgrade pipeline (job unpause-micro-depls-bosh-jobs)
 
### Workaround
Manually unpause jobs
* deploy-k8s-jcr
* deploy-k8s-gitlab
* deploy-00-core-connectivity-k8s

### Affected releases
v53.0.0

**Comment by o-orand** [comment]
As k8s-jcr is removed in this release, I think we can skip it. Others need to be managed.
