### ISSUE TITLE
upload-openstack-stemcell-on-bosh-coab fails during paas-templates 53 upgrade

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1457]
### Expected behavior
* As a paas-templates operator
* In order to be confident during upgrade process
* I need all pipeline upgrade jobs turn green

### Observed behavior
 upload-openstack-stemcell-on-bosh-coab jon turns red

### Affected releases
v53

### Traces
**v52 (success)**
IP validated for bosh-coab(192.168.99.155)
Processing bosh-coab(192.168.99.155)
Successfully authenticated...
Succeeded
Using environment '192.168.99.155' as client 'admin'
...

**v53 (failure)**
bosh-coab.internal.paas has address 192.168.99.155
Processing bosh-coab(bosh-coab.internal.paas)
Processing bosh-coab(bosh-coab.internal.paas)
Fetching info:
  Performing request GET 'https://bosh-coab.internal.paas:25555/info':
    Performing GET request:
      Retry: Get "https://bosh-coab.internal.paas:25555/info": Forbidden
Exit code 1

**Comment by JCL38-ORANGE** [comment]
no_proxy problem

**Comment by o-orand** [comment]
Starting with v53, we switch bosh IP to dns name. But bosh director dns name were not listed in no_proxy, so we add it in v53. But thoses dns name in no_proxy won't be usable until concourse in deployed during v53 upgade.
As workaround, it is possible to hijack to concourse containers:
```
# log fly
# hijack
fly -t <target_name> hijack -u <concourse_job_url>
  # choose a failed step
# include 'internal.paas' url to no_proxy
export no_proxy=$no_proxy,internal.paas
# relaunch failing op
./script.sh
```
