### ISSUE TITLE
remove debug profiles settings for all bosh directors

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1462]
### Expected behavior
* As a paas-templates operator
* In order to avoid ip conflicts
* I need to have debug profiles disabled for all bosh-directors

### Observed behavior
remote-r2-depls and remote-r3-depls have the debug profile enabled 

### Affected releases
53.0.0 and prior

**Comment by poblin-orange** [comment]
As bosh ssh is ko to remote-r2-depls/00-bootstrap, having a predictible root password can be usefull for direct ssh with vcap user
