### ISSUE TITLE
deploy-00-core-connectivity-k8s job (k8s bridge) fails because of missing credhub values

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1465]
### Expected behavior
* As a paas-templates operator 
* In order to be confident with my platform upgrade
* I need all jobs turn green

### Observed behavior
micro-depls-generated/deploy-00-core-connectivity-k8s job (k8s bridge) fails during execute-shell task
 
### Traces in concourse job
...
+ for file in ${MANIFESTS}
++ dirname 00-flux-kustomizations/05-traefik-kustomization.yaml
+ mkdir -p /tmp/build/d17f1a38/result-dir/micro-depls/00-core-connectivity-k8s/k8s-config/manifests/00-flux-kustomizations
+ grep -q '((' 00-flux-kustomizations/05-traefik-kustomization.yaml
+ credhub interpolate -f 00-flux-kustomizations/05-traefik-kustomization.yaml -p micro-bosh/00-core-connectivity-k8s
Expected to find variables: /uaa/connectivity-client-secret
/uaa/connectivity-cookie-secret
...

### Affected releases
v53.0.0

**Comment by poblin-orange** [comment]
cyclic dependency (secrets generated by ops-routing/uaa bosh deployment variables section)
