### ISSUE TITLE
[Bootstrap] Step 6 Deploy micro-depls minimal prerequisites

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#147]
### Expected behavior
Upload docker bosh release

### Observed behavior

Upload bosh release "git+https://github.com/cloudfoundry-incubator/docker-boshrelease --version=32.0.0"...
- Expected to find 'golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86'

Exit code 1

Bosh upload release "git+https://github.com/cloudfoundry-incubator/docker-boshrelease --version=32.0.0" failed.

To fix, we add a comment in deploy-micro-depls.sh:
       #uploadRelease "docker" "docker-boshrelease" "https://github.com/cloudfoundry-community/docker-boshrelease --version=" "git"
    and execute manually:
    bosh upload-release https://github.com/cloudfoundry-incubator/docker-boshrelease/releases/download/v32.0.0/docker-32.0.0.tgz

### Affected release
v35.0.0

**Comment by poblin-orange** [comment]
fixed in 35.0.1
