### ISSUE TITLE
[Bootstrap] log-bosh tools

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#148]
### Observed behavior
ERROR : Log to bosh director "micro" failed.

### Affected release
v35.0.0

### Traces and logs
Failed to authenticate with UAA

Requesting token via client credentials grant:
  UAA responded with non-successful status code '401' response '{"error":"unauthorized","error_description":"Bad credentials"}'
Exit code 1
ERROR : Log to bosh director "micro" failed.

=> Fix : to connect on micro-bosh, we have to add the following lines after "unset BOSH_CLIENT_SECRET":
    export BOSH_CLIENT="admin"
    export BOSH_CLIENT_SECRET=`bosh int ${SHARED_SECRETS} --path /secrets/bosh/admin/password`

**Comment by poblin-orange** [comment]
could not reproduce on 35.0.0.

**Comment by aurelienbouleau** [comment]
Reproduced on 35.0.1 on bootstrap machine (not on docker-bosh-cli) :

Same error for micro-bosh as above and also for master-bosh:
```
Director BOSH :

1 : micro
2 : master
3 : ops
4 : kubo
5 : coab
6 : ondemand
7 : expe

Your choice : 2
Enter CF LDAP user and password :
Failed to authenticate with UAA

Requesting token via client credentials grant:
  UAA responded with non-successful status code '401' response '{"error":"unauthorized","error_description":"Bad credentials"}'

Exit code 1


ERROR : Log to bosh director "master" failed.

```

**Comment by poblin-orange** [comment]
suggest cleaning bosh coordinate in ~/.bosh (might be from a previous bootstrap)

**Comment by ogrand** [comment]
Can't reproduce on v35.0. and v35.0.1 on FE-DEV and FE-INT tenants
~/.bosh may keep reference to static old account.
Using uaa/ldap change this functionnality.
You have to delete this directory once on the bootstap instance.
rm -fr ~/.bosh
When log-bosh tells you to set credentials for micro-bosh, log with admin account (password defined in shared/secrets.yml).
Bosh-master and other bosh directors save their admin passwords in credhub.
