### ISSUE TITLE
no fluxcd notifications with v53.0.0 upgrade

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1484]
### Expected behavior
* As a paas-templates operator 
* In order to have information on my platform
* I need to receive both concourse and fluxcd notifications on my slack channel

### Observed behavior
no notification received in mattermost channel

### paas-templates file configuration
fluxcd-notification-provider-patch.yaml (bad information in secrets ?)

### Affected releases
v53.0.0

**Comment by poblin-orange** [comment]
flux notification use shared/secrets.yml credhub configuration.
Align prometheus with credhub (not local secrets)
Align COA secrets to credhub configuration

The aim is to have a single slack mattermost channel for:
- concourse COA notif
- fluxcf notif
- prometheus alert manager notif
