### ISSUE TITLE
[Bootstrap] Step 6 Deploy micro-depls - missing folder

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#150]
When we relaunch deploy-micro-depls.sh, errors occured.

### Affected release
v35.0.1

### Trace
./deploy.sh: 104: ./deploy.sh: cannot create /home/cloud/bosh/secrets/micro-depls/credhub-ha/secrets/certs/**credub-certs**/server.crt: Directory nonexistent
./deploy.sh: 105: ./deploy.sh: cannot create /home/cloud/bosh/secrets/micro-depls/credhub-ha/secrets/certs/**credub-certs**/server.key: Directory nonexistent
./deploy.sh: 106: ./deploy.sh: cannot create /home/cloud/bosh/secrets/micro-depls/credhub-ha/secrets/certs/**uaa-credub-certs**/server.crt: Directory nonexistent
./deploy.sh: 107: ./deploy.sh: cannot create /home/cloud/bosh/secrets/micro-depls/credhub-ha/secrets/certs/**uaa-credub-certs**/server.key: Directory nonexistent

Generate jwt private and public keys...
Saving key "/home/cloud/bosh/secrets/micro-depls/credhub-ha/secrets/certs/uaa" failed: No such file or directory
./deploy.sh: 113: ./deploy.sh: cannot create /home/cloud/bosh/secrets/micro-depls/credhub-ha/secrets/certs/uaa.pub: Directory nonexistent

Fix: 
mkdir -p ${SECRETS_REPO}/micro-depls/${DEPLOYMENT}/secrets/certs/{credhub-certs,uaa-credhub-certs,internal_paas-ca}

**Comment by poblin-orange** [comment]
fixed in 35.0.2
