### ISSUE TITLE
Scrape errors of some prometheus for intranet-facing IP address of coab services mysql-extended proxy vms

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1516]
### Expected behavior

* As a paas-templates operator 
* In order to handle alarms
* I need no false alarms

and

* As a paas-templates operator 
* In order to monitor coab vms 
* I need the nodeexporter to scrape correctly coab instances with both intranet and private IP (cf-mysql-extended proxy)

#### scrape errors
Scrape alarms for some coab instance intranet IP addresses (deployment identified with #1514) are raised.

This is a side effect of branch `feature-add-bosh-metric` merged in v53 in order for discovery of the intranet facing coab vms by their dedicated prometheus instance (which is a prereq for metrics to be collected)

Additional private notes in pad issue-1516

#### missing node exporter in prometheus-coab inventory

the cf-mysql-extended deployments don't have their r2-z1 proxy nodes private IP adress in the prometheus-coab inventory (bosh_target_groups.json file)

### Possible fixes
* fix the routing problem preventing prometheus-exporter-coab from reaching intranet IP (i.e allow prometheus-exporter-coab (z1) to reach public IP (r2-z1))
* refine the scraping filter to exclude intranet ip addresses from cf-mysql-extended jobs and rather use private IP addresses

### Affected releases

* 52.x with `feature-add-bosh-metric` 
* 53.0.1
* earlier versions

**Comment by JCL38-ORANGE** [comment]
I think it is not possible to apply "refine the scraping filter to exclude intranet ip addresses from cf-mysql-extended jobs and rather use private IP addresses" because private IP adress is not present in the discovery file (bosh_target_groups.json file).

**Comment by JCL38-ORANGE** [comment]
as explained there https://github.com/bosh-prometheus/bosh_exporter/pull/18, it is possible to select : 
*VM with both private IP and public IP -> select private IP (case of r2-z1 proxy for mysql-extended)
*VM with only public IP -> select public IP (case of mongodb node)
```
        filter:
          cidrs: "192.168.0.0/16,10.0.0.0/8"
```
