### ISSUE TITLE
step-0-pause-git-flux-scan turns red during v53.0.1 upgrade

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1517]
### Expected behavior
* As a paas-templates operator 
* In order to be confident with my platform upgrade
* I need all jobs turn green

### Observed behavior
step-0-pause-git-flux-scan turns red because k3s-sandbox k8s cluster has been deleted and its credentials remain in credhub

### Workaround
clean credhub entry /kubeconfigs/00-sandbox
 
### Affected releases
v53.0.1

**Comment by o-orand** [comment]
This should occur only on brmc-int, as sandbox has not been activated on preprod and prod env.
