### ISSUE TITLE
bosh coab always recreates vm with multi-cpi and different stemcells (eg: vpshere and openstack) even if it not necessary (bad stemcell change detection)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1546]
### Expected behavior
* As a paas-templates operator
* In order to save time during PTF maintenance
* I need vm recreation only during stemcell bump

### Observed behavior
VM recreation occurs even if there is no change in the manifest
 
### Affected releases
v53.0.3

### Traces and logs
See https://github.com/cloudfoundry/bosh/issues/2363

**Comment by JCL38-ORANGE** [comment]
Story added in pivotal tracker (private)

**Comment by JCL38-ORANGE** [comment]
Workaround applied as hot fix in v53 and merged in v54

**Comment by poblin-orange** [comment]
fixed upstream, waiting for release (see https://github.com/cloudfoundry/bosh/issues/2363)

**Comment by JCL38-ORANGE** [comment]
Regression in v56
