### ISSUE TITLE
Trigger jobs when new paas-templates version is released

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1547]
### Expected behavior

* As a paas-templates operator
* In order to have deployments inline with paas-template version
* I need deployments without changes to be redeployed and resulting manifest to include accurate paas template version.

### Observed behavior
Deployments without changes does not detect accurate version of paas-templates. Related to #1366

### Affected releases

* 53.x with COA 5.3
* earlier versions

**Comment by gberche-orange** [comment]
Manual workaround tested by @JCL38-ORANGE of commenting return line on bosh director at https://github.com/cloudfoundry/bosh/blob/da56d19e30234239582ecfdd6a2da682631f6832/src/bosh-director/lib/bosh/director/deployment_plan/instance_plan.rb#L458

**Comment by o-orand** [comment]
Closing, considered as duplicate of of #1366.
