### ISSUE TITLE
leverage harbor registry

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1552]
### Expected behavior

* As a paas-templates operator
* In order to
  * benefit from ha
  * docker image security scan
  * helm repo feature ? 
* I need 

### Observed behavior

- harbor features
  - api availability
  - replication feature (eg par region harbor docker registry)  #1449
  - docker image security scan (trivy / clair )
     - FYI: use of trivy by crossplane in https://togithub.com/crossplane/crossplane/pull/4000
  - missing aggregation feature (docker registry, helm repo) ?
  - granular http proxy support (intranet / internet)
  - generic registry support ?  #621
 
### Affected releases

* 54
* earlier versions

**Comment by o-orand** [comment]
Current limitation with harbor:
* it seems not possible to proxy helm release, only hosting is supported,
* it is not possible to define a proxy per endpoint, so we have to create an harbor dedicated to internet, and chain it to an internet one.

Architecture overview:
![overview](https://www.plantuml.com/plantuml/png/bP0_JyD03CLtVmgh2nBe20micIh104nHrwg3Ux6IqFiJEGu28RuxvIf4Sn6H66vvztxFpruFIgAZTt3HglP3MHIze_2jNDleY-FhO-2Wfkwe4V80riMnnW_0RJNkNMVn8Te32swuwGQLznry0lHa3zGmhcvlJ4koZsBazD_ni4hqOvBnAIXBODrD9A4aJPBkp8kLonFyVB-P3eI_sg0nkFqPWfN4joEmQAwaUoNb-LvvJ7BdQs29TG8X2vfN4Zghb0l9b1_aDtlkpevIOilEuzKvmV8VOlgxt6TsXcNxcaCzUlS5)

**Comment by o-orand** [comment]
Harbor configuration automation is done using terraform (https://registry.terraform.io/providers/BESTSELLER/harbor/latest/docs) 

## Limitations
 [ ] htpasswd brypt encoding required manual op
 [ ] S3 bucket backend is created manually
 [ ] Cyclic dependency between minio and harbor when s3 backend is used
 [ ] Full namespace recreation not tested 
 [ ] TF spec files in config maps is not working
 [ ] K8s backend does not work properly

**Comment by o-orand** [comment]
#1584

**Comment by poblin-orange** [comment]
Firt install on v54, for troubleshooting and future live usage on v55

**Comment by poblin-orange** [comment]
waiting for fix release https://github.com/isaaguilar/terraform-operator/issues/102
