### ISSUE TITLE
COAB Rabbitmq extended broker disk quota exceeded

### ISSUE THREAD

**Issue by njoubert-orange** [orange-cloudfoundry/paas-templates#1557]
### Expected behavior

* As a paas-templates operator
* In order to create rabbitmq-extended instance
* I need enough disk space on the coa cf app

https://github.com/orange-cloudfoundry/paas-templates/issues/1075

done : bump the cf disk quota to 1,5 GB

**Comment by JCL38-ORANGE** [comment]
fixed in https://github.com/orange-cloudfoundry/paas-templates-private/pull/1136
