### ISSUE TITLE
[Bootstrap] Step 10: Deploy master-depls jobs manually with Concourse - following pipeline master-depls-init-generated wrong typo

### ISSUE THREAD

**Issue by wdesplas** [orange-cloudfoundry/paas-templates#157]
**Affected Release**
v35.0.1

**Explaination**
The step "manually unpause following pipeline **master-depls-init-generated** and trigger init-concourse-boshrelease-and-stemcell-for-master-depls" must be  "manually unpause following pipeline **master-depls-generated** and trigger init-concourse-boshrelease-and-stemcell-for-master-depls".

**Comment by poblin-orange** [comment]
fixed in 35.0.2
