### ISSUE TITLE
[Bootstrap] Step 10: Deploy master-depls jobs manually with Concourse - ops-routing dependencies failed

### ISSUE THREAD

**Issue by wdesplas** [orange-cloudfoundry/paas-templates#158]
**Observed behavior**
The shield deployment failed due to the  ops-routing dependencie after refering to the documentation.
In fact, dependencies to cf-internet-rps to isolation-segment-internet will put the job in a failed statement.
The documentation related to bosh-master deployments does not driver properly and the jobs scheduling should be first ops-routing, then prometheus (for intranet-interco-relay)

**Affected Release**
v35.0.1

**Comment by poblin-orange** [comment]
correct initial deployment order is now documented in bootstrap README.MD
see 35.0.2
