### ISSUE TITLE
Fluxcd HelmRelease stuck in the "upgrade retries exhausted"

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1581]
### Expected behavior

* As a paas-templates operator | paas-templates author 
* In order to recover from a Helm release fluxcd deployment stuck in the UpgradeFailed, upgrade retries exhausted state
* I need a workaround

### Observed behavior
 
Describe on the HelmRelease fluxcd resource shows

```
warning: Upgrade "minio" failed: post-upgrade hooks failed: timed out waiting for the condition
  Normal  error  34m                    helm-controller  reconciliation failed: Helm upgrade failed: post-upgrade hooks failed: timed out waiting for the condition
  Normal  error  10m (x418 over 4d15h)  helm-controller  reconciliation failed: upgrade retries exhausted
``` 

### Workaround

Suspend the resource and unsuspend (using k9s or manually, see docs at https://fluxcd.io/docs/components/helm/helmreleases/#reconciliation )

### Reference

https://github.com/fluxcd/helm-controller/issues/454

### Affected releases

* 54.x
* earlier versions

**Comment by poblin-orange** [comment]
related to drift detection feature

**Comment by gberche-orange** [comment]
closed as duplicate of https://github.com/orange-cloudfoundry/paas-templates/issues/2163

Reported cross reference to helm drift detection, and added current available capability to enable infinite retries for some selected few helm releases known to require such retries in paas-templates

/CC @poblin-orange
