### ISSUE TITLE
K8s terraform support

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1584]
### Expected behavior

* As a paas-templates operator, paas-templates author or paas-templates maintainer
* In order to migrate our bosh terraform
* I need first class terraform support in k8s

### Observed behavior
 We currently have two options:
   - [Isaaguilar Terraform operator](https://github.com/isaaguilar/terraform-operator/issues)
      _Pro :_
        * custom backend,
        * simple workflow with dedicated pod (setup, init, plan and apply)
        * CLI to ease debugging (https://github.com/isaaguilar/terraform-operator-cli)      

      _Current limitations:_
        * cannot use terraform K8S provider in paas-templates (for looking up objects like ConfigMap, Secrets, etc...) as we cannot connect to it due to https://github.com/orange-cloudfoundry/paas-templates/issues/1578
        * recurrent stale error during apply
        * current limitation on number of tf apply execution. See https://github.com/isaaguilar/terraform-operator/issues/97 Failed due to K8S resource status max size reached (2 MB)
        * operator does not automatically detects changes to remote git repo containing TF spec files: https://github.com/isaaguilar/terraform-operator/issues/85
           * Possible workarounds:
             * Inline terraform spec files into Terraform CR (instead of relying 
              * Manual triggering (injecting an env variable in the Terraform CR)
              * Automatic triggering 
                 * at commit time: [git pre-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)
                 * at runtime, through a cronjob modifying the Terraform CR (with reverts from Flux kustomize operator)
                    * subdir checksum
                    * git commit id for subpath
   - [Weave TF-Controller](https://github.com/weaveworks/tf-controller/)
      _Pro:_
        * larger community,
        * better integration with flux,

      _Current limitations:_           
        * https://github.com/weaveworks/tf-controller/pull/223
        * https://github.com/weaveworks/tf-controller/issues/97  only K8S backend is supported with 1 MB secret size limitation => plan to be release with 0.12.0 (https://github.com/weaveworks/tf-controller/issues/292)
### Affected releases

* v54

**Comment by Nalum** [comment]
223 was closed as reworked for 232 FYI :+1: 
- weaveworks/tf-controller#223
- weaveworks/tf-controller#232

**Comment by artem-nefedov** [comment]
Just passing by here.

There's also a [Terraform provider for Crossplane](https://github.com/crossplane-contrib/provider-terraform).

But I would still use Weave tf-controller.

**Comment by poblin-orange** [comment]
Tested successfully weave-tf-controller 0.13.
Probably the way to go thks to good integration with fluxcd

**Comment by o-orand** [comment]
Already merged in v55
