### ISSUE TITLE
investigate how to mix legacy bosh alerts with native k8s alerts (PrometheusRule object) 

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1587]
### Expected behavior
* As a paas-templates operator
* In order to reuse existing alerts from the community
* I need a way to mix legacy bosh alerts with native k8s alerts (PrometheusRule) 

### Observed behavior
It is not possible to mix legacy bosh alerts (kustomize generated configmap) with PrometheusRule objects because the prometheus operator replaces kustomize generated configmap with the configmap generated by the operator 

### Affected releases
v54

### Study/references
Kyverno generate usage ?
https://kyverno.io/docs/writing-policies/external-data-sources/#looking-up-configmap-values
https://kyverno.io/docs/writing-policies/variables/
https://kyverno.io/docs/writing-policies/mutate/

**Comment by poblin-orange** [comment]
short term workaround might be a separate Prometheus CR for legacy bosh metrics / alerts.
