### ISSUE TITLE
jcr is deleted too early during 53.0.4 upgrade (circular dependency)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1593]
### Expected behavior
* As a paas-templates operator
* In order to be confident with my platform
* I need all jobs turn green

### Observed behavior
- image check failed raised by concourse jobs (jcr has been removed : 404 not found et namespace empty)

- gitops repository not updated because deploy-00-core-connectivity-k8s failed
```
kustomization path not found: stat /tmp/paas-k8s-gitops-bridge-kustomizations3724313325/micro-depls/00-co │
│ re-connectivity-k8s/k8s-config/manifests/00-bridge-kustomizations: no such file or directory
```

- deploy-00-core-connectivity-k8s failed because step-6-upgrade-micro-depls-credhub-seeder can't be triggered (image check failed)
```
Expected to find variables: /uaa/connectivity-client-secret
/uaa/connectivity-cookie-secret
```
 
### Affected releases
v53.0.4

**Comment by o-orand** [comment]
We can try to manually create credhub entries to unlock core-connectivity :
```
credhub generate -t password -n /uaa/connectivity-client-secret
credhub generate -t password -l 32 -n /uaa/connectivity-cookie-secret
```
