### ISSUE TITLE
concourse is slow

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#16]
### Observed behavior
transition from tasks to tasks in a job are slow 
### Affected release
paas-templates; 18
cf-ops-automation: 1.9 +

Reproduced on version 24

### related issue (root cause)
https://github.com/concourse/concourse/issues/1404 (issue introduced in 3.14.01). workaround: limited uses of credhub secrets in COA secrets (s3-br and s3-stemcell upload)

### solution outline
- [x] scale up concourse worker
- [x] add prometheus postgres exporter on postgres db
- [x] add prometheus exporter on gitlab (check git response time)
- [ ] add prometheus postgres on minio s3 (check bosh release download time)
- [x] use skeleton concourse-deployment
- [x] bump to concourse 5.3

**Comment by poblin-orange** [comment]
concourse 3.9.2 + baggage claim explicit btrfs config improved somewhat the perf.

**Comment by poblin-orange** [comment]
https://discuss.concourse-ci.org/t/concourse-5-0-experience-report/1063

**Comment by o-orand** [comment]
https://github.com/concourse/concourse/issues/2346
