### ISSUE TITLE
vsphere csi - bosh vm recreation issue wrt to VolumeAttachment

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1609]
### Expected behavior

* As a paas-templates operator
* In order to 
  * leverage csi volumes on bosh based k8s nodes (k3s bosh release) 
* I need
  * a gracefull coordination between bosh vms lifecycle and k8s nodes/volumes/volumes attachement inventory 

### Observed behavior
csi pvc still stays attached to a node

### references
https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/359#issuecomment-818903727

 
### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
TODO: v54.0.2 targets only R1. Test recreation on ops-depls/00-shared-services-r1

**Comment by o-orand** [comment]
Fixed
