### ISSUE TITLE
[Bootstrap] Bosh Directors secrets setted on different locations lead to inconsistency

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#161]
Related to #148  

When deploying a new BOSH director (master or ops) we are facing some issues on Concourse for related deployments (ie, master-depls, ops-depls respectively). This is due to the fact that newly deployed directors are setted with password generated by Credhub but secrets file aren't updated automatically accordingly. This leads to inconsistency of password handling during concourse deployments.

Why bosh directors password are both locally in credhub and secrets.yml ?

Workaround applied by example for bosh-ops (same should have been done for master): 
1. retrieve correct password with 
```credhub get -n /bosh-master/bosh-ops/admin_password```
and change : 
    1. master-depls/concourse-ops/pipelines/credentials-ops-depls-pipeline.yml
    2.~/bosh/secrets/master-depls/bosh-ops/secrets/secrets.yml 
with credhub value

A solution could be the usage of an operator file replacing the old secrets after retrieving it from Credhub ? 

Release impacted : 35.0.1

Regards,

**Comment by poblin-orange** [comment]
test on v40 suggest we can switch to credhub generated ssl certs for bosh directors, targeting v41

**Comment by poblin-orange** [comment]
merged in v41
