### ISSUE TITLE
[Bootstrap] Step 11: Deploy ops-depls jobs manually with Concourse - CF deployment failed due to the cf-networking missing

### ISSUE THREAD

**Issue by wdesplas** [orange-cloudfoundry/paas-templates#162]
**Observed behavior**
While activating the CF-Deployment, it failed due to the missing of cf-networkin

**Affected release**
V35.0.1

**Workaround**
We upload manually the release :
bosh upload-release https://bosh.io/d/github.com/cloudfoundry/cf-networking-release?v=1.13.0

**Comment by poblin-orange** [comment]
the issue depends on bosh deployment order. ie, if you do ops-routing before cf, the release is uploaded to bosh director, and the issue is invisble.
=> target v36.x
