### ISSUE TITLE
master_vip_api could not be joigned when creating multi-masters cluster

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1624]
### Expected behavior

* As a paas-templates operator
* In order to create k8s cluster with multi-master nodes
* I need create k3s server with local api

### Observed behavior
When initially creating `shared-services` k8s cluster, bosh deploy `mysql` instance, then `server` instance.
From k3s server post-deploy job try to join `master_vip_ip` rather than local `spec.ip` (see `k3s-boshrelease/jobs/k3s-server/templates/bin/post-start.erb`), which is created further on `ha-k8s-vip` instance.

```
cat /var/vcap/store/k3s-server/k3s.yaml |sed -r 's/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'/"<%= spec.ip %>"/ > /var/vcap/store/k3s-server/kubeconfig.yml

<% if_p('k3s.master_vip_api') do |vip| %>
cat /var/vcap/store/k3s-server/k3s.yaml |sed -r 's/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'/"<%= vip %>"/ > /var/vcap/store/k3s-server/kubeconfig.yml
<% end %>

#wait for k8s api to be available, wait for 5 min max
<% if_p('k3s.master_vip_api') do |vip| %>
timeout 300 sh -c 'until nc -z <%= vip %> 6443; do sleep 1; done' /var/vcap/packages/kubectl-k3s/kubectl --kubeconfig=/var/vcap/store/k3s-server/kubeconfig.yml get pods --all-namespaces
<% end %>
```
So post-start job failed and we could not deploy cluster.

### Affected releases
* 54.0.0

**Comment by poblin-orange** [comment]
Seems k3s server are updated before k8s ha api vms, blocking the first deployment
Should colocate the keepalived jobs on k3s server (and avoid server nodes when applying openstack-init Daemonset)

Workaround: manuel bosh deploy with k3s-server-instances:0, should setup the keepalived vm pair.
Then nominal / COA bosh deploy

**Comment by poblin-orange** [comment]
https://github.com/orange-cloudfoundry/paas-templates-private/commit/e1b80687954be350e9c61a1a11c5d6a853258ea2
