### ISSUE TITLE
Setup a Cloudfoundry org, as osbcmdb "self" client

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1626]
### Expected behavior

* As a paas-templates paas-templates author
* In order to 
  * be able to test end to end hosted service consumption
  * be able to build a broker leveraging osb-cmdb services (composite services) e.g. app-watcher broker
* I need 
  * a reserved osbcmdb org for paas-templates internal needs
  *  with a limited service broker visibility

### Observed behavior

* ~~org orange exist, but is configured directly on backing OSB brokers (osbcmdb shunte)~~
* org osb-cmdb-brokered-services-org-client-0 has osb-cmdb-broker-0 registered. 
 
### Affected releases

* 54
* earlier versions

**Comment by gberche-orange** [comment]
@poblin-orange additional documentation/slides about osb-cmdb can be found at:

on private plazza docs/DOC-1428475
publicly at https://docs.google.com/presentation/d/1cI1BjM2_NiFRuIZe3DaeHdhDElzbLQxB/edit#slide=id.p62
