### ISSUE TITLE
production manual steps during v53 upgrade

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1630]
### Expected behavior
* As a paas-templates operator
* In order to upgrade my platform
* I need to follow some manual steps

### Observed behavior
- [00-core-connectivity] jcr is not up after automatic upgrade : 

```
Warning  error   5m23s (x403 over 13h)  kustomize-controller  Ingress/jcr/jfrog-jcr dry-run failed, reason: InternalError, error: Internal error occurred: failed calling webhook "validate.nginx.ingr │
│ ess.kubernetes.io": an error on the server ("") has prevented the request from succeeding   
```

**workaround applied :** (from https://stackoverflow.com/questions/61365202/nginx-ingress-service-ingress-nginx-controller-admission-not-found)
kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
flux suspend kustomization -n fluxcd 15-jcr
flux resume kustomization -n fluxcd 15-jcr
flux suspend helmrelease -n ingress-nginx ingress-nginx
flux resume helmrelease -n ingress-nginx ingress-nginx

- [00-core-connectivity] reloader helm release can't be deployed :
 ```
Deployment.apps "reloading-reloader" is invalid: spec.template.spec.containers[0].image: Required value
```
caused by policy kyverno-rancher-agent-add-ca-cert not disabled during v53 upgrade on BRMC-PROD (was automatically disabled during INT & PPROD upgrades)

**workaround applied :**
use k9s in order to delete the policy
flux suspend helmrelease -n fluxcd reloader
flux resume helmrelease -n fluxcd reloader

- [00-core-connectivity] kustomization 10-static-routes not removed by v53 upgrade 

**workaround applied :**

use k9s in order to delete the kustomization 

- [01-ci-k8s] helmrelease minio has the status upgrade retries exhausted 

**workaround applied :**

flux suspend helmrelease -n minio minio
flux resume helmrelease -n minio minio

- [00-supervision] HelmChart 'fluxcd/01-loadbalancer-metallb' is not ready

**workaround applied :** 

bump metallb to 2.6.2 (previously 2.5.10)

- [00-supervision] helmrelease ingress-nginx has the status upgrade retries exhausted 
describe gives :  
Service does not have load balancer ingress IP address: 01-loadbalancer/ingress-nginx-controller
in namespace 01-loadbalancer, "kind: Service" is pending with the error : 
ngress-nginx-controller-776c786964-lt4q7 2022/06/24 08:28:19 http: TLS handshake error from 10.42.0.0:59530: remote error: tls: bad certificate                                                         │
The service ingress-nginx-controller external-ip was in pending mode.
The vip 192.168.99.16 was taken by loki service (promtail-syslog).  See also https://github.com/orange-cloudfoundry/paas-templates/issues/1631

**workaround applied :**
use k9s in order to delete the service promtail-syslog
use k9s in order to suspend the kustomization 40-loki
use k9s in order to delete the kustomization 01-loadbalancer
use k9s in order to trigger the kustomization 01-loadbalancer
use k9s in order to resume the kustomization 40-loki

### Affected releases
* v53.0.4 on BRMC-PROD

**Comment by o-orand** [comment]
Occurred during 54.0.4 on pre-prod, hotfix included in a dedicated branch.
