### ISSUE TITLE
core connectivity flux cd bad slack config

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1639]
### Expected behavior

* As a paas-templates operator
* In order to be notified
* I need slack notifications to 
* I need the installation to complete

### Observed behavior

```
Provider/fluxcd/slack dry-run failed, reason: Invalid, error: Provider.notification.toolkit.fluxcd.io "slack" is │
│  invalid: spec.channel: Invalid value: "null": spec.channel in body must be of type string: "null"
``` 

* blocks the installation

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
This is induce by shared/secrets.yaml channel secrets propagation to fluxcd => should not have # prefix.
Missing instruction in release note

**Comment by poblin-orange** [comment]
removing channel attribut on Fluxcd Notification CR can solve the issue (provided the configured webhook is channel scoped)
