### ISSUE TITLE
declare missing dependency for k3s deployment: networking

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1663]
### Expected behavior

* As a paas-templates operator
* In order to 
* I need declare missing dependency for k3s deployment: networking

### Observed behavior
Failed to deploy ops-depls/00-shared-services:
`Could not deploy: Creating and uploading releases: Uploading release 'networking/9': Uploading remote release <s3>/compiled-releases/cloudfoundry/networking-9-ubuntu-bionic-1.88.tgz': Expected task '4609691' to succeed but state is 'error'`

We've already fixed issue with version inconsistency.

 
### Affected releases

* 54.0.0 and earlier versions

**Comment by ogrand** [comment]
To validate in v54.0.1
