### ISSUE TITLE
vpn wireguard silent failure

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1665]
### Expected behavior

* As a paas-templates operator
* In order to have a resilient inter region vpn set up   
* I need explicit bosh level failure when the vpn peer handshake fails after a given timeout 

### Observed behavior

When `wireguard` vpn instance reboot, lifecycle (which contains static routing creation) is not running, so instance could not communicate with others vpn instances.

Before reboot:
```
vpn/7aa2103d-5642-4ff3-b2ad-742fcc172988:~# route -n | grep eth0
10.228.194.0    0.0.0.0         255.255.255.240 U     0      0        0 eth0
10.228.xxx.xx   10.228.xxx.x    255.255.255.255 UGH   0      0        0 eth0
10.228.yyy.yy   10.228.xxx.x    255.255.255.255 UGH   0      0        0 eth0
```

After reboot:
```
vpn/7aa2103d-5642-4ff3-b2ad-742fcc172988:~# route -n | grep eth0
10.228.194.0    0.0.0.0         255.255.255.240 U     0      0        0 eth0
```

**Consequence:**
- scripting bosh release setting vm static route is not reexecuted on reboot (could migrate to neworking release 10 which has not this issue)
- wiregard peer silently fails to handshake (see wireguard bosh release limitation: https://github.com/orange-cloudfoundry/wireguard-boshrelease/issues/6) 
- traffic to / from `vpn` instance is disabled

### Affected releases

* < 54

**Comment by ogrand** [comment]
Priority on alerting wg keepalive

**Comment by poblin-orange** [comment]
Issue seem to occur on iaas level failure  (eg: vm restart on a new esx on source esx failure).
Note that in that case bosh lifecycle is not reapplied (pre-start, post-start, ...), resulting in failed route if we use bosh release depending on that cycle:
- wireguard bosh release
- generic scripting bosh release
