### ISSUE TITLE
unreliable traffic routing to concourse

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1669]
### Expected behavior

* As a paas-templates operator
* In order to 
* I need a reliable traffic routing to Concourse

### Observed behavior
When we try to reach concourse we encounter an error (about 1 failure on 5 tries)
 
```
Could not find a valid token.
logging in to team 'main'

could not reach the Concourse server called concourse:

    Get "https://elpaaso-concourse.<ops-domain>/api/v1/info": x509: certificate signed by unknown authority

```
#### Workaround

restart traefik deployment

### Affected releases

* 54.0.0 & 54.0.1

**Comment by poblin-orange** [comment]
with v53, access to micro-depls/concourse/web:8080 instance group is direct from 00-core-connectivity (no more gorouter indirection, nginx-ingress loadbalances to a single externalName service based on bosh-dns).

As previously, the access layer is still stateless (no JSESSIONID was set by concourse, gorouter had not sticky session set).

Suspecting the dex sky requires sticky session. We can try to set it on nginx-ingress

**Comment by o-orand** [comment]
Session affinity is enabled via [c2ac018e6139112d97326f7d578f086db4658200](https://github.com/orange-cloudfoundry/paas-templates-private/pull/1251/commits/c2ac018e6139112d97326f7d578f086db4658200)
