### ISSUE TITLE
openldap deployment - passwords must be managed by a configuration server (credhub)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#167]
**Expected behavior**

As an ops, I expect to have most of passwords managed by  a configuration server (credhub)

**Observed behavior**

Openldap deployment is currently using a root and a database passwords  stored in secrets file

**Actions**
- [ ] Use configuration server to generate root and database passwords for openldap deployment
- [ ] Remove root and database password from secrets file
- [ ] Update deployments, scripts and cf-apps in order to use configuration server 
- [ ] Check that the bootstrap process is still working with this new behaviour (shoud be since openldap deployment is not part of core platform deployments) 

**Affected release**
Reproduced on version 36.0.0

**Comment by poblin-orange** [comment]
fix merged for v40
