### ISSUE TITLE
Kapp-controller package spike 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1672]
### Expected behavior

* As a paas-templates contributor
* In order to address offline/airgap #621 issue
* I need further study/test kapp-controller Package Management support

### Observed behavior
 
Further aspects to study:
- hot fix/patch support
   - https://carvel.dev/blog/kctrl-pkg-authoring-cmds/

### References

*  https://carvel.dev/kapp-controller/docs/v0.38.0/packaging/
* https://carvel.dev/kapp-controller/docs/v0.38.0/air-gapped-workflow/
* https://carvel.dev/blog/imgpkg-image-collocation-and-tagging/ Bundle concept and use of `imgpkg`to copy it and its dependent images across OCI repositories
* https://carvel.dev/kbld/
* https://carvel.dev/kapp-controller/docs/v0.40.0/packaging-gitops/#package-management-gitops-example steps for installing a bundle/package built from a specific release from an internal OCI repository. May contain other bundles/packages
* https://carvel.dev/blog/kctrl-pkg-authoring-cmds/ `Introducing kctrl package authoring commands`
* https://github.com/vmware-tanzu/carvel/blob/develop/ROADMAP.md

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
to compare with offlining with harbor ?
