### ISSUE TITLE
bosh-coab fails to deploy  due to metrics_server

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1675]
### Expected behavior

* As a paas-templates operator
* In order to install paas-templates
* I need to deploy bosh coab

### Observed behavior

Bosh deploy fails with:
```
'bosh/9aec1ed1-52b6-4683-8fdd-f0843cd6c14e (0)' is not running after update. Review logs for failed jobs: metrics_server
```
And monit say: `Process 'metrics_server'            Does not exist`
 
### Affected releases

* 54.0.1

**Comment by poblin-orange** [comment]
issue was caused by duplicate az definition in coab-depls cloud-config ?

**Comment by ogrand** [comment]
Error message: 
```
/var/vcap/data/packages/director/f9a42818ceba1e4a5425cc5bae46f862ccb8659e/gem_home/ruby/3.1.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:39:in `parse_availability_zones': Duplicate az name 'r1-z2' (Bosh::Director::DeploymentDuplicateAvailabilityZoneName)
```

With cloud-config configuration:

```
- cpi: region-1
  name: r1-z2
- cpi: region-1-z2
  name: r1-z2
```
