### ISSUE TITLE
upgrade should upload stemcell for all cpi (including ops-depls region-1-z2)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1677]
### Expected behavior

* As a paas-templates operator 
* In order to 
  * have a complete upgrade of pf 
* I need
  * the bosh upload stemcell to apply to all cpi 

### workaround
force upload stemcell with [fix flag](https://bosh.io/docs/cli-v2/#upload-stemcell):
```
bosh upload-stemcell  bosh-stemcell-1.91-vsphere-esxi-ubuntu-bionic-go_agent.tgz --fix
```

> --fix replace previously uploaded stemcell with the same name and version to repair stemcells that might have been corrupted in the cloud.

### Affected releases

* 54.0.1

**Comment by o-orand** [comment]
We should discuss about this, as using `--fix` will perform a new upload on each run.
