### ISSUE TITLE
dedicated vm rabbitmq (COAB )

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#168]
### Expected behavior
As a platform user, i want to be able to get a dedicated rabbitmq cluster

### Observed behavior
The offered rabbitmq service is based on a shared rabbitmq cluster

### design
- [ ] revue engineering (clustering)
- [ ] backup
- [ ] monitoring
- [ ] k8s compat
- [ ] cf api dependency ?
- [ ] activate monitoring for users in osb broker (possible as its a dedicated cluster)
   - https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/master/jobs/rabbitmq-service-broker/spec#L86
  - https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/master/src/rabbitmq-service-broker/broker/bind.go#L34

### Affected release

Reproduced on version 36.0.0

### Traces and logs

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by poblin-orange** [comment]
duplicate of #467

**Comment by gberche-orange** [comment]
The rabbitmq broker exposes a dashboard url which contains credentials in the url. This dashboard is necessary to access queue statistics and perform some configurations.

Related support in COAB is tracked in https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/47

**Comment by JCL38-ORANGE** [comment]
delivered in v45
