### ISSUE TITLE
support google cloud artifact registry

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1684]
### Expected behavior

* As a paas-templates paas-templates author
* In order to 
  * support all on the shelf helm charts 
* I need 
  * docker image access chain to be able to retrieve google cloud hosted images 

### Observed behavior

robusta helm chart pulls the following image:  us-central1-docker.pkg.dev/genuine-flight-317411/devel/kubewatch:v1.12

see https://cloud.google.com/artifact-registry/docs/docker/store-docker-container-images
 
### Affected releases

* 55
* earlier versions

**Comment by o-orand** [comment]
Done, access authorized in [feature-bump-for-v55](https://github.com/orange-cloudfoundry/paas-templates-private/pull/1226)
