### ISSUE TITLE
bosh - migrate to Jammy Jellyfish Stemcell

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1689]
### Expected behavior

* As a paas-templates operator 
* In order to 
  * benefit from supported vm os 
* I need 
  * an updated bosh stemcell os 

### Observed behavior
 Still using bionic stemcell 

https://ubuntu.com/about/release-cycle
![image](https://user-images.githubusercontent.com/4748380/188115732-e42d2939-4d19-426e-ab80-ec64fd2af6eb.png)

With Openssl 3 included in jammy, it requires dependencies bump to a newer version, for instance:
  * Ruby 2.7 → 3.1
  * nginx 1.20.1 → 1.21.6,
  * HAProxy 1.8.13 → 2.5.1

see https://bosh.io/docs/jammy-migration/#openssl-3
Related issue:
[ ] https://askubuntu.com/questions/1420966/method-https-has-died-unexpectedly-sub-process-https-received-signal-4-after, observed on containerized bastion, and concourse containerd resources.

(Ntp-release)[https://github.com/cloudfoundry-community/ntp-release/] v4.2.8p13 seems not compatible with openssl 3 neither.
 see https://github.com/cloudfoundry-community/ntp-release/issues/4

### Dependencies

* [ ] concourse.
* [ ] mongodb
* cf-mysql

### Affected releases

* 54
* earlier versions

### references
- https://github.com/orange-cloudfoundry/open-iscsi-boshrelease/issues/1
- https://github.com/concourse/concourse/releases/tag/v7.9.0 (jammy support for worker) #1928 
- https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/tag/v4.12.0 
- helm kubectl compile issue https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease/issues/35
- https://github.com/orange-cloudfoundry/paas-templates/issues/1933
- https://github.com/orange-cloudfoundry/paas-templates/issues/1943
- might induce https://github.com/orange-cloudfoundry/paas-templates/issues/991 ?
- https://github.com/orange-cloudfoundry/paas-templates/issues/1974

**Comment by JCL38-ORANGE** [comment]
Expiration of bionic stemcell in april 2023

**Comment by gberche-orange** [comment]
Cf-deployment start being only qualified on Jammy, see https://lists.cloudfoundry.org/g/cf-dev/message/9434

> we will soon release a new major version of cf-deployment [1] which switches the default stemcell from Bionic [2] to Jammy [3]. From then on, we will run the cf-deployment release and evaluation process only with Jammy. If you have a custom CF deployment, you should check if an upgrade to Jammy is possible.
> 
> For Bionic, we will set up a basic validation which deploys a default CF installation and runs the CF Acceptance and Smoke tests. We will also provide an ops file to switch back the default stemcell to Bionic.

**Comment by poblin-orange** [comment]
Virtualization related capability
- https://communities.vmware.com/t5/ESXi-Discussions/Need-help-with-guest-CPUID-bit-masking/td-p/1358131
