### ISSUE TITLE
00-supervision does not allocate enough  resources to kube-ops-view

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1691]
### Expected behavior

* As a paas-templates operator
* In order to complete upgrade
* I need kube-ops-view to run smoothly

### Observed behavior
Kube-ops-view is killed by K8S controller: 

```
     State:          Waiting
       Reason:       CrashLoopBackOff
     Last State:     Terminated
       Reason:       OOMKilled
       Exit Code:    137
     Ready:          False
     Restart Count:  390
     Limits:
       cpu:     200m
       memory:  100Mi
     Requests:
       cpu:      50m
       memory:   50Mi
``` 

### References

* https://codeberg.org/hjacobs/kube-ops-view
* https://codeberg.org/hjacobs/kube-ops-view/issues/8 No releases, has this been deprecated?

### Affected releases

* 54.0.1

**Comment by o-orand** [comment]
Increasing memory to 512Mo does not solve the OOM issue.

**Comment by poblin-orange** [comment]
reopen, still in v55

**Comment by poblin-orange** [comment]
still failing. bumping to https://codeberg.org/hjacobs/kube-ops-view/src/tag/23.2.0

**Comment by poblin-orange** [comment]
still failing following bump.reschuling for v56

**Comment by o-orand** [comment]
In v56, a bump to 23.5.0  is included by orange-cloudfoundry/paas-templates-private#2251 (https://github.com/orange-cloudfoundry/paas-templates-private/commit/9ef307a9dc0a27dbef9be7e493c423365612eaa4)

It seems fine on Fe-Int:
```
NAME↑                                    PF    READY       RESTARTS STATUS         CPU    MEM    %CPU/R    %CPU/L     %MEM/R     %MEM/L IP              NODE          AGE      
 kube-ops-view-66dccc7c8-q7l64            ●     1/1                0 Running          2    108         4         1         54         54 10.42.7.23      agents-3      20d   
 kube-ops-view-redis-76454f9845-5q7p8     ●     1/1                0 Running          2      5         4         1         11          5 10.42.1.25      agents-0      20d   


```
