### ISSUE TITLE
Default cf domains lack internal domain (apps.internal.paas )

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#17]
### Expected behavior

apps.internal.paas CF  domain should be managed by paas-template and reacheable from apps.

### Observed behavior

apps.internal.paas  Cf domain is not managed by paas-template and manually managed in our CF deplouments

Additionally, the domain is not registered in the internal DNS server, resulting in apps being unable to user them.

### Affected release

Reproduced on version 24.0

**Comment by poblin-orange** [comment]
Probably should remove this private domain, as the coming polyglot dns discovery will supercede it with domain apps.internal, with container networking
see  #15.

**Comment by gberche-orange** [comment]
I was expecting to leverage such private domains for operators smoke tests (e.g. COAB cassandra smoke tests) that don't need to be made visible to end-users, but probably can't easily leverage the C2C network (as they'd be invoked from concourse workers who can't ingress the C2C)

**Comment by gberche-orange** [comment]
Additionally, the domain is not registered in the internal DNS server, resulting in apps being unable to user them.

/CC @T0FFF

**Comment by poblin-orange** [comment]
fixed as of v37
