### ISSUE TITLE
Support marketplace services to be consumed outside of the master-depls/cf deployment

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#170]
### Expected behavior

Shared and dedicated on-demand services need to:
* consumed from other platforms (say 3rd party K8S svcat, or custom portals)
* be instanciated without `master-depls/cf` (for reducing operation costs) in the latter scenario

### Observed behavior

Shared and dedicated on-demand services can only currently be exposed on internal addressing.

Shared and dedicated on-demand services leverage `master-depls/cf` for exposing their broker endpoint using FQDN over tls with valid tls cert

### Affected release

Reproduced on version 36.0

### reference
- https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/50
- https://github.com/orange-cloudfoundry/paas-templates/issues/72

**Comment by poblin-orange** [comment]
initial version delivered in v39

**Comment by poblin-orange** [comment]
merged, closing for v40
see nsx improvement in #329

**Comment by gberche-orange** [comment]
pending issues to create for remaining work:
* aggregated logs (logsearch) without CF authentication
* COAB support outside of CF (deployment, smoke tests)
* FQDN service bindings & DNS authority server
* external services consummeable from public intranet IP addresses

/CC @poblin-orange
