### ISSUE TITLE
coab-depls(cloud-config): r4 vsphere networks misconfiguration

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1701]
### Expected behavior

* As a paas-templates operator
* In order to upgrade to v54
* I need to have a valid cloud config

### Observed behavior
After updating COAB cloud config for remote-r4 support, we introduce a regression on vsphere.

During vpn-probe deployment, we use the latest cloud-config: 
```
  azs:
+ - cpi: region-1
+   name: r1-z1
+ - cloud_properties:
+     availability_zone: "((/secrets/openstack_4_availability_zone))"
+   cpi: region-4
+   name: r4-z1
``` 
Leading to error below:
` Error: - Failed to find variable '/secrets/openstack_4_availability_zone' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'`

### Affected releases
* 54.0.2

**Comment by poblin-orange** [comment]
Also missing private networks credhub seeding (as we do not have terraform to generate the networks, we need to set networks name in shared-secrets.yml + seed + use in cloud-config)
