### ISSUE TITLE
vsphere iaas metrics are missing on r2

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1703]
### Expected behavior

* As a paas-templates operator
* In order to be confident on our platform status
* I need to get metrics from all vsphere regions

### Observed behavior

Alert on failed scrapping of the iaas exporter

 Vsphere API region 2 is not available from Integration, nor pre-production environments due to untrusted certificates. But we can access vsphere API r2 from Production enviroment.

From Int or PP:
  - accessing to xxx**19**yyy.<our-domain> is **KO**
  - accessing to xxx**29**yyy.<our-domain> is **OK**

### Affected releases

* 54.0.0

**Comment by poblin-orange** [comment]
env specific issue?
