### ISSUE TITLE
Kafka & ksqldb filling up disk fast with experimental paas-templates stream & tables

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1730]
### Expected behavior

* As a paas-templates operator 
* In order to leverage ksqldb
* I need to have ksqldb reliably process stream & tables 

### Observed behavior
 
After a few days kafka cluster gets full

### Possible approaches

* easy clean up of ksqldb state #1729 

* reduce kafka topic sizes
   * using lower retention
   * by aggressive filtering
* ensure ksql processing are copying with inputsource rate and don't lag
   * monitor ksql processing
   * tune processing
      * increase parallelism
         * increase partitions (see book p42 and p177)
      * optimize processing
         *  ~~use GlobalKTable for small, mostly static inventory tables (services, service plans, Iaas pricing ). See book 
p107-109~~
   * scale ksqldb cluster, see [scaling-ksqldb](https://docs.ksqldb.io/en/latest/operate-and-deploy/capacity-planning/#scaling-ksqldb)
* Apply "controlling ksqldb state size" strategies, see book p189 

### Affected releases

* x.y
* earlier versions

**Comment by Guilamb** [comment]
The use of Global KTable isn't possible with KSQLDB : https://github.com/confluentinc/ksql/issues/3636
But there is a request for this feature : https://github.com/confluentinc/ksql/issues/816

**Comment by gberche-orange** [comment]
Blocked by metrics KafkaTopic not converging. No relevant traces found in kafka-cluster-entity-operator-57987cb89f-twf9x. No events. NO metrics topic visible in kafka ui  No trace of topic in ksqldb-cli (show topics). 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  creationTimestamp: "2022-10-05T12:52:35Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: 20-kafka-ksqldb-bi
    kustomize.toolkit.fluxcd.io/namespace: fluxcd
  name: metrics
  namespace: 20-kafka-ksqldb-bi
  resourceVersion: "213436118"
  uid: e65f40a1-b475-4cda-a36c-591ba1572ffb
spec:
  config:
    retention.ms: 28800000
  partitions: 15
  replicas: 1
  topicName: metrics
```

**Comment by gberche-orange** [comment]
We have pause our exploration project of ksqldb. Reopen if we resume in the future.
