### ISSUE TITLE
openstack cpi - vm creation failure, bad userData base 64 encoding

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1735]
### Expected behavior

* As a paas-templates operator 
* In order to 
  * keep using bosh to provision user on flexible engine openstack 
* I need 
  * to solve recent regression wrt userData base 64 data set by bosh openstack cpi 

### Observed behavior

Recent flexible engine upgrade are blocking bosh vm creation
Context:
- bosh openstack cpi bosh-openstack-cpi/46
- bosh version bosh/273.0.0
- stemcell bionic bosh-openstack-kvm-ubuntu-bionic-go_agent/1.97

 
### Affected releases

* 53
* and earlier versions

**Comment by ogrand** [comment]
The pb occurs after openstack 22.3 version upgrade on Flexible Engine iaas.
bosh Openstack cpi uses `create_vm` api and send a POST request with body content.
`user_data` row in this body is base64 encoded with newlines `\n` every 60 characters:

```
body: {
  "server": {
    "flavorRef": "s3.small.1",
    "name": "vm-d35f15af-9840-44be-8d95-a2b1e1ad5358",
    "imageRef": "97727138-8334-4188-9b1e-4x558599d99b",
    "user_data": "eyJzZXJ2ZXIiOnsibmFtZSI6InZtLWQzNWYxNWFmLTk4NDAtNDRiZS04ZDk1\nLWEyYjFlMWFkNTM1OCJ9LCJuZXR3b3JrcyI6eyJ0Zi1uZXQtY29hYi1kZXBs\ncy1pb
```

The new iaas base64 decoder is less permissive and refuses newlines `\n`.

So, to workaround we replace encoding format in `/var/vcap/packages/bosh_openstack_cpi/vendor/bundle/ruby/*/gems/fog-openstack-*/lib/fog/openstack/compute/models/server.rb` ruby script:

Replace `[ascii_userdata].pack('m')` with `[ascii_userdata].pack('m0')` which disable newlines assertion.
```

**Comment by ogrand** [comment]
Upstream issue : https://github.com/cloudfoundry/bosh-openstack-cpi-release/issues/255
