### ISSUE TITLE
[Bootstrap] Step 10: Deploy master-depls jobs manually with Concourse - LDAP deployment

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#174]
### Observed behavior
Error during openldap deployment:

### Trace
ldap_bind: Invalid credentials (49)
Adding pwm schema
Add or modify entries from an LDAP server
Fix: /home/cloud/bosh/template/master-depls/openldap/template 

### Version
v35.0.1

### Fix
Error in master-depls/openldap/template/post-bosh-deploy.sh, the grep returns all password in secrets.yml file
Fix: ldap_pass=$(grep ldap ${SECRETS_DIR}/../../shared/secrets.yml -A5 | grep database -A2 | grep password | awk '{print $2}')

**Comment by poblin-orange** [comment]
issue fixed in v36.0.1

**Comment by poblin-orange** [comment]
also fixed in 35.0.2
