### ISSUE TITLE
00-supervision fails to apply fluxcd kustomization 10-grafana-dashboards

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1741]
### Expected behavior
* As a paas-templates operator
* In order to upgrade paas-templates
* I need all kustomizations applied

### Observed behavior
In 00-supervision, the 10-grafana-dashboards fluxcd kustomization fails with message
```
'var substitution failed for ''mysql-galera'': YAMLToJSON: yaml: line 38: did not find expected key'                                                                                                             
```

In annotations : 
```
standardize-root-fluxcd-kustomization.root-kustomizations-policy.kyverno.io: replaced /spec/wait                                                                                                    
```

### Affected releases
54.0.4

### Analysis
It seems that the policy standardize-root-fluxcd-kustomization was not correctly applied on 10-grafana-dashboards 10-grafana-dashboards kustomization

**Comment by JCL38-ORANGE** [comment]
workaround = delete 10-grafana-dashboards kustomization

**Comment by o-orand** [comment]
Not reproduced in v55, should be closed ?
