### ISSUE TITLE
shared-services cluster: remove shield backup provisioning on each region

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1747]
### Expected behavior

* As a paas-templates operator
* In order to have backup for shared-services
* I need successful shield provisioning

### Observed behavior
 
`run-errand-00-shared-services-r1-shield-provisioning` and `run-errand-00-shared-services-r2-shield-provisioning` fail with `Error: Errand 'import' doesn't exist`

### Affected releases

* 54

**Comment by gberche-orange** [comment]
closed on preprod env
