### ISSUE TITLE
missing ssh bastion IngressRouteTCP

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1751]
### Expected behavior

* As a paas-templates operator
* In order to 
   * upgrade v54 
* I need 
  * to not loose ssh access 

### Observed behavior
 
after v53 post upgrade, ops-depls dns switched to 00-core-connectivity:
- this should have revealed the missing traefik ingressroutetcp for ssh docker bosh cli.
- however, ops still using ip (legacy ops relay) don't see the issue

after v54.0.4 post upgrade, legacy master-depls/ops-routing is deleted.
- ops still using ip (legacy ops relay) lose access
- switching to dns reference does not help (missing IngressRouteTCP)

### Resolution
add missing reference to yaml file in micro-depls/00-core-connetivity/10-traefik-static-route/kustomization.yaml
 

### Affected releases
* 53
* 54.0.4
* earlier versions

**Comment by gberche-orange** [comment]
will be fixed on preprod env
