### ISSUE TITLE
helm releases under helm remote repositories targeting other artifactory virtual repositories are not cached by jcr

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1765]
### Expected behavior
* As a paas-templates operator | paas-templates author
* In order to support offline mode
* I need all helm releases cached by jcr

### Observed behavior
 helm releases under helm remote repositories targeting other artifactory virtual repositories are not cached by jcr
```
helm pull --debug jcr/orange-mariadb
Error: Get "https://<artifactory end point>:443/artifactory/<virtual repository>/mariadb/orange-mariadb-1.0.3.tgz": dial tcp 10.XX.YY.ZZ:443: connect: connection timed out
helm.go:84: [debug] Get "https://<artifactory end point>:443/artifactory/<virtual repository>/mariadb/orange-mariadb-1.0.3.tgz": dial tcp 10.XX.YY.ZZ:443: connect: connection timed out
```
debug traces show that the artifactory backend is accessed at pull time

### Affected releases
v54 and before

**Comment by o-orand** [comment]
It seems our JCR is not able to cache artifacts from another artifactory virtual repository.
As corporate helm charts refers to this virtual repo, we cannot bypass it, unless we download and patch index.yaml (from virtual repo)

**Comment by poblin-orange** [comment]
Having this issue:
```
$ helm template fluxtest jcr/flux2 --debug install.go:178: [debug] Original chart version: "" Error: Get "[https://github.com/fluxcd-community/helm-charts/releases/download/flux2-2.6.0/flux2-2.6.0.tgz":](https://github.com/fluxcd-community/helm-charts/releases/download/flux2-2.6.0/flux2-2.6.0.tgz%22:) dial tcp: lookup github.com on 10.43.0.10:53: no such host helm.go:84: [debug] Get "[https://github.com/fluxcd-community/helm-charts/releases/download/flux2-2.6.0/flux2-2.6.0.tgz":](https://github.com/fluxcd-community/helm-charts/releases/download/flux2-2.6.0/flux2-2.6.0.tgz%22:) dial tcp: lookup github.com on 10.43.0.10:53: no such host poblin@fe-int ☸️  supervision:15-strimzi-operator ~
```

Looks like the index.yaml given to client is not rewritten toward jrc internal url ?

**Comment by poblin-orange** [comment]
jcr helm support to be replaced with harbor + oci helm charts. => wont fix
