### ISSUE TITLE
vendir/vendor.sh error traces when run from bosh-cli

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1774]
### Expected behavior

* As a paas-templates paas-templates maintainer
* In order to complete vendir bumps until renovate supportds it (see https://github.com/renovatebot/renovate/issues/17711)
* I need to run vendir sync from a managed environment

### Observed behavior
 
* [x] vendir/vendor.sh shows error traces when run from bosh-cli, likely because the bosh-template binary is missing from bosh-cli. See more about bosh-template ruby gem into https://bosh.io/docs/job-templates/

```
### rendering bosh_alerts                                                                            
processing bosh_tsdb_system_predict.alerts.yaml  
./vendor.sh: line 58: bosh-template: command not found                                                                                                                                                     
processing bosh_tsdb_system.alerts.yaml
./vendor.sh: line 58: bosh-template: command not found
[...]
### rendering credhub_alerts      
processing prometheus_credhub_exporter.alerts.yaml 
./vendor.sh: line 58: bosh-template: command not found
processing credhub.alerts.yaml    
./vendor.sh: line 58: bosh-template: command not found
[...]
```

* [x] vendir/vendor.sh does not fail. As a result, the resulting `git status` is ambiguous

### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
Fixed for v55 : 
- a base script called vendor.sh
- an enhanced script called vendor-with-rules-and-dashboards.sh
