### ISSUE TITLE
images under image remote repositories targeting other artifactory virtual repositories are not cached by jcr

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1784]
### Expected behavior
* As a paas-templates operator | paas-templates author
* In order to support offline mode
* I need all images cached by jcr

### Observed behavior
images under image remote repositories targeting other artifactory virtual repositories are not cached by jcr
```
helm pull --debug jcr/orange-mariadb:10.6.8-ubuntu20-1
Error: Get "https://<artifactory end point>:443/artifactory/<virtual repository>/orange-mariadb:10.6.8-ubuntu20-1": dial tcp 10.XX.YY.ZZ:443: connect: connection timed out
helm.go:84: [debug] Get "https://<artifactory end point>:443/artifactory/<virtual repository>/orange-mariadb:10.6.8-ubuntu20-1": dial tcp 10.XX.YY.ZZ:443: connect: connection timed out
```

### Workaround

Bypass JCR and load images straight from upstream OCI repo using intranet proxy with support in k3s-bosh-release through a specific env var

### Affected releases
v54 and before

**Comment by poblin-orange** [comment]
Should remove the containerd proxy configuration.
Image can be reached through harbor proxy
