### ISSUE TITLE
Kafka Prometheus Exporter Error: "couldn't produce message in kafka topic metrics"

### ISSUE THREAD

**Issue by Guilamb** [orange-cloudfoundry/paas-templates#1785]
### Expected behavior

* As a paas-templates operator
* In order to ksqldb to properly work

### Observed behavior
 Kafka Prometheus Exporter can't push metrics into Kafka Topic, and return error : 
 ```
     prometheus-kafka-exporter-prometheus-kafka-adapter :

    │ 2022-11-07T10:50:21.470735642Z {"error":"Local: Queue full","level":"debug","msg":"Failing metric [123 34 116 105 109 101 115 116 97 109 1 │

    │ 2022-11-07T10:50:21.470753924Z {"error":"Local: Queue full","level":"error","msg":"couldn't produce message in kafka topic metrics","time" │
```

### Configuration
![image](https://user-images.githubusercontent.com/18172904/202472521-0c6a6f12-5a87-4a0e-83bf-81259dda4002.png)

### Affected releases

* Kafka 3.2
* telefonica/prometheus-kafka-adapter:1.8.0

**Comment by Guilamb** [comment]
# Error Queue Full 
This Error is due to an unreachable Kafka topic.
In this case, the Prometheus kafka exporter, was unable to write on topic metrics.

# The size of the current ISR Set(1) is insufficient to satisfy the min.isr

On one of the kafka clusters, this error might appear : 
```
    clusters kafka : 
    kafka 2022-11-07 10:49:02,643 ERROR [ReplicaManager broker=1] Error processing append operation on partition metrics-1 (kafka.server.Repli │

    │ kafka org.apache.kafka.common.errors.NotEnoughReplicasException: The size of the current ISR Set(1) is insufficient to satisfy the min.isr │
```
By default, the min isr is set to 1, but it might have been changed for the topic you are trying to write to. Unfortunately the name of the topic isn't specified.
In order to resolve the error reduce the number of `min.insync.replicas` to the specified number, or increase the number of brokers.
This configuration can be changed on the UI, in the topic parameter, with
 `kafka-configs.sh --bootstrap-server localhost:9092 --alter --entity-type topics --entity-name configured-topic --add-config min.insync.replicas=2`, or directly in the Topic yaml.
![image](https://user-images.githubusercontent.com/18172904/201692797-f5052610-4c6d-44f5-9cd0-ad3dc263ac2b.png)

**Comment by Guilamb** [comment]
The exceptions NotEnoughReplicas or NotEnoughReplicasAfterAppend, are raised if a min.insync.replicas value is higher than the number of available brokers.
Also increasing the replication factor will cause the partitions to be stored on as much brokers as specified.
https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#topicconfigs_min.insync.replicas

**Comment by gberche-orange** [comment]
@blezoray any suggestion on why the  min.insync.replicas=3 seems to not be reached with current Kafka CR configuration ?

**Comment by gberche-orange** [comment]
We have pause our exploration project of ksqldb. Reopen if we resume in the future.
