### ISSUE TITLE
add initial support for COAB cf-ops-automation-broker, dedicated on-demand deployments

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#18]
### Expected behavior
Paas user want some service hosted as dedicated resources (not a tenant in a shared service deployment)
We should offer support for https://github.com/orange-cloudfoundry/cf-ops-automation-broker

### Affected release

Reproduced on version 1.24

### Solution outline

- [x] a dedicated bosh-director master-depls/bosh-coab
- [ ] a dedicated prometheus server, for metrics collection and local alerting. Possibily federated with general master-depls/prometheus deployment
- [x] a dedicated cloud-config network

**Comment by gberche-orange** [comment]
complete in v31.0.0
