### ISSUE TITLE
k8s 1.25 - ocp 4.11

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1811]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to
  * have aligned platform  
* I need 
  * target k8s 1.25, openshift 4.11 

### references
I just want to warn that OCP 4.11 comes with some new features that might cause problems.

Here is a Red Hat article about the main new features of OCP 4.11: https://cloud.redhat.com/blog/whats-new-in-red-hat-openshift-4.11

The main feature causing potential problem is the Pod Security Admission (PSA) due to Kubernetes API changes.
Here are two very technical articles describing the change:
-	https://cloud.redhat.com/blog/pod-security-admission-in-openshift-4.11
-	https://connect.redhat.com/blog/important-openshift-changes-pod-security-standards

According to the previous articles, adjustments will be needed to deploy some applications on OCP 4.11.

Depreciations: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#deprecation

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
should skip 1.24 ?
- identify deprecated api used.
- mitigate use of news apis.

**Comment by gberche-orange** [comment]
required sequential bump between K8S version
    mini paas-templates version for K8S bump
    K8S 1.25
    v56 / v55+

**Comment by poblin-orange** [comment]
bumped in 56.1
