### ISSUE TITLE
longhorn 1.4

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1821]
### Expected behavior

* As a paas-templates author
* In order to
  * benefit of a iaas independant csi solution  
  * have a RWX csi storage class https://github.com/longhorn/longhorn/issues/2293
  * combine csi with datalocality https://github.com/longhorn/longhorn/issues/3957
  * get volume level iops visibility https://github.com/longhorn/longhorn/issues/2406
* I need 
  * to evaluate longhorn 1.4 https://github.com/longhorn/longhorn/releases/tag/v1.4.0

### Observed behavior
 
As of v55:
- csi is based on iaas type (cinder csi and sphere csi)
- inherits iaas specific csi driver limitations wrt:
  - multi DC
  - multi cluster (vsphere, nexenta cluster and vsan cluster can not be mixed on a single k8s cluster)
  -  disk resize
  - disk snapshoting
- limited csi usage due to these constraints
- most payload uses k3s local storage path (combined with bosh single disk per vm allocation) 

### References
- https://github.com/orange-cloudfoundry/paas-templates/issues/1771

### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
spike on 00-shared-services (services with storage)
