### ISSUE TITLE
Weave git-ops webui

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1828]
### Expected behavior

* As a paas-templates operator | paas-templates author 
* In order to share permalinks to flux kustomizations
* I need a web ui to display fluxcd objects

### Observed behavior
 
Not yet web ui wiht permalinks for flux

### Reference
* https://docs.gitops.weave.works/docs/intro
* screenshots in https://docs.gitops.weave.works/docs/getting-started/index.html
* chart at https://github.com/weaveworks/weave-gitops/tree/main/charts/gitops-server
   * https://github.com/weaveworks/weave-gitops/blob/main/LICENSE Mozilla Public License 2.0

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
first use case: 00-shared-services
