### ISSUE TITLE
COA failed when root-deployment.yml unknown

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1832]
### Expected behavior

* As a paas-templates operator
* In order to update v55
* I need to deploy coa pipelines without error

### Observed behavior

`coa-v6.0.3-upgrade/trigger-root-deployment-update-pipelines` concourse job failed with following error:

```
/tmp/build/fa403e5a/result-dir/lib/root_deployment_version.rb:21:in `load_file': file not found: ../templates/gcp-depls/root-deployment.yml (RuntimeError)
```

Previous release doesn't set  `gcp-depls/root-deployment.yml` file wich generate error in `main/pipelines/shared-control-plane-generated` concourse jobs.

### Workaround
Create fix branch ` feature-fix-gcp-root-deployment` with `gcp-depls/root-deployment.yml` file. 

For pre-prod and prod deployment, it should be transparent as we include expected workaround in jcr hotfix branch.

### Affected releases

* 55.0.0

**Comment by o-orand** [comment]
This situation is not a very common one: closing
