### ISSUE TITLE
wrong jcr preloaded image

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1837]
### Expected behavior

* As a paas-templates operator
* In order to update v55.0.0
* I need jcr preloaded image to be at good version release

### Observed behavior

New preloaded release must be `7.41.14` on `preload-jcr-images-daemonset`
```
Image:         releases-docker.jfrog.io/jfrog/artifactory-jcr:7.35.2
```

### Affected releases

* 55.0.0

**Comment by o-orand** [comment]
We currently pre load:
 - 7.35.2 (corresponding to v54)
 - 7.41.10 instead of 7.41.14
