### ISSUE TITLE
klipper loadbalancer services failed to get a node

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1843]
### Expected behavior

* As a paas-templates operator
* In order to update v55.0.0
* I need to deploy `00-ci-k8s` cluster without errors

### Observed behavior
 
loadbalancer services `svclb-xxx` failed with following events

```
│ Events:                                                                                                                                    │
│   Type     Reason            Age                     From               Message                                                            │
│   ----     ------            ----                    ----               -------                                                            │
│   Warning  FailedScheduling  8m45s (x275 over 6h7m)  default-scheduler  0/12 nodes are available: 1 node(s) didn't have free ports for the │
│  requested pod ports, 2 node(s) had taint {concourse: true}, that the pod didn't tolerate, 9 node(s) didn't match Pod's node affinity/sele │
│ ctor.                                                                                                                                      │
```
### Affected releases

* 55.0.0

**Comment by poblin-orange** [comment]
change in klipper between versions 1.21 and  1.23.
k3s create supporting DaemonSet in service namespace in 1.21.
k3s creates supporting DaemonSet in kube-system in 1.23

The upgrade path of paas-tempaltes induces a leak in k3s DaemonSet 
https://github.com/k3s-io/klipper-lb/issues/38

**Comment by poblin-orange** [comment]
v55.0.1 post-upgrade should clean

**Comment by ogrand** [comment]
Meanwhile `upgrade/releases/v55.0.0/20-post-upgrade/05-cleanup-old-loadbalancer-services-issue-1843.sh` script to delete `svclb-ldap` pods, `svclb-ldap-0` daemonset recreate old pod inside `openldap` namespace before `kube-system` namespace pods.

**Woraround** : Delete `svclb-ldap-0` daemonset

**Fix** : Add dameonset deletion to the script
