### ISSUE TITLE
Gitlab CA injector pod failed

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1844]
### Expected behavior

* As a paas-templates operator
* In order to update v55.0.0
* I need to deploy `00-ci-k8s` cluster without errors

### Observed behavior

`gitlab/gitlab-cainjector-xxx`failed with error

 ```
│ I0124 07:15:51.336725       1 start.go:82] starting ca-injector v0.10.1 (revision 4aa10bedc)                                               │
│ F0124 07:15:52.596304       1 start.go:123] error registering controllers: no matches for kind "MutatingWebhookConfiguration" in version " │
│ admissionregistration.k8s.io/v1beta1"                                                                                                      │
```

### Affected releases

* 55.0.0
* earlier versions

**Comment by o-orand** [comment]
This is #1693, we fix it by moving to latest Gitlab version, but on core-connectivity cluster. Gitlab on ci-k8s, is going to be deprecated after migration.

**Comment by ogrand** [comment]
Pb comes from k8s 1.23 bump.
This issue will disapear with new flux gitlab in v55.
