### ISSUE TITLE
gitlab-config-tf-runner pod can't access to kubernetes api

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1846]
### Expected behavior

* As a paas-templates operator
* In order to update v55.0.0
* I need `00-core-connectivity-k8s` cluster to have no errors when deployed

### Observed behavior
 
`gitlab/gitlab-config-tf-runner` pod failed with followin error:

```
2023/01/23 15:53:27 Get "https://10.43.0.1:443/api?timeout=32s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

### Affected releases

* 55.0.0

**Comment by poblin-orange** [comment]
same on fe-int v55
