### ISSUE TITLE
approve-and-delete-disabled-deployments (on non-prod env) should be paused before squashing secrets repository

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1849]
### Expected behavior

* As a paas-templates operator
* In order to update v55.0.0
* I need to squash secrets repository without any risks

### Observed behavior
 
when squashing secrets repository, I noticed that every commit will trigger `root-depls/delete-deployments-review` job (don't understand why), taking long time to achieve.
Most of this triggers plan to delete all deployments.
The pb is that `approve-and-delete-disabled-deployments` job is unpaused and some times triggered.
Main risk is that all deployments will be deleted (by chance I manually paused the job before been triggered).

### Affected releases

* 55.0.0

**Comment by o-orand** [comment]
Only Coab-depls `approve-and-delete-disabled-deployments` is scheduled on QA/pre-prod env to avoid smoke tests service leaks. The scheduling is done by `cleanup-coab-deployments` job in `coab-cleanup-pipeline` pipeline and in `coab-depls` team, but this pipeline is not deployed on production env.

**Comment by gberche-orange** [comment]
Action by @gberche-orange to document this prereq in v56 release nots

**Comment by JCL38-ORANGE** [comment]
the pre-requisite is documented in V56_0_5-manual-steps-overview.md.
