### ISSUE TITLE
Prometheus sending Kafka metrics is falling in error regulary "WAL segment"

### ISSUE THREAD

**Issue by Guilamb** [orange-cloudfoundry/paas-templates#1860]
### Expected behavior

* I need to identify the origin of the corruption of prometheus datas

### Observed behavior

Inside  prometheus-remote-write-prometheus-0 pod, the container Prometheus regulary fall in crashLoopBackOff state.
We have identified that the problem come from a corruption of "wal".
After deleting the file, everything come back to normal.

### Traces and logs

```
ts=2023-01-30T09:56:14.624Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673337600000 maxt=1673344800000 ulid=01GQJW1KP4ARNAVGCXBGHV0RDC                               │

│ ts=2023-01-30T09:56:14.626Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1673346567964 maxt=1673352000000 ulid=01GQJW1WSVJ2TJM6JX3STW4JS2                               │

│ ts=2023-01-30T09:56:14.646Z caller=dir_locker.go:77 level=warn component=tsdb msg="A lockfile from a previous execution already existed. It was replaced" file=/prometheus/lock                         │

│ ts=2023-01-30T09:56:14.741Z caller=head.go:562 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"                                                                          │

│ ts=2023-01-30T09:56:14.741Z caller=head.go:606 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=3.347µs                                                         │

│ ts=2023-01-30T09:56:14.741Z caller=head.go:612 level=info component=tsdb msg="Replaying WAL, this may take a while"                                                                                     │

│ ts=2023-01-30T09:56:18.021Z caller=head.go:648 level=info component=tsdb msg="WAL checkpoint loaded"
```

* [x] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by Guilamb** [comment]
Current workaround of deleting wal, come from here : 
https://stackoverflow.com/questions/69417569/unavailable-prometheus-service-with-wal-segment-loaded-entries-in-log-file

**Comment by Guilamb** [comment]
# WAL

## What is it ?
A WAL ( Write-Ahead-Log ) is a sequential log of event.
If the machine or the program decides to crash, the events recorded in the WAL can be replayed back in the same order to restore the data.

Prometheus also uses WAL for graceful restarts to restore the in-memory state.  It does not involve in any other way in read or write operations.

## How it works ?

The write request in TSDB consists of label values of the [series](https://prometheus.io/docs/concepts/data_model/) and their corresponding [samples](https://prometheus.io/docs/concepts/data_model/#samples).

The WAL is stored as a sequence of numbered files with 128MiB each by default. A WAL file here is called a "segment".
```
data
└── wal
    ├── 000000
    ├── 000001
    └── 000002
```

The old WAL segments regularly needs to be deleted, else, the disk will fill up and the startup of TSDB will take a lot of time as it has to replay all the events in this WAL (where most of it will be discarded because it’s old). 

The WAL truncation is done just after the Head block is truncated. The files can't be deleted at random and the deletion happens for first N files while not creating a gap in the sequence.

The series records are written only once, so if you blindly delete the WAL segments, you will lose those records and hence can't restore those series on startup. 
Also, there might be samples which are not truncated from the Head yet, hence you lose them too. This is where checkpoints come into picture.

Before truncating the WAL, a "checkpoint" from those WAL segments to be deleted is created. You can consider a checkpoint as a filtered WAL.
After the WAL truncation and checkpointing, the files on disk look something like this :
```
data
└── wal
    ├── checkpoint.000003
    |   ├── 000000
    |   └── 000001
    ├── 000004
    └── 000005
```

**Comment by Guilamb** [comment]
# Crash Investigation 🔍 
---

**prometheus container describe :**
```
State:       Waiting                                                                                                                                                                                
       Reason:    CrashLoopBackOff                                                                                                                                                                       
       Last State:  Terminated                                                                                                                                                                             
       Reason:    OOMKilled                                                                                                                                                                              
       Message:   maxSegment=5635

```

We can see that the reason for terminating the container is `OOMKilled` which stand for 
Out of memory killed.

**Comment by Guilamb** [comment]
# Prometheus remote write customization 
---
The problem come from the prometheus remote write. We can tune it in order to improve remote settings.
https://prometheus.io/docs/practices/remote_write/

I am experimenting on the different options provided by prometheus in order to find a lesser space consuming solution.

I looked at this blog post, from Saurabh Hirani to get a better understanding of the parameters of prometheus remote write
https://last9.io/blog/how-to-scale-prometheus-remote-write/

```
max shards : 100 => reduce parallelism 
capacity : 2500 => shard memory queue size per shard
max sample per send : 500 =>  batch size of a single remote write
```

In the Prometheus remote write documentation, we can read that : `Shard memory is proportional to the number of shards * (capacity + max_samples_per_send).`
We also get the information that default configuration will constrain shard memory usage to less than 500 kB per shard.
So 100 x ( 2500 + 500 ) = 600 000 => 500 kB

**Comment by Guilamb** [comment]
![image](https://user-images.githubusercontent.com/18172904/230025864-4c767a57-602c-462a-914f-8c530db0b569.png)
![image](https://user-images.githubusercontent.com/18172904/230025969-c029afdd-ff2b-4e40-912a-34622bd0df32.png)
We can see that pics in memory and cpu consumption are directly linked to a drop of packets rate.

- Is a drop of packets rate causing an increase of memory and cpu use 
- Is an increase of memory and cpu usage causing a drop of packets rate

Knowing that the pod fails with a OOMKilled error (out of memory killed)

command ran when container is in CrashLoopBackOff state 
`$ ls | wc -l
183

$ du -sh .
 785.3MB

$ echo "scale=2; $(du -sb . | awk '{ print $1 }') /  $(ls | wc -l) / 1024" | bc
4370.06
`

**Comment by gberche-orange** [comment]
We have pause our exploration project of ksqldb. Reopen if we resume in the future.
