### ISSUE TITLE
missing backup chartmuseum 

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#188]
ChartMuseum store the chart into Minios bucket. This bucket has not backup.

**Comment by poblin-orange** [comment]
consider switching to new harbor 1.6 helm chart support

**Comment by obeyler** [comment]
Don't we just wait for obos V4 ? I think we'll have the same trouble with harbor.

**Comment by poblin-orange** [comment]
closing as we target JCR for helm proxy / hosting #640
