### ISSUE TITLE
Fix Kustomization strategic patch deprecated syntax and leverage new overlay capabilities

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1883]
### Expected behavior

* As a paas-templates maintainer
* In order to bump to latest kustomize CR api version
* I need to not use deprecated syntax

* As a maintainer
* In order to reduce code duplication
* I need to leverage the latest kustomization overlay features

### Reference

- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/

> The patchesStrategicMerge field was deprecated in v5.0.0. This field will never be removed from the kustomize.config.k8s.io/v1beta1 Kustomization API, but it will not be included in the kustomize.config.k8s.io/v1 Kustomization API. When Kustomization v1 is available, we will announce the deprecation of the v1beta1 version. There will be at least two releases between deprecation and removal of Kustomization v1beta1 support from the kustomize CLI, and removal itself will happen in a future major version bump.
> 
> Please move your patchesStrategicMerge into the [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches) field. This field supports patchesStrategicMerge, but with slightly different syntax. You can run kustomize edit fix to automatically convert patchesStrategicMerge to patches.
> 

- https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/ 
> With patches it is possible to override the kind or name of the resource it is editing with the options allowNameChange and allowKindChange

> ```yaml
> # kustomization.yaml
> resources:
> - deployment.yaml
> patches:
>   - path: add-label.patch.yaml
>   - path: fix-version.patch.yaml
>     target:
>       labelSelector: "app.kubernetes.io/name=nginx"
> ```    

> As with the Inline Strategic Merge, the target field can be omitted. In that case, the target resource is matched using the apiVersion, kind and name from the patch.

https://github.com/fluxcd/kustomize-controller/blob/main/CHANGELOG.md
> 0.32.0 Release date: 2022-12-20
> This prerelease comes with experimental support for Kustomize components. 
> 
> 0.27.0 Release date: 2022-08-08
> In addition, the controller has been updated to Kubernetes v1.24.3 and Kustomize v4.5.7
> 

  
### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
No trouble detected in v56.1.0. So I close it.
