### ISSUE TITLE
add the ability to store helm chart just present as source and not in repository

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#189]
some helm chart (such as istio, eclipse che, piripli for example) are not present in any repository but as source code.
we need to have the ability to store them if we want to use it.

**Comment by poblin-orange** [comment]
harbor 1.6 has a new helm chart hosting feature

**Comment by poblin-orange** [comment]
orange made helm hosted in github

**Comment by poblin-orange** [comment]
vendir could be used to integrate helm chart source code in paas-templates repo.
Moreover, tools like rancher are able to retrieve helm charts from git repo

**Comment by poblin-orange** [comment]
Seems Fluxcd v2 is able to leverage github repo as HemRepository resource cc @gberche-orange 
Closing issue, to leverage later
