### ISSUE TITLE
docker repo team sunset.

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1909]
### Expected behavior

* As a paas-templates  author
* In order to 
  * maintain service beyond april 2023
* I need 
  * to decouple paas-templates from docker team hosting 

### Possible steps

* [ ] bump & move images in coa
* [ ] move images in on-prem jcr

### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
Update from Docker Inc 
> On March 14, 2023, we emailed you about your Free Team subscription, outlining our intention to sunset that plan. After listening to the concerns of the community, we’ve decided to reverse course, and are no longer sunsetting the Free Team plan. 
> If you’re currently on the Free Team plan, you no longer have to migrate to another plan by April 14. All customers who upgraded to a paid subscription will automatically receive a full refund for the transaction in the next 30 days, allowing them to use their new paid subscription for free for the duration of the term they purchased. 
> We apologize for the alarm our decision caused. For more details, please 

See also https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

**Comment by o-orand** [comment]
We no longer require to switch to user repository, but as it is done, we keep it.
