### ISSUE TITLE
fix for misconfigured metallb vip pool

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1922]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to 
* I need 

### constraints for resolution

- vip pool should not be in bosh allocatable ips list => fix: vip pool should be  included in bosh network reserved list

- metallb resolution: metallb wont renew vip if pool change (product feature). Must recreate the artifact with metallb annotation
   - LoadBalancer service
   - Ingress
   - eg: Services and Ingress directly managed with fluxcd Kustomization, manual delete + flux reconcile will reallocate ips (service interuption)
 - dns resolution: 
   - will converge with external dns controller (sync policy will align dnsaas with new vips)
   - additional service interruption (dns record TTL, client will keep old ip in their dns cache for the TTL period)
 - HelmRelease managed loadbalancer/ingress
   - helm wont detect the change (same helmchart version, same values). 
   - eg: redis helm chart / mariadb helm chart
   - solution:
     - batch remove all metallb annotations on "out of pool" vips, wait a delay for metallb to free the vips, then re annotate with the metallb annotation => intermediate commit removing the annotation from HelmRelease values yaml, let it converge, then revert commit.  ==> KO, to check with metallb upstream issues.

 
### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
If we restart both metallb controller and speakers, all services (load-balancer) are updated with VIPs taken from the new configured pool.
