### ISSUE TITLE
HA for internet ingress routing

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#193]
### Expected behavior

As a service operator, in order to avoid manual orchestration among components that need updates in a release, I need ingress routing to update without downtimes (e.g. version bumps, stemcell bumps, or config changes can be applied without triggering routing downtimes )

As a service author, in order to spend less time with describing manual orchestrations in the release notes (see #342), I expect components to update independently of others and without downtimes.

### Observed behavior

Currently out internet FQDN resolves to a single elasticIp which is bound to a single VM. This is a SPOF.

We need to add high availability to this connectivity.

Possible evolutions:
* Use user-facing DNS load balancing to multiple elasticIps, bound to distinct AZ (i.e. internet FQDNs resolves to multiple IP addresses)
   * See related [cloudflare DNS load balancing](https://support.cloudflare.com/hc/en-us/articles/212794707-General-Best-Practices-for-Load-Balancing-at-your-origin-with-Cloudflare) and [cloudflare load balacing, intelligent fail over](https://support.cloudflare.com/hc/en-us/articles/115000081911-Tutorial-How-to-Set-Up-Load-Balancing-Intelligent-Failover-on-Cloudflare) with active health checks against your origin servers
* Set up HA at the internet-relay level: study feasibility of 
   * Use Iaas load balancer to distribute traffic floating ip to multiple vms

see related  #182

**Comment by poblin-orange** [comment]
Solution outline - Cloudflare generalization:
- [ ]  remove legacy openstack security group filtering (no more hardcoded inbound filter ips)
- [ ]  new security group, filtering https (443) traffic from a configurable list of cloudfare IPs 
- [ ] add 2 configurable floating ips, on 2 new cf-internet-rps z1/z2 inside master-depls/isolation-segment-internet, appy the new cloudfare security group, wire the backend to gorouter with az aware bosh dns local aliases.
- [ ] switch cloudflare bakend to the 2 new floating ips. Ensure the Cloudflare config will switch/failover  in case of az failure.
- [ ] switch custom cloudflare subscription to new 2 new ips


clean-up
- [ ] purge legacy o-internet-access, instances, brokers
- [ ] remove legacy micro-depls/internet-relay
- [ ] purge non-cloudflare internet cf domains ?

**Comment by poblin-orange** [comment]
merged for v43, not activable due to #556
