### ISSUE TITLE
Cassandra multi data center support

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#194]
In order to support statefull applications deployed across distinct CF deployments, we need data services that are available in an active-active setup across different Cf deployments, likely different regions.

Cassandra seems a good candidate for the key/value data service use-case (see related [doc extract](https://docs.datastax.com/en/cassandra/3.0/cassandra/dml/dmlClientRequestsMultiDCWrites.html)).

Steps:
* [ ] Configure cassandra (on-demand) cluster with multiple DCs matching CF deployment topology. See related [cassandra-boshrelease](https://github.com/orange-cloudfoundry/cassandra-boshrelease/blob/fd66a7d8544e783fd50bfd7e36c4bf5c243a5bf7/jobs/cassandra/spec#L574-L606) configuration
* [ ] Enable networking cassandra replication across CF deployment networks (where cassandra clusters are colocated)
* [ ] Surface multi-CF support in service UX (i.e provide ways to connect on-demand C* clusters together with desired [data distribution and replication](https://docs.datastax.com/en/cassandra/3.0/cassandra/architecture/archDataDistributeAbout.html) when [adding/removing the new DC](https://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsAddDCToCluster.html?hl=datacenter) to each cluster)

**Comment by poblin-orange** [comment]
I understand the cassandra bosh releases supports multiple azs (not multiple region). For flexible Engine, we can have 2 azs on different dcs. Supporting multiple datacenter in a portable way (say azure)  will require an upstream change to cassandra bosh release ?

**Comment by poblin-orange** [comment]
@regismarg is cassandra an expected target for acdc ?

**Comment by regismarg** [comment]
@poblin-orange : cassandra analyzed by erablr PaaS Team, to see in our services if intersting or not
