### ISSUE TITLE
Wireguard observability (supporting diagnostic of mysql galera flapping masters and flushing client connections)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1953]
### Expected behavior

* As a paas-templates operator 
* In order to quickly diagnose flushed mysql extended cnx (e.g. etherpad)
* I need automated diagnostics and alerts

### Observed behavior

For yet undiagnosed issue, we suspect network congestions leading mysql on r1-z1 to split brain from mysql on r2-z1 and arbitrator on r3-z1: galera is not receiving expected ACKs within 3s

Context:
- backend-0 at 192.168.65.25 (r2-z1)
- backend-1 at 192.168.70.26:3306 (r1-z1)
- arbitrator 192.168.68.23 (r3)
- bosh coab 192.168.99.155 (r1)

```
mysql/b714892d-6a65-494f-97ab-e147b80e4152:/var/vcap/sys/log/mysql# less mysql.err.log

2023-04-26 15:00:09 0 [Note] WSREP: (064522b8, 'tcp://0.0.0.0:4567') connection to peer 793b08c7 with addr tcp://192.168.65.25:4567 timed out, no messages seen in PT3S
2023-04-26 15:00:09 0 [Note] WSREP: (064522b8, 'tcp://0.0.0.0:4567') connection to peer 18a29a69 with addr tcp://192.168.68.23:4567 timed out, no messages seen in PT3S
2023-04-26 15:00:09 0 [Note] WSREP: (064522b8, 'tcp://0.0.0.0:4567') turning message relay requesting on, nonlive peers: tcp://192.168.65.25:4567 tcp://192.168.68.23:4567 
2023-04-26 15:00:11 0 [Note] WSREP: (064522b8, 'tcp://0.0.0.0:4567') reconnecting to 793b08c7 (tcp://192.168.65.25:4567), attempt 0
2023-04-26 15:00:11 0 [Note] WSREP: (064522b8, 'tcp://0.0.0.0:4567') reconnecting to 18a29a69 (tcp://192.168.68.23:4567), attempt 0
2023-04-26 15:00:11 0 [Note] WSREP: (064522b8, 'tcp://0.0.0.0:4567') connection established to 18a29a69 tcp://192.168.68.23:4567
```

PT3S = 3s duration
https://stackoverflow.com/questions/51168022/what-does-pt-prefix-stand-for-in-duration

As a result mysql on r1 closes its tcp connection with r2, which r1 receives. r1 does not detect a connection close from r3

```
2023-04-26 14:00:14 0 [Note] WSREP: (793b08c7, 'tcp://0.0.0.0:4567') turning message relay requesting off
2023-04-26 15:00:10 0 [Note] WSREP: (793b08c7, 'tcp://0.0.0.0:4567') turning message relay requesting on, nonlive peers: tcp://192.168.70.26:4567 
2023-04-26 15:00:11 0 [Note] WSREP: (793b08c7, 'tcp://0.0.0.0:4567') reconnecting to 064522b8 (tcp://192.168.70.26:4567), attempt 0
2023-04-26 15:00:11 0 [Note] WSREP: (793b08c7, 'tcp://0.0.0.0:4567') connection established to 064522b8 tcp://192.168.70.26:4567
2023-04-26 15:00:11 0 [Note] WSREP: (793b08c7, 'tcp://0.0.0.0:4567') connection established to 064522b8 tcp://192.168.70.26:4567
2023-04-26 15:00:11 0 [Note] WSREP: declaring 18a29a69 at tcp://192.168.68.23:4567 stable
2023-04-26 15:00:11 0 [Note] WSREP: Node 18a29a69 state prim
2023-04-26 15:00:11 0 [Note] WSREP: view(view_id(PRIM,18a29a69,5266) memb {
```

No discriminant wireguard traces on r1 or r3

```
vpn/acbc4638-34c3-4036-9b9f-cf6ee1a5e19d:/var/log# grep -rih wireguard . | grep 2023-04-26 | sort > /tmp/wireguard.logs
2023-04-26T14:58:30.556407+00:00 129f8f81-3320-446d-b2ec-298cf9463ce7 kernel: [9996348.368629] wireguard: wg0: Keypair 166619 destroyed for peer 7
2023-04-26T14:58:30.556407+00:00 129f8f81-3320-446d-b2ec-298cf9463ce7 kernel: [9996348.368629] wireguard: wg0: Keypair 166619 destroyed for peer 7
2023-04-26T14:58:30.556409+00:00 129f8f81-3320-446d-b2ec-298cf9463ce7 kernel: [9996348.368631] wireguard: wg0: Keypair 166623 created for peer 7
2023-04-26T14:58:30.556409+00:00 129f8f81-3320-446d-b2ec-298cf9463ce7 kernel: [9996348.368631] wireguard: wg0: Keypair 166623 created for peer 7
```

### Reference

#1510
#1509

### Possible fixes

* [ ] Configure prometheus exporter to compute the `wireguard_latest_handshake_delay_seconds` (seconds passed since the last handshake)
* [ ] Configure grafana dashboard for wireguard exporter, possibly adapting https://github.com/mdlayher/wireguard_exporter#grafana-dashboard

### Workaround

Manually observe tcp connection states during the periodic problem window

```
(sleep  $(( $(date -f - +%s- <<< "today 13:58"$'\nnow') 0 )); while true; do date; vmstat; ps -Ao user,uid,comm,pid,pcpu,rss,tty --sort=-pcpu | head -n 10; iostat; netstat -s -t; echo "Connections:"; netstat -anp | grep -e 192.168.99.155 -e 192.168.65.25 -e 192.168.70.39 -e 192.168.70.26; sleep 1; done;) | tee -a /var/vcap/store/diagnostic.txt
```

This shows simultaneous growing network queues and tcp cnx closing
```
Wed Apr 26 17:00:06 UTC 2023
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 192.168.65.25:9104      192.168.70.40:36476     ESTABLISHED 27151/mysqld_export 
tcp        0      0 192.168.65.25:9200      192.168.65.26:37938     ESTABLISHED 27078/galera-health 
tcp        0    581 192.168.65.25:58210     192.168.99.155:4222     ESTABLISHED 22112/bosh-agent    
tcp        0  68494 192.168.65.25:40022     192.168.99.17:5514      ESTABLISHED 23545/rsyslogd      
tcp        0    861 192.168.65.25:44754     192.168.70.26:4567      FIN_WAIT1   -                   
tcp        0      0 192.168.65.25:41290     192.168.70.40:443       CLOSE_WAIT  27167/shield-agent  
tcp        0  29352 192.168.65.25:22        192.168.116.100:33964   ESTABLISHED 29574/sshd: bosh_13 
tcp        0  68662 192.168.65.25:40024     192.168.99.17:5514      ESTABLISHED 23545/rsyslogd      
tcp        0      0 192.168.65.25:9200      192.168.70.39:49602     ESTABLISHED 27078/galera-health 
tcp        0      1 192.168.65.25:51268     192.168.70.40:443       SYN_SENT    27167/shield-agent  
tcp        0      1 192.168.65.25:56074     192.168.70.26:4567      SYN_SENT    27018/mysqld        
tcp        0      0 192.168.65.25:4567      192.168.68.23:34348     ESTABLISHED 27018/mysqld        
tcp        0      0 192.168.65.25:9100      192.168.99.143:40786    ESTABLISHED 27193/node_exporter 
tcp        0     25 192.168.65.25:60226     192.168.70.40:443       LAST_ACK    -                   
tcp        0  13928 192.168.65.25:22        192.168.116.100:51502   ESTABLISHED 30780/sshd: bosh_5f 
```

ntop ui on vpn r1 and vpn r2 might show traffic burst on relative url `lua/if_stats.lua?ifid=0&page=historical`

Check `severing` tcp connexion from `mysql proxy` (to check event frequency):

```bash
#--- Check severing proxy tcp connexions
deployments="$(bosh deployments --json | jq -r '.Tables[].Rows[].name' | grep "t_")"
if [ "$1" != "" ] ; then
  if [ "$1" = "all" ] ; then
    current_date="Severing"
  else
    current_date="$1"
  fi
else
  current_date="$(date +%a" "%b" "%d)"
fi

for deployment in ${deployments} ; do
  printf "\n%b${deployment}%b\n" "${REVERSE}${GREEN}" "${STD}"
  instances="$(bosh -d ${deployment} vms --json | jq -r '.Tables[].Rows[].instance' | grep "proxy/")"
  for instance in ${instances} ; do
    printf "  %b${instance}%b\n" "${REVERSE}${YELLOW}" "${STD}"
    bosh ssh -d ${deployment} ${instance} -c 'grep "Severing" /var/vcap/sys/log/proxy/switchboard.combined.log' | perl -pe 's+([0-9]*)\.([0-9]*)+localtime($1)+e' | grep "${current_date}" | grep "stdout" | sed -e 's+^.*timestamp":"+  +g' -e 's+","source.*switchboard.Severing+ Severing+g' -e 's+".*++g'
  done
done
```

**Result**

```
t_3f13c01b-0214-434b-929a-67732e599186 proxy/5e774a09-9a23-45be-80ed-bba4f0b5f4f4
  Thu Apr 27 00:00:06 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 00:00:11 2023 Severing all connections to backend-0 at 192.168.65.25:3306
  Thu Apr 27 01:00:12 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 01:00:15 2023 Severing all connections to backend-0 at 192.168.65.25:3306
  Thu Apr 27 02:00:06 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 02:00:13 2023 Severing all connections to backend-0 at 192.168.65.25:3306
  Thu Apr 27 03:00:10 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 03:00:18 2023 Severing all connections to backend-0 at 192.168.65.25:3306
  Thu Apr 27 04:00:07 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 04:00:12 2023 Severing all connections to backend-0 at 192.168.65.25:3306

t_3f13c01b-0214-434b-929a-67732e599186 proxy/d7fc1f80-a6fb-473e-af7c-d598a5d32cd9
  Thu Apr 27 00:00:11 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 00:00:12 2023 Severing all connections to backend-0 at 192.168.65.25:3306
  Thu Apr 27 01:00:12 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 01:00:15 2023 Severing all connections to backend-0 at 192.168.65.25:3306
  Thu Apr 27 02:00:11 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 02:00:14 2023 Severing all connections to backend-0 at 192.168.65.25:3306
  Thu Apr 27 03:00:13 2023 Severing all connections to backend-1 at 192.168.70.26:3306
  Thu Apr 27 03:00:18 2023 Severing all connections to backend-0 at 192.168.65.25:3306
```

### Affected releases

* 55.x
* earlier versions

**Comment by gberche-orange** [comment]
Suspicion that the network congestion at every hour might be linked to time desynchronization across wireguard nodes.

After the following manual time synchronization, the network congestion every hour problem is not observed anymore:
```
vpn/c5f3bdca-860f-490d-bc00-eaae9fe3ef3a:~# date --set="Thu Apr 27 13:35:10 UTC 2023"                                                                                                                              Thu Apr 27 13:35:10 UTC 2023  
```

Still missing evidence and explanation of the effect of time desynchronization w.r.t. vpn packet loss at fixed time

The wireguard white paper at https://www.wireguard.com/papers/wireguard.pdf mentions:
> Handshake messages
> 12-byte TAI64N [7] timestamp is included, encrypted and
authenticated, in the first message. The responder keeps track of the greatest timestamp received per peer and
discards packets containing timestamps less than or equal to it. (In fact, it does not even have to be an accurate
timestamp; it simply must be a per-peer monotonically increasing 96-bit number.)
> 

https://www.wireguard.com/protocol/
> This handshake occurs every few minutes, in order to provide rotating keys for perfect forward secrecy. It is done based on time, and not based on the contents of prior packets, 
> The following timers are at play:
> [...]

**Comment by gberche-orange** [comment]
https://github.com/MindFlavor/prometheus_wireguard_exporter is already installed and configured on vpn-r1
> This tool exports the wg show all dump (or wg show <interface> dump if you specify a config file) results in a format that [Prometheus](https://prometheus.io/) can understand.

Man page extract
> COMMANDS
       show { <interface> | all | interfaces } [public-key | private-key | listen-port | fwmark | peers | preshared-keys | endpoints | allowed-ips | latest-handshakes | persistent-keepalive  |  transfer  |
       dump]
              Shows  current  WireGuard  configuration  and runtime information of specified <interface>.  If no <interface> is specified, <interface> defaults to all.  If interfaces is specified, prints a list of all WireGuard interfaces, one per line, and quits. If no options are given after the interface specification, then prints a list of all attributes in a visually pleasing way meant for the  terminal.  Otherwise,  prints specified information grouped by newlines and tabs, meant to be used in scripts. For this script-friendly display, if all is specified, then the first field for all categories of information is the interface name. If dump is specified, then several lines are printed; the first contains in order separated by tab: private-key,  public-key,  listen- port,  fwmark.  Subsequent lines are printed for each peer and contain in order separated by tab: public-key, preshared-key, endpoint, allowed-ips, latest-handshake, transfer-rx, transfer-tx, persistent-keepalive.

```
vpn/acbc4638-34c3-4036-9b9f-cf6ee1a5e19d:/var/log# curl http://localhost:9586/metrics | grep '#'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1660  100  1660    0     0  69166      0 --:--:-- --:--:-- --:--:-- 69166
# HELP wireguard_sent_bytes_total Bytes sent to the peer
# TYPE wireguard_sent_bytes_total counter
# HELP wireguard_received_bytes_total Bytes received from the peer
# TYPE wireguard_received_bytes_total counter
# HELP wireguard_latest_handshake_seconds Seconds from the last handshake
# TYPE wireguard_latest_handshake_seconds gauge
```

The `wireguard_latest_handshake_delay_seconds` metric is currently missing

> <html><body>
> <div class="highlight highlight-source-shell notranslate position-relative overflow-auto" dir="auto"></div>
> 
> Parameter | Env | Mandatory | Valid values | Default | Accepts multiple occurrences? | Description
> -- | -- | -- | -- | -- | -- | --
> [...]
> -d | EXPORT_LATEST_HANDSHAKE_DELAY | No | true or false | false | No | Adds the wireguard_latest_handshake_delay_seconds metric that automatically calculates the seconds passed since the last handshake.
> 
> 
> </body>
> </html>

**Comment by ogrand** [comment]
**Note:** Exists alert `vpnFailed` when `wireguard_latest_handshake_seconds` is null
