### ISSUE TITLE
COA should support older stemcell (eg: bionic versus main stemcell jammy)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1964]
### Expected behavior

* As a paas-templates paas-templates author 
* In order to 
  *  be able to run transiently bosh release not compatible with current stemcell
* I need 
  * the ability to decouple bosh release download url for specified bosh deployment

### Observed behavior
 
As of v56, paas-templates is bumping to jammy stemcell. mongodb 4 bosh release is not compatible

### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
Enhancement to be able to partially support multiple stemcells are included in [COA 6.1](https://github.com/orange-cloudfoundry/cf-ops-automation/milestone/24?closed=1) :
 - https://github.com/orange-cloudfoundry/cf-ops-automation/pull/416
