### ISSUE TITLE
Update cassandra service shared deployment with latest release (v9)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#198]
This issue is about the bump of the latest Orange cassandra release : 
### Steps:
- [ ] Update the cassandra shared deployment in order to bump latest cassandra release (https://github.com/orange-cloudfoundry/cassandra-boshrelease/releases/tag/v9)
- [ ] Use the cassandra deployment repository (https://github.com/orange-cloudfoundry/cassandra-deployment)

**Comment by poblin-orange** [comment]
cassandra v10 merged in v37
