### ISSUE TITLE
Whitelist for internet-proxy bypassed

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1987]
### Expected behavior

As a paas-templates operator in order to secure internet-proxy doamins acces, I need that whitelisting feature works

### Observed behavior
 
squid acl `whitelist_domains` doesn't work yet when lifen prometheus squid exporter add acl

### Affected releases

* 55

**Comment by poblin-orange** [comment]
side effect of lifen squid helm chart bump
