### ISSUE TITLE
offline docker registry

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#20]
### Expected behavior
cfcr k8s, COA pipeline and jobs should not depend on internet public docker registry

### Observed behavior
permanent access to internet dockerhub from concourse.

### Affected release
38

### Traces and logs
Impacted components
- all COA pipelines use community images from public docker hub
- docker bosh release components.
  - master-depls/prometheus thanos sidecars
  - micro-depls/gitlab

### Solution outline
- [X] add an embedded private docker registry (eg vmware harbor or sonatype nexus). v41
- [X] update COA to use this private repo. COA >=3.5 - v42
- [ ] update bosh manifests template
- [x] set up a private proxy for docker - sonatype nexus OSS (artifactory has docker registry, but only on pro commercial edition)
- [ ] CFCR use installed nexus instead of direct download with docker daemon registry mirror configuration

**Comment by gberche-orange** [comment]
Somewhat related article describing alternative airgapped environment strategy. https://docs.pivotal.io/pivotalcf/2-5/customizing/offline_installation.html 

@oblin I'm not sure we have a more generic airgap issue to attach this comment to (as this one is focused on docker registry). Should we create one then ?

**Comment by obeyler** [comment]
https://blog.inkubate.io/how-to-use-harbor-private-registry-with-kubernetes/

**Comment by obeyler** [comment]
habor trouble for ldap member of admin group
https://github.com/vmware/harbor-boshrelease/issues/49

**Comment by poblin-orange** [comment]
as of v41, micro-depls/nexus is added.
will switch concourse (COA 3.5), docker bosh-release and cfcr docker registry references in v42

**Comment by poblin-orange** [comment]
switch merger for v42

**Comment by gberche-orange** [comment]
@poblin-orange Should we track pending work on nexus component into a distinct issue (ha, backup, automated configuration, monitoring) ? See related #377 for potential checklist.

FYI nexus is also available as a bosh release https://github.com/making/nexus-boshrelease supporting backups through BBR but it does not yet seem to expose properties for provisionning its configuration https://github.com/making/nexus-boshrelease/blob/master/jobs/nexus/spec#L15-L51

**Comment by gberche-orange** [comment]
follow up work tracked in #489
