### ISSUE TITLE
Merged branches from release notes not renamed

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#2017]
### Expected behavior

* As a paas-templates operator
* In order to upgrade version
* I need oldest branches merged in new paas-template release to be deactivated

### Observed behavior
 
=> Status after job `paas-templates-55.0.3-upgrade/manual-step-apply-git-already-merged-branches-removal` bee triggered

- Only 3 branches to be renamed
```
origin/55.0.0-auto-delete-feature-activate-mariadb-dedicated-xlarge-plan
origin/55.0.0-auto-delete-feature-fix-openstack-cpi-user-data-for-v54
origin/55.0.3-auto-delete-feature-hotfix-squid-deadlock-v54
```

- Other branches included in v55 not renamed

```
origin/feature-adapt-cf-mysql-xlarge-persistent-disk-type
origin/feature-basic-auth-for-strimzi-dashboards
origin/feature-enable-rabbitmq-diag-plugins
origin/feature-hotfix-coab-strimzi-acl-loss
origin/feature-hotfix-increase-agent-timeout
origin/feature-hotfix-squid-deadlock-v54
origin/feature-increase-cf-redis-osb-flavor
origin/feature-increase-persistant-disks-mysql-shared
origin/feature-increase-vm_type-mysql-shared
origin/feature-jcr-adapt-airgap-images
origin/feature-mariadb-shared-staging
origin/feature-rabbitmq-1-or-2-node-down
origin/feature-reduce-memory-remote-write-prometheus
origin/feature-set-coab-cf-mysql-health-check-type-process
origin/feature-strimzi-v54-tuning
```

### Affected releases
* 55.0.3

**Comment by JCL38-ORANGE** [comment]
To check against automatic rebase done by COA in 6.X ?

**Comment by o-orand** [comment]
With [ feature-auto-rebase-during-upgrade #2519 ](https://github.com/orange-cloudfoundry/paas-templates-private/pull/2519) introduced in v56, not deleted branches are rebased automatically.
