### ISSUE TITLE
old openstack iaas-type master-depls cloud-config-tpl.yml still present

### ISSUE THREAD

**Issue by shoudusse** [orange-cloudfoundry/paas-templates#202]
Versions:
- 34.0.0
- 35.0.0
- 36.0.0

The file `master-depls/template/openstack/cloud-config-tpl.yml` is still present and overrides the good one `master-depls/template/cloud-config-tpl.yml`
Consequently all upgrade for master-depls cloud-config are not taken into account for openstack IaaS type.
Example:
`Expected to find exactly one matching array item for path '/networks/name=tf-is-internet' but found 0`

**Comment by shoudusse** [comment]
After some investigation, we have agreed the file `master-depls/template/openstack/cloud-config-tpl.yml` is needed as it contains some particularities needed for openstack iaas-type.
Consequently, upgrades from central cloud-config-tpl and needed for openstack iaas-type shoud be report in this file

**Comment by poblin-orange** [comment]
target  36.0.3
