### ISSUE TITLE
offer mysql over TLS

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#203]
Currently, we offer mysql access through plain mysql protocol on 3306 port. Traffic goes unencrypted between application workloads in CFAR and the mysql cluster closeby, and potentially vulnerable to MIT attacks.

When offering mysql to remote workloads (see #170 ), confidentiality of exchanges become more important.

### References

Related support in cf-mysql-release, and inspiration in COTS products describing impact for applications to consume. The 
* https://github.com/cloudfoundry/cf-mysql-deployment/blob/2a35d5ab47dc99d0b2a1a2ff818818fc40a5544b/operations/add-tls.yml#L2
* https://github.com/pivotal-cf/docs-mysql/blob/cd4fce8fd66501ea9bea6511630755a83c68639a/prepare-tls.html.md.erb#L13-L32 
> Enabling TLS provisions a MySQL server with a certificate so that apps and clients can establish an encrypted connection with the data service. The certificate deployed with the MySQL server is a **server certificate**. The server certificate is generated by **CredHub**. [...] 
> PCF distributes the public component of the CA certificate to apps in two ways:
> * PCF provisions a copy of the CA certificate in the trusted store of each container's operating system.
>  Apps written in Java and Spring automatically discover the CA certificate in the trusted stored.
> * PCF supplies the public CA certificate in an environment variable called `VCAP_SERVICES`

* https://github.com/pivotal-cf/docs-mysql/blob/cd4fce8fd66501ea9bea6511630755a83c68639a/modify-apps-tls.html.md.erb#L19-L54
>    Retrieve the hostname, username, password, database name, and CA certificate for the bound > MySQL for PCF service instance from the VCAP_SERVICES environment variable.
>    Use the hostname, username, password, and CA certificate to establish a secure connection > with the bound MySQL for PCF service instance.

For Java applications, the jdbc url from service binding credentials are expected to include the proper properties to enable TLS using JDBC driver:
* Mysql JDBC driver support params for TLS connections, see https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-using-ssl.html https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html (useSSL, requireSSL, verifyServerCertificate, ...)
So explicit JVM configuration or JDBC driver connection isn't needed within CF, but would might be required in other hosting environments. See related https://stackoverflow.com/questions/43635449/how-to-configure-spring-boot-application-to-use-ssl-tls-over-mysql

**Comment by JCL38-ORANGE** [comment]
Merged in v43 (dedicated)

**Comment by gberche-orange** [comment]
Credentials returned are of the following form with jdbcUrl expecting TLS

```json
    "credentials": {
     "ca_certificate": "-----BEGIN CERTIFICATE-----\nMIIDETCCAfmgA[...]\n-----END CERTIFICATE-----\n",
     "hostname": "192.168.211.73",
     "jdbcUrl": "jdbc:mysql://192.168.211.73:3306/cf_0fc91fac_bda9_496b_b0c3_a43dcbead5ed?user=...\u0026password=...\u0026useSSL=true\u0026enabledTLSProtocols=TLSv1.2\u0026enabledSslProtocolSuites=TLSv1.2",
     "name": "cf_0fc91fac_bda9_496b_b0c3_a43dcbead5ed",
     "password": "...",
     "port": 3306,
     "uri": "mysql://...:...@192.168.211.73:3306/cf_0fc91fac_bda9_496b_b0c3_a43dcbead5ed?reconnect=true",
     "username": "..."
    },
```

**Comment by gberche-orange** [comment]
The problem reported by @skortobi is that java applications need to include the mysql server certificate packaged as a java truststore in their code (i.e. the file needs to be present in the application droplet, eg in the jar in a `resources/` path) so that the mysql driver can read it 

See https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html
> The next step is to configure Java or Connector/J to read the truststore you just created or modified. This can be done by using one of the following three methods: 
> 1 Using the Java command line arguments:
> -Djavax.net.ssl.trustStore=path_to_truststore_file 
> -Djavax.net.ssl.trustStorePassword=mypassword
>  2. Setting the system properties directly in the client code:
> System.setProperty("javax.net.ssl.trustStore","path_to_truststore_file"); 
> System.setProperty("javax.net.ssl.trustStorePassword","mypassword");
>3.  Setting the Connector/J connection properties:
> clientCertificateKeyStoreUrl=file:path_to_truststore_file 
> clientCertificateKeyStorePassword=mypassword

Options:

1- before app start, extract the cert onto disk, and point the driver to it

a script executed at application startup which will 
* extract the content of the VCAP_SERVICES credentials.ca_certificate json entry and store it onto the disk
* modify the environment variables to point the jdbc driver to this file, e.g. transform the jdbc url in VCAP_SERVICES  to add the `clientCertificateKeyStoreUrl` to file://

See https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#profile

> Your app root directory may also include a .profile.d directory that contains bash scripts that perform initialization tasks for the buildpack. 
> Note: CFAR does not support initialization scripts for the Java buildpack or PHP buildpack versions prior to v4.3.18

2- modify paas-templates so that it serves through https the internal ca certs, so that the driver than load it through the network

3- Have the client OSB platform import the paas-templates internal ca certs used to sign the database certs.

See https://docs.cloudfoundry.org/running/trusted-system-certificates.html

/CC @poblin-orange @JCL38-ORANGE @ldangeard-orange

**Comment by poblin-orange** [comment]
Context
- mariadb jdbc driver validates certificate
- mysql jdb driver does not ?
- when cf and marketplace are split, no shared credhub ca. The certs injected by diego and java buildpack in cf apps truststore do not match.
