### ISSUE TITLE
cf-cli-cmdb-functions alias are not sourced anymore in bastion cli in v55

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2033]
### Expected behavior

* As a paas-templates operator 
* In order to access osb-cmdb 
* I need to leverage the bash aliases published in https://github.com/orange-cloudfoundry/cf-cli-cmdb-scripts see https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/issues/60

### Observed behavior
 
As of v55 bastion statefulset containers, the scripts are properly mounted in container, but not sourced anymore

```bash
$ cf_cmdb_cli_usage 
-bash: cf_cmdb_cli_usage: command not found
```

### Workaround

```bash
source /usr/local/bin/cf-cli-cmdb-functions.bash
source /usr/local/bin/cf-cli-cmdb-functions.bash
```

### Affected releases

* x.y
* earlier versions

**Comment by ogrand** [comment]
Done in bastion-ssh image with latest release
