### ISSUE TITLE
ha-datastore k8s cluster lacks observability and recovery

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#2064]
### Expected behavior
* As a paas-templates operator
* In order to be confident with my platform
* I need to have observability and recovery materials for ha-datastore k8s cluster

### Observed behavior
ha-datastore k8s cluster doesn't have  observability and recovery materials
 
### Possible fixes

* [ ] Collect Postgresql metrics (including slow queries)
   * [x] Install `pg_stat_statements` in cnpg  https://cloudnative-pg.io/documentation/1.19/postgresql_conf/#enabling-pg_stat_statements
      * [x] see sample usage https://www.postgresql.org/docs/current/pgstatstatements.html
   * [ ] Install alternative postgresql exporter https://coroot.com/blog/pg-agent
      * https://github.com/coroot/coroot-pg-agent
         > Metrics should help you identify issues with your Postgres servers.
         > This agent collects metrics that can help you answer questions such as:
         >   * What queries are consuming the most IOPS or CPU time?
         >   * Which transactions are hanging in the Idle in transaction state?
         >   * Which query is holding the lock?

   * [x] Configured pq cli on bastion to run statements within pg
      * See https://cloudnative-pg.io/documentation/1.20/kubectl-plugin/#launching-psql

```
echo "select count(*) from kine;" |  kubectl cnpg psql postgres -n 95-shared-services-datastore -- --dbname=k3s  
 count 
-------
  7716
(1 row)
```

  
* [ ] Visualize Postgresql metrics 
   * [x] through CNPG dashboards
   * [ ] through PMM ([Percona Monitoring and Management](https://www.percona.com/doc/percona-monitoring-and-management/index.html)) Grafana dashboard https://grafana.com/grafana/dashboards/10017-postgresql-queries-overview/
      * https://www.percona.com/blog/adding-postgresql-queries-overview-dashboards-to-the-pmm-plugin/
      * https://docs.percona.com/percona-monitoring-and-management/
   
>    ```
> bench=# SELECT query, calls, total_exec_time, rows, 100.0 * shared_blks_hit /
>                nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent
>           FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 5;
> -[ RECORD 1 ]---+--------------------------------------------------​------------------
> query           | UPDATE pgbench_branches SET bbalance = bbalance + $1 WHERE bid = $2
> calls           | 3000
> total_exec_time | 25565.855387
> rows            | 3000
> hit_percent     | 100.0000000000000000
> -[ RECORD 2 ]---+--------------------------------------------------​------------------
> query           | UPDATE pgbench_tellers SET tbalance = tbalance + $1 WHERE tid = $2
> calls           | 3000
> total_exec_time | 20756.669379
> rows            | 3000
> hit_percent     | 100.0000000000000000
> ```
> 

* [x] static ip for 00-ha-datastore server/*
* [x] scrape from prometheus supervision using static ip
* [x] new 00-ha-datastore grafana datasource. TBC filtering criteria compatible with static ip

**Comment by gberche-orange** [comment]
Reopening to complement with postgresql slow query supports
