### ISSUE TITLE
tmux is missing from inception vm

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2071]
### Expected behavior

* As a paas-templates operator
* In order to be able to recover my work context (k9s session, ssh connections) enviroment across network disconnections such as
   * remoting home/work
   * disconnect from remoting vpn
   * switch vpn to access inception from openstack to vmware environment
* I need tmux to keep my session active

### Observed behavior
 
tmux is missing

### Workaround

* Search for secrets.multi_region.region_1.corporate_internet.proxy_host in shared/secret.yaml

```
sudo -i
export https_proxy=http://xx:443
export http_proxy=http://xx:443
apt-get update
apt-get install tmux
```

### Affected releases

* x.y
* earlier versions

**Comment by ogrand** [comment]
Done
