### ISSUE TITLE
[v36.0.1] Release_notes : interco 2 creation

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#208]
### Expected behavior

In the procedure:
- define static routing from interco VPC to Paas VPC (for 192.168.29.x/24, tcp)

Please provide a complete procedure:
- Create the VPC pearing
- Create route...
- ...

### Affected release

Reproduced on version 36.0.1

**Comment by poblin-orange** [comment]
Missing instruction to set peer route on flexible engine vpc peering
