### ISSUE TITLE
[v36.0.1]Error in init-shield.sh script

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#209]
### Observed behavior

The scripts returns errors during execution:

- Typo: l16 ${1} != instead of ${!1} = 

- Typo : ACCESS instead of ACCES

- When the credhub password contains & the script crash.
...
+ [ S3_ACCES_KEY !=  ]
+ jq .value -r
+ credhub g -n /secrets/shield_obos_secret_access_key -j
+ credhubGet=<xxxxxxxxxxxx>_&rUrS
+ [ 0 = 0 ]
+ eval S3_ACCES_KEY=<xxxxxxxxxxxx>_&rUrS
+ rUrS
init-shield.sh: 1: eval: rUrS: not found

Fix: We have to add quote arround the `
l19 eval $1='`echo "${credhubGet}"`'

### Affected release

Reproduced on version 36.0.1

**Comment by ogrand** [comment]
Fix in merge request [343](https://elpaaso-gitlab.nd-int-ops-paas.itn.intraorange/skc-ops-int/paas-templates/merge_requests/343)
