### ISSUE TITLE
bosh coab - ruby package conflict between cpi releases

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#2100]
### Expected behavior

* As a paas-templates operator paas-templates author
* In order to 
  * be able to manage multiple heterogoneous iaas
  *  
* I need 
  * no package conflict between cpi bosh releases 

### Observed behavior

Versions:
- stemcell  bosh-vsphere-esxi-ubuntu-jammy-go_agent/1.207
- bosh/277.4.3                                                                                          
- bosh-openstack-cpi/51                                                                                 
- bosh-vsphere-cpi/88                                                                                   

```
Task 16603828 | 08:34:31 | Preparing deployment: Preparing deployment (00:00:01)

                     L Error: Package name collision detected in instance group 'bosh': job 'bosh-openstack-cpi/openstack_cpi' depends on package 'bosh-openstack-cpi/ruby-3.1' with fingerprint '3f4082e7a37663dd2766982d7df5c50d13f0439bc8276f0df3c8b81a2c246267', job 'bosh-vsphere-cpi/vsphere_cpi' depends on package 'bosh-vsphere-cpi/ruby-3.1' with fingerprint '9ff0c627ab22a33f0c38fcda43304f7f7e634f76ebfeb074dd8c489b52cf5047'. BOSH cannot currently collocate two packages with identical names and different fingerprints or dependencies.

Task 16603828 | 08:34:32 | Error: Package name collision detected in instance group 'bosh': job 'bosh-openstack-cpi/openstack_cpi' depends on package 'bosh-openstack-cpi/ruby-3.1' with fingerprint '3f4082e7a37663dd2766982d7df5c50d13f0439bc8276f0df3c8b81a2c246267', job 'bosh-vsphere-cpi/vsphere_cpi' depends on package 'bosh-vsphere-cpi/ruby-3.1' with fingerprint '9ff0c627ab22a33f0c38fcda43304f7f7e634f76ebfeb074dd8c489b52cf5047'. BOSH cannot currently collocate two packages with identical names and different fingerprints or dependencies.



```
### References
- https://github.com/cloudfoundry/bosh/issues/2471
### Workaround

align bosh release versions with a common ruby package
- openstack cpi: 53
- vsphere cpi: 96.0.2  (since v93 until at least v97)

### Affected releases

* 56.0.0-rc1

**Comment by JCL38-ORANGE** [comment]
issue upstream to open

**Comment by o-orand** [comment]
See comments on wrong issue from JPalermo [random failure in pre-compilation and compilation process (SHA1 mismatch) #991 - comments](https://github.com/orange-cloudfoundry/paas-templates/issues/991#issuecomment-1751481159)
