### ISSUE TITLE
cilium - collect prometheus metrics from 00-shared-services hubble

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#2104]
### Expected behavior

* As a paas-templates operatormaintainer
* In order to 
  * have visibility and alerting on 00-shared-services CNI 
* I need 
  * to collect hubble metrics to prometheus

### References
- https://docs.cilium.io/en/stable/observability/metrics/
- https://jysk.tech/inspect-deployment-network-traffic-in-kubernetes-8a348110df4d
- https://isovalent.com/blog/post/cilium-hubble-observability-cni-chaining-mode/
- https://www.datadoghq.com/blog/monitor-cilium-cni-with-datadog/

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
Interesting community request to get traffic metrics per pod https://github.com/cilium/cilium/issues/29586
