### ISSUE TITLE
Bad openstack IaaS type AZs declaration for ops-depls

### ISSUE THREAD

**Issue by shoudusse** [orange-cloudfoundry/paas-templates#214]
### Expected behavior
When deploying V35, i want to have correct AZs declarations for ops-depls when using openstack IaaS type

### Observed behavior
AZs are set as variable but the corresponding vars are not set

### Affected release

Reproduced on version 35.0.0

### Traces and logs
```
Error: - Failed to find variable '/bosh-ops/admin-ui/az_1' from config server
```

* [x] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by poblin-orange** [comment]
backport hotfix on 36.0.2
