### ISSUE TITLE
Ease access to k8s api metrics from 00-k8s-ha-datastore 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2151]
### Expected behavior

* As a paas-templates operator
* In order to troubleshoot 00-k8s-ha-datastore k8s api
* I need to access metrics from 00-k8s-ha-datastore through prometheus, grafana or thanos

This is a follow up of https://github.com/orange-cloudfoundry/paas-templates/issues/2092

### Observed behavior

00-k8s-ha-datastore prometheus (server-2 r4-z1) performs a sync remote write to 00-shared-services prometheus (r1 agents-prometheus-0) instance 

prometheus instance from 00-k8s-ha-datastore is not yet accessible at https://prometheus-ha-datastore.OPS_DOMAIN but yet missing from ops portal
* no vip for 00-k8s-ha-datastore
   * no metallb deployment
* no Ingressroutetcps on 00-core-connectivity-k8s

* 00-k8s-ha-datastore k8s api metrics are included/labelled as 00-shared-services (resulting in extra k8s api metrics), see  
[screenshot](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/3dc5770e-45b8-4b1c-9433-fe4a1585bc6a)

### workaround

configure tiny proxy from bastion to reach 00-k8s-ha-datastore agents and its ingress route http://prometheus-ha-datastore.<ops-domain>/graph :

```bash
switch 00-k8s-ha-datastore
# record ip address of server/2 
sudo cp /etc/hosts /etc/hosts.orig
sudo bash -c 'echo "192.168.60.49 prometheus-ha-datastore.${OPS_DOMAIN}" >> /etc/hosts'
diff /etc/hosts /etc/hosts.orig
```

open browser to http://prometheus-ha-datastore.<ops-domain>/graph

### Possible fixes

* add metallb to  00-k8s-ha-datastore
* ~~prometheus instance from 00-k8s-ha-datastore pushes metrics to central prometheus instance~~

### Affected releases

* 56.0.1
* earlier versions

**Comment by poblin-orange** [comment]
global solution to find for inter-cluster service exposition

**Comment by JCL38-ORANGE** [comment]
Since 56.0.3, 00-k8s-ha-datastore metrics are available on prometheus central.
