### ISSUE TITLE
Polutting hedgedoc failing kustomization

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2169]
### Expected behavior

* As a paas-templates operator
* In order to focus on production issues
* I need that failing workloads related to operational issues that need care

### Observed behavior
 
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/888b5380-4a24-48c7-a558-c9c307c23420)

### workaround

Just ignore the failed kustomization in alerts and check-k8s

### Affected releases

* 56.0.1
* earlier versions

**Comment by poblin-orange** [comment]
fixed in hedgedoc branch
