### ISSUE TITLE
metrics are duplicated on k8s prometheus central

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#2175]
### Expected behavior
* As a paas-templates operator
* In order not to save resources
   * Thanos compaction may be prevented to remove duplicated timeseries, and save space
* I need to collect metrics once

TBC whether dashboards show duplicated data

### Observed behavior
metrics scrapped by prometheus central (in 00-supervision) are duplicated (one by each of the two prometheus pods on r1-z1)
`sort_desc(bosh_job_ephemeral_disk_inode_percent{bosh_deployment="concourse", bosh_job_name="worker"})`

![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/5accd4c5-b951-4972-b9a6-585e55985087)

### Affected releases
56 and prior

**Comment by JCL38-ORANGE** [comment]
Check : 
sort_desc(prometheus_build_info{namespace="14-prometheus-central"})
sort_desc(bosh_job_ephemeral_disk_inode_percent{bosh_deployment="concourse", bosh_job_name="worker"})

**Comment by ogrand** [comment]
Promql method to get metrics form `apiserver` and `kubelet` exporters

```
group by(__name__) ({job="apiserver"})
group by(__name__) ({job="kubelet"})
```

Then copy `prometheus` display data in linux env variable (RES="<tab content>" and format result

```
$ echo "${RES}" | grep -v "1$" | sed -e "s+{.*++g"
```

**Comment by gberche-orange** [comment]
see https://github.com/orange-cloudfoundry/paas-templates/issues/1712 for the documentation of metrics emitted by the different available exporters. Need to intersect with the currently scraped exporters

@ogrand @JCL38-ORANGE  is this problem still visible in v56.0.3 ? Can we reopen the issue closed by https://github.com/orange-cloudfoundry/paas-templates-private/pull/2780 ?

**Comment by JCL38-ORANGE** [comment]
This issue deals with prometheus and bosh metrics. It is fixed. There is an another issue for the intersection of the currently scraped exporters (apiserver, kubelet, ...) => https://github.com/orange-cloudfoundry/paas-templates/issues/2199
So for me, this issue is closed.
