### ISSUE TITLE
offline buildpack build is ko - multiple fs2/fs3 rootfs

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#218]
### Expected behavior
As a platform operator, i expect the concourse pipeline to download, then build offline buildpacks before storing them in micro-depls/minio, and load them in cloudfoundry

### Observed behavior
Since this week, we have broken builds
```
error running command: more than one match found for pattern: bp-cached/*.zip
[/tmp/build/put/bp-cached/python_buildpack-cached-cflinuxfs3-v1.6.24.zip /tmp/build/put/bp-cached/python_buildpack-cached-v1.6.24.zip]
```
Seems related to linux-fs2/ linux-fs3 buildpack declinaison

**Comment by poblin-orange** [comment]
see fix https://github.com/orange-cloudfoundry/ci-buildpack-cached/commit/56ddbc6f175f951ea1bed3f139b3402798eee521

**Comment by o-orand** [comment]
Fixed in upstream: https://github.com/orange-cloudfoundry/ci-buildpack-cached/issues/7

**Comment by poblin-orange** [comment]
fixed as of v39
