### ISSUE TITLE
v55.0.1: feature-auto-setup-upgrade-pipeline fails to load 56.0.2

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2182]
### Expected behavior

* As a paas-templates operator | paas-templates maintainer
* In order to benefit from feature brought by `feature-auto-setup-upgrade-pipeline`
* I need 56.0.2 upgrade pipeline to automatically load

### Observed behavior

Given 56.0.2 tag is available upstream, the plateform fails to load the associated pipeline 
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/2408db05-b81c-4110-9a6a-0d9aad8775f1)
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/19c23730-4512-4803-949c-04b7d868cc52)
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/0edf2df9-29c9-443e-af6e-5a98b6f50373)
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/a8e93a4f-435a-4ac6-ae06-11a302dd77bf)

### Affected releases

* 56.0.1 (and likely 56.0.2 despites this was not yet tested)
* earlier versions

**Comment by o-orand** [comment]
This should have been fixed by https://github.com/orange-cloudfoundry/paas-templates-private/pull/2739, but it requires a manual reload of the pipeline (like an initial setup, describes in upgrade process)

**Comment by JCL38-ORANGE** [comment]
should be fix with 56.0..3, so we close it.
