### ISSUE TITLE
dedicated vm postgresql (COAB)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#220]
### Expected behavior
As a platform user, i need a postgresql service with predictable performances (dedicated vms)

**Comment by gberche-orange** [comment]
Possible associated upstream bosh releases:
* https://github.com/cloudfoundry/postgres-release/ 
   * has support for  PostgreSQL 11.4 and PostgreSQL 9.6.10 (see [details](https://github.com/cloudfoundry/postgres-release/tree/develop/packages))
   * has no official for replication or clustering, see https://github.com/cloudfoundry/postgres-release/issues/45#issuecomment-447692405
   * supports TLS
   * supports BBR (bosh backup & restore) through pg_dump

* https://github.com/cloudfoundry-community/postgres-boshrelease
   * has support for  PostgreSQL 9.5.1 (see [details](https://github.com/cloudfoundry-community/postgres-boshrelease/blob/master/packages/postgres/packaging))
   * HA through active/passive and replication (see [details](https://github.com/cloudfoundry-community/postgres-boshrelease#ha-configuration))

**Comment by poblin-orange** [comment]
milestone cleared. First solution will be FE RDS postgres. COAB postgres will be rescheduled when reprioritized

**Comment by poblin-orange** [comment]
Due to delay in k8s operator solution for postgres service, reconsider coab vm scenario for postgres service

**Comment by poblin-orange** [comment]
Alternative Orange internal service is proposed for OSBCMDB integration. depriorize
