### ISSUE TITLE
Bosh-based bastion clean up

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2201]
### Expected behavior

* As a paas-templates operator  | paas-templates maintainer
* In order to avoid using a deprecated bastion environment incompatible with current release
* I need a fail-fast feedback

and

* As a paas-templates operator  
* In order to save computing resources 
* I need old Bosh-based bastion bosh deployment to be deleted

### Observed behavior

* Lack of automation of client-side configuration may lead to usage of outdated configuration still using old bosh-based bosh-cli: https://github.com/orange-cloudfoundry/paas-templates/issues/1332
* old bosh-based bosh-cli is not yet removed
* k8s-based bastion (00-core-connectivity in r1) introduced in v55, https://github.com/orange-cloudfoundry/paas-templates-private/pull/1247 and https://github.com/orange-cloudfoundry/paas-templates-private/pull/1721 introduced k8s-based bastion
* inception vm are available as a recovery in r1
* jumpbox bosh vms are available as a recovery in r1,r2,r3, r4 . Introduced in v54, https://github.com/orange-cloudfoundry/paas-templates-private/pull/1149 

 
### Affected releases

* 56.0.2
* earlier versions

**Comment by JCL38-ORANGE** [comment]
@gberche-orange docker bosh-cli is no more present in paas-templates with 56.1.0. Could we close this issue ?

**Comment by poblin-orange** [comment]
done in 56.x upgrade pipeline
