### ISSUE TITLE
add missing rabbitmq prometheus metrics and alerting

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#223]
### Expected behavior
as a platform operator, i need to have insight and alerting on rabbitmq

### Observed behavior
no metric and alerting for rabbitmq configured

### references
- https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/p_rabbitmq_alerts/templates/p_rabbitmq.alerts.yml

**Comment by JCL38-ORANGE** [comment]
Included in v40 (anticipated)
