### ISSUE TITLE
configure k9s by default in read-only mode in production

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2258]
### Expected behavior 

* As a paas-templates operator 
* In order to prevent accident in production #2249 
* I need that k9s be configured in read-only mode by default in production

### Observed behavior

* k9s is r/w mode

### Reference

https://github.com/derailed/k9s#the-command-line
> ```shell
> # Start K9s in readonly mode - with all cluster modification commands disabled
> k9s --readonly
> ```

### Workaround

* 

### Possible fixes

* 

### Affected releases and environments

* affects release: x.y
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--

**Comment by ogrand** [comment]
Done with latest bastion image
