### ISSUE TITLE
k9s helmrelease suspend/resume fails in v56.0.4

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2259]
### Bug Impact 

* As a paas-templates operator
* This bug prevents me to resume one-shot stuck helm release
* 

### Observed behavior

* resume command does a noop

### Workaround

```
flux -n fluxcd suspend kustomization 20-minio 
flux -n fluxcd resume kustomization 20-minio 
```

or patch the script 

```diff
$ diff /usr/local/bin/suspend-resume-hr.sh  /usr/local/bin/suspend-resume-hr.sh.orig
36c36
<   flux suspend hr ${name} --context=${context} --namespace ${namespace}
---
>   flux suspend hr ${name} --namespace ${namespace}
```

### Possible fixes

* 

### Affected releases and environments

* affects release: x.y
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--

**Comment by ogrand** [comment]
Fixed in latest bastion image version
