### ISSUE TITLE
Ops portal is missing prometheus ha-datastore

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2263]
### Bug Impact 

* As a paas-templates operator 
* In order to test bypassing thanos
* I need to access ha-dastatore prometheus at https://prometheus-ha-datastore.ops-domain.org/graph
 -->

### Observed behavior

* 

### Workaround

* 

### Possible fixes

* 

### Affected releases and environments

* affects release: x.y
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--

**Comment by ogrand** [comment]
Set in ops-portal
