### ISSUE TITLE
unconsistent dns resolution between powersdns-docker slave and master (apps domain)

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#232]
### Expected behavior
dns resolution must be consistent between powerdns-docker slave and master

### Observed behavior
dns resolution is not consistent between powerdns-docker slave and master

Reproduced on version 36
 
### Traces and logs
dig toto.<apps domain> @master returns an IP with value A
dig toto.<apps domain> @slave returns an IP with value B

**Comment by poblin-orange** [comment]
fix on bind port merged for v37
