### ISSUE TITLE
unable to restore mongodb backup using shield boshrelease

### ISSUE THREAD

**Issue by szaouam** [orange-cloudfoundry/paas-templates#233]
### Expected behavior
shield must be able to restore a mongodb cluster 
### Observed behavior

> 2018-12-18T09:02:46.031+0000	Failed: no reachable servers
Unable to exec '/var/vcap/packages/mongodb/bin//mongorestore': exit status 1
TASK FAILED!!  shield worker 2 failed to execute the command against the remote agent X.X.X.X:5444 (Process exited with: 3. Reason was:  ())

EXITING 3

shield boshrelease version : 7.0.2
mongodb boshrelease : https://github.com/orange-cloudfoundry/mongodb-boshrelease/releases/tag/v3

### Affected release
ALL

**Comment by poblin-orange** [comment]
fixe in 37.0.0
