### ISSUE TITLE
CF-wall 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#24]
### Expected behavior

* As a paas-templates operator 
* In order to notify Osb client platform users of incidents on a service offering (e.g. shared cf mysql) or on a dedicated service instance
* I need some automation to send email to related users 

### Observed behavior

CF-Wall is not yet available to paas-templates operators

### Possible implementation

https://github.com/orange-cloudfoundry/cf-wall provides a way for operators to notify CF users. Packaging it into paas-template will automate its operations and make it available in all paas-template supported deployments

Suggesting to package cf-wall either 
* as a CF app with [current native support](https://github.com/orange-cloudfoundry/cf-ops-automation#cloudfoundry-application-resources-template-format)
* as a terraform-cf config. Prereqs
   * https://github.com/orange-cloudfoundry/cf-ops-automation/issues/80 / https://github.com/orange-cloudfoundry/cf-ops-automation/issues/82

### Affected release

Reproduced on version 24.0

**Comment by poblin-orange** [comment]
tentative package as a COA cf apps.
got issue https://github.com/orange-cloudfoundry/cf-wall/issues/1
