### ISSUE TITLE
Authentication token expires on elpaaso-sandbox

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#242]
### Expected behavior
As an Ops, I want an `Elpaaso-Sandbox` up and running

### Observed behavior
Authentication token expires on `elpaaso-services` and leads to `Service Unavailable`, see https://github.com/orange-cloudfoundry/elpaaso-sandbox-service/issues/13

The workaround currently running is a periodic restart scheduled by Faas

### Affected release

All versions

**Comment by JCL38-ORANGE** [comment]
Authentication token expires on db-dumper-service and leads to Service Unavailable, see https://github.com/orange-cloudfoundry/db-dumper-service/issues/11

**Comment by poblin-orange** [comment]
merged for v43
