### ISSUE TITLE
update bosh 270.x

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#250]
### Expected behavior
As a platform operator, i want to benefits from latest bosh features (eg: bosh links apis) and bug fixes.
One new feature is the ability to include/exclude runtime add ons per instance_group

#### Reference
- https://github.com/cloudfoundry/bosh/releases/tag/v268.4.0
- https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/issues/33

**Comment by poblin-orange** [comment]
https://github.com/cloudfoundry/bosh/releases/tag/v268.5.0  see to fix the #46  issue

**Comment by poblin-orange** [comment]
As of  v40, 268.7.0 is applied on master-depls (and new bootstrapped micro-bosh).
issue #46 is still present though.
delaying to v41 the 268.x generalization

**Comment by o-orand** [comment]
We can collect new metrics for bosh director, see [](https://static.sched.com/hosted_files/cfna19/64/ways-to-monitor-your-bosh-director.pdf):
 * director.enable_metrics_endpoint
 * blobstore.enable_metrics_endpoint
 * nats.enable_metrics_endpoint

Latest 268.x version seems to fix an issue with multiple stemcell upload: one stemcell can be uploaded at time. I didn't find any reference in the release notes, but we get this talking with bosh team.

**Comment by poblin-orange** [comment]
bump bosh 270 to check

**Comment by poblin-orange** [comment]
270.3 applied on bosh-master/ops/kubo/coab. scale up vm type xlarge, disk_type xlarge
