### ISSUE TITLE
admin-ui is ko

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#251]
### Expected behavior
As a platform operator, i need admin-ui to troubleshoot

### Observed behavior
Fix admin-ui. Define best option, bosh releases or cf apps

**Comment by shoudusse** [comment]
UAA secret key is hard-coded in template and should be set as a variable

**Comment by T0FFF** [comment]
The service has been disabled.

**Comment by poblin-orange** [comment]
bosh deployment removed from paas-templates
cf apps fixed for v42
