### ISSUE TITLE
coab - shield backups - s3 storage conflict on bucket name

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#252]
### Expected behavior
As a platform operator, i need to be able to install a staging and a production environnement in 2 iaas tenant of the same iaas.
Backup bucket name should be post-fixed with ((site)) to avoid this conflicts

### Observed behavior
The bucket used by COAB deployments are fixed in paas-templates, inducing naming conflict when using COAB and 2 env with the same s3 provider

### Affected release
37.0.0

**Comment by JCL38-ORANGE** [comment]
Hello,

I don't understand very well the problem. 
To my understanding, there is one dedicated bucket by tenant => one bucket for the staging tenant and one bucket for the production tenant.
Is there a change on that ?
Regards,
Jean-Christophe.

**Comment by poblin-orange** [comment]
the bucket namespace is global (2 different accounts can not use same bucket name).
fixed in 38.0.0
