### ISSUE TITLE
(services) Snyk pro onprem support

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#26]
### Expected behavior

Install and operate [snyk pro](https://snyk.io/plans) self hosted server and its integration with cloudfoundry
* [ ] Package snyk airgapped installer in a bosh release
* [ ] Integrate snyk airgapped bosh release in paas-template
   * Using an external postgresql db
   * Set up shield backup of the db
   * Integrate with paas-template LDAP server

### Affected release

Reproduced on version 24.0

**Comment by poblin-orange** [comment]
bosh packaging provided is not stabilizable.
requiring a k8S packaging from the vendor

**Comment by poblin-orange** [comment]
closing this as we didnt manage to integrate snyk successfully
