### ISSUE TITLE
postgresql service loses credentials

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#261]
### Observed behavior

cf apps credentials become invalid randomly
a cf unbind-service / cf-bind-service generates new credentials successfully

### analysis
Same issue on platform

**Comment by shoudusse** [comment]
Fix found:
- Deploy all deployment VMs serialy (to always have a minimum of 2 nodes in the postgreSQL cluster)
- Add persistent disks to etc instances

**Comment by poblin-orange** [comment]
merged for v40
