### ISSUE TITLE
gitlab backup should include postgresql

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#262]
### Expected behavior
As a platform operataor, i want to be able to recover gitlab in case of failure

### Observed behavior
The git repositories are backup with shield.
However, the gitlab metadata in postql are not backuped (includng merge request, user rights, ...)

### Solution outiline
- [ ] externalize postgres db with bosh postgresql release
- [ ] raise the shield frequency, 1 backup per hour, with reduced retention delay
- [ ] add  shield backup for postgres db
- [ ] activate postgres wal to enable a short RTO

**Comment by shoudusse** [comment]
As gitlab omnibus i used, possibility to use the integrated backup command: `sudo gitlab-rake gitlab:backup:create`
And then backup the created tar file with shield file system backup?

**Comment by poblin-orange** [comment]
as a first level, a global postgres fs is scheduled in V39.
Target will be to leverage gitlab helm chart for a full cloud native gitlab arch
