### ISSUE TITLE
Quota for on-demand COAB services 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#264]
### Expected behavior

As a service operator, in order to protect myself against abuse and unpaid financial debt from consummers that could result into unpaid large Iaas , I need to set quotas on services that imply dynamic spendings (such as COAB triggering Iaas resources dynamic consumptions)

As a service operator, in order to protect the services that need Iaas capacity for their day 2 activities, I need to protect against intensive on-demand services exhausting the Iaas capacity.

### Observed behavior

Currently, COAB broker does not enforce quota, and CF does not support fine grain quota (i.e. service plan quotas).

### Affected release

Reproduced on version 37.x

### Alternative impls considered

* Configure COAB bosh director to use dedicated Iaas tenant/pool
* Implement quotas into an intermediate broker 
   * In the OSS peripli service manager.
      * Although simple quota is mentioned in [service manager Cf summit basel 2018 slide 14](https://schd.ws/hosted_files/cfseu18/75/service-manager-cf-summit-eu-2018.pdf), SAP quotas are tights to SAP CRM and is not opensource, see https://openservicebrokerapi.slack.com/archives/C99PBB6ER/p1550045784007300?thread_ts=1550045534.007100&cid=C99PBB6ER
      * ServiceManager does not currently manages/stores service instances, 
         * Postgresql database does not yet store service instances https://github.com/Peripli/service-manager/blob/master/storage/postgres/types.go necessary for quota accounting
         * draft api is being refined into https://github.com/Peripli/specification/blob/sm-ops/api.md with management of service instance, service bindings 
   * In a distinct dedicated broker (similar to sec-group-broker-filter)
* Implement quotas in coab (as a distinct processor, possibly independently configureable)

**Comment by JCL38-ORANGE** [comment]
A very short term solution would be to restrict available bosh ips at cloud-config level on the network called tf-net-coab-depls-instance.
This solution will prevent from allocating a hugh number of service instances because bosh will fail at provisioning time (not enough available IPs) and the create-service-instance will result in failure for the end user.

**Comment by gberche-orange** [comment]
A slight alternative to quotas, might be monitoring and alerting.

See related https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/150

**Comment by poblin-orange** [comment]
fronting COAB with OSB CMDB might resolve globally this per product quota see #492

**Comment by gberche-orange** [comment]
@poblin-orange should be marked this as closed with osb-cmdb #492 and set milestone to delivered in v45 ?
