### ISSUE TITLE
end-user visibility to the dedicated database services backups

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#265]
### Expected behavior
As a platform user, using a dedicated data services in the marketplace, i need to have visibiliy on automated backups success. Ideally, i want to be able to trigger backup in self services.

### Observed behavior
The shield backup for coab dedicated db is automated since v37. However, no access is given to end user

**Comment by ldangeard-orange** [comment]
With operator profil, you can : 
- consult backup
- run an restore backup

You need 
- change password for admin
- to create a user with profil enginer
- attach user on tenant <deployment name> with operator role

**Comment by ldangeard-orange** [comment]
restore PITR : https://github.com/orange-cloudfoundry/cf-oss-service-providers-best-practices/blob/master/backup-restore-PITR-instructions-with-shield-v7-v8-eng.md

**Comment by gberche-orange** [comment]
related and somewhat overlapping with #302
/CC @poblin-orange

**Comment by poblin-orange** [comment]
close as duplicate
