### ISSUE TITLE
COA 3.3.0 - missing automation for  team "currently-disabled"

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#274]
### Observed behavior
bootstrap pipelines does not reference this team

### Affected release

Reproduced on version 38.0.0, COA 3.3.0

**Comment by o-orand** [comment]
This is a consequence of https://github.com/orange-cloudfoundry/cf-ops-automation/issues/215

**Comment by o-orand** [comment]
This will be fixed by COA 4.0 (concourse 5)
