### ISSUE TITLE
remove legacy o-logs service

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#275]
### Expected behavior

As a platform user, I dont want non-functional deprecated service in the marketplace.
As a platform user, I need to discover how to access my log aggregation system, including documentation on how this access is protected (uaa authentification) and authorized to space members (which role is checked between SpaceAuditor, SpaceManager, SpaceDeveloper), the retention duration etc... 

### Observed behavior
The legacy o-logs service is offered in the marketplace. Its is however unused, every cf apps in the platform has its logs collected in the shared logsearch.

### implementation
- remove the service from marketplace (terraform publication, static cred osb broker)

<!-- 
### Affected release

Reproduced on version 38

**Comment by gberche-orange** [comment]
@poblin-orange refined the description to mention discovery/documentation use cases.

**Comment by poblin-orange** [comment]
merged for v39
