### ISSUE TITLE
Dedicated redis (COAB)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#279]
### Expected behavior
As a platform user, i need to have dedicated redis:

- [ ] standalone
- [ ] sentinel
- [ ] cluster
- [ ] broker

### Observed behavior
only a shared p-redis offering

**Comment by ldangeard-orange** [comment]
Le service REDIS DEDICATED est disponible au travers du service `redis-ondemand` en standalone
La release utilisé est : https://github.com/orange-cloudfoundry/redis-orange/tree/broker

. MarketPlace
```
Getting service plan information for service redis-ondemand as ldangeard...
OK

service plan   description                                free or paid
small          Redis 3GB data storage with 4GB RAM/1CPU   paid

```
. Branch `feature-coab-redis`

RAF :
. Parametrage du smoketest
. Cost Plan

**Comment by jmainfroid-orange** [comment]
Merci d'ajouter le n° de version majeure dans le nom du service :
par exemple Redis Dedicated 4

**Comment by JCL38-ORANGE** [comment]
Merged in v43 without backup/monitoring.
