### ISSUE TITLE
Mongo db dashboards

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#280]
### Expected behavior
As a platform operator, i need grafana dashboards on shared mongodb cluster

### Observed behavior
No dashboard as of v38

### reference
-

**Comment by poblin-orange** [comment]
grafana version change breaks two level menus.
- []fix on github bosh release @T0FFF 
- [] built by @JCL38-ORANGE 
- []paas-templates update

**Comment by jraverdy-orange** [comment]
This should be corrected by [MR-126](https://elpaaso-gitlab.nd-int-ops-paas.itn.intraorange/skc-ops-int/paas-templates/merge_requests/126)

**Comment by poblin-orange** [comment]
@JCL38-ORANGE fixed and merged
