### ISSUE TITLE
autoscaler restart timeout

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#282]
### Observed behavior
autoscaler startup issue (unable to access postgres db with consul)

**Comment by shoudusse** [comment]
Is this issue for stratos (as said in the description) ou autoscaler (as said in the title)?

**Comment by poblin-orange** [comment]
yes, mistake. this is for autoscaler.
Fix merged on v39.0.0

**Comment by poblin-orange** [comment]
hotfix provided for v38.x
