### ISSUE TITLE
reduce platform minimal footprint

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#288]
### Expected behavior
 reduce footprint by using K8S for main component

- [x] install K8S  on micro-depls 
- [ ] on new K8S install gitlab
- [ ] on new K8S install NTP
- [ ] on new K8S install miniosS3 
- [ ] on new K8S install harbor

### solution outline
- [x] ensure muti-iaas compatibility (vsphere/openstack flexible engine )
- [ ] define internal.paas DNS mapping for k8s hosted servce
  - [ ] https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md
- [x] define external domain routing strategy (ie: ops-domain / ops routing for gitlab)
- [x] leverage a robust k8s storage class, ideally multi-az and / or iaas provided
  - flexible engine sfs
  - rook ceph storage, with multi az iaas block volumes?
- [ ] check tcp/udp routing compatibility
  - ntp / udp
  - ldap
  - smtp relays

**Comment by gberche-orange** [comment]
@poblin-orange interesting material in pivotal "Small Footprint PAS" https://docs.pivotal.io/pivotalcf/2-5/customizing/small-footprint.html which reduces footprint by colocating some jobs in the same vm, and documents resulting [limits of the tile](https://docs.pivotal.io/pivotalcf/2-5/customizing/small-footprint.html#limits) and recommended use-cases such as reduced availability during updates.

This may provide some inspiration for subtasks of this story, or a distinct one ?

**Comment by ogrand** [comment]
Process with v51 release
