### ISSUE TITLE
logsearch cf apps collection freezes

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#29]
### Expected behavior
cf apps logs should be collected and accessible 

### Observed behavior
apps logs stop being collected.
logstash JVM hang in deadlock due to a poison log message.

### Affected release
v24
logsearch bosh release:
-  https://github.com/cloudfoundry-community/logsearch-boshrelease/releases/tag/v208.0.0
- https://github.com/cloudfoundry-community/logsearch-boshrelease/issues/117

**Comment by poblin-orange** [comment]
alerting added when log collection. wich version ?

**Comment by aveyrenc** [comment]
Fix delivered in v32
