### ISSUE TITLE
Handle CC API V2 deprecation / support CC API V3

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#291]
### Expected behavior

Paas-templates components relying to CC API won't be able to use CC API V2 following CC V2 API deprecation, see related [deprecation plan](https://docs.google.com/document/d/1KFZogeeexOqFf13oKHloe2QAorLh9OqwQHp8JvBl9lY/edit). They either should migrate to use CC API V3 or be functionally replaced by alternatives

### Observed behavior

The current deployed features and component currently rely on CC API V2:
* https://github.com/orange-cloudfoundry/osb-cmdb-spike/issues/44
* https://github.com/mevansam/terraform-provider-cf/issues/120
* https://github.com/orange-cloudfoundry/elpaaso-sandbox-service/issues/15
* https://github.com/orange-cloudfoundry/db-dumper-service/issues/12
* https://github.com/orange-cloudfoundry/sec-group-broker-filter/issues/120
* https://github.com/icclab/cf-webui/issues/21
* log search, at least https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/e9863c801d151f5643bbd0e6483f845fe41beab0/src/kibana-cf_authentication/index.js#L29-L30
* https://github.com/bosh-prometheus/cf_exporter/issues/46

Current backlog items that rely on CC API V2:
* https://github.com/cloudfoundry-community/autosleep/issues/296

### Affected release

Reproduced on version 38.x

**Comment by poblin-orange** [comment]
adapt with latest roadmap info from cf community
