### ISSUE TITLE
improve prometheus grafana dashboards for mysql

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#295]
### reference
- https://github.com/bosh-prometheus/prometheus-boshrelease/pull/271
- https://github.com/bosh-prometheus/prometheus-boshrelease/pull/302

**Comment by ldangeard-orange** [comment]
Dashboard MySQL (https://github.com/bosh-prometheus/prometheus-boshrelease/pull/271) are push in git prometheus-addns. 
Branch `feature-dashboard-grafana-redis` contains
- Dashboard MySQL with deployment variable
- Dashboard Redis ans Redis Sentinel  with deployment variable
- RabbitMQ with deployment variable
for COAB

**Comment by JCL38-ORANGE** [comment]
merged in v47 (in the main prometheus/grafana). Already merged in v46, for the coab prometheus/grafana.
