### ISSUE TITLE
cf-mysql 36.19 - configurable plan prices

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#298]
### Expected behavior
- as a platform user, i want the price and currency of the service to be exposed

**Comment by ldangeard-orange** [comment]
you have to take advantage of it to outsource prices

**Comment by ldangeard-orange** [comment]
Broker COAD don't send metadata plan to CF . 
@gberche-orange, we need this feature to see price in market place

**Comment by poblin-orange** [comment]
NB: coab broker will soon be hosted as bosh deployment (+docker bosh release). This will enable credhub access for COAB broker secrets

**Comment by poblin-orange** [comment]
upstream https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/49

**Comment by poblin-orange** [comment]
shared service price is OK as of v40
price not yet visible for dedicated
