### ISSUE TITLE
cf rolling app  deployment feature

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#301]
### Expected behavior
As a platform user, i expect my cf push command to update progressivly the cf app instances, with no service interruption

### references:
- #270

**Comment by gberche-orange** [comment]
Related cf acceptance test https://github.com/cloudfoundry/cf-acceptance-tests/blob/2e451ca0c50defff800c9ed67cc83ed4c153a516/v3/deployment.go#L94-L120

**Comment by poblin-orange** [comment]
requires #474

**Comment by o-orand** [comment]
this requires #743 as pre-requisite

**Comment by poblin-orange** [comment]
seems cli v7 has not all the feature of cli v6. Bimode could help, but we dont want to do non trivial evolution on COA cf #579

**Comment by o-orand** [comment]
As cf cli v6 and cf cli v7 have 2 different login methods, it seems not easy to have both of them provided by COA. So only cf cli v7 is going to be provided by COA release 5.1, and only cf cli v6 for prior COA releases.

Provided by https://github.com/orange-cloudfoundry/cf-ops-automation/pull/337
