### ISSUE TITLE
nfs service

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#303]
### Expected behavior
As a platform user, i want to use a nfs service.

### Observed behavior
A broker is provided by cloudfoundry
A NFS service is offered by Flexible Engine (no broker)

**Comment by jmainfroid-orange** [comment]
Service available
Need service description to be updated in marketplace

**Comment by poblin-orange** [comment]
@jmainfroid-orange @T0FFF need to contribute the OCB fix feature to paas-templates for inclusion
cc @tgauthier-orange

**Comment by gberche-orange** [comment]
Workaround for deployments where a shared NFS server is available in the environment: deploy the static-creds broker with its volume mount support, see https://github.com/orange-cloudfoundry/static-creds-broker#volume_mount-binding

**Comment by poblin-orange** [comment]
contrib merged for v42
