### ISSUE TITLE
Recurrent COAB OPS tasks automation 

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#304]
### Expected behavior

As a platform operator, I expect that recurrent COAB tasks, instance branch rebasing, are automated in a concourse pipeline

### Observed behavior

The recurrent COAB tasked are described in each release note 

### Affected release

Reproduced on version 39
 
#### Updating  brokers tasks

cf update-service-broker p-coab-cassandra user<redacted_password> <end_point>
cf update-service-broker p-coab-cf-mysql user<redacted_password> <end_point>
cf update-service-broker p-coab-mongodb user<redacted_password> <end_point>

#### Rebasing tasks + `reset-merged-wip-features` job

    # COAB cassandra
    git checkout feature-coabdepls-cassandra-serviceinstances
    git pull
    git rebase origin/master
    git push -f
    
    # COAB mongodb
    git checkout feature-coabdepls-mongodb-serviceinstances
    git pull
    git rebase origin/master
    git push -f
    
    
    # COAB cf-mysql
    git checkout feature-coabdepls-cf-mysql-serviceinstances
    git pull
    git rebase origin/master
    git push -f

Note: the rebasing should be done against the branch used as reference in the associated coa config: `coa/config/credentials-sync-feature-branches-pipeline.yml:paas-templates-reference-branch`. On fe-dev deployment this is `reference` instead of `master`

**Comment by gberche-orange** [comment]
@poblin-orange @JCL38-ORANGE @o-orand We need to further discuss this together, including formalizing user requirements. Here is a first attempt below

## requirements:

### ops requirements :

* temporal/causality traceability between model templates and service instances 
   * i.e. being able to check that a service instance symlink is dependent on related model template commit
* user actions are transactions that occured and should be immutable.
   * i.e. coab transactions appear in reference branch: need manual revert commit to remove them
avoid manual actions during release bumps
* avoid manual operations on the git repos

### template authors requirements 

* test service instances against latest templates without manual work

### paas-templates release managers requirements 

* on integration platform, service instances commits should not be merged into paas-templates distribution
* git history rewrites of service models branches should not trigger manual work

## possible implementations

* coa deletes any orphan bosh deployment in coab-depls
* prod configuration: 
  * coab transactions made onto reference branch
* feint configuration:
  * automatically squashes & rebase the service instance branch
      * by coab
      * by a dedicated pipeline,  see #398

**Comment by poblin-orange** [comment]
as of v42, scripting for rebase is provided

**Comment by poblin-orange** [comment]
@o-orand  @JCL38-ORANGE  @gberche-orange  
as of v44, this rebase could be included in upgrade pipelines ? With an additional tag before rebasing, so tracability is kepts

**Comment by o-orand** [comment]
Here is some details about the script:
As an alternative, you can use `admin/rebase-paas-templates-branches.sh` script:
```bash
cd admin
./rebase-paas-templates-branches.sh -h #to understand option available, the script ask for confirmation before overriding remote branch
./rebase-paas-templates-branches.sh -s reference -p <gitlab_url> -b "*serviceinstances" -f
```
This script is not included in V44 upgrade automation.

**Comment by poblin-orange** [comment]
see #524
