### ISSUE TITLE
mongodb 3.6.4 - release v7

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#307]
### Expected behavior
As  platform user, i need a recent 3.6.4 mongodb version
see https://github.com/orange-cloudfoundry/mongodb-boshrelease/releases/tag/v7

As a pltform operator,new dashboards, exporters  and alerts are required

NB: sharding is not activated to start, see dedicated issue #472 
### Affected release
reproduced on version 40.0.0

**Comment by JCL38-ORANGE** [comment]
https://github.com/orange-cloudfoundry/mongodb-boshrelease/releases/tag/v7

**Comment by JCL38-ORANGE** [comment]
Merged in v42
