### ISSUE TITLE
r buildpack 

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#308]
### Expected behavior
As a platform, I'd like to use the new R buildpack 
https://docs.cloudfoundry.org/buildpacks/r/index.html

### Observed behavior
r buildpack is not provided in default buildpack (though i can use it with internet url for buidpack at cf push time)

**Comment by gberche-orange** [comment]
Sample app for r buildpacks:
* some tested apps in https://github.com/cloudfoundry/r-buildpack/blob/70bf6a358f978cf8e12f90f89d6d8fd41370feb4/src/r/integration/deploy_an_app_test.go#L21-L87
* some hints in https://github.com/MarcialRosales/r-pcf-workshop although prior to official buildpack
* no r samples included in https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets

**Comment by poblin-orange** [comment]
part of cf-deployment 7, v41
