### ISSUE TITLE
internal dns / powerdns hardening - phase 2

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#309]
### Expected behavior
as a platform operator, i expect the terraform state to be cleaned from powerdns automation see #305 

(this includes micro-depls and kubo-depls terraform powerdns configs)

**Comment by poblin-orange** [comment]
for v41, all powerdns records definition must be removed (paas-templates + instructions to remove in secrets, eg: micro-depls/terraform-config/private-dns.tg )

**Comment by poblin-orange** [comment]
merged for v41

**Comment by gberche-orange** [comment]
@poblin-orange this phase is breaking the micro-bosh which was not updated to use `dns-recursor` deployment.

Until the next version recreates the bosh-micro (for cert rotation), the powerdns entry clean up need to be skipped in v41-RC2 as a workaround.

Reopening therefore the issue to bring a better fix in 41-RC3

**Comment by poblin-orange** [comment]
@gberche-orange @ogrand can update bootstrap as part of v41?

**Comment by obeyler** [comment]
👍

**Comment by poblin-orange** [comment]
v42 will purge and delete powerdns
