### ISSUE TITLE
postgresql - maxconnections reached

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#312]
### Expected behavior

* [ ] postgresql metrics reliably include number of connections
* [ ] postgresql alerting triggers when number of connections reach a threshold

### Observed behavior

* [ ] application developers report "connection refused" when postresql max cnx reached on the shared cluster
* [ ] postgresql metrics seem to include unreliable number of connections
![image](https://user-images.githubusercontent.com/4748380/54923615-e6aee680-4f0a-11e9-8aaf-a26896cf66a1.png)

* Postgresql alerts at https://github.com/bosh-prometheus/prometheus-boshrelease/blob/85d376ac7d4c56f47cde3da34dfcd79f2f415a22/jobs/postgres_alerts/spec only include `postgres_alerts.scrape_error.evaluation_time` but lack other connection related alerts

**Comment by wdesplas** [comment]
Hi, 

The posgres deployment is based on stolon docker.

Therefore, the following actions must be performed after the deployment :
```
#On the master keeper
stolonctl --cluster-name=${STKEEPER_CLUSTER_NAME} --store-backend=${STKEEPER_STORE_BACKEND} --store-endpoints=${STKEEPER_STORE_ENDPOINTS} update --patch '{"automaticPgRestart":true,"pgParameters":{"max_prepared_transactions":"100","max_connections":"500"}}'
#Then restart the master keeper to activaate the configuration.
docker restart keeper

This configuration will be set as post configuration script.

**Comment by gberche-orange** [comment]
@wdesplas @T0FFF I tried to refine the description of the issue related to monitoring and alerting, can you please review and confirm my understanding ?

**Comment by wdesplas** [comment]
@gberche-orange : In my point of view, you have to close this ticket and create a new one regarding the monitoring alterting. In fact, this is not the same topic. The fist one was on cluster configuration and this new one will be on monitoring.

Br,
Willy

**Comment by gberche-orange** [comment]
@wdesplas created #320 to follow up monitoring & alerting. Feel free to update/close this issue #312 when the related fix got merged into paas-templates

**Comment by poblin-orange** [comment]
contrib doc merged for v42
