### ISSUE TITLE
deprecate legacy cf-console

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#314]
### Observed behavior
Cloud Foundry admin console seems to be obsolete regarding the statos console
is it good to maintain this link to admin console in the customer web site for FP ?

**Comment by poblin-orange** [comment]
change
Cloud Foundry Stratos Console => Cloud Foundry Stratos Management Console
Cloudfoundry Admin Console => Deprecated : legacy cf console

**Comment by poblin-orange** [comment]
merged for v41
