### ISSUE TITLE
Internal certs generated during bootstrap expires after only 12 months

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#315]
### Expected behavior

As a service operator, until a mechanism is available for cert rotation without user facing impact (#306) and all certs are monitored for expiration (#84 + alerting for non credhub hosted certs), I expect default cert expiration to be long enough to avoid service disruption.

### Observed behavior

Internal certs generated during bootstrap using bosh-cli expire after only 12 months. See related upstream bug https://github.com/cloudfoundry/bosh-cli/issues/273

This means that many certs (internal CA, concourse-micro, credhub-micro) expire 12 months after their instanciation. As a result, TLS clients refuse to communicate with these elements. This is likely to trigger user-facing downtime.

### Possible fixes:

* for next bootstrap, if upstream bug https://github.com/cloudfoundry/bosh-cli/issues/273 is not fixed
   * use a temporary patched version of bosh-cli which assigns 3 years expiration duration, see https://github.com/cloudfoundry/config-server/pull/13
   * use alternative way to create certs, such as openssl cli

**Comment by obeyler** [comment]
This link could help us: 
https://github.com/ishustava/rotato

**Comment by poblin-orange** [comment]
v41 includes dual internalCA management.
TBC: need credhub 2.3 and transitional feature
see related #306 #357

**Comment by poblin-orange** [comment]
procedure and associated tools provides (tested post v41)
