### ISSUE TITLE
Postgresql is lacking reliable max connection monitoring & alerting

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#320]
### Expected behavior

* [ ] postgresql metrics reliably include number of connections
* [ ] postgresql alerting triggers when number of connections reach a threshold

This is a follow up of #312 upon suggestion by @wdesplas in https://github.com/orange-cloudfoundry/paas-templates/issues/312#issuecomment-477497049

### Observed behavior

* [ ] application developers report "connection refused" when postresql max cnx reached on the shared cluster
* [ ] postgresql metrics seem to include unreliable number of connections
![image](https://user-images.githubusercontent.com/4748380/54923615-e6aee680-4f0a-11e9-8aaf-a26896cf66a1.png)

* Postgresql alerts at https://github.com/bosh-prometheus/prometheus-boshrelease/blob/85d376ac7d4c56f47cde3da34dfcd79f2f415a22/jobs/postgres_alerts/spec only include `postgres_alerts.scrape_error.evaluation_time` but lack other connection related alerts

**Comment by poblin-orange** [comment]
closed (no postgres offering as of v50)
