### ISSUE TITLE
secure ops endpoints with oauth2

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#321]
### Expected behavior
As a platform operator, i expect to have a sso oauth2 for all portail

### Observed behavior
Missing oauth 2 for 
- [ ] prometheus/grafana/alertmanager
- [x] ops-routing/uaa SSO for logsearch-ops
- [ ] k8S hosted portals
  - kibana
  - elk
  - prometheus

### references
- spring cloud gateway now has support for oauth 2, see  https://github.com/spring-cloud-samples/sample-gateway-oauth2login
- bosh release (version 4.0.0) https://github.com/cloudfoundry-community/oauth2-proxy-boshrelease/
- helm chart https://github.com/helm/charts/tree/master/stable/oauth2-proxy

**Comment by poblin-orange** [comment]
1 - idp. see logsearch-ops, oauth2-proxy as been used to attach to master-depls/ops-routing/uaa. uaa client id/secret as widlcard redirection.
2 - k8s level. 1 shared traefik middleware, applied on the different ui.

**Comment by obeyler** [comment]
https://github.com/thomseddon/traefik-forward-auth/issues/205
