### ISSUE TITLE
Solve COA scalability issues in integration environments

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#323]
### Expected behavior
As a platform integrator, i need a stable COA when handling 30+ feature branches, 15+ contributors on integration environment

### Observed behavior
numerous issues;
- [x]  excessive git secrets scanning
- [x] excessive dockerhub requests. Need a private caching docker registry
- [ ] 502 errors
- [ ] max container reached on concourse worker.

### design outline
- bump concourse 5
- use k8s to host gitlab/git
- use k8s to host gitlab/gitlab-ci instead of concourse-ci as COA engine
- use ovh CDS as COA engine

**Comment by poblin-orange** [comment]
COA 3.5 restricted secrets scan + nexus docker registry helped a lot. Still need to explore k8s hosting for this CD components (gitlab / concourse)

**Comment by o-orand** [comment]
@poblin-orange, it seems fine with concourse 5, maybe we can close this ?

**Comment by poblin-orange** [comment]
most problems fixed in v42
