### ISSUE TITLE
cf weighted routing

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#326]
### Expected behavior

As an application developer/operator, in order to have more control over progressive rollout patterns such os blue/green deployment, I need to be able to control the weight associated to each mapped application.

### Observed behavior

Currently, when multiple applications are mapped to a route, the load balancing algorithm associates evenly split traffic portion to each mapped application.

### Background

Weighted routing is a new feature, brought by istio and envoy sidecars in cloudfoundry.

In the future, istio support [is also planned to bring](https://www.altoros.com/blog/cloud-foundry-advisory-board-meeting-mar-2019-yaml-templating-tool/):
- support for dynamically configured sidecars
- client-side load balancing
- transparent mutual TLS for an app-to-app communication

### references

- user facing documentation https://docs.cloudfoundry.org/devguide/weighted-routing.html
   - CF CLI UX is still beta, not GA as of [CF summit Philly April 2019 demo](https://www.youtube.com/watch?v=-ZmSYzoWmto&list=PLhuMOCWn4P9h-9tcBVRFCaQ7rmdof66pe&index=2&t=0s) Using transient CF CLI plugins instead https://gist.github.com/dieucao/78443f09a635df0770dbbd683bae6989 . As a result, weighted routes are not yet covered in CATS
   - See [Weighted Routing user experience in CF](https://docs.google.com/document/d/1XDkGEe0i2t0UHBcOjJMUJhQ_ksYh-Jes3uOJiOFEqg0/edit) design proposal - [cf-dev@thread](http://cf-dev.70369.x6.nabble.com/cf-dev-Proposal-for-weighted-routing-user-experience-in-Cloud-Foundry-td8772.html)
- operator documentation and deployment steps:
   - https://docs.cloudfoundry.org/concepts/architecture/istio-routing.html
   - https://docs.cloudfoundry.org/adminguide/service-mesh.html 
   - https://docs.cloudfoundry.org/running/deploying-service-mesh.html 
   - As of Aprl 2019 ([cf-deployment-7.10.1](https://github.com/cloudfoundry/cf-deployment/releases/tag/v7.10.0)), istio support is still experimental, and its ops files are managed in the istio-release itself and yet not in the cf-deployment, see https://github.com/cloudfoundry/cf-deployment/pull/458
- architecture/design/implementation and futur evolutions:
   - [CF Networking: Our Journey to Service Mesh, CF Summit North America - User Day](https://drive.google.com/file/d/0B6q750mOzPzSUGxhZ3lHTnRBXzg/view)
   - [V3 routes proposal](https://docs.google.com/document/d/1EGJu6BvU-1GewpGqcpBUV7wiPqGY1Myi-cZafaflqCw/edit) and [V3 Routes Update Sub-Proposal](https://docs.google.com/document/d/1Sh1cTHs2lN2KccjIWzSyG4wrtquKI2sMXeyZ4MWIqFI/edit#heading=h.au9bn42gfxx4)

- https://github.com/cloudfoundry/istio-release

**Comment by gberche-orange** [comment]
See related documentation for installation and usage of Beta version supported by [istio release 1.3](https://github.com/cloudfoundry/istio-release/releases/tag/v1.3.0)
https://docs.cloudfoundry.org/adminguide/service-mesh.html
https://docs.cloudfoundry.org/running/deploying-service-mesh.html
https://docs.cloudfoundry.org/devguide/weighted-routing.html
