### ISSUE TITLE
leverage nsx automation on vsphere

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#329]
### Expected behavior
As a platform operator, i want to benefit on vsphere on the same level of features as on openstack
- [ ] virtual network management / automation
- [ ] inbound filterging security groups

### Observed behavior
as of v40:
- paas-templates networks have been manually set on vsphere
- no nsx security groups enabled, double nic architecture for paas-templates connectivity

**Comment by gberche-orange** [comment]
NSX-V has support from https://github.com/GSLabDev/terraform-provider-nsxv referenced in https://www.terraform.io/docs/providers/type/community-index.html but with limited coverage, in particular without support for provisionning network

NSX-T has official support https://www.terraform.io/docs/providers/nsxt/index.html

**Comment by gberche-orange** [comment]
@ArthurHlt has started contributions around nsx-v terraform provider in https://github.com/orange-cloudfoundry/terraform-provider-nsx levaraging https://github.com/orange-cloudfoundry/gonsx (go-lang library for nsx)

Potentially matching use-cases:
* firewall security rules (to do L4 filtering on inbound/outbound traffic associated to a vm pools aka "nsx security group") https://github.com/orange-cloudfoundry/terraform-provider-nsx/blob/e71807c08e5c41a3551461d27eca8a6a07e84c67/resource_firewall_rule.go#L23-L117
* logical switch (to connect new virtual networks) https://github.com/orange-cloudfoundry/terraform-provider-nsx/blob/e71807c08e5c41a3551461d27eca8a6a07e84c67/resource_logical_switch.go#L19

Currently not implemented use-cases:
- edge NAT rules
- edge static routing rules
- load balancer

**Comment by gberche-orange** [comment]
An alternative is the NSX python cli created by vmware and apparently maintained by pivotal, and available as a Docker image:

* https://github.com/pivotalservices/pynsxv
   * https://hub.docker.com/r/pivotalservices/pynsxv/ docker hub image
   * https://github.com/pivotalservices/pynsxv/commits/master 2018 activity
   * https://github.com/pivotalservices/pynsxv/network pivotal fork
   * https://github.com/vmware/nsxramlclient upstream vmware python nsx client
   * https://github.com/pivotalservices/pynsxv/search?q=proxy&unscoped_q=proxy no trace of http proxy or socks proxy support

Possible use-cases:
* interactive cli usage: operators can read and write nsx configuration interactively
* automated provisionning: 
   * shell based idempotent script using CLI
   * python idempotent script using python library

**Comment by poblin-orange** [comment]
deprecated with nsx-t ? #908
