### ISSUE TITLE
cf-deployment 8.x  (incl cflinux3 rootfs)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#330]
### Expected behavior
as a platform operator, i expect :
- legacy linuxfs2 not be available for cf apps
- linuxfs 3 bionic to be the only available rootfs

### references:
- https://github.com/cloudfoundry/cf-deployment/releases/tag/v8.0.0

**Comment by o-orand** [comment]
Some reminders from cf-deployment 8.0 high-level changes:

- We will have to restage all applications enforcing "cflinuxfs3"
- We will also need to identify and remove all buildpacks associated to cflinuxfs2
- Once all applications have been migrated to cflinuxfs3, delete the cflinuxfs2 stack using the CF API

**Comment by poblin-orange** [comment]
merged for v43
