### ISSUE TITLE
refactor corporate saml service - bosh operators and credhub

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#331]
### Expected behavior
As a platform operator, i need a maintenable structure for guardian-uaa and gardian-uaa-prod bosh deployment.

As a platform user, the cloudfoundry branded OAUTH authorization is confusing for end users, need a an corporate branding.

### Observed behavior
All the bosh deployment is in a monolithiq ops-depls secrets.yml file, preventing smooth update and cert rotation

**Comment by poblin-orange** [comment]
coordinate with intranet OIDC.
need subscription for skc integration environment

**Comment by gberche-orange** [comment]
Might be worth considering inspiration or reuse from https://github.com/starkandwayne/quick-uaa-deployment-cf bosh : deployment ops files for uaa

See related [Cf session abstract](https://cfna19.sched.com/event/d7209d4765b69ed8d7684fc5406e1deb), [video](https://www.youtube.com/watch?v=GKy9rENZ1LM&list=PLhuMOCWn4P9h-9tcBVRFCaQ7rmdof66pe&index=61&t=0s)
