### ISSUE TITLE
Activate TLS on MariaDB dedicated

### ISSUE THREAD

**Issue by ldangeard-orange** [orange-cloudfoundry/paas-templates#345]
### Expected behavior
Activate TLS, to encrypt data in transit between the server and clients using the Transport Layer Security (TLS) protocol. 
duplicate of #203  ?

**Comment by poblin-orange** [comment]
the broker gives a certificate to the client at binding time.
NB: COAB only to start

**Comment by ldangeard-orange** [comment]
Active TLS MariaDB. 
* The server certificate is generated by CredHub.
* ca_certificate in credentials
```
  "credentials": {
    "ca_certificate": "-----BEGIN CERTIFICATE-----xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n-----END CERTIFICATE-----\n",
    "hostname": "xxx.xxx.xxx.xx",
    "password": "xxxxxxxxxxx",
    "port": 3306,
    "name": "cf_xxxxxxxxxxxxxxxxxxx",
    "jdbcUrl": "jdbc:mysql://xxx.xxx.xxx.xx:3306/cf_xxxxxxxxxxxxxxxxxxxxx?user=xxxxxxxxxxxxxxx&password=xxxxxxxxxxxxxxxx&useSSL=true&enabledTLSProtocols=TLSv1.2&enabledSslProtocolSuites=TLSv1.2",
    "uri": "mysql://xxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxx@xxx.xxx.xxx.xx:3306/cf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?reconnect=true",
    "username": "xxxxxxxxxxxxx"
  },
````
User mysql create by broker use by apps is "require SSL = NONE", so if 
*  apps send ca_certificate, data between the server and clients is encrypted
*  apps don't send ca_certificate, data between the server and clients is not encrypted

**Comment by ldangeard-orange** [comment]
We need to test TLS with java application, to verify if certificate is correctly used.

**Comment by ldangeard-orange** [comment]
We test with PhpAdmin.

- No regression with an application that does not use TLS, data between the server and clients is not encrypted

**Comment by JCL38-ORANGE** [comment]
Merged in v43
