### ISSUE TITLE
shield - migration from shield v7.0.2 to latest stable v8 release

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#347]
### Expected behavior
Shield is the used tool in order to manage backup/restore data in paas-templates distribution.
The purpose of this issue is to give an plan for migration from v7 to v8.

We will proceed with a dual mode shield v7/shield v8 in order to migrate root deployments after root deployments. The coab-depls root deployment is already using shield v8.
We will keep shield v7 during progressive migration in cas of trouble.
The shield v7 server will empty

We also need to choose between old buckets (v2 signature) and new buckets (v4 signature).
The v8 shield release seems now be compliant with v2 signature (https://github.com/starkandwayne/shield/issues/499#issuecomment-479872986).

**Comment by poblin-orange** [comment]
shield server v8 for v44
migration of bosh-deployment to v8 will follow in next versions

**Comment by JCL38-ORANGE** [comment]
shieldv8 server is embedded in v44 / migration of agents in all the root deployments will be embedded in next releases (v45/v46).

**Comment by JCL38-ORANGE** [comment]
migration of agents in all the root deployments is embedded in v45
