### ISSUE TITLE
internet inbound private key on HSM

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#348]
### Expected behavior
As a platform user, i want my internet inbound traffic private key to be secured in a HSM.

**Comment by gberche-orange** [comment]
The https://github.com/zipcar/bosh-vault project might be able to leverage [hashicorp vault hsm support](https://www.vaultproject.io/docs/configuration/seal/index.html), however this does not list flexible engine KMS yet.

Terraform provider however provides access to FlexibleEngine KMS https://www.terraform.io/docs/providers/flexibleengine/d/kms_key_v1.html https://www.terraform.io/docs/providers/flexibleengine/d/kms_data_key_v1.html

**Comment by poblin-orange** [comment]
probably too specific to be managed in shared solution
