### ISSUE TITLE
GitLab 401 request flood

### ISSUE THREAD

**Issue by mickaelso** [orange-cloudfoundry/paas-templates#350]
### Expected behavior
no 401 request registered

### Observed behavior
GitLab receives 3 unauthentified http request per second that hinders gitlab performance heavily.

### Affected release
v38 and above (perhaps before this version)

### Traces and logs
On micro / gitlab deployment
bosh ssh gitlab 

docker exec -it <docker instance id> /bin/bash

root@elpaaso-gitlab:# zcat /var/log/gitlab/gitlab-rails/production_json.log.*.gz | grep 401 | wc -l
3710956

root@elpaaso-gitlab:# zcat /var/log/gitlab/gitlab-rails/production_json.log.*.gz | grep 200 | wc -l
3962289

**Comment by poblin-orange** [comment]
the originating subnet is 172.0.0.1, probably a concourse garden container. Might be an old pipeline using bad credentials

**Comment by mickaelso** [comment]
The issue has been noticed on 3 different implementations on our side. Seems more related to a core item.

**Comment by poblin-orange** [comment]
activating  proxy protocol confirms that the origin of the clone come from concourse. Still need to find the precise jobs

**Comment by poblin-orange** [comment]
production log for 401

```
{"method":"GET","path":"/skc-ops-int/paas-templates.git/info/refs","format":"*/*","controller":"Projects::GitHttpController","action":"info_refs","status":401,"duration":9.21,"view":0.38,"db":1.15,"time":"2019-07-02T00:21:50.659Z","params":[{"key":"service","value":"git-upload-pack"},{"key":"namespace_id","value":"skc-ops-int"},{"key":"project_id","value":"paas-templates.git"}],"remote_ip":"172.17.0.1","user_id":null,"username":null,"ua":"git/2.17.1","correlation_id":"ae271502-3777-4259-b8e8-44fef192caa8"}

```

**Comment by poblin-orange** [comment]
it seems that git clone does a 2 phase access to the git server. One unauthenticated (gives a standard 401), then one authenticated
