### ISSUE TITLE
platform event bus (kafka)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#353]
### Expected behavior
As a platform operator, in order to satisfy billing, auditing, and security requirements, i need a generic event sourcing support to export all required events

Added components:
- [X] multi-az kafka cluster
- [X] ksql base infrastucture, for future event streaming support
- [X] CDC change data capture from master-depls/cloudfoundry-datastore postgres db to the kafka cluster. Based on debezium CDC + postgres wal2json plugin
- [X] postgres compatible replica, based on yugabyte db YSQL

see related issues:
- #339 
- #337

**Comment by gberche-orange** [comment]
@poblin-orange do we need mean the full `event sourcing` architectural pattern (e.g. described into https://martinfowler.com/eaaDev/EventSourcing.html ) or rather an `event bus` such as Kafka, fed with events captured from different components of the systems that might not leverage event sourcing architecture ?

Can we rename this issue into `platform event bus (kafka)` ?

**Comment by poblin-orange** [comment]
initial CDC arch + kafka cluster + yugabyte replicat db merged for v43
