### ISSUE TITLE
Dashboard url for mysql service not reachable

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#354]
### Expected behavior
When we create a mysql service instance, a cf service <newMysqlServiceInstance> provide a dashboard Url to show the service details. 

### Observed behavior
The request doesn't work (TOO MANY REDIRECTS). From what I remember, it never worked.
Could please fix this issue or remove the dashboard Url ?

### Affected release
All
Reproduced on version v38

**Comment by poblin-orange** [comment]
@T0FFF duplicate of #141  ?

**Comment by T0FFF** [comment]
Oups, yes!
