### ISSUE TITLE
leverage envoy proxy for front end lb

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#356]
### Expected behavior
As a platform operator, i need state of the art techno for platform front loadbalancing, with transparency, monitoring

### Observed behavior
as of v39, inbound traffic has the following limitations:
- aging haproxy and nginx bosh releases, with related limitations (eg: proxy protocol support)
- used technos dont have discovery / multi az / hot reconfiguration features

### Discussion
Migrating from haproxy / nginx bosh releases has the following pro/cons:
- pros:
  - envoy is the target techno with cloudfoundry community. Its being used for cf apps containers side-cars. Moreover the gorouter web layer is being adapted to leverage istio / envoy
  - envoy has a rich discovery mechanism set. One of them is DNS discovery, wich match perfectly with bosh-dns az/health aware.
  - envoy supports proxy protocol, to propagate inbound access IPs
  - prometheus and opentracing interoperability
  - same techno as istio / k8S target.

- cons:
  - no existing envoy bosh release 
  - envoy is pubshed as docker image. We need docker bosh release to use it
  - without an out off the shelf control plane (like istio), we must use envoy static configuration. We can use generic scripting bosh release to generate the envoy static config file, but its not as clean as first class bosh release spec configuration

### references
- https://www.envoyproxy.io/docs/envoy/latest/intro/comparison
- https://www.datawire.io/envoyproxy/getting-started-envoyproxy-microservices-resilience/
- https://www.katacoda.com/envoyproxy/scenarios/migrating-from-haproxy-to-envoy
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/tcp_proxy

**Comment by poblin-orange** [comment]
first use in ops-routing, for ops ssh access to micro-depls/docker-bosh-cli. v41

**Comment by gberche-orange** [comment]
@poblin-orange 

We weed to check that the envoy admin port 9901 is not bound outside of 127.0.0.1 i.e. not on the public ip address.  Otherwise this may cause a security issue

See https://www.envoyproxy.io/docs/envoy/latest/operations/admin.html?highlight=admin

> The administration interface in its current form both allows destructive operations to be performed (e.g., shutting down the server) as well as potentially exposes private information (e.g., stats, cluster names, cert info, etc.). It is critical that access to the administration interface is only allowed via a secure network. It is also critical that hosts that access the administration interface are only attached to the secure network (i.e., to avoid CSRF attacks). 

@apog7416

**Comment by poblin-orange** [comment]
see  https://github.com/orange-cloudfoundry/paas-templates/issues/1039 wrt access layer refactoring
