### ISSUE TITLE
kubecf - cf-containerization/quarks - eirini

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#358]
### Expected behavior

As a platform operator : 
- I need a lightweight (containers) footprint for cloudfoundry application runtime. See #288 
- I want to be able to use existing k8s skills and infrastructure for cloudfoundry operations

### Observed behavior

* CF is deployed using Bosh
* CFAR control and data planes are using VMs, with extra unused capacity

### Upstream status

As of may 2019:
* the cf quarks/containerization project is packaging CF control plane bosh releases into K8S. 
   * The project is getting some involvement from pivotal+google
   * The project is also working on K8S native operations UX through K8S custom resources for operating cloudfoundry. 
   * Seems only Suse is currently fully containering CF in K8S.
   
* the eirini project is using K8S as a data plane for CF applications. 
   * Eirini is passing [core CATS](https://github.com/cloudfoundry/cf-acceptance-tests#test-configuration) but not advanced features such as container networking, volume mounts, isolation segments, etc... 
      * Network feature parity is likely to be brought through future full routing/networking migration to istio 

### references:
- https://www.cloudfoundry.org/project-quarks/ ([new name] for Cf containerization as of Aprl 2019)
   - Cf containerization status at cf summit philly [slides](https://static.sched.com/hosted_files/cfna19/a5/CF_OPERATOR_NA_SUMMIT_2019.pdf)
   - [Containerization CF design proposal](https://docs.google.com/document/d/1_IvFf-cCR4_Hxg-L7Z_R51EKhZfBqlprrs5NgC2iO2w/edit)

- https://www.starkandwayne.com/blog/running-cloud-foundry-on-kubernetes-using-kubecf/
-https://developer.ibm.com/articles/how-to-easily-deploy-cloud-foundry-applications-on-a-kubernetes-cluster/
- https://medium.com/@jmpinto/deploying-cloudfoundry-on-a-local-kubernetes-9103a57bf713
- https://kubecf.s3.amazonaws.com/index.html
- https://github.com/cloudfoundry-incubator/kubecf/releases/tag/v2.2.0

**Comment by poblin-orange** [comment]
@gberche-orange should follow eirini in a distinct issue ?

**Comment by gberche-orange** [comment]
https://github.com/cloudfoundry-incubator/kubecf 
> KubeCF is a distribution of Cloud Foundry Application Runtime (CFAR) for Kubernetes. It works with the cf-operator from Project Quarks to deploy and manage releases built from cf-deployment.

**Comment by poblin-orange** [comment]
kube-cf and cf for k8s superseded with cloudfoundry korifi project. closing
