### ISSUE TITLE
private gitlab - initial configuration

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#36]
### Expected behavior
When creating a new environnement, micro-depls/gitlab provides the minimum git lab server.
Operators should have necessary COA dependencies including:
- gitlab group creation
- gitlab project for paas-templates
- gitlab projets for secrets
- gitlab COA account
- correct access right

releated to #899 #748 

### Observed behavior

Manual prereqs setup

### Affected release

v24

### Solution outline

use terraform gitlab provider + COA terraform support to set up and maintain a correct configuration
- https://www.terraform.io/docs/providers/gitlab/r/project.html
- https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs

**Comment by o-orand** [comment]
No progress on my side. But is it relevant to keep this issue, in our k8s git approach, it may be more interesting to use another tools to manage intermediate git repo. I'm not sure we require all gitlab feature.

**Comment by poblin-orange** [comment]
As of v51, we introduce k8s hosted gitlab, in micro-depls/01-ci-k8s deployment.
Should leverage https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs
So we have a reproductible git managed solution

Note other git solution (eg: gitea)  do not offer native project/repo/ ... automation
