### ISSUE TITLE
Ease inclusion of arbitratry content format into bosh deployment manifests

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#361]
### Expected behavior

As a template author, I need to author some content of various format (bash, HTML, terraform configs, K8S config files, docker file) using default IDE tooling (completion, navigation across files, syntax highlighting...) and have it included inline as bosh variables (e.g. docker bosh release [containers.command](https://github.com/cloudfoundry-incubator/docker-boshrelease/blob/3bb542decfd7e48a1e39b1a0a3c90ddf7616b092/jobs/containers/spec#L17), or [kubectl-boshrelease.kubectl](https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease/blob/32ca4098ba31f8c20d73498ab0c382405fd6e8fd/jobs/kubectl/spec#L40-L46))

### Observed behavior

I currently have to inline these into yaml file, and use IDE specific heuristics to detect or to configure explicitly code fragments such as:
* [Intellij language injection](https://www.jetbrains.com/help/idea/using-language-injections.html)

https://github.com/orange-cloudfoundry/paas-templates/blob/a992ea557873e36f4381914d257de02ca2a346a1/micro-depls/powerdns-docker/template/vsphere/docker-operators.yml#L19-L35

* ALT+ENTER on the heredoc block shows intention
![image](https://user-images.githubusercontent.com/4748380/57130713-ad378980-6d9a-11e9-815b-f0f1ba330386.png)

![image](https://user-images.githubusercontent.com/4748380/57130723-b58fc480-6d9a-11e9-8257-df6412f16a20.png)

![image](https://user-images.githubusercontent.com/4748380/57128523-fa642d00-6d93-11e9-98e4-e1788087a851.png)

![image](https://user-images.githubusercontent.com/4748380/57130699-96913280-6d9a-11e9-9e62-30ec95277e3c.png)

This is Ok for small fragments, but becomes cumbersome for large fragments that require features for multiple files (navigation across multiple files)

For larger segments, I need to use the spruce `(( file ))` syntax with the a relative path to the templates `../../../additional-resource/micro-depls/powerdns-docker/template/`  to get from `/tmp/build/181302e9/credentials-resource/master-depls/bosh-expe`

https://github.com/orange-cloudfoundry/paas-templates/blob/c660e49584f3f327616a8a9930fb413eede981c2/master-depls/bosh-expe/template/bosh-vars-tpl.yml#L16

See related COA source code at https://github.com/orange-cloudfoundry/cf-ops-automation/blob/2f17e01861ce7e65261e50f48d87baa500933670/concourse/pipelines/template/depls-pipeline.yml.erb#L541-L553

/CC @ogrand 

### Affected release

Reproduced on version 40.x

**Comment by poblin-orange** [comment]
first implementation with master-depls/prometheus for additional dahboards (with generic scripting release and 'EOF' )

**Comment by poblin-orange** [comment]
cc @obeyler to apply on k8s yaml files

**Comment by gberche-orange** [comment]
#824 adds K8S native support. Workaound for bosh
