### ISSUE TITLE
Minio micro has SPOF, and downtimes during planned maintenances

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#369]
### Expected behavior

As an service operator, in order to avoid manual orchestration among components that need updates in a release, I need a minio micro bosh deployment to update without downtimes (e.g. version bumps, stemcell bumps, or config changes can be applied without triggering minio downtimes)

As a service author, in order to spend less time with describing manual orchestrations in the release notes (see #342), I expect components to update independently of others and without downtimes.

### Observed behavior

Minio micro updates do trigger some downtimes + has SPOFs:

https://github.com/orange-cloudfoundry/paas-templates/blob/9c21e00f351398d6ecd9c4fb32c0f7758341209c/micro-depls/minio-private-s3/template/minio-private-s3.yml#L26-L29

### Affected release

Reproduced on version 40.x

**Comment by poblin-orange** [comment]
v51 introduces a new k8s minio helm chart, with redudancy.
