### ISSUE TITLE
disable owned cf domain cross space context_path mapping.

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#378]
### Expected behavior

As an app developer/operator team being owner of a CF space, I expect other members of spaces in same org or distinct orgs to not be able to interfere with my apps.

I need to be able to  disable owned cf domain_cross space context_path mapping.

### Observed behavior

Currently, other unrelated space developers in other/same org can indeed interfere with my app, by using CF documented edge case. 

### Affected release

Reproduced on version 40.x

**Comment by gberche-orange** [comment]
Recent history with upstream (url/references redacted to somewhat preserve confidentiality until fix is available
* Aprl 24: up stream notified, confirmation of the current behavior, and security impact.
* Aprl 25-26: private discussion on whether this issue should follow responsible security disclosure. Not considered upstream as a security disclosure. Workarounds shared. Likely heavy impacts for space members, and requires downtime for affected apps.
* Aprl 30-May 3rd: issue added to upstream backlog. Currently in ice box.

**Comment by gberche-orange** [comment]
@poblin-orange upstream support is now available in cf-deployment [v9.1.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v9.1.0) through [capi 1.81.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.81.0) release, by an opt-in deployment manifest: [disable_private_domain_cross_space_context_path_route_sharing](https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.81.0#p%3dcc.disable_private_domain_cross_space_context_path_route_sharing).

Next steps:
* [ ] contribute a `cf curl | jq` script to identity cross space context path shared routes and warn legitimate users, and have them remove the route
* [ ] contribute cf-docs update to inform the community about the need to turn on this flag in common use-cases.
* [ ] install cf-deployment 9.1.0 and activate option to disable new overlapping routes creation
* [ ] test new overlapping path can't be created across spaces

**Comment by poblin-orange** [comment]
merged for v44
