### ISSUE TITLE
Stratos ui stable version broken

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#379]
### Expected behavior
As a platform operator, i want the portal statos to be stable

### Observed behavior
As of v39, the paas-templates references the 'stable' release, which has been updated to 2.4.0 on May 3rd 2019. This broke on 04/05/2019, the latest 'stable' release broker the portal.

###  solution outline
- [ ] the paas-templates should stick to the latst qualified version (was 2.3.0 for v39)
- [X] hotfix feature by OCB 
- [X] schedule the backport of the hotfix on v41
- [ ] prometheus blackbox exporter should target stratos (not legacy).

**Comment by aurelienbouleau** [comment]
# Actions done
- [x] Force Stratos UI v2 to stick to v2.3.0 
  I pushed the branch feature-hotfix-stratos-ui-v2 on our platform, with sole commit 66080a5efe884e279af5344439cd5f32e195847d forcing Stratos to be deployed with release v2.3.0.
# Remaining actions

- [ ] Commit to be cherry-picked/ Branch merged into next release

**Comment by poblin-orange** [comment]
hotfix merged to v41
