### ISSUE TITLE
OSB brokers should be exposed on a new service control plane domain

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#38]
### Expected behavior
the service brokers are not to be directly exposed to end users

### Observed behavior

brokers are exposed on the system domain (api.xx). 
Exposing the broker endpoints on ops-domain could enable deploying a simple paas-templates, with only OSB services and ops functions (logsearch prometheus) without requiring a cf-deployment.

NB: check the dashboard access, sometimes the broker also exposes the dashboard on the same domain

### Affected release
v24

**Comment by gberche-orange** [comment]
@poblin-orange do you mean the ops-domain which is using its own dedicated gorouter to register routes independent of CF's control plane ?

**Comment by poblin-orange** [comment]
@gberche-orange yes, dedicated gorouter not depending on cf.

**Comment by poblin-orange** [comment]
Might need to reconsider this. Theres is a coming requirement for a shared marketplace (beyond CFAR and CFCR). ops routing access layer might not be the good target domain (should be dedicated to platform level operations)

**Comment by poblin-orange** [comment]
closed as of v39. a now osb routing, domain and interco dedicated to osb service exposition for external platforms
