### ISSUE TITLE
Stratos 2.4.0 bump

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#381]
### Expected behavior

As a CF user, I want new features of stratos [2.4.0 release](https://github.com/cloudfoundry-incubator/stratos/releases/tag/2.4.0) such as 

>  improvements to the side navigation, support for inviting users, support for user favorites and support for user provided services.

### Observed behavior

Stratos version is sticked to 2.3 release, see #379 

### Affected release

Reproduced on version 40.x

**Comment by gberche-orange** [comment]
Related issues: https://github.com/orange-cloudfoundry/stratos-ui-cf-packager/issues/3

Root causes:
* Need a bump in stratos buildpack version. 

https://github.com/orange-cloudfoundry/paas-templates/blob/a992ea557873e36f4381914d257de02ca2a346a1/ops-depls/cf-apps-deployments/stratos-ui-v2/template/stratos-ui-v2_manifest-tpl.yml#L7

* In addition the golang version is cached in the buildpack cache. 


```
Stratos Buildpack
-----> Stack cflinuxfs2
-----> go install package available in cache
[...]
Cache directory [/tmp/cache/final] exists
```


   * According to [cf-dev@ thread](https://lists.cloudfoundry.org/g/cf-dev/topic/buildpack_cache/22187254?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,60,22187254) `the buildpack cache can only be erased by deleting the app or dropping all cache artifacts on the platform.`


Possible steps:
* Make the build reproductible and in sync with stratos by avoiding building off latest dependencies
   * [ ] NodeJS and npm.  `apk add npm` seems pulling the latest npm and nodejs version (11.14.0):  https://pkgs.alpinelinux.org/package/edge/community/x86/nodejs-current  https://pkgs.alpinelinux.org/package/edge/main/x86/npm whereas stratos is still testing on node js 8.11.2 https://github.com/cloudfoundry-incubator/stratos/blob/c853b460b40d96d642f3ae1f2bf87e7eb5a5efd5/.travis.yml#L1-L3

https://github.com/orange-cloudfoundry/paas-templates/blob/a992ea557873e36f4381914d257de02ca2a346a1/ops-depls/cf-apps-deployments/stratos-ui-v2/template/pre-cf-push.sh#L35-L39

   * [ ] Go lang version: find a way to (automatically?) bump the stratos buildpack in sync with stratos's shipped [manifest.yml](https://github.com/cloudfoundry-incubator/stratos/blob/2.4.0/manifest.yml) file

* Consider running a fully offline version of stratos and reusing work from https://github.com/orange-cloudfoundry/stratos-ui-cf-packager

**Comment by poblin-orange** [comment]
merged for v41
