### ISSUE TITLE
CF metadata support (labels and annotations)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#382]
### Expected behavior

As a CF app team, in order to better classify/search/filter/correlate my CF resources, I need to leverage CF labels and annotations

### Observed behavior

Some teams/entities add metadata using workarounds:
* cf app using environment variables
* spaces using space name (see #339)
* service instance using names or tags

### Upstream status

As of May 2019:
- the CF CLI UX meta-data support is still experimental. See [beta plugins](https://gist.github.com/dieucao/78443f09a635df0770dbbd683bae6989) used in [Cf summit Philly keynote](https://www.youtube.com/watch?v=-ZmSYzoWmto&list=PLhuMOCWn4P9h-9tcBVRFCaQ7rmdof66pe&index=2&t=0s). Therefore CATS are not yet including metadata coverage
- The CRUD for labels and annotations in CAPI release are pretty much done. See [Labels epic](https://www.pivotaltracker.com/epic/show/4093080) and [Annotations epic](https://www.pivotaltracker.com/epic/show/4124692)
- Annotations are not yet in sync with K8S conventions, see https://github.com/cloudfoundry/cloud_controller_ng/issues/1335
- Status on use of selectors across spaces and orgs is'nt yet clear.

### Reference

* User-facing documentation:
   * https://docs.cloudfoundry.org/adminguide/metadata.html shows CF curl commands using CC API rest endpoints for defining 

* Design documentation
   - [Metadata for Cloud Controller API Resources](https://docs.google.com/a/pivotal.io/document/d/1Ebko_wNu4wWLnAdHg6wmydEMTx_IdwYnb4Ys0mxVmM4/edit?disco=AAAAB5L1r5A&ts=5b22a753&usp=comment_email_document) 
   - [Metadata Workflows With CLI Options](https://docs.google.com/document/d/1fVO3nA0T5uApN5yWqSZaD3ddZQClCzogeivKxhriLJs/edit)
   - Metadata in application manifest [story](https://www.google.com/url?q=https://www.pivotaltracker.com/story/show/163924841&sa=D&ust=1556285461435000&usg=AFQjCNGMrPNv0dgD-Me4ar5mb5Z82Cw1iA)

### Affected release

Reproduced on version 40.X

**Comment by poblin-orange** [comment]
annotation and labels have beed integrated with v48 cf-deployment 13.20
