### ISSUE TITLE
bump pivotal cf-redis

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#390]
### Expected behavior
As a platform operator, I expect to have the latest available cf-redis release compliant with the paas-templates distribution : 
https://bosh.io/releases/github.com/pivotal-cf/cf-redis-release?version=434.2.10

### Observed behavior
Currently, the cf-redis available in the paas-templates distribution is : 
https://bosh.io/releases/github.com/pivotal-cf/cf-redis-release?version=430.0.0  

### Affected release
Reproduced on version v40

**Comment by JCL38-ORANGE** [comment]
The bumped release is 
https://github.com/pivotal-cf/cf-redis-release/releases/tag/v434.0.25 (26/10/2018)
All releases up to v434.0.25 are failing because of security group broker filter limitations => 
 https://github.com/orange-cloudfoundry/sec-group-broker-filter/issues/86

**Comment by poblin-orange** [comment]
merged for v41
