### ISSUE TITLE
group bosh releases upload for all directors

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#401]
### Expected behavior
as an ops , when i manage a new version installation, there is sometime an upload per director
is it possible to manage the upload on for all using a global minio all the directors ?
### solution outline
- see https://github.com/orange-cloudfoundry/cf-ops-automation/issues/264
- upstream https://github.com/cloudfoundry/bosh-deployment-resource/issues/63

**Comment by poblin-orange** [comment]
need to clarify the expectation: there is already 1 global minio s3 for all director.
Is the issue related to concourse upload team ?

**Comment by regismarg** [comment]
yes, the issue is related to concourse upload team 
The goal is to have one place to upload the bosh-releases , not multi uploads

**Comment by poblin-orange** [comment]
updated the upstream related COA issue

**Comment by poblin-orange** [comment]
see related ADR #754 #44
