### ISSUE TITLE
optimize PaaS Template install between services and stemcells

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#402]
### Expected behavior
As an ops team, i try to optimze the version installation global time
to be able to cut the installation between different parts en short, i would like to have a process to separate the works related to services installation and stemcell upgrades

**Comment by regismarg** [comment]
Proposition to optimize time:
During a deployment, when a director is used:
vérify before if the stemcells and releases ares available 
If not, :  execute automatically the  team upload jobs.

**Comment by poblin-orange** [comment]
related to https://github.com/orange-cloudfoundry/cf-ops-automation/issues/264

**Comment by gberche-orange** [comment]
possibly solved/duplicate of #44
