### ISSUE TITLE
Provide S3 object storage service in marketplace 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#411]
### Expected behavior

As an application developer, in order to build a cloud-native application, I need S3 storage for my apps.

### Observed behavior

* The riakcs has been decommissioned in #129
* a Flexible Engine service broker exists,  but has security issue
 -  #271 
 - https://github.com/huaweicloud/huaweicloud-service-broker/issues/63
* Some paas-templates deployments may have access to Iaas-provided S3 service, but they are lacking a service broker in the marketplace enabling self service
* Some paas-templates deployments without Iaas-provided S3 service, do have internal minio instanciation for control plane, but not exposed in the marketplace, and lack multi az/cloud replication/backup for durability.

### Affected release

Reproduced on version 41.0 

#### Minio 

a service broker
* terraform-based service broker:
   * terraform minio support: 
      * https://github.com/negronjl/terraform-provider-s3
      * https://github.com/rongfengliang/terraform-minio-s3-provider-demo
   * terraform service broker: see https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/docs/brokerpak-specification.md
* native minio service broker: seems on hold for now
   * https://github.com/minio/minio/issues/5406
   * https://github.com/minio/minio/issues/4112
* adapt/extend existing S3 broker
   * https://github.com/cloudfoundry-community/s3-cf-service-broker (java)
   * https://github.com/cloudfoundry-community/s3-broker (go)
* composite OSB s3 gateway
  * a docker bosh release container broker https://github.com/cloudfoundry-community/docker-broker-deployment
  *  provisioning on the fly minio containers https://hub.docker.com/r/minio/minio/
  * using a remote storage, eg FE SFS (NFS) mounted
* k8S root.io
  * https://github.com/rook/rook

a minio backup to another cloud

**Comment by jmainfroid-orange** [comment]
Target change : S3 on OBOS (Flexible Datastore)
Status : ongoing (test)

**Comment by wdesplas** [comment]
### Expected behavior
We must be allow to access to the OBOS api i.e api-intranet1.inet.france1.object-storage.orange-business.com though the port 443 and 8600 for the CF system_domain and for the port 443 for the all the CF domain.

### Observed behavior
We have an issue with security acess on system_domain in PREPROD.
In fact, we are not able to reach nerther the OBOS API through the CF system_domain (port 443 and port 8600) nor though the other CF domain through the port 443.

### Affected release
Reproduced on version 41.0

**Comment by regismarg** [comment]
check if Broker can be put in open source : 
To see with Olivier Chantrel

**Comment by poblin-orange** [comment]
broker will be managed as a custom branch (waiting for OBOS broker opensourcing)
paas-templates will provide NAT + secruity group to enable internet access. v43

**Comment by poblin-orange** [comment]
NAT merged for v43

**Comment by poblin-orange** [comment]
waiting for Orange OSS publication of the s3 OSB broker for inclusion in paas templates
