### ISSUE TITLE
Bosh director provisionning multiple vsphere/openstack region endpoints (multi cpi)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#414]
### Expected behavior

As a service user, in order to run applications requiring high availability across more than one vsphere cluster, I need associated data services (mysql, mongodb, cassandra) to be spread among multiple vsphere clusters, using bosh multi cpi support.

### Observed behavior

bosh directors provisoned by paas-templates has a single vsphere cpi 

### Affected release

Reproduced on version 41.0 

### References

* https://bosh.io/docs/cpi-config/ mentions multi-cpi 
* https://docs.pivotal.io/pivotalcf/2-4/customizing/understand-az.html 
* https://docs.pivotal.io/pivotalcf/2-4/om/vsphere/config.html#create-az
* https://github.com/orange-cloudfoundry/cf-ops-automation/issues/191

**Comment by poblin-orange** [comment]
cpi config in COA 4.2, closing (follow up in #673 )
