### ISSUE TITLE
k8S software defined storage - openebs

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#416]
### Expected behavior
As a platform operator, i need to leverage k8S for the platform control plane, including statefull load, in a multi-cloud (openstack/vsphere), and multi-az way.

### Observed behavior
As of v41, most of the control plane is managed by bosh vm.
Each bosh vm can have (at most) 1 external persistent iaas disk, on an az

CFCR K8S cloud provider can mount multiple disk , but again on a single az. More over, using iaas level volumes per PV has limitations (we also met some robustness issue with cinder, volumes leaks, failing drains ...)

*** references:
- https://vitobotta.com/2019/07/03/openebs-tips/
- https://www.cncf.io/blog/2018/04/19/container-attached-storage-a-primer/
- https://docs.openebs.io/docs/next/architecture.html
- https://docs.openebs.io/docs/next/cas.html

### Solution outline
- add cfcr k8S rook.io layer, targeting locally mounted disk (TBC)
- adapt cfcr manifest and let bosh allocate and mount the volumes, one per worker, on an additionnal worker instance group
- configure rook to offer block level PV, as a dedicated storage class. cfcr k8S worker being multi-az deployed, we expect the rook.io provided storage to be highly available

**Comment by obeyler** [comment]
https://www.dadall.info/article662/rook-pour-gerer-le-systeme-de-fichiers
https://github.com/rook/rook/blob/master/Documentation/quickstart-toc.md
https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487

**Comment by obeyler** [comment]
I select OpenEBS in prior solution as the support is really good.

**Comment by poblin-orange** [comment]
merged for v43 (cfcr-master, cfcr-micro)
