### ISSUE TITLE
Cassandra coab nodes high memory usage trigger bosh alerts

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#417]
### Expected behavior

As a service operator, I expect the cassandra coab deployment to not trigger prometheus alerts under normal conditions

### Observed behavior

The following alerts trigger on cassandra seeds and servers

```
alertname="BOSHJobLowFreeRAM" bosh_deployment="cassandra" bosh_job_index="1" bosh_job_name="cassandra-seeds" bosh_name="bosh-coab" environment="coab" service="bosh-job" severity="warning"
```

The cassanda bosh release enables configuring the heap max memory in 
[max_heap_size](https://github.com/orange-cloudfoundry/cassandra-boshrelease/blob/master/jobs/cassandra/spec#L779-L794) property

### Affected release

Reproduced on version 40.x

### Possible fixes

Alternative fixes:

Option 1) Adjust memory configuration of JVM to leave 10% free memory
* Fix the COAB model on openstack so that the cassandra bosh-deployment cassandra jobs (both seeds and non seeds instance groups) are configured a bit less RAM to the JVM for currently configured hws flavors
* Possibly provide a parameters in secrets repo to adapt max JVM memory  to current infrastructure flavor size

Option 2) Tune the default OS alert to cassandra specifics (in terms of RAM usage on the OS and possibly CPU usage)
* Exclude cassandra from RAM alerts, see related pending https://github.com/bosh-prometheus/prometheus-boshrelease/issues/272

### Further traces

![image](https://user-images.githubusercontent.com/4748380/58545533-bc77ee80-8203-11e9-9874-af6f542c1bb6.png)

![image](https://user-images.githubusercontent.com/4748380/58546006-c1896d80-8204-11e9-8e12-285e43ffe5de.png)

![image](https://user-images.githubusercontent.com/4748380/60679787-2e89c600-9e89-11e9-92ed-374c0ada5033.png)

````
cassandra-seeds/2d91fd6f-af78-489a-adbf-43339e7e462f:~# free 
              total        used        free      shared  buff/cache   available
Mem:        8167840     6862472      159440       35928     1145928      995264
Swap:             0           0           0
cassandra-seeds/2d91fd6f-af78-489a-adbf-43339e7e462f:~# free -h
              total        used        free      shared  buff/cache   available
Mem:           7.8G        6.5G        155M         35M        1.1G        971M
Swap:            0B          0B          0B
```

**Comment by gberche-orange** [comment]
Refined description following help provided by @OMI69-orange that pointed out that the bosh release indeed supports tuning max JVM setting. Option 1) seems preferable

**Comment by JCL38-ORANGE** [comment]
Merged in v42 (option 1 implementation)
