### ISSUE TITLE
Users portal automation requires npm package in minio-private-s3 making it stateful

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#418]
### Expected behavior

As a service operator, I expect to install paas-templates with as little manual operations as possible.

As a service operator, I expect minio-private-s3 to only be a cache which can be repopulated automatically by concourse (i.e. which can be cleared/destructed without impact)

### Observed behavior

Minio contains an npm apk package, pinned to a specific version into minio to support the portal construction.

```bash
mc ls minio-private-s3/packages
[2018-12-07 08:45:22 UTC]  4.3MiB npm-8.14.0-r0.apk
```

This package is not available anymore on the internet, and is not currently backed up as part of the minio-private-s3 deployment.

Current rationale is to workaround lack of archival of old npm release in apk distribution

### Affected release

Reproduced on version 36.0

### Possible fix

* archive apk package on the internet (e.g. along with orange bosh releases) as to make it available for offline replications automatically
* rework ops portal automation to use cloudnative buildpacks (see #388 )

**Comment by ogrand** [comment]
Obsolete component (not use with OFR)
