### ISSUE TITLE
shield backup should leverage system proxy for public s3

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#423]
### Expected behavior
As a platform operator:
- i expect all outbound internet access to be traced with micro-depls/internet-proxy access log
- being able to disable tenant internet SNAT
- keeping all the shield backup ok

### Observed behavior

as of v41, the shield backup use SNAT to push backups to internet s3 (OBOS)

### Affected release

Reproduced on version 41

**Comment by poblin-orange** [comment]
shield v7 proxy support is KO. postpone this for final SNAT disabling

**Comment by gberche-orange** [comment]
Workaround for ACDC project: 
* use intranet S3 instances with either
   * set up L7 reverse proxy with self signed certificates
   * set up intranet SNAT in NSX + allow configuration of S3 API endpoint to intranet FQDN

**Comment by poblin-orange** [comment]
depending on iaas type, the shield v8 solution will leverage public s3 (internet-proxy) or private s3 (intranet proxy)

**Comment by JCL38-ORANGE** [comment]
Done with shield V8 (specific operator by iaas_type) in v45
