### ISSUE TITLE
shared rabbitmq  3.7

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#426]
### Expected behavior
As a platform operator i want a recent supported version of rabbitmq

### Observed behavior
As of v41, bosh release is 249. Still offers rabbit 3.6, unsupported in may 2019

### references
- https://github.com/pivotal-cf/cf-rabbitmq-release/releases/tag/v266.0.0

## solution outline
- a new service in the marketplace is preferable (letting the projets move by themselves to the new service)
- new broker must follow osb-routing exposition to align with runners without cf

**Comment by gberche-orange** [comment]
Support for shareable service instance, see [pivotal doc](https://docs.pivotal.io/pivotalcf/2-3/services/enable-sharing.html), requires catalog  [metadata.shareable](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#cloud-foundry-service-metadata) which is supported in [spec: rabbitmq-service-broker.service.shareable](https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/blob/d8c008fa2df248a2b697f9dbacb301bcf982b0f5/jobs/rabbitmq-service-broker/spec#L72-L74 )

This was introduced in [cf-rabbitmq-multitenant-broker-release v42.0.0](https://github.com/pivotal-cf/cf-rabbitmq-multitenant-broker-release/commit/d8c008fa2df248a2b697f9dbacb301bcf982b0f5)

Currently in paas-templates v41

```yaml
    cf-rabbitmq-version: "256.0.0"
    cf-rabbitmq-multitenant-broker-version: "31.0.0"
```

**Comment by JCL38-ORANGE** [comment]
Merged in v43
