### ISSUE TITLE
study solution for  mysql service (Lacks HA for switchboard proxies (SPOF) #103 )

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#427]
### Expected behavior
As on operator, I'd expect no SPOF on the marketplace mysql access layer
I need a study on how to have multu 
### Observed behavior

Only a single switchboard proxy is used. Miss a ha mechanism:

    iaas level loadbalancer to the 2 switchbord, exclusive mode (no sync between the switchboard, this could result in different "master" galera vm used)
    keep alived vrrp mechnism, so a single VIP is served by the 2 switchboard. see https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/docs/keepalived.md

### references:
- Lacks HA for switchboard proxies (SPOF) #103 
- https://bosh.io/docs/openstack-vrrp/

**Comment by JCL38-ORANGE** [comment]
Merged in v43.
