### ISSUE TITLE
CFCR manifest - openstack domain-id and tenant-id 

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#428]
### Expected behavior
domain-id and tenant-id are required for K8S configuration. We dont want to add these to shared/secrets.yml (redundant with projet / domain names).

### solution outline

- use terraform to fetch ids, and load in credhub the following item
   - name: /secrets/openstack_router_id
   - name: /secrets/openstack_tenant_id
   - name: /secrets/openstack_project_id

### Affected release
40

**Comment by poblin-orange** [comment]
merged for v44.0.3
