### ISSUE TITLE
Invalid intranet cf domain automation: creates private non-shared domains

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#429]
### Expected behavior

As a cf operator, in order to have apps use the domain on the orange org, I expect automation to make the domain available to apps

### Observed behavior

* Intranet domain created is only visible to system domain
* concourse job in `/teams/main/pipelines/ops-depls-cf-apps-generated/jobs/cf-push-probe-apps-domains` fail with `Domain redacted not found` 
* associated probe is firing

Root cause: domain is created as a [private domain](private-domains) and is not shared
https://github.com/orange-cloudfoundry/paas-templates/blob/a992ea557873e36f4381914d257de02ca2a346a1/ops-depls/cloudfoundry/terraform-config/spec-openstack-hws/domains.tf#L6-L9

### Affected release

Reproduced on version 41

### Possible fix

 * #96 and use [cloudfoundry_private_domain_access](https://github.com/cloudfoundry-community/terraform-provider-cf/blob/dev/website/docs/r/private_domain_access.html.markdown) to share it to other orgs.
 * #433

### workaround:

```bash
    cf delete-shared-domain redacted-domain1 [not needed ??]
    cf t -o system_domain
    cf delete-domain redacted-overlapping-domain2
    cf create-shared-domain redacted-overlapping-domain2
    cf create-shared-domain redacted-domain1
```

**Comment by poblin-orange** [comment]
apps-http-domain removed.
merged for v42
