### ISSUE TITLE
Refactored intranet domain management & isolation segment (current ops-depls terraform fails)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#433]
### Expected behavior

As a cf app team, I need a default intranet domain to deploy samples and apps that don't require custom domain.

As a cf operator, I need robust automation for intranet domain management

### Observed behavior

Current intranet domain management is broken
* historical debts: 
   * intranet domain 1 and intranet domain 2 are overlapping, requiring to declare them in specific order to bypass CF checks.
   * intranet domain 1 and intranet domain 2 are declared as shared domains, making them available on internet isolation segments
* current automation is broken, see #429 

Intranet domains are not consistent/symetrical with intranet domains that have currently associated an isolation segment and routing layer. Instead, they are bundled with cloudfoundry deployment. This prevents selective operations on only intranet-related diego cells.

### Affected release

Reproduced on version 41.X

**Comment by poblin-orange** [comment]
merged for v42. @gberche-orange can we close this issue ?

**Comment by gberche-orange** [comment]
thanks @poblin-orange for the MR `feature-fix-cf-overlapping-domains-impacts` which addresses this issue with
> remove http ns decicated domain terraform
> remove http/https selective smoke tests

**Comment by gberche-orange** [comment]
Reopening as we plan to migrate the intranet domain to being `owned` (instead of `shared`) to better control is access among organization.

This is dependent on #378

**Comment by poblin-orange** [comment]
closing, dedicated issue for shared apps domaine #636
