### ISSUE TITLE
Flexible Engine disable SNAT 

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#437]
### Expected behavior
As a platform operator, need to avoid direct internet SNAT on the platform iaas tenant.

### Observed behavior
A natgw vm, set at bootstrap, plus default static route do establish a SNAT

## solution outline
explicit proxy/caching for platform;
- [X] v40. micro-depls/internet-proxy, based on docker squid
- [X] v41. micro-depls/nexus, offline docker registry based on sonatype nexus
- [X] v45. add a Jfrog Container Registry Mirror for docker and helm charts caching

as of v41, remaining SNAT dependencies:
- [ ] ops-depls/neo4j-docker, docker bosh broker release requires internet gem see https://github.com/cloudfoundry-community/cf-containers-broker-boshrelease/issues/1
- [ ] ops-depls/memcache, bosh  release requires internet nexus
- [x] shield backups access to public s3 (OBOS) #423 , proxy require shield v8. dependency on #347

**Comment by poblin-orange** [comment]
to help reaching this target, integration environment will be SNAT disabled to identify dependencies.
Shield v7 (no http proxy support) jobs will be bosh-dns/nated through a temporary micro-depls/internet-proxy  haproxy nat relay to OBOS.
This wont be merged, expecting to leverage shield v8 before disabling SNAT on openstack
/cc @JCL38-ORANGE

**Comment by poblin-orange** [comment]
with v45 shield is bumped to v8 with http_proxy support.
We can now disable global SNAT except for compilation network (same bosh release still require SNAT). New Flexible Engine NAT Gateway service can be provisionned, and associated to compilation network only. The global vm NAT gateway can be removed

**Comment by ogrand** [comment]
nat gateway vm (created with platform bootstrap) has been disabled on FE-INT
