### ISSUE TITLE
fake domain *.apps.internal.paas must be removed

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#446]
### Expected behavior
As a platform operator, i expect projet willing to use internal route to leverage the cloudfoundry internal domain feature (domain: *.apps.internal)

### Observed behavior
As of v41, paas-templates provides the shared domain  *.apps.internal.paas, to fake the internal routing feature (was not available on cf at the time).
This solution has security limits : its based on internal.paas DNS, but the traffic is routed to the intranet gorouter (ie: the route is not really internal, can be reached with intranet interco ip with a forged Host header)

### references
- https://docs.google.com/document/d/1Kix6QzXn8Q2Rbgdl97S4E6xsHUTSfKUQJKrBv7JzAVc/edit#heading=h.p4gzhx2q1ykr
- built-in dns discovery https://github.com/orange-cloudfoundry/paas-templates/issues/15 
- sample cf app https://github.com/cloudfoundry/cf-networking-examples/blob/master/docs/c2c-with-service-discovery.md

**Comment by poblin-orange** [comment]
cert rotation operations illustrated that this domains defeats the isolation segment purpose. When cf is updated, the internal dialog of internet and intranet-2 isolation segment is broken.

@regismarg @T0FFF  => should communicate to disable this for v44

**Comment by jmainfroid-orange** [comment]
Ok on principle.
1- count use of this domain by hosted projects (Stratos ?)
2 - communicate to projects
3 - plan removal

**Comment by poblin-orange** [comment]
domain mistakenly removed in v44.
Closing (transient hotfix managed out of paas-templates)
