### ISSUE TITLE
bosh director ssl certs should be generated by credhub from shared /internalCA

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#45]
### Expected behavior

Should be able to generator bosh-master and bosh-ops ssl certificate, from parent bosh director config server credhub support

### Observed behavior

Unable to use the ssl cert produced by a director. SSL failure from cli v2 (go ?!)

### Affected release
v24

### Traces and logs

know issue on config server used by bosh.
- https://github.com/cloudfoundry/config-server/issues/5

Maybe the bosh-deployment variables declaration could apply a workaround (as diego team did in cf-deployment):
- https://github.com/cloudfoundry/cf-deployment/pull/363

**Comment by poblin-orange** [comment]
should be fixed with credhub 1.9.5 see https://github.com/pivotal-cf/credhub-release/releases/tag/1.9.5

**Comment by JCL38-ORANGE** [comment]
Operations carried out on bosh-expe : 

1. remove credhub key /bosh-master/bosh-expe/director_ssl

2. in file master-depls/bosh-expe/template/2-patch-internalCA-operators.yml, remove following lines 
- type: replace
  path: /instance_groups/name=bosh/properties/director/ssl
  value:
    key: ((director_key))
    cert: ((director_cert))

3. remove credhub key /bosh-master/bosh-expe/uaa_ssl

4. in file master-depls/bosh-expe/bosh-expe/template/2-ldap-uaa-operators.yml, remove following lines 
- type: replace
  path: /instance_groups/name=bosh/jobs/name=uaa/properties/uaa/sslCertificate
  value: ((uaa-sslCertificate))

- type: replace
  path: /instance_groups/name=bosh/jobs/name=uaa/properties/uaa/sslPrivateKey
  value: ((uaa-sslPrivateKey))

Checks performed : 
- bosh-cli access
- cf-ops-automation access

**Comment by poblin-orange** [comment]
applied on all director and merged for v41
