### ISSUE TITLE
Powerdns deployment - typo in system_domain_operators

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#454]
### Observed behavior
The containers dont' start (mysql, dsns, dnsmasq). There is a typo in a operators file for the slave powerdns:
openstack-hws/add-system-domain-operators.yml:
  value: INTERNAL_DOMAIN_3=((system_domain))" 
  => missing quote

**Comment by o-orand** [comment]
See #443
