### ISSUE TITLE
coab prometheus exporter to include "tags": service-instance-guid, space, org, user

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#455]
### Expected behavior
As a paas-templates operator, I expect to identify easily the coab instances in case of troubleshooting. 

### Observed behavior
When I look for a specific instance only the VM IP is available to drilldown into a dedicated instance, and troubleshoot it from its metrics
### Affected release
Reproduced on v40

### Traces and logs

**Comment by poblin-orange** [comment]
All coab-vars property have been used as relabelling of the coab instance relabelling
detail @JCL38-ORANGE

**Comment by JCL38-ORANGE** [comment]
As part of v48, two labels have been introduced and are visible on embedded prometheus targets endpoint.
osb_client_organization takes the value from coab-vars.yml (parameters.x-osb-cmdb.labels.brokered_service_context_organization_guid)
osb_client_space takes the value from coab-vars.yml (parameters.x-osb-cmdb.labels.brokered_service_context_space_guid)

**Comment by gberche-orange** [comment]
@JCL38-ORANGE 

Looking at v48 implementation below, I wonder how it behaves for dedicated service instances provisionned from a K8S platform into which CF profile field (org/space) would be missing

https://github.com/orange-cloudfoundry/paas-templates/blob/8f0e26e7a484fba431a76f6d0dc39f093caf2f81/coab-depls/01-cf-mysql-extended/template/80-enable-prometheus-and-grafana-operators.yml#L168-L186

**Comment by JCL38-ORANGE** [comment]
hotfix was applied in order to allow service instances provisioning from K8S in v49/v50 (disable osbcmdb parameters usage)

**Comment by gberche-orange** [comment]
Problem observed in prod with v50 with the following symptom

```
Finding variable 'parameters.x-osb-cmdb.labels.brokered_service_context_organization_guid':
  Expected to find a map key 'brokered_service_context_organization_guid' for path '/x-osb-cmdb/labels/brokered_service_context_organization_guid' (found map keys: 'brokered_service_context_clusterid', 'brokered_service_context_instance_name', 'brokered_service_context_namespace', 'brokered_service_instance_guid', 'brokered_service_originating_identity_uid')
```

The v50 branch https://github.com/orange-cloudfoundry/paas-templates-private/pull/554 `feature-hotfix-dedicated-instance-bosh-exporter-scraping` seems missing commits to clean usage of Cf specific x-osb-cmdb metadata

A new hot fix `feature-hotfix-missing-values-from-metallikaas` was produced on 22/06/2021

**Comment by gberche-orange** [comment]
Pending osb-cmdb improvement: fill-in cf and k8s labels possibly empty/null regardless of the current OSB profile. Pending osb-cmdb upstream issue.
