### ISSUE TITLE
External services consumeable from public intranet IP addresses (instead of current hardcoded private ip CIDR)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#460]
### Expected behavior

As a service operator, in order to offer my marketplace services to intranet users outside of my local network, I need the marketplace services to be exposed on public intranet IP addresses

### Observed behavior

As of v41, the OSB services are exposed onto hardcoded 172.17.48.0/24 which is part of [Private_network#Private_IPv4_addresses](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses)

master-depls/terraform-config/spec-openstack-hws/osb-data-plane-shared-pub-network.tf: 

```hcl
resource "openstack_networking_subnet_v2" "tf-net-osb-data-plane-shared-pub-subnet" {
  name = "tf-net-osb-data-plane-shared-pub-subnet"
  network_id = "${openstack_networking_network_v2.tf-net-osb-data-plane-shared-pub.id}"
  cidr = "172.17.48.0/24"
  gateway_ip = "172.17.48.1"
  ip_version = 4

  enable_dhcp = "true"
  allocation_pools {
     start = "172.17.48.2"
     end = "172.17.48.20"
  }
}
```

### Affected release

Reproduced on version 41.x

**Comment by JCL38-ORANGE** [comment]
Merged in v43.
