### ISSUE TITLE
upgrade vm_memory_high_watermark rabbitmq parameter

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#468]
### Expected behavior
as an ops operator, i need the Rabbitmq shared serice to be able to work for all de customers
It appear that a parameter limitation do not permit to make work well the rabbitmq usage

### Observed behavior
When rabbitmq parameter is
vm_memory_high_watermark=0,4

the maximum usable memery for all queues is 0,4*16= 6,4GB

But

on production usage, the average necessary memory used to work well for queues is at least 7.4GB

So, to run well, we must modify the PaaS Template and update RabbitMQ parameter to:
vm_memory_high_watermark=0,6

to be able to have
0.6*16= 9.6GB available memory for queues

**Comment by poblin-orange** [comment]
Not sure we have to change this value, default set by pivotal as default value for rabbitmq. Id suggest following #452 , to limit per service instance stored messages.

Can prioritize #168 for dedicated.
