### ISSUE TITLE
Postgresql broker returns null password

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#471]
### Expected behavior

As a paas-templates users, in order to use the postgresql service, I expect service binding to return valid binding credentials.

### Observed behavior

Test prove in concourse job `ops-depls-cf-apps-generated/cf-push-postgresql-docker-test-app` fails with

```
    OUT 'postgres-cluster' has been found in VCAP_SERVICES, we use it!
    OUT uri of postgres-cluster : [object Object]
    OUT { port: '25432',
    OUT   host: '192.168.31.39',
    OUT   database: '0812efc0-5891-4c9a-9eb2-c0f1919e36f6',
    OUT   user: 'redacted',
    OUT   password: 'null' }
    ERR { error: password authentication failed for user "0812efc0-5891-4c9a-9eb2-c0f1919e36f6"
    ERR     at Connection.parseE (/home/vcap/deps/0/node_modules/pg/lib/connection.js:602:11)
    ERR     at Connection.parseMessage (/home/vcap/deps/0/node_modules/pg/lib/connection.js:399:19)
    ERR     at Socket.<anonymous> (/home/vcap/deps/0/node_modules/pg/lib/connection.js:121:22)
    ERR     at Socket.emit (events.js:189:13)
    ERR     at addChunk (_stream_readable.js:284:12)
    ERR     at readableAddChunk (_stream_readable.js:265:11)
    ERR     at Socket.Readable.push (_stream_readable.js:220:10)
    ERR     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Deleting the (app and hence its service binding) does not solve the problem.

Manual test with service key reproduces the same issue

```
cf t -o system_domain -s postgresql-docker-test-app
cf create-service-key  postgresql-docker-test-app-service postgresql-docker-test-app-service-key
cf service-key  postgresql-docker-test-app-service postgresql-docker-test-app-service-key
cf delete-service-key  postgresql-docker-test-app-service postgresql-docker-test-app-service-key
```

No apparent related error traces in the broker logs

Related code base seems close to https://github.com/orange-cloudfoundry/postgresql-cf-service-broker/blob/master/src/main/java/org/cloudfoundry/community/servicebroker/postgresql/service/PostgreSQLDatabase.java#L50-L71

Next diagnostic steps: 
* connect to the master postgresql to inspect it content

### Affected release

Reproduced on version 41.x (during qualification on fe-dev)

**Comment by poblin-orange** [comment]
cant reproduce on integration and staging environments.
