### ISSUE TITLE
networks for external marketplace are hardcoded, preventing preprod/integration instanciations

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#483]
### Expected behavior

As an external marketplace service operator, in order to repeat operations on my production platform, I expect paas-templates to be deployable multiple times (including integration & preprod environment)

### Observed behavior

Paas-templates current hard codes  172.17.48.0/24 for tf-net-osb-data-plane-shared-pub

See ops-depls/template/cloud-config-tpl.yml
```hcl
    #--- Osb data plane shared public network
    - name: tf-net-osb-data-plane-shared-pub
      type: manual
      subnets:
      - range: 172.17.48.0/24
        gateway: 172.17.48.1
        dns: ((dns))
        azs: [z1,z2]
        reserved:
        - 172.17.48.1 - 172.17.48.20          #--- Exclude dhcp address (see terraform )
        static:
        - 172.17.48.21 - 172.17.48.61
```

+ master-depls/terraform-config/spec-openstack-hws/osb-data-plane-shared-pub-network.tf

See also ops-depls/cloudfoundry-mysql-osb/template/99-osb-operators.yml

```hcl
    - type: replace
      path: /instance_groups/name=proxy/networks
      value:
        - name: tf-net-osb-data-plane-shared-pub
          static_ips:
          - 172.17.48.27
          - 172.17.48.28
```
### Affected release

Reproduced on version 40.x

**Comment by poblin-orange** [comment]
172 networks is supposed to be private (like 192), induce no conficts between FE tenant. Is the point is about making it configurable and public ?

**Comment by JCL38-ORANGE** [comment]
Merged in v43.
