### ISSUE TITLE
cyclic dependency of service brokers to cf

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#485]
### Expected behavior
As a platform operator, using paas-templates to offer a marketplace (and not cf) brokers deployment
 
### Observed behavior
cf-mysql and cf-redis depend on a cf api to start.

### Affected release

Reproduced on version 41

**Comment by gberche-orange** [comment]
At start up, the mysql broker seems to be fetching the UAA authorization and token endpoints to support dashboard redirects. 

A solution could therefore to configure the broker with a `cf.api_url` pointing onto a static https endpoint returning data pointing to the main CF OSB client. Turning off ssl validation would also impact uaa urls which should be avoided.

The static HTTPS endpoint should at least return json content with the following two keys (made configurable from secrets repo)

```json
{
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io"
}
```


### Alternative options

* Independently host a minimal static http server, registered in ops routing to be exposed as https. 
   * Using a docker container which statically serves from a mounted volume, a json file generated from spruce templating.
   * Using a docker container which gets injected 2 env vars
* colocate a minimal http server with the mysql release, serving the static content. 
   * Pb: there is a dependency between broker start up and this server. Bosh does not support job dependencies (see https://bosh.io/docs/create-release/#graph `Jobs never depend on other [jobs.`)](url)
   * This would typically require the broker to perform retries
   * E.g. could be using [generic-scripting-release/](https://github.com/orange-cloudfoundry/generic-scripting-release/), embed a [minimal http server such as with netcat](https://stackoverflow.com/questions/16640054/minimal-web-server-using-netcat)



### Detailed diagnostic of dependency in cf-mysql release

Release requires CC endpoint configuration

https://github.com/cloudfoundry/cf-mysql-release/blob/9c077a9d04089821339bcef336574941d382d1b1/jobs/cf-mysql-broker/spec#L38-L40

>   cf.api_url:
    description: 'URL of the CloudFoundry Cloud Controller'
example: 'https://api.your-domain.example.com'

This is injected as configuration in the broker
https://github.com/cloudfoundry/cf-mysql-release/blob/b42f5e9b52708bd7b1aa5625458151a888785b0b/jobs/cf-mysql-broker/templates/settings.yml.erb#L12
> cc_api_uri: <%= p('cf.api_url') %>

Broker at startup invokes CF endpoint 

https://github.com/cloudfoundry/cf-mysql-broker/blob/499b039875/lib/configuration.rb#L28-L35
>   def cc_api_info
>    return store[:cc_api_info] unless store[:cc_api_info].nil?
>
>    cc_client = CloudControllerHttpClient.new
>    response = cc_client.get('/info')
>
>    store[:cc_api_info] = response
>end

Using HTTP client

https://github.com/cloudfoundry/cf-mysql-broker/blob/c4ca47aeda9d22a70d51db7683d9c39fa51b611d/app/models/cloud_controller_http_client.rb

>   def get(path)
>    uri  = cc_uri(path)
>    http = build_http(uri)
>
>    request = Net::HTTP::Get.new(uri)
>    request['Authorization'] = auth_header
>
>    response = http.request(request)
>
>    JSON.parse(response.body)
>end

Json HTTP response is parsed to configure dashboard redirects

https://github.com/cloudfoundry/cf-mysql-broker/blob/c4ca47aeda9d22a70d51db7683d9c39fa51b611d/lib/configuration.rb#L16-L26

>   def auth_server_url
>    cc_api_info["authorization_endpoint"]
>  end
>
>  def auth_server_logout_url
>    "#{cc_api_info["authorization_endpoint"]}/logout.do"
>  end
>
>  def token_server_url
>    cc_api_info["token_endpoint"]
>end

The legacy `/info` endpoint returns the following output on PWS (not to be confused with the documented [/v2/info endpoint](https://apidocs.cloudfoundry.org/9.4.0/info/get_info.html]

```sh
cf curl /info
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "allow_debug": true,
   "user": "526cc2f7-3d07-4e04-85b2-e3c96282541c",
   "limits": {
      "memory": 2048,
      "app_uris": 4,
      "services": 16,
      "apps": 20
   },
   "usage": {
      "memory": 0,
      "apps": 0,
      "services": 13
   }
}
```

**Comment by gberche-orange** [comment]
For redis, it seems only the smoke tests are calling in CF (the broker does not expose a dashboard)

https://github.com/pivotal-cf/cf-redis-release/blob/e5a2eef7ab664618937202191c7e13696a3625e4/jobs/smoke-tests/spec

**Comment by poblin-orange** [comment]
As we use cf as a osb cmdb facade, we can deal with that cyclic dependency inside the paas-templates (wont induce cyclic dep with client platform).
closing
