### ISSUE TITLE
mongo-db smoke tests need a CF with internet connectivity

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#487]
### Expected behavior

As a mongodb service operator, in order to offer services to an airgapped CF deployment, I need the mongodb smoke test to be passing with an airgapped CF instance

### Observed behavior

Mongodb smoke test is failing because `cf-mongodb-example-app` is failing to deploy in an airgapped instance.

Reported by @skortobi @Darrel63

### Alternative options

* pull dependencies in CI: airgapped CF apps: https://github.com/orange-cloudfoundry/cf-mongodb-example-app/issues/2
   * + download resulting tar in errand
   * Downside: does not benefit from app dependencies unless manually triggered
* pull dependencies prior to push using internet proxy
   * through a modification in https://github.com/orange-cloudfoundry/mongodb-boshrelease/blob/master/jobs/broker-smoke-tests/templates/bin/run 
      * takes a new proxy as job spec https://github.com/orange-cloudfoundry/mongodb-boshrelease/issues/59

### Affected release

Reproduced on version 40.x

**Comment by Darrel63** [comment]
Working on the second approach "pull dependencies prior to push using internet proxy"
With the use of generic-scripting, we inject HTTP_PROXY env var and update VM to install bundler in order to package vendor lib prior to "cf push"

**Comment by poblin-orange** [comment]
with v44, we will be able to have a cf activated on vsphere, with correct outbound internet proxy for staging. This should solve the issue.
