### ISSUE TITLE
New ruby sample app should be monitored

### ISSUE THREAD

**Issue by shoudusse** [orange-cloudfoundry/paas-templates#491]
### Expected behavior
New ruby sample app should be monitored

### Observed behavior
Old ruby sample app is still monitored
As new sample app does not have the same name `cf-sample-app-ruby` -> `cf-default-app-ruby`, monitoring config should be updated

### Affected release
Reproduced on version 41.0.2

**Comment by poblin-orange** [comment]
merged for v42
