### ISSUE TITLE
master-deps/cf for external marketplace consumption (including vsphere iaas type)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#494]
### Expected behavior

As a paas-templates author, 
* in order to optimize efforts and avoid automation divergences between marketplace automation targeted for internal paas-templates consumption and marketplace automation targeted  for external consumption
* I need to leverage `master-deps/cf` for marketplace automation

As an external service operator, in order to provide good QoS to services outside of CF (#492), I need to reduce risks of 3rd party CF causing marketplace control plane outages or marketplace credentials leaks.

Other expected benefits of leveraging `master-deps/cf` for external marketplace:
* Leverage CF for hosting marketplace control plane features and workloads
   * aggregated service operator logs (logsearch) leveraging CF authentication (#287)
   * Service brokers leveraging CF for their deployment, such as CF (#459)
* Leverage dedicated/controlled CF for validating marketplace compliance to CF
   * e.g. #487 workaround for airgapped 3rd party CF limitation on sample app execution
   * rabbitmq smoke tests expect CF permissions to create user & space 
      * see https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release/blob/554e2665f2af0f4c6194134a61ad3d8078efbefe/src/rabbitmq-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/workflowhelpers/user_context.go#L74-L86 
 `Creating user rmq-smoke-tests-1-USER-df4e4fec756ff84b...  Error creating user rmq-smoke-tests-1-USER-df4e4fec756ff84b. You are not authorized to perform the requested action.`
      * would require `cloudcontroller.admin` permissions or feature flag `user_org_creation` which is disabled in 3rd party CF
* Support external marketplace services consumption by non CF/K8S platform (#492 option 2: expose CF API & UI))
   * Including providing built-in logging/metrics UI to provide access to service metrics and logs 
      * user-facing service logs are metrics are ingested in CF logging/metrics pipeline
      * user-facing service logs and metrics are consumed by CF CLI or user-facing log search
      * user-facing service logs can be drained to syslog corporate endpoints (#479)
      * user-facing metrics can be exposed in hosted metrics ui #346

### Observed behavior

Currently, the external marketplace targeted for external consumption leverages a 3rd party CF deployments, which has the following limitations:
* Credhub (marketplace credentials vault) is not accessible outside of private network (exposed as `https://credhub.internal.paas:8844`), hence from 3rd party CF. This prevents hosting some service brokers (such as COAB, see https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/35) on 3rd party CF.
* Security implications: marketplace workloads hosted in 3rd party CF would leak sensitive credentials in case the 3rd party CF gets compromised (see #169)
* Marketplace team dependency on 3rd party CF during CF incidents:
   * Inability to log into marketplace aggregated logs (#287)
* Insufficient permissions are granted to the service operators to run some unmodified community smoke tests that assume control over the CF deployment (ability to create users/spaces/security-groups). => Associated smoke tests need adaptation
* Some team coordination are required to obtain UAA client registration in 3rd party CF for #287

### Affected release

Reproduced on version 41.x

### Implementation steps

* [ ] external "osb" marketplace services introduced in #170 are 
   * registered in `master-deps/cf` using brokers exposed on external intranet FQDNs (currently `p-mysql-osb` isn't registered )
   * tested against `master-deps/cf` enforcing ingress traffic coming from intranet and not private network, and don't have iaas-specific (hws) dependencies
      * support service keys (osb-cmdb prereq) whereas sec-group-broker-filtered brokers currently fail with https://github.com/orange-cloudfoundry/sec-group-broker-filter/issues/97
      * can support test of OSB-facing features in client CF platform such as [Sharing a service instance between orgs/spaces](https://docs.cloudfoundry.org/devguide/services/sharing-instances.html) 
* CF dedicated isolation segment intranet-1 is available
* [ ] study if further configuration properties are necessary in secrets to tune resource footprint of master-depls/cf 
   * scale down minio

**Comment by poblin-orange** [comment]
merged for v44:
- isolation segment intranet 1
- cf activated for vsphere-iaas-type
