### ISSUE TITLE
Shared and dedicated mongodb services must support password rotation

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#496]
### Expected behavior
As a mongodb service operator, in order to protect my platform, I need sometimes to perform password regeneration.

### Observed behavior
credhub regenerate -n "path to mongodb root password"
After regeneration, neither deploy, neither recreate can be done on deployments.
The following error is raised :
Task 2359451 | 12:29:06 | Updating instance mongod: mongod/48713cb5-ac31-41ea-b451-ed087a63a432 (0) (canary) (00:00:41)
14:29:47
	
                     L Error: Action Failed get_task: Task 63022b42-c6c7-4b1c-4fe4-0f2146d83e89 result: 1 of 6 pre-start scripts failed. Failed Jobs: mongod. Successful Jobs: login_banner, bpm, bosh-dns, syslog_forwarder, ca_certs.
14:29:47
	
Task 2359451 | 12:29:47 | Error: Action Failed get_task: Task 63022b42-c6c7-4b1c-4fe4-0f2146d83e89 result: 1 of 6 pre-start scripts failed. Failed Jobs: mongod. Successful Jobs: login_banner, bpm, bosh-dns, syslog_forwarder, ca_certs.
14:29:47

### Affected release
v40, v41, v42

### Reference
https://github.com/orange-cloudfoundry/mongodb-boshrelease/issues/60

**Comment by jraverdy-orange** [comment]
# MongoDB emergency recovery

This operation should be usefull in the following cases

* password inconsistency between nodes and/or clients
* replication failures

## Stop all running processes 

* stop mongodb process on **all nodes**

  ```
  monit stop mongodb_server 
  ```

  kill -9 PID if needed

* stop mongodb_exporter as well

  ```
  monit stop mongodb_exporter 
  ```

## On the node which will be primary 

* modify /var/vcap/job/mongod/mongodb.conf

  comment all the security and replication §

```shell
#security:
# authorization: enabled
# keyFile: /var/vcap/jobs/mongod/config/keyfile
...
#replication:
#  replSetName: rs0
#  oplogSizeMB: 256
```



* start mongodb in noauth mode

  ```shell
  /var/vcap/packages/mongodb/bin/mongod --config /var/vcap/jobs/mongod/config/mongod.conf --pidfilepath /var/vcap/sys/run/mongod/mongod.pid --noauth
  ```

* At this point you can update the passwords of  users if needed

  ```json
  use admin
  db.changeUserPassword("MongoRoot", "new_password")
  ```

* **uncomment the previously commented** sections in the conf file and restart mongo with auth (you should kill the current mongodb process)

  ```shell
  monit start mongodb_server
  ```

  force the node to be primary and remove all the others nodes from the replicaset configuration

  ```shell
  cfg = rs.conf()
  
  printjson(cfg)
  ```

  * identify the current node index in the conf and rewrite the conf

  ```shell
  cfg.members = [cfg.members[<index of the current node>]]
  ```
  * reconfigure the replicaset

  ```shell
  rs.reconfig(cfg, {force : true})
  ```

  * get out from mongo shell and reconnect, the node should now be identify as primary

  ```shell
  rs0:PRIMARY> 
  ```

  * if you ran the previous operation as root, be aware to change the database directory rights to vcap

  ```shell
  chown -R vcap:vcap /var/vcap/store/mongod/data
  ```

## on the others nodes (secondary)

* remove the whole data content

  ```
  rm -rf /var/vcap/store/mongod/data/*
  ```

* start mongodb process

  ```shell
  monit start mongodb_server
  ```

  

* connect to **primary**

  ```shell
  mongo --host <PRIMARY IP>:27017 --username MongoRoot --password <root_password> --authenticationDatabase admin
  ```

  ```json
  rs0:PRIMARY> 
  ```

* add the secondary to replicaset

  ```json
  rs.add('<SECONDARY_IP>:27017')
  ```

**Comment by jraverdy-orange** [comment]
Previous comment is a workaround solution. 
Password rotation have to be corrected in the release.
Keeping issue open

**Comment by ldangeard-orange** [comment]
Correction with Mondb V4 : https://github.com/orange-cloudfoundry/paas-templates/issues/501

**Comment by JCL38-ORANGE** [comment]
Embedded in v45
