### ISSUE TITLE
bump concourse 5.8

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#498]
### Expected behavior
We should evaluate and bump to concourse [5.4](https://github.com/concourse/concourse/releases/tag/v5.4.0):

 - We have switched to a more efficient algorithm for streaming volumes between various components of the system - the web and worker nodes now transmit volumes compressed with the Zstandard algorithm rather than Gzip - fly is affected, too (when uploading/downloading artifacts during fly execute). We're hoping this will resolve some general complaints of steps being slow to start or appearing to "hang" in clustered environments. note: this will require upgrading your workers #3880.

 -  Because of the efficiency gained from employing Zstandard compression to volume streaming, the CPU on the web and worker nodes is no longer a limiting factor. Now volumes will be streamed over multiple parallel connections, and we have seen some very exciting improvements in the time taken to initialize build steps. You can see some of our measurements in the discussion on this issue #3993.

 - On the build page all steps are now collapsed by default. This means that the build page loads faster, but if you want to watch the logs in real time, you will need to click on the header of the running step #4058.

 - Improved the appearance of the sidebar (re-introduced in v5.2.0) in response to user feedback. Teams and pipelines are now easier to distinguish, and there are nicely styled tooltips for long items #4032.
 - When you abort a pending build before it gets scheduled, the build page will now report it as 'cancelled' instead of showing a loading spinner forever #3922.
 - deadNightTiger added a fly completion subcommand that allows fly to output autocompletion for the bash and zsh shells #4012.

### Observed behavior

<!-- 
### Affected release

Reproduced on version x.y

**Comment by poblin-orange** [comment]
merged for v46.0.0
