### ISSUE TITLE
mongodb 4.x

### ISSUE THREAD

**Issue by tgauthier-orange** [orange-cloudfoundry/paas-templates#501]
### Expected behavior
As a platform user, I need mongodb 4.x to benefit from transaction management capability.

**Comment by jmainfroid-orange** [comment]
Adding 2 points :
- licensing change : will we have an impact on our use of Mongo ? Paying license ?
- Actual release is 4.0.11. From experience, from which minor version can we consider commit on SLA on Mongo 4?
Thanks

**Comment by ccambien** [comment]
Regarding Mongodb licensing, it's possible to refer to https://www.mongodb.com/licensing/server-side-public-license and   https://www.mongodb.com/licensing/server-side-public-license/faq 

You may refer to the section 13 of the new licence. Here it is

_If you make the functionality of the Program or a modified version available to third parties as a service, you must make the Service Source Code available via network download to everyone at no charge, under the terms of this License. Making the functionality of the Program or modified version available to third parties as a service includes, without limitation, enabling third parties to interact with the functionality of the Program or modified version remotely through a computer network, offering a service the value of which entirely or primarily derives from the value of the Program or modified version, or offering a service that accomplishes for users the primary purpose of the Program or modified version.

“Service Source Code” means the Corresponding Source for the Program or the modified version, and the Corresponding Source for all programs that you use to make the Program or modified version available as a service, including, without limitation, management software, user interfaces, application program interfaces, automation software, monitoring software, backup software, storage software and hosting software, all such that a user could run an instance of the service using the Service Source Code you make available._

All the Mongodb service here is based on opensource package and opensource code published here.

**Comment by poblin-orange** [comment]
Does paas-templates global open sourcing covers us wrt this license ?

**Comment by JCL38-ORANGE** [comment]
Embedded in v45

**Comment by poblin-orange** [comment]
@JCL38-ORANGE @jraverdy-orange 
need to check upgrade compatiblity (mongo 3 => mongo 4).
New service might be required (shared and dedicated)
+ missing release note in https://github.com/orange-cloudfoundry/mongodb-boshrelease/releases/tag/v8

**Comment by JCL38-ORANGE** [comment]
merged in v47.
