### ISSUE TITLE
quota enforcement for shared mongodb

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#502]
### Expected behavior

upstream issue https://github.com/orange-cloudfoundry/mongodb-boshrelease/issues/61

**Comment by poblin-orange** [comment]
see mongofb v9 for mongo broker level quota enforcement
Note that mongodb broker can benefit from osbcmdb quota management, if the service is exposed externally

**Comment by JCL38-ORANGE** [comment]
quota management is embedded in mongodb bosh-release since v10 (https://github.com/orange-cloudfoundry/mongodb-boshrelease/releases/tag/10) but this feature is not yet activated in paas-templates. It will be done in v49.

**Comment by poblin-orange** [comment]
will be integrated while integrating OFR branches

**Comment by JCL38-ORANGE** [comment]
link to https://github.com/orange-cloudfoundry/paas-templates/issues/969
