### ISSUE TITLE
cyclic bosh-dns / credhub /shield dependencies: fails restart/update of credhub-ha on vsphere

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#509]
### Expected behavior
As a platform operator, i want to be able to restart all the platform after a major failure

### Observed behavior
Cyclic dependencies prevent smooth restart/update

- credhub => credhhub. ((/dns...)) reference
- credhub shield. ((/secrets )) reference to bucket access key

Observed error trace during deployment of `micro-depls/credhub-ha` deployment, as a result of the credhub db spof #368
```
Task 887106 | 10:02:10 | Updating instance credhub-db: credhub-db/63bd91c1-c336-45b9-81b1-83accb509bcd (0) (canary) (00:02:43)
                      L Error: - Unable to render templates for job 'shield-agent'. Errors are:
  - Failed to fetch variable '/secrets/shield_obos_secret_access_key' with id '1400f0b3-4e89-430e-86db-332a36fd9a42' from config server: HTTP Code '500', Error: 'An application error occurred. Please contact your CredHub administrator.'
```

### Affected release

Reproduced on version 40, 41, 42

### Workaround

- get a local copy of credhub-ha.yml in secrets repo in `micro-depls/credhub-ha/credhub-ha.yml`
- manually replace the credhub references with their values :

```sh
$ grep -n '((' micro-depls/credhub-ha/credhub-ha.yml
99:            secret_access_key: ((/secrets/shield_obos_secret_access_key))
313:            password: ((credhub_uaa_admin_client_secret))
```

   * `credhub_uaa_admin_client_secret` can be found in micro-depls/credhub-ha/secrets/secrets.yml#secrets.uaa-users-admin
   * `/secrets/shield_obos_secret_access_key` is optional and can be transiently left empty.

- using bosh-cli perform a `bosh deploy credhub-ha-patched.yml`

**Comment by gberche-orange** [comment]
Fix tested and proposed in branch `feature-hot-fix-issue-509-credhubha`

**Comment by poblin-orange** [comment]
merged for v42
