### ISSUE TITLE
Micro-bosh director is lacking configured ssh key for recovery cases

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#522]
### Expected behavior

As a paas-templates operator, in order to troubleshoot/fix micro-bosh, I expect to be able to connect to ssh using an ssh key (which is more secured than the interactive login fixed in #442 which should be restricted for iaas console access).

### Observed behavior

The ssh private key at in secrets repo at `./shared/keypair/bosh.pem` or the private key from ` bootstrap/micro-bosh/creds.yml` don't allow to connect using ssh.

Instead the bosh-deployment documents in its [ops-file section](https://github.com/cloudfoundry/bosh-deployment/tree/master#ops-files)
> [jumpbox-user.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/jumpbox-user.yml): Adds user jumpbox for SSH-ing into the Director (see Jumpbox User)

https://bosh.io/docs/jumpbox/
> To obtain SSH access specifically to the Director VM when necessary you can opt into jumpbox-user.yml ops file when running bosh create-env command. It will add a jumpbox user to the VM (by using user_add job from cloudfoundry/os-conf-release).

Additionally, the `zz-docs/HOW_TO.md` section `ssh to bosh-micro` needs an update on where to find the micro-bosh ssh key.

### Affected release

Reproduced on version 42.0

/CC @ogrand

**Comment by poblin-orange** [comment]
fixed in v42.0.4
