### ISSUE TITLE
micro-depls/nexus should use system http proxy to retrieve own image.

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#523]
### Expected behavior
As a platform runner on vsphere, internet air gaped env, i expect to be able to install micro-depls/nexus

### Observed behavior
micro-depls/nexus once installed offers internet cached access to dockerhub and quay.io.
However, its itself implemented as a docker bosh release. Docker daemon must be able to reach internet, through system http proxy.

NB: on Flexible Engine, SNAT is not yet disabled (see #437), so this issue is only for vsphere air gaped envs.

**Comment by gberche-orange** [comment]
See related branch `feature-fix-nexus-docker-daemon-should-use-http-proxy` contributed by @poblin-orange

**Comment by poblin-orange** [comment]
merged for v42
