### ISSUE TITLE
support dedicated instance updates

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#524]
### Expected behavior

As a service operator, 
* in order to benefits from new paas-templates models (e.g. bosh operators/vars) 
* I need each COAB service instances to include new models files (e.g. bosh operators/vars) once updated. This is tracked in https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/40 which goes beyond https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/33

As a service operator, 
* in order to ensure consistency among stemcell, release and bosh deployment manifest updates
* I need to trigger (or control when) a refresh of service instances deployments against deployment model

As a service operator, 
* in order to avoid rolling out failure to all service instances upon a model update
* in order to spread load when many service instances need update
* + CANARY
* I need to trigger (or control when) a refresh of service instances deployments against deployment model

### Observed behavior

Currently, 
* new paas-templates releases might come with stemcell and bosh-release bumps managed by [*-depls-versions.yml](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/develop/docs/reference_dataset/template_repository/hello-world-root-depls/hello-world-root-depls-versions.yml)
   * bumped release and stemcell might require changes in bosh deployment manifest of service models and associated service instances.
* operators manually rebase service instance branches against latest versions (see #304), but this does not include symlinks to newly introduced model files.

### Other elements to consider

The following elements might change after a dedicated service instance is initially created. We might need coab impacts
   * models (e.g. bosh operators/vars) 
   * stemcell / bosh-releases
   * bosh-director config (e.g. runtime config for prometheus agent config)
   * dependent credhub properties (if any) ?
   * shared/secrets.yml keys

### Affected release

Reproduced on version 42.x

**Comment by poblin-orange** [comment]
0 - stemcell and bosh releases bumps are COA automated
1 - Non structural changes was managed with 46 (symlink + COA scan path)
2 - Structural changes. A COA concourse-config  pipeline is provided to realign existing instance with current model

Missing:
- coab variables list change (parameters, plans, x-osbcmdb vars). => new issues @gberche-orange
