### ISSUE TITLE
manage time diffrence between bosh os (UTC) and database

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#525]
### Expected behavior
As a service database user, I need to ensure that the date/time i manager in my database is in relation with the timezone where i use my data.
### Observed behavior
database commands like now() in MariaDb send by default de the os time
os time is set to UTC

If i need to manage a date/time related to my own time zone

**Comment by poblin-orange** [comment]
Bosh manages all vm in UTC. This makes senses, as if offers a cloud solution (for Orange, we have users in France and Egypt for instance).

Not sure we can do much on the mariadb size ? Would require defining the client timezone as a cf create-service parameter ?

**Comment by poblin-orange** [comment]
reference open issue on pxc-release https://github.com/cloudfoundry-incubator/pxc-release/issues/2

**Comment by ldangeard-orange** [comment]
cf-mysql-release don't load `mysql.time_zone*` tables, so you can not use for example country (ex Europe/Paris) like `set time_zone='Europe/Paris';`

However, however, you can set session parameters like `set time_zone='+4:00';`

**Comment by poblin-orange** [comment]
@plafosse-orange has implemented support see #744 
cc @ldangeard-orange  @regismarg

**Comment by ldangeard-orange** [comment]
Include in release cf-mysql MariaDB 10.3 https://github.com/orange-cloudfoundry/paas-templates/issues/744

**Comment by poblin-orange** [comment]
v48 will adapt maria db dedicated.
closing
