### ISSUE TITLE
Docker default bridge cidr conflicts with vsphere private network 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#528]
### Expected behavior

As a paas-service template author, in order to contribute mongodb for external consumption (#431), I expect v41 to deploy without error.

### Observed behavior

In the mongodb deployment, the shield agent instances fail to reach the shield server through the intranet interco relay split brain.

```
curl -vv -Lks "https://shield-webui.ops-data-services.redacted-domain.org/v1/meta/pubkey"
*   Trying 192.168.99.30...


mongod/7f73d9ed-904a-4722-9a42-96e67b884d11:~# traceroute 192.168.99.30
traceroute to 192.168.99.30 (192.168.99.30), 30 hops max, 60 byte packets
 1  172.17.48.1 (172.17.48.1)  0.474 ms  0.425 ms  0.385 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *

mongod/7f73d9ed-904a-4722-9a42-96e67b884d11:~# tcptraceroute 192.168.99.30 443
traceroute to 192.168.99.30 (192.168.99.30), 30 hops max, 60 byte packets
 1  172.17.48.1 (172.17.48.1)  0.102 ms  0.075 ms  0.045 ms
 2  * * *
 3  * * *
 4  * * *
```

The root cause seems a conflict on the target intranet interco relay 192.168.99.30 between the osb data plane network and the docker default bridge network 

```
ops-relay/849dd669-44fb-44c1-8270-425b48b61b90:~# ip route
default via 192.168.99.1 dev eth1 onlink 
10.0.0.0/8 via 10.118.127.129 dev eth0 
10.118.127.128/25 dev eth0  proto kernel  scope link  src 10.118.127.137 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.99.0/24 dev eth1  proto kernel  scope link  src 192.168.99.30 

ops-relay/849dd669-44fb-44c1-8270-425b48b61b90:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.99.1    0.0.0.0         UG    0      0        0 eth1
10.0.0.0        10.118.127.129  255.0.0.0       UG    0      0        0 eth0
10.118.127.128  *               255.255.255.128 U     0      0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
192.168.99.0    *               255.255.255.0   U     0      0        0 eth1
```

This was introduced in #112 with the envoy

### Affected release

Reproduced on version 41.0.2

### Alternative fixes

* configure docker to use a different cidr for brige network, simillar to `micro-depls/docker-bosh-cli/template/docker-bosh-cli-tpl.yml`

```yaml
properties:
  bridge: docker0
  cidr_prefix: 172.18
```

* handle the problem more generally in network architecture (#505 )
* consider other docker networking mode (to the expense of port conflicts) ?

**Comment by poblin-orange** [comment]
this is a smell we should not rely on private 172.xx networks to communicate with cloudfoundry client,

**Comment by poblin-orange** [comment]
172 network used by current (may 2020) vsphere API. Expecting this API to be exposed on a clean intranet level 10.x IP

**Comment by poblin-orange** [comment]
migrating to k8s
