### ISSUE TITLE
Logsearch apps/Kibana collected data perimeter too restrictive for admin account

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#531]
### Expected behavior
As an OPS, I expected to be able to see ALL the orgs/apps logs of the platform when connected as admin user. 
### Observed behavior
Parameter cf-org is restricted to system_domain and cf-skc. Dashboard graphs in consequence only show content for those orgs and not other ones.
### Affected release

Reproduced on version 41.0

**Comment by poblin-orange** [comment]
This can be solved by declaring ops user on each cf org (one way of doing it is cf create-space / cf-delete-space on each org)
