### ISSUE TITLE
prometheus addon bosh release should be on github orange teams org

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#533]
### Expected behavior
As a platform runner, i expect the bosh releases dependencies to be on shared/teams github org

### Observed behavior
On v42, paas-templates has a dependency on a develop github account
https://github.com/jraverdy-orange/prometheus-addons-boshrelease

**Comment by JCL38-ORANGE** [comment]
It will be part of orange cloudfoundry in v46 => https://github.com/orange-cloudfoundry/prometheus-addons-boshrelease
