### ISSUE TITLE
shield (fork) bosh release should be on github orange teams org

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#534]
### Expected behavior
As a platform runner, i expect the bosh releases dependencies to be on shared/teams github org

### Observed behavior
On v42, paas-templates has a dependency on a developer github account
uploadRelease "tgz" "gk-shield-boshrelease" "https://github.com/gstackio/gk-shield-boshrelease/releases/download/v7.0.8/shield-7.0.8.tgz" "7.0.8"

**Comment by poblin-orange** [comment]
@JCL38-ORANGE can we close as v45 is shield v8 ?

**Comment by JCL38-ORANGE** [comment]
It will be closed in v46 with the shield v7 cleaning

**Comment by JCL38-ORANGE** [comment]
delivered in v46
