### ISSUE TITLE
CFCR Ingress traefik version 1=> version 2 

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#539]
### Expected behavior
need to upgrade traefik ingress controller to allow TCP routing and not just HTTP/HTTPS
see documentation: 
- https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305 
- https://docs.traefik.io/v2.0/routing/routers/ 
- https://community.containo.us/t/traefik-release-v2-0-0-beta1/951 

### Affected release
41

**Comment by poblin-orange** [comment]
merged for v46.0.0
