### ISSUE TITLE
All bosh director deployments except micro-bosh deployment should use credhub in order to pick keystone credentials

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#54]
### Expected behavior
All bosh director deployments except micro-bosh deployment should use Credhub in order to pick up keystone credentials

### Observed behavior
All bosh director deployments except micro-bosh deployment use low level configuration files (secrets.yml) in order to pick up keystone credentials

### Affected release
Reproduced on version 24.0.0

### Traces and logs
N/A

**Comment by poblin-orange** [comment]
v34 includes bosh 266 + bosh-deployment 1.1.0 standard config.
