### ISSUE TITLE
[writing in progess] v42.0.0/v42.0.1 Release Note issues

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#543]
### Expected behavior
As an ops, I expect to encounter no issue on Release Notes manual ops actions
#### Issue 1 : Bad manual cmd
l158:
```bash
~/bosh/template/admin/unpause-jobs.sh -p coab-depls-bosh-generated
~/bosh/template/admin/unpause-jobs.sh -p cloudflare-depls-update-generated
```
should be instead
```bash
~/bosh/template/admin/unpause-jobs.sh -p coab
~/bosh/template/admin/unpause-jobs.sh -p cloudflare
```
as in the script unpause-jobs.sh we can read :
```
 56 #--- Unpause pipelines and jobs
 57 unpauseJobs() {
 58   pipeline="$1-depls-bosh-generated"

```

#### Issue 2 : Docker bosh cli prompt doesn't support line return anymore
when writing on more than screen size on docker bosh cli, there is no more line return made which lead to unreadable line commands:
__ex:__  `er.tfeau@fe-staging-fp:~$ echo "#disabled, see https://github.com/orange-cloudfoundry/paas-templates/issues/432" > coab-depls/terraform-config/spec/noop-service-broke
`

#### Issue 3 : Bad manual cmd

l318 : `bosh -e micro -d powerdns-docker`
should be read instead :
` bosh -e micro -d powerdns-docker delete-deployment`

same on l322
`bosh -e ops -d admin-ui` should be read `bosh -e ops -d admin-ui delete-deployment`
### Affected release

Reproduced on version 42.0.0/42.0.1

**Comment by poblin-orange** [comment]
issue 1 - bad cmd. fix for v43 update by @o-orand 
issue 2 - ubuntu issue. Ubuntu issue, see @obeyler for workaround. / @ogrand. To test

**Comment by obeyler** [comment]
issue 2 workaround:
put into key.sh
```
LTGREEN="\[\033[40;1;32m\]"
LTBLUE="\[\033[40;1;34m\]"
CLEAR="\[\033[0m\]"
LIGHT_GRAY="\[\033[40;1;33m\]"
export PS1="$LTGREEN\u$LTBLUE@\h:$LIGHT_GRAY\w$CLEAR "
```
source key.sh
