### ISSUE TITLE
Recreate script for Micro do not work on vsphere

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#544]
### Expected behavior
As on operator i expect recreate script for Micro bosh to update stemcell and regenerate CA Internal

### Observed behavior
On first launch on vSphere IAAS, the Openstack stemcell is downloaded.
When activating "internet proxy", credhub FQDN is not included into "no_proxy" var
On a second launch, the script stop on 3 unspecified var :
```
Generate micro-bosh vars manifest...
3 error(s) detected:
 - $.ca_cert.internal2: Unable to resolve `INTERNAL_CA2_CERT`: `$.INTERNAL_CA2_CERT` could not be found in the datastructure
 - $.vsphere_cpi_release: Unable to resolve `cpi_release`: `$.cpi_release` could not be found in the datastructure
 - $.vsphere_cpi_sha1: Unable to resolve `cpi_sha1`: `$.cpi_sha1` could not be found in the datastructure
```
### Affected release
v42.0.1

**Comment by poblin-orange** [comment]
fixed in v42.0.4
