### ISSUE TITLE
cf-deployment 12.x

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#546]
### Expected behavior

- cf-deployment 12 scope: 
https://docs.google.com/document/d/18sTD5e3x-l2DaN-bfaIch4A7Z-Ez95P7gIosxRUEX-0/edit
+ likely firehose endpoint depreciation announced in https://lists.cloudfoundry.org/g/cf-dev/topic/29741830#8510

> after a lot of deliberation and many good conversations, we came to the conclusion that we will go ahead and remove the firehose endpoint in six months. So, in the first release published after September 14th, there will be no more firehose endpoint. Until then, we will continue to help the community to migrate commonly used firehose integrations over to using the new endpoints located on the Reverse Log Proxy.

Dependent bumps: 
* https://github.com/bosh-prometheus/firehose_exporter/pull/43
* ~https://github.com/cloudfoundry-community/autosleep/issues/299~ (autosleep not leveraged in paas-templates)

**Comment by poblin-orange** [comment]
merged for v45
