### ISSUE TITLE
Externalize Shield storage on vsphere

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#548]
### Expected behavior
As an operator, i want to externalize my backup

### Observed behavior
Storage of backup are collocalized on the same disk as deployement. In case of site disaster, we lost deployement data and backup

<!--

**Comment by poblin-orange** [comment]
v40 applied a workaround to backup inside the vsphere iaas tenant (missing external S3).
Point here is to have a generic configuration for s3 backups (compatible with all S3 providers, not just OBOS scality S3 public service)

**Comment by poblin-orange** [comment]
done in v44
