### ISSUE TITLE
Redis TLS support

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#549]
### Expected behavior

As a service user, in order to securely use redis over the network where untrusted 3rd parties may be listening, I need to connect to redis over TLS.

### Observed behavior

Redis coab in v43 returns credentials without tls details , see https://github.com/orange-cloudfoundry/redis-orange/issues/2

```json
 "VCAP_SERVICES": {
  "redis-ondemand": [
   {
    "binding_name": null,
    "credentials": {
     "host": "192.168.211.57",
     "password": "...",
     "port": "6379"
    },
    "instance_name": "redis-smoketest-1568969291",
    "label": "redis-ondemand",
    "name": "redis-smoketest-1568969291",
    "plan": "small",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "Redis",
     "Document"
    ]
}
```
### Affected release

Reproduced on version 43.x

**Comment by ccambien** [comment]
Considering the [Redis Security](https://redis.io/topics/security) model and security features in Redis (or the lack of...), we can wonder if this feature is desirable. Redis is designed for performance with the deliberate choice to sacrifice security. 
If an application has sensitive information, it might not be the best idea to choose Redis from the start. Other key values stores like etcd has buit in security features like automatic TLS with optional client cert authentication, and can be a better choice for sensitive information.

**Comment by poblin-orange** [comment]
https://redislabs.com/blog/stunnel-secure-redis-ssl/

**Comment by ccambien** [comment]
For sure, using stunnel ou spiped is a way to encrypt any flow. However, It's a hack and goes against Redis design. If an application has strong requirements regarding the security, Redis should be chosen in the first place. It's not only a question on encrypting data in transit. Redis has not been designed for security and have no security feature at all. For instance, Redis does not have any mechanims for access control.

**Comment by poblin-orange** [comment]
closing as redis is not the correct solution given this ssl constraint.
Might consider alternative product (eg: hazelcast/ memcache) depending on the required use case

**Comment by gberche-orange** [comment]
@ccambien @poblin-orange pivotal redis does support redis over TLS see https://docs.pivotal.io/redis/2-2/preparing-tls.html 

Could this be an acceptable transient workaround until an alternative marketplace offer gets proposed ?
