### ISSUE TITLE
Prometheus fail to scrape node

### ISSUE THREAD

**Issue by Darrel63** [orange-cloudfoundry/paas-templates#553]
### Expected behavior
As an operator, i want prometheus to scrape each deployed node

### Observed behavior
If the node has a non addressable IP on his eth0, Prometheus register the node with the wrong IP and therefore, could not scrape it.

### Affected release
v42.0.1

 -->

**Comment by Darrel63** [comment]
As mentionned in the documentation (https://github.com/bosh-prometheus/bosh_exporter#filtering-ips)
When Service Discovery add a node, it will take the first IP that match the CIDR Filter.
By default, the filter match 0.0.0.0, and then 'eth0' is set as a target node. In our case, "eth0" is on a non addressable cidr by Prometheus. 
We have to use filter.cidrs to limit acceptable IP.

**Comment by poblin-orange** [comment]
merged for v43
