### ISSUE TITLE
Openstack FE loadbalancer issue. prevents internet  ingress HA activation

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#556]
### Expected behavior
Following #193, i expect to be able to activate the new internet ingress access layer

### Observed behavior
We experience iaas level security group issue on the Flexible Engine loadbalancer

**Comment by regismarg** [comment]
no OCB value ???? this is HA purpose

**Comment by poblin-orange** [comment]
closing. The issue was related to a missing openstack security group (must enable inbound  FE loadbalancer ips )
