### ISSUE TITLE
Stemcell bump for CVE usn-4135-1

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#557]
### Expected behavior

As a paas-templates operator, in order to run a safe system, I expect known CVE with high severity to be handled

### Observed behavior

https://www.cloudfoundry.org/blog/usn-4135-1/ requires stemcell bump to 315.97

### Affected release

Reproduced on version 42.x

**Comment by poblin-orange** [comment]
merged for v43
