### ISSUE TITLE
Internet-proxy : use an authenticate relaying proxy (vsphere)

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#570]
### Expected behavior
As a platform operator, i want to use an authenticate relaying proxy to intranet proxy giving Internet connectivity

### Observed behavior
micro-depls/internet-proxy deploiment allow to set proxy host and port from secrets but do not take credentials properties

**Comment by poblin-orange** [comment]
Note that we use floating ips  for internet access on openstack iaas-type. This authent evolution if for proxy cache only  (iaas type vsphere)

**Comment by poblin-orange** [comment]
merged for v43
