### ISSUE TITLE
Add a variable to set DNS used by intranet-interco

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#572]
### Expected behavior
As a platform operator, i want to choose the DNS to be used by Squid in `master-depls/intranet-interco-relay` by setting a variable

### Observed behavior
DNS IP is hardcoded inside an operator.

**Comment by poblin-orange** [comment]
correction will be part of intranet management refactoring see

**Comment by poblin-orange** [comment]
merged for v44
