### ISSUE TITLE
Prometheus-master : false alert thrown for Logsearch-ops and Logsearch (vSphere)

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#576]
### Expected behavior
As an platform operator, i want to see a prometheus alert when the node is down.
If the node is up, i don't want to get alerted.

Also, i only want to be alerted on deployed component.

### Observed behavior
`micro-depls/prometheus-master` rely on a `elasticsearch_exporter` that try to collect ES metric throught a DNS entry that point to the wrong IP that result to a cluster health "red" in prometheus

`master-depls/prometheus` rely on a `elasticsearch_exporter` that try to collect ES metric from `master-depls/logsearch` that is not deployed.

**Comment by poblin-orange** [comment]
merged for v46 thks @JSimon-Orange
