### ISSUE TITLE
dedicated redis -sentinel / cluster

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#578]
### Expected behavior
As a platform user, i need a ha solution for dedicated redis service

### reference
- https://github.com/orange-cloudfoundry/redis-orange

**Comment by regismarg** [comment]
Redis in cluster and sentinel are two topics
Seen with Laurent D and Thai Hoa T: 
Redis Sentinel dedicated mode and HA will be in V44
Redis cluster: not necessary for the moment (nedd use cases with huge memory needs)

**Comment by JCL38-ORANGE** [comment]
Merged in v44.
