### ISSUE TITLE
Prometheus probe url for Logsearch-ops not updated for v42

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#580]
### Expected behavior

As an OPS, I expect that Prometheus probe for logsearch-ops are correctly setted in order to avoid false positive alarms.

### Observed behavior
Prometheus is not able to correctly monitor logsearch-ops as he is checking a not updated URL :
@`
paas-templates/blame/master/micro-depls/prometheus-exporter-master/template/openstack-hws/1-black-box-scrape-operators.yml#L76
`, man can read :
` - "https://logsearch-ops.((/secrets/cloudfoundry_system_domain))/login" #probe for logsearch-ops app.`. But with feature branch **feature-logsearch-ops-on-ops-routing** that is included in v42.0.0 tag, logsearch-ops is now on ops-domain. Therefore, Prometheus probe should be also updated.

Fix available in branch **feature-fix-prometheus-logsearch-ops-probe**
### Affected release

Reproduced on version 42.0.1 (seems also not fixed in 42.0.4)

**Comment by poblin-orange** [comment]
contrib merged for v44
