### ISSUE TITLE
traefik desactivate gzip compression

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#590]
### Expected behavior
traefik ingress controller has trouble with gzip compression on content-type text/event-stream (these kind of content-type is used by concourse to display job result)
as workaround I desactivated gzip compression
=> traefik team has create a way to desactivate gzip compression
https://github.com/containous/traefik/pull/5721
but the chart doesn't implement it yet
### Affected release
v44

**Comment by poblin-orange** [comment]
v44 sets a workaround configuration (disable gzip).
Waiting for upstream fixes

**Comment by obeyler** [comment]
need to be confirm with last traefik V2 currently used

**Comment by poblin-orange** [comment]
cant reproduce with concourse + traefik helm as of v51. closing
