### ISSUE TITLE
v43: missing Credhub value during installation

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#591]
### Expected behavior
As an OPS, I expect to deploy installation script without error: a credhub value is missing

### Observed behavior
When Lauching the mentioned script in Release Notes v43.0.1 [update-upgrade-param.sh](https://elpaaso-gitlab.nd-stg-ops-paas.itn.intraorange/fe-group/forge-tags-stg/blob/43.0.1/zz-docs/release-notes/V43_0_0.md#L70), a Credhub value is missing:
```
:~/bosh/template/upgrade$ ./update-upgrade-param.sh

Enter LDAP user and password :
username: **************
password: ********************
Setting the target url: https://credhub.internal.paas:8844
Login Successful
id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
name: /concourse-micro/main/paas-templates-version
type: value
value: <redacted>
version_created_at: "2019-10-30T15:43:55Z"

id: xxxxxxxxxxxxxxxxxxxxxx
name: /concourse-micro/main/cf-ops-automation-version
type: value
value: <redacted>
version_created_at: "2019-10-30T15:43:55Z"

skipping /concourse-micro/main/stemcell-version. Current credhub value: <> - !! Key Not Found in credhub !!
```
I checked on others environments (INT, PROD), and did not find the value. 

### Affected release

Reproduced on version 43.0.1 (during installation process)

**Comment by poblin-orange** [comment]
Was just a warning, not blocker
fixed for v44.
