### ISSUE TITLE
migrate mysql/mariadb services to pxc bosh release

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#593]
### Expected behavior
As a platform operator, i need an active upstream bosh release for the mysql/mariadb shared/dedicated marketplace

### Observed behavior
The current cf-mysql bosh release is not active anymore.
The possible K8S service target solution are not yet mature enough

**Comment by ldangeard-orange** [comment]
Percona is not group prescription

**Comment by regismarg** [comment]
need a first step to define complexity,cost,time to crete such a new service
