### ISSUE TITLE
dedicated services backup jobs must be unpaused at creation time

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#597]
### Expected behavior
As a platform operator and as a platform user, i want dedicated services backup jobs 
to be unpaused.

### Observed behavior
the dedicated services backups are paused so no backup is performed.

### Affected release
v42, v43

### Traces and logs
The shield dashboard backups jobs are tagged as paused. Shortly, it is possible to unpause them as a workaround via the GUI (at the same time, the bosh deployment of the instance must be paused, in order not to remove GUI unpause action).
It will be definitely fixed in v44.

**Comment by poblin-orange** [comment]
manual workaround provided (avoid bosh deploy)
fixed merged for v44
