### ISSUE TITLE
Error during cf-sample-apps deployment

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#598]
# Observed behavior
The cf-sample-app go cannot be deployed. This deployement use the go-buildpack 1.8.40
With the last version, it's ok (https://github.com/cloudfoundry/go-buildpack.git#v1.9.3)

### Affected release
v42.0.1
### Traces and logs
`
  Downloaded app package (1.4K)
   -----> Go Buildpack version 1.8.40
          **WARNING** [DEPRECATION WARNING]:
          **WARNING** Please use AppDynamics extension buildpack for Golang Application instrumentation
          **WARNING** for more details: https://docs.pivotal.io/partners/appdynamics/multibuildpack.html
   -----> Installing godep 80
          Download [https://buildpacks.cloudfoundry.org/dependencies/godep/godep-v80-linux-x64-cflinuxfs3-b60ac947.tgz]
   -----> Installing glide 0.13.2
          Download [https://buildpacks.cloudfoundry.org/dependencies/glide/glide-v0.13.2-linux-x64-cflinuxfs3-b50997e2.tgz]
   -----> Installing dep 0.5.3
          Download [https://buildpacks.cloudfoundry.org/dependencies/dep/dep-v0.5.3-linux-x64-cflinuxfs3-b9679cb1.tgz]
          **ERROR** Unable to determine Go version to install: go version 1.10.8 does not support go modules
   Failed to compile droplet: Failed to run all supply scripts: exit status 16
`

**Comment by poblin-orange** [comment]
go sample ok for v44 with

```
buildpack                 position   enabled   locked   filename                                      stack
go_buildpack              4          true      false    go_buildpack-cflinuxfs3-v1.9.1.zip            cflinuxfs3
cached-go-buildpack       16         true      false    go_buildpack-cached-v1.9.1.zip
```
