### ISSUE TITLE
Stratos user favorites

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#602]
### Expected behavior

As a Cf user, in order to quickly browse to my apps/spaces, I need the stratos favorite feature to be enabled

See https://static.sched.com/hosted_files/cfeu19/2d/CFEU2019_%20Project%20Update%20LATEST.pptx.pdf and associated video at https://www.youtube.com/watch?v=oGN0v7Qpdi4&list=PLhuMOCWn4P9hP8zloAKsXTPFx16dY0klx&index=46&t=0s

### Observed behavior

User favorites are not yet enabled

### Affected release

Reproduced on version 44.x

**Comment by poblin-orange** [comment]
fixed on v50 (k8s statos 4.4 ?)
