### ISSUE TITLE
Enforce micro-bosh recreate during paas-template upgrade

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#605]
### Expected behavior
As an Operator, I want paas-templates  upgrade pipeline to include micro-bosh recreation in order to reduce manual operation.

### Observed behavior
Micro bosh must be recreated from `inception` or `docker-bosh-cli` 

### Affected release
Reproduced on version 43.0.1

**Comment by poblin-orange** [comment]
merged for v44
