### ISSUE TITLE
Add backup on K8S bdd 

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#607]
### Expected behavior
no backup is provided into K8S database
should implement shield agent.
### Affected release
V44
Reproduced on version x.y
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->

**Comment by poblin-orange** [comment]
cfcr bosh release comes with bbr instrumentation. Use shield v8+bbr for backups see #606 #347

**Comment by JCL38-ORANGE** [comment]
cfcr-micro will be backuped in v46
