### ISSUE TITLE
memcached service shared HA

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#609]
### Expected behavior
As a platform operator, i expect the marketplace services to leverage multi-az
this service topic is: memcached
### Observed behavior
This memcached service is not leveraging multi-az

refers to global card: 
https://github.com/orange-cloudfoundry/paas-templates/issues/410

###  design outline
The memcache service is composed of:
  memcache (2,0)  : already HA, to be deployed on 2 az
   memcache_broker (1,0) : to modify and move 2 brokers

**Comment by poblin-orange** [comment]
merged with 2 azs in 45.0.0
