### ISSUE TITLE
KAFKA service shared HA

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#610]
### Expected behavior
As a platform operator, i expect the marketplace services to leverage multi-az
this service topic is: kafka

### Observed behavior
This kafka service is not leveraging multi-az

refers to global card:
https://github.com/orange-cloudfoundry/paas-templates/issues/410

### Design outline
The kafka service is composed of:
kafka-manager (1,0)  : to modify and move 2 managers
    kafka-service-broker (1,0) : to modify and move 2 brokers
    kafka (3,0) : already HA, to be deployed on at least 2 az
    zookeeper (3,0) : already HA, to be deployed on at least 2 az

**Comment by poblin-orange** [comment]
merged on 2 azs for 45.0.0
