### ISSUE TITLE
MariaDB coab dedicated service on multi AZ en HA

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#612]
### Expected behavior
As a platform operator, i expect the marketplace services to leverage multi-az
this service topic is: MariaDB
Already multi AZ but automatic load balancing must be done

### Observed behavior
pre-requisit:
Issue smoke test loadbalancer:
  https://github.com/orange-cloudfoundry/paas-templates/issues/556

One  un spof on the  proxy:
    proxy (1,1) => a Solution must be designed (LB FE ? or  DNS ?)

**Comment by poblin-orange** [comment]
recent release colocate the proxy with the db, loadbalanced equally. Each proxy routes to the smaller index available instance. 
- colocating the proxy reduce the vm consumption
- perf gain (1 on 3 request)
- possibility to use an stable alias *.mysql.network.cf-mysql.bosh.
- or, for external HA, 1 single vip
  - option 1 - possiblity to front with a vrrp vm pair with a stable vip => 
  - option 2 - colocate a keepalived. Optimisation:  with a check script (same algo as switchboard, or reuse existing switch board script), could avoid a hop. TBC: keepalived ok with 3 ips and 1 vip

**Comment by regismarg** [comment]
milstone moved from 46 to 48 send the MariadB HA on bisite to not available before april ?
seems to be late

**Comment by JCL38-ORANGE** [comment]
https://github.com/cloudfoundry/bosh-vsphere-cpi-release/issues/257

**Comment by gberche-orange** [comment]
relates to #676

**Comment by JCL38-ORANGE** [comment]
release note in order to install cf-mysql-extended service is available in v47.0.3 : 
coab-depls/cf-apps-deployments/coa-cf-mysql-extended-broker/install/releasenote.md

**Comment by gberche-orange** [comment]
@JCL38-ORANGE the step 3 and 4 related to broker management using terraform seem outdated since common-broker-scripts handle this without the terraform lack of ops-controlled activation.

**Comment by poblin-orange** [comment]
Closing this issue, v47.0.3 delivered the core feature, and final fixes merged for v48.
