### ISSUE TITLE
missing cron release on Paas-template upgrade v43.0.1 for Master director

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#614]
### Expected behavior
As an operator, i want the upgrade pipeline to add mandatory bosh release to each director

### Observed behavior
When upgrading Master director, the cron bosh release was not uploaded nor expressed as a dependency

### Affected release
v 43.0.1

**Comment by poblin-orange** [comment]
merged for v44
