### ISSUE TITLE
VRRP IP may be out of range

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#615]
### Expected behavior
As a platform operator, i want that VRRP IP selected by indice from a range exist. 

### Observed behavior
VRRP IP are taken from the end of the range. Using positive indice make the deployment dependant of the network range.
In our case, subnet are only /25 and indice 246 result in an array out of bound

**Comment by poblin-orange** [comment]
merged for v44 thks
