### ISSUE TITLE
Store terraform tfstate to credhub

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#62]
### Expected behavior

TF state safely stored remotely out of the paas-secret git repo. In our case this may mean using the [orange-cloudfoundry/terraform-secure-backend](https://github.com/orange-cloudfoundry/terraform-secure-backend) for storing TF state.

### Observed behavior

TF state is currently stored in paas-secrets git repo.

https://www.terraform.io/docs/state/sensitive-data.html mentions 

> Terraform state can contain sensitive data [...] Recommendations: Storing state remotely may provide you encryption at rest depending on the backend you choose. [...] Long term, the Terraform project wants to further improve the ability to secure sensitive data. There are plans to provide a generic mechanism for specific state attributes to be encrypted or even completely omitted from the state. These do not exist yet except on a resource-by-resource basis if documented.

The credhub provider attempts to reduce storing such secret see related https://github.com/orange-cloudfoundry/terraform-provider-credhub/issues/2#issuecomment-386536868

### Affected release

Reproduced on version V 24.0.0

**Comment by poblin-orange** [comment]
as of terraform 0.13, multiple backend are supported, including locking (eg: posgres)
Wont use credhub for that purpose
