### ISSUE TITLE
remove legacy o-internet-access service (replaced by o-internet-ha-access)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#625]
### Expected behavior
As a platform operator, i dont want to maintain legacy o-internet service

### Observed behavior
There are 2 internet services provided

```
[root@localhost vsphere]# cf m |grep internet
Getting services from marketplace in org orange-internet / space prometheus-probe as apog7416...
o-internet-access      default                                                            returns the http proxy to use for internet access                                                        o-internet-access
o-internet-ha-access   default                                                            returns the http proxy to use for internet access                                                        o-internet-ha-access

```

### solution outline
- [ ] notify projets to switch to o-internet-ha-access
- [ ] purge o-internet-access instances
- [ ] unregister o-internet-access broker
- [ ] purge unused artifact
  - spring cloud config repo static brokers
  - terraform registration
  - bosh micro-depls/internet-relay
  - cf asg security group to the legacy internet relay

**Comment by regismarg** [comment]
before doing that in prodution, a check must be done to verify how many customers use legacy o-internet-access and explain to move to new one

**Comment by poblin-orange** [comment]
removed in 45.0.0
