### ISSUE TITLE
Stemcell bump to 456.69 for USN-4182-1 and USN-4185-1

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#628]
### Expected behavior

As a paas-templates operator, in order to run a safe system, I expect known CVE with high severity to be handled

### Observed behavior

https://www.cloudfoundry.org/blog/usn-4182-1/ and https://www.cloudfoundry.org/blog/usn-4182-1/ recommend upgrade to 456.69 or higher

### Affected release

Reproduced on version 44.02

**Comment by poblin-orange** [comment]
merged for v44.0.3
