### ISSUE TITLE
move default grafana dashboard into helm and remove it from paastemplate

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#629]
### Expected behavior
move default grafana dashboard into dedicated helm chart and remove it from paastemplate

**Comment by poblin-orange** [comment]
Should design a general way to reuse community dashboards / store orange specific dashboards
- grafana
- kibana
- metabase
- prometheus alerts

**Comment by poblin-orange** [comment]
reuse bosh release grafana dashboard (bosh release colocation with a bosh errand + helm kubectl to create the related k8s configmap). prometheus-release / orange-prometheus-add-on.

**Comment by poblin-orange** [comment]
bosh release dashboards has been loaded in grafana
