### ISSUE TITLE
cf cups with TCP port

### ISSUE THREAD

**Issue by jvizier** [orange-cloudfoundry/paas-templates#632]
### Expected behavior

Using cf cups between two app in the same space with a TCP port

### Observed behavior

TCP is ok between the two apps

### Affected release

V42 / V43

### Traces and logs
Trace on the first app :

**[LGR.] Failed to resolve syslog drain host: xxx.apps.internal**

### Test

test TCP between cell2 and app2 --> OK
test TCP between cell1 and app2 --> KO

**Comment by poblin-orange** [comment]
the *.apps.internal domain is set for app to app communication.
But its not visible out of the diego cf apps. This, syslog drain cups (managed by cloudfoundry runtime) can not reference apps.internal.domain
