### ISSUE TITLE
Add Network Security Policy inside k8s runtime

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#637]
### Expected behavior
Add Network Security Policy inside CFCR
to do that replace flannel CNI by Calico

### references

- https://github.com/sbueringer/kubecon-slides/blob/master/slides/2019-kubecon-eu/Kubernetes%20Networking%20How%20to%20Write%20a%20CNI%20Plugin%20From%20Scratch%20-%20Eran%20Yanay%2C%20Twistlock%20-%20CNI%20-%20Kubecon%20Barcelona(1).pdf

- https://github.com/orange-cloudfoundry/calico-boshrelease
- https://github.com/cloudfoundry-incubator/kubo-release/issues/351

**Comment by poblin-orange** [comment]
to discuss as
- we switched from cfcr to k8s-bosh release (activated with weave)
- also planning to use rancher k3s (default flannel)
