### ISSUE TITLE
cfcr openebs - Increase stability

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#638]
### Expected behavior
CFCR need to be more robust

### Observed behavior
When turbulence is used to shake CFCR (it kills some cfcr vm) lot of bad behaviour occured 
by example many container are in state container creating
or if 2 of the 3 persistents workers are destroyed, the openebs corum for iscsi is broken and all cstor volume become ReadOnly instgead of ReadWrite

### Affected release
44.0
Reproduced on version x.y

**Comment by obeyler** [comment]
To solve the trouble of Read Only cstor volume a script is done to reproduce the openebs manual procedure descibe here : 
https://docs.google.com/document/d/1cASJqls1LSKvypCLeeL-tWUcQEfy5RJuWbiIhXGeRlA/edit

The script is on this repo: 
https://github.com/orange-cloudfoundry/openebs-repare-script

**Comment by obeyler** [comment]
a mettre en errand

**Comment by poblin-orange** [comment]
script seem ok.
Must add as an errand

**Comment by poblin-orange** [comment]
current status. open ebs 17.
disabling the k8S cloud provider solved the issue => each node a stable immutable IP, openebs can use ip to identify PVC
