### ISSUE TITLE
missing instructions to setup mattermost SSO auth with gitlab

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#64]
### Expected behavior
As an operator, i need instructions to setup correct credentials, and gitlab oauth application, so that operators can log into mattermost using with LDAP identity

### Observed behavior
No instructions given

### Affected release
v27
Reproduced on version x.y

### references
- https://docs.mattermost.com/administration/config-settings.html#gitlab
- https://github.com/mattermost/mattermost-server/issues/3944
- https://docs.mattermost.com/administration/config-settings.html#logging
- https://github.com/cloudfoundry-community/mattermost-cf-integrator

**Comment by poblin-orange** [comment]
need to confirm the requirement for including mattermost in paas templates.
a k8S hosting is probably better

**Comment by o-orand** [comment]
@poblin-orange , as we don't use mattermost embedded with paas-template anymore, we may close this ?
