### ISSUE TITLE
cfcr - higher scheduling prioriry for traefik and openebs

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#643]
### Expected behavior
As a platform operator, i expect the embedded cfcr deployments to manage infrastructure k8S deployments with higher scheduling priority  then hosted helm charts deployments

https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
(requires K8S 1.14)

**Comment by obeyler** [comment]
I proposed by slack channel to implent it for OpenEBS

**Comment by poblin-orange** [comment]
close (switched from openebs to longhorn in v 48)
