### ISSUE TITLE
paas-template open sourcing

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#65]
### Expected behavior

paas-template public on github. This is an umbrella ticket referencing sub-issues:
- Includes secrets leak automated preventions, see #4
- Paas-template freshness w.r.t. CVEs #21

COA prereqs https://github.com/orange-cloudfoundry/cf-ops-automation/issues/83

### Observed behavior

paas-template is shared privately within Orange

### Affected release

Reproduced on version 27.0

**Comment by poblin-orange** [comment]
new commit drop 04/2019 for cf-summit philadelphie

**Comment by gberche-orange** [comment]
Paas-templates has been published in https://github.com/orange-cloudfoundry/paas-templates closing this long running issue.
