### ISSUE TITLE
1st class support for feature flags

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#650]
### Expected behavior

As a paas-templates author, in order to efficiently support optional features, I need 1st class support with:
- automated test of the different flag values (e.g. leveraging display such as [upcoming concourse spatial resource](https://blog.concourse-ci.org/core-roadmap-towards-v10/#rfc-29-spatial-resources)
- centralized management of the feature test (such as having bosh ops/vars files being conditionally selected when the feature flag is turned on/off)

Example use-cases:
- choose whether S3 backups should go over internet or intranet proxy
- choose the type of S3 API (S3 v2/v4 or scality variants)

### Observed behavior

Feature flags can be proposed in secrets/shared.yml or deployments secrets/secrets.yml or credhub. 

On the integration platform, only a single flag value is tested per deployment (no pipeline exist to dynamically test different flag values on potentially dynamically created environments)

### Affected release

Reproduced on version x.y
 -->

**Comment by poblin-orange** [comment]
COA profile support enables conditional activation (bosh operators, terraform, ...)
