### ISSUE TITLE
Clean up of workaround for "Expected variable xx to be already versioned"  bosh-director "errand-scripting"

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#651]
### Expected behavior

As a paas-templates authors, in order to avoid maintaining deprecated code (following fix of https://github.com/orange-cloudfoundry/paas-templates/issues/46#issuecomment-558241239 through COA credhub interpolation of runtime config ), I need associated deadcode to be cleaned up or moved/archived somewhere to be useable on other future occurences

### Observed behavior

 bosh-director "errand-scripting" errand is still present in v45

### Affected release

Reproduced on version 45.x

**Comment by poblin-orange** [comment]
check : interpolation issue on runtime-config (v46.0.0, profile COA 99-debug). TBC
@o-orand

**Comment by poblin-orange** [comment]
issue confirmed, fixed on COA 5 => need to keep workaround for v47 => reschedule cleanup in v48
