### ISSUE TITLE
deleted coab service instance leaks in secrets and template git repos

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#654]
### Expected behavior

As a paas-templates operator, in order to avoid human errors within service instances directories in git repos, I expected deleted service instances to be removed automatically

### Observed behavior

COA is preventing COAB from properly cleaning up deleted service instances in templates and secrets repos, see  https://github.com/orange-cloudfoundry/cf-ops-automation/issues/67

COAB delete would need to be adapted after that, see https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/221

### Affected release

Reproduced on version 45.x

**Comment by poblin-orange** [comment]
done for secrets.
TODO: clean instance in git instance branch

**Comment by JCL38-ORANGE** [comment]
The cleaning is embedded in v47.0.3 for new services (embedded in https://github.com/orange-cloudfoundry/cf-ops-automation-broker/releases/tag/v0.30.0).
Remaining work : a bash script has to be written in order to clean service instances created prior to v47.0.3.
