### ISSUE TITLE
COAB instances retrofit

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#655]
### Expected behavior
As a platform operator, when upgrading paas-templates, i expect existing COAB/dedicated service instances to align with new vxx bosh components (ie: tuning values / ...)

I also expect COAB deployments update rate to be controlled by human actions.

### Observed behavior

As of v44: 

* dedicated instances `bosh deploy` are inconsistently triggered
   - the coab model update do not trigger a `bosh deploy` job for dedicated instances
   - however, the concourse reset does trigger a `bosh deploy` job for dedicated instances
   - all coab deployments are unpaused at the end of the upgrade pipeline

* dedicated instances `bosh deploy` don't consistently include the expected inputs:
   - model updates are not propagated to symlinked dedicated instances, unless triggered by a concourse reset
   - bumps bosh release outside bosh.io are uncontrolled, see #653
   - new files in model updates are not taken into account (see #524)

### Solution outline
- at the end of the upgrade pipeline, we should let coab bosh deployments individually paused. This should let operators choose which instance to deploy/update (globally or individually) by selectively unpausing them.

- fix the template
  - add COA [extended_scan_path](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/dc3663fb3e8e9759b02b9a9086e0c9d6f23022ac/docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/deployment-dependencies.yml#L6-L7 ) clause to let dedicated jobs deployment jobs trigger and symlink refresh when model gets updated.
  - replace "latest" version in deployment manifests with the exact version of bosh releases not managed by COA but uploaded to bosh-director through deploy.sh script #653. This prevents uncontrolled/unexpected release bumps.
    - mongodb
    - cassandra
    - (cf-mysql and cf-redis are COA list their dependent releases in [deployment-dependencies.yml](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/develop/docs/reference_dataset/template_repository/hello-world-root-depls/bosh-deployment-sample/deployment-dependencies.yml) and the version is set by root deployment in [coab-depls-version.yml](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/develop/docs/reference_dataset/template_repository/hello-world-root-depls/hello-world-root-depls-versions.yml#L6-L10))

**Comment by JCL38-ORANGE** [comment]
delivered in v46
