### ISSUE TITLE
High memory usage on cron-blobstore-backup 

### ISSUE THREAD

**Issue by T0FFF** [orange-cloudfoundry/paas-templates#659]
### Observed behavior
on v43.0.1, the cron configured on the cron-blobstore-backup crashed due to important load on the minio mirror command between local minio and OBOS. the problem occurs since the minio cli update (2019-12-17)

` 
./mc mirror --remove ... in /var/vcap/jobs/cron/config/backup-sh
`

The script (backup-sh) download automatically the latest version of mc cli each time. (It's dangerous to use "latest")

### Traces and logs
`
mc: <ERROR> Unable to list comparison retrying.. Truncated response should have continuation token set
`
(more than 15000 objects in the bucket) 

### Workaround
I downloaded the previous cli version:
https://dl.minio.io/client/mc/release/linux-amd64/archive/mc

**Comment by poblin-orange** [comment]
minio version fixed for v46 (no more latest)
Pending additionnal details from ops wrt / memory issue @T0FFF ?

**Comment by poblin-orange** [comment]
wont fix. the cloudfoundry minio will migrate to minio k8s (container based approach will eliminate this type of vm level memory leaks)
