### ISSUE TITLE
Stratos SSH feature isn't working

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#66]
### Expected behavior

Stratos UI provides a way for users to ssh into their container instances.

### Observed behavior

Fails both in stratos v1 and v2

### Affected release

Reproduced on version 27.0

**Comment by gberche-orange** [comment]
Diagnostic: the stratos space is missing network permissions to egress to the ssh public IP.: TCP cnx is refused from stratos container, whereas it is accepted from users desktop.

Note that ssh to ssh endpoint fails from bosh-cli: cnx refused by peer. Also visible with netcat.

```
$ nc -v ssh.nd-int-cfapi.mydomain 80
Warning: inverse host lookup failed for 10.xx.xx Unknown host
ssh.mydomain  [10.xx.xx] 80 (http) open
```

/CC @poblin-orange 

Potential fixes:
- [ ] add a split dns entry from ssh.${system_domain} so that cf apps within cloudfoundry hit the internal network in the private adress space: 192.168...
- [ ] add a new security group `cf-ssh-internal` enabling cf apps to reach the ssh internal IP (192.168...) on port 80
- [ ] assign `cf-ssh-internal` ASG to system_domain/ cf-ui space

**Comment by poblin-orange** [comment]
a new cf-ssh-internal ASG is defined.  The related terraform spec is split by iaas type.

**Comment by gberche-orange** [comment]
Blocked by https://github.com/cloudfoundry-incubator/stratos/issues/1377, see related https://cloudfoundry.slack.com/archives/C80EP4Y57/p1540396660000100

**Comment by poblin-orange** [comment]
ok on v30, stratos 2.3.0
