### ISSUE TITLE
support rabbitmq 3.8

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#660]
### Expected behavior
As a platform user, i want to be able to provision rabbitmq 3.8 service instances

### Observed behavior
As of v44, only rabbimq 3.7 is provided

**Comment by regismarg** [comment]
https://www.rabbitmq.com/versions.html
Release 3.7 : End of Life 31 -->  March 2020

**Comment by poblin-orange** [comment]
merged for v47.0.0
