### ISSUE TITLE
add velero cli on bosh cli

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#664]
### Expected behavior
add velero cli on bosh cli ( tools for backup/restore K8S)
https://github.com/vmware-tanzu/velero/releases/tag/v1.2.0

https://github.com/vmware-tanzu/velero/releases/download/v1.2.0/velero-v1.2.0-linux-amd64.tar.gz

**Comment by poblin-orange** [comment]
merged with cli 1.38 in 45.0.0
