### ISSUE TITLE
bump helm 3 version on bosh cli

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#665]
### Expected behavior
bump new helm version 3.0 for bosh cli to be compliant with new helm-kubectl-bosh-release
**Caution** the download url has changed to:
```

HELM_FILE=helm-v${HELM_VERSION}-linux-amd64.tar.gz
wget https://get.helm.sh/${HELM_FILE}

```

**Comment by poblin-orange** [comment]
merged with cli 1.38 in 45.0.0
