### ISSUE TITLE
[spike] cpi-config multi -iaas

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#673]
### Expected behavior
as a platform operator, i need to ensure SLA and quality by providing the services on multi AZ or multi regions
I need to be able to pilot multi iaas installation.

### Observed behavior
Goal: be able with cpi-config to pilot multi iaas and create VM on each region

**Comment by poblin-orange** [comment]
Spike progress
- [ ] define a new root deployment, targeting remote region
- [ ] COA terraform remote region network provisioning
- [ ] cpi-config for multiple regions configuration
- [ ] cloud-config adaptation (1 bosh network = 1 r1 subnet + 1 r2 subnet)

**Comment by poblin-orange** [comment]
initial version merged for v46
