### ISSUE TITLE
[spike] disaster recory tool in mono-cpi for bi-region

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#674]
### Expected behavior
as a platform operator, i need to accelerate recovery in case of problem if a service is multi region installed
I need to be able to pilot with tools a recovery

### Observed behavior
Goal: be able to have tools helping in recory of lost region

example to prevent:
bosh failed deployment mono-cpi

check recovery for different services:
 ex: jdbc mariadb : does driver support n ips backend  and can switch ? 

same question for
 mongo ok
redis ok
rabbit 

error condition
unreacheable bosh agents
(can be simulated easy)
  cpi z2 triggering errors
 harder to similate without multi-cpi
 "Bosh ignore" helpful ?
 no_converge ?

**Comment by poblin-orange** [comment]
multi-az hosting possible with
- #972 
- postgrest stolon HA k8s deployment
