### ISSUE TITLE
[spike] disaster recory tool in multi-cpi for bi-region

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#675]
### Expected behavior
as a platform operator, i need to accelerate recovery in case of problem if a service is multi region installed
I need to be able to pilot with tools a recovery

Goal: be able to have tools helping in recory of lost region in multi-cpi mode

### Observed behavior
example to prevent:
bosh failed deployment multi-cpi

**Comment by poblin-orange** [comment]
only 3 region will be qualified
