### ISSUE TITLE
credhub-ha upgrade issue

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#678]
### Observed behavior
Due to remaining spof on credhub db, we observe issue when bumping ha, due to shield variables.

```
Finding variable 'docker-registry-url': Get https://credhub.internal.paas:8844/api/v1/data?path=%2Fconcourse-micro%2Fmicro-depls%2Fmicro-depls-bosh-generated%2Fdocker-registry-url: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (after 5 retries)
```
Workaround: 
- short term
- with bbr, the credhub backup mechanism will be centralized on master-depls/shield (no more shield reference)

### Affected release
Reproduced on version 45.

**Comment by gberche-orange** [comment]
Similar symtoms and workaround documented in v45 release notes.

This problem may also arise on a "bosh recreate" of credhub-ha

---------------

Credhub-ha still suffers from a cyclic dependency similar to  https://github.com/orange-cloudfoundry/paas-templates/issues/509 in v45.0.0 and would fail with the following message unless patched

```
Unable to render templates for job 'shield-agent'
    Failed to fetch variable '/bosh-master/shieldv8/shield-agent-key'
Unable to render templates for job 'import'
    Failed to fetch variable '/bosh-master/shieldv8/failsafe-password'
    Failed to fetch variable '/bosh-master/shieldv8/shield-agent-key'
``` 

Apply the following workaround procedure to setup a transient hot fix branch "feature-v45-hot-fix-credhub-ha-disable-shield-agent-during-upgrade". This branch would be removed in the post-upgrade step

```bash
#On the bosh-cli
cd ~/bosh/template/
git checkout reference
git reset --hard origin/reference
git clean -fdx
git status
git pull --rebase

git checkout -b "feature-v45-hot-fix-credhub-ha-disable-shield-agent-during-upgrade"
cp micro-depls/credhub-ha/bootstrap/remove-shieldv8-operators.yml micro-depls/credhub-ha/template/remove-shieldv8-operators.yml
# remove dangling reference to shield release and shield import errand 
# i.e. comment the last 6 lines
vi micro-depls/credhub-ha/deployment-dependencies.yml 
git add micro-depls/credhub-ha/remove-shieldv8-operators.yml
git add micro-depls/credhub-ha/deployment-dependencies.yml
git commit -m "feature-v45-hot-fix-credhub-ha-disable-shield-agent-during-upgrade"
git push --set-upstream origin feature-v45-hot-fix-credhub-ha-disable-shield-agent-during-upgrade 
```

Once the credhub-ha deployment is up, then the commit in `feature-v45-hot-fix-credhub-ha-disable-shield-agent-during-upgrade` can be reverted using the `git revert` command

**Comment by JCL38-ORANGE** [comment]
Merged for v46
