### ISSUE TITLE
credhub import fails silently

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#68]
### Expected behavior
the micro-depls/credhub-seeder successful deployment should be ok on concourse when all credhub credentials are loaded successfully

### Observed behavior
Bosh deploy is ok, but numeric values are not inserted, insert errors are invisible (need to look at /var/vcap/sys/log files)

### Affected release

Reproduced on version 27

### Traces and logs

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by poblin-orange** [comment]
maybe reconsider the seeding of credhub with alternate solutions.

**Comment by poblin-orange** [comment]
generic scripting workaround eval by @JCL38-ORANGE

**Comment by gberche-orange** [comment]
Related workaround applied in #89:
* manually trigger credhub seeder concourse job to upload cert to credhub. 
   * Check with credhub cli successful completion as a workaround for #68
   * If not updated, manually remove the entry from credhub `credhub delete -n /secrets/certs/internet-cert` + retrigger manually the job in concourse
