### ISSUE TITLE
COAB brokers don't use latest version of common broker scripts in v44 and some fail

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#681]
### Expected behavior

As a paas-templates operator, I expect the version of the files used to push and test coab brokers to be consistent among coab brokers, and to use the latest commited version in the paas-templates reference branche

### Observed behavior

The workaround for https://github.com/orange-cloudfoundry/cf-ops-automation/issues/144 has not been applied in recent paas-templates versions with coab common-broker-changes

As a result, coa-cassandra-broker fails during cf push with the following symptom

```
curl: no URL specified!
        
curl: try 'curl --help' or 'curl --manual' for more information 
```

Workaround:  set the following value in `coab-depls/cf-apps-deployments/coa-cassandra-broker/secrets/secrets.yml`

```
secrets:
#  smoke_test_service_plan: small    #name of the service plan to instanciate in smoke tests
  mode: release
```

### Affected release

Reproduced on version 44

#### Short term (v45)

* trigger a forced bump of symlinked content possibly using `coab-depls/common-broker-scripts/commit-and-bump-shared-content.sh`

#### Mid term (avoid regressions in v46, v47)

* Integrate into the release process a forced bump of symlinked content possibly using `coab-depls/common-broker-scripts/commit-and-bump-shared-content.sh`

* Independently version common broker scripts, see #579

**Comment by poblin-orange** [comment]
fixed in 45.0.1
