### ISSUE TITLE
v44.0.5 - BPM bosh-release wrong url link

### ISSUE THREAD

**Issue by aurelienbouleau** [orange-cloudfoundry/paas-templates#682]
### Expected behavior
As an ops, I expect that all Bosh releases configured in Paas-Templates are correctly configured and their changes in URL taken into account.

### Observed behavior
Concourse error: `bpm - pinned version {"path":"cloudfoundry/bpm-1.1.3.tgz"} is not available`
BPM bosh release  v1.1.3 is not found as url of this bosh release has changed:

__In Paas-Template v44.0.5__, this BR is configured with this link: 
`https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release` but now the right location for new bpm releases is no more the incubator but:
`https://github.com/cloudfoundry/bpm-release`.

What is fun here is that '[cf incubator' bpm bosh release](https://bosh.io/releases/github.com/cloudfoundry-incubator/bpm-release) contains all versions **until v1.0.4** and the ['cloudfoundry' one](https://bosh.io/releases/github.com/cloudfoundry/bpm-release) contains **ALL available versions (past and new)**. A switch to the new link will normally induce no impact as old versions are also present in this new repo.

### Affected release

Reproduced on version v44.0.5

**Comment by poblin-orange** [comment]
@ogrand  @o-orand is this fix with v46 deployment-versions.yml cleanup ?

**Comment by ogrand** [comment]
Upload of bpm bosh-release is now in deploy.sh script
uploadRelease "http" "bpm" "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=" "1.1.6"

**Comment by poblin-orange** [comment]
fixed in v46
