### ISSUE TITLE
COA : Automated COA 4.2.0 upgrade pipeline fails

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#684]
### Expected behavior
As a platform operator, i want the upgrade pipeline to update secrets and COA version

### Observed behavior
When running coa-v4.2.0-upgrade/update-to-cf-ops-automation-v4.2.0 job, an error occured when trying to push new secrets and prevent the pipeline to success

It seems that new version use a _git commit --porcelain_ on added/changed files and it implies a _git commit --dry-run_ . 

### Affected release
v45.0.1

### Traces and logs
**update-secrets**
...
18:12:40 Cloning into 'secrets-updated'...
18:12:40 done.
18:12:40 Setting the target url: https://credhub.internal.paas:8844
18:12:40 Login Successful
18:12:40 upgrading COA from <v4.1.0> to <v4.2.0>
18:12:40 > INFO: generating new credentials-credhub.yml. Please check it content
18:12:40 updating docker-registry-url in shared/secrets.yml
18:12:41 Credhub - Setting key '/concourse-micro/upload/docker-registry-url'
18:12:41 Credhub - Setting key '/concourse-micro/coab-depls/docker-registry-url'
18:12:41 Credhub - Setting key '/concourse-micro/master-depls/docker-registry-url'
18:12:41 Credhub - Setting key '/concourse-micro/micro-depls/docker-registry-url'
18:12:42 Credhub - Setting key '/concourse-micro/ops-depls/docker-registry-url'
18:12:42 Credhub - Setting key '/concourse-micro/utils/docker-registry-url'
18:12:42 Credhub - Setting key '/concourse-micro/main/docker-registry-url'
18:12:42 > INFO: generating new credentials-docker-registry.yml. Please check it content
18:12:42 executing upgrade file
18:12:42 Diff with HEAD
18:12:42 A  coa/config/credentials-credhub.yml
18:12:42 M  coa/config/credentials-docker-registry.yml
18:12:42 M  coa/config/credentials-git-config.yml
18:12:42 M  shared/secrets.yml
	
**secrets**
18:12:47 rebasing...
18:12:47 error: cannot pull with rebase: Your index contains uncommitted changes.
18:12:47 error: please commit or stash them.

* [x] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by JSimon-Orange** [comment]
workaround : 
cd secrets-updated/
git commit --no-verify -a -m "micro-depls(coa-upgrade): automated bump to 4.2.0"
git pull --rebase push-target master
git push push-target master

**Comment by poblin-orange** [comment]
merged for v45.0.2
