### ISSUE TITLE
JCR offers partial mirroring of docker resources

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#685]
### Expected behavior
As a platform opeerator, i expect all required docker images to be served from micro-depls JCR artifact repository

### Observed behavior
Issues with non docker.io images
- quay.io
- k8s.gcr.io

NB: this issue can be silent, as cfcr or docker bosh release can be configured with mirror AND proxy to internet (thus failing over to internet proxy does not error the job)

**Comment by poblin-orange** [comment]
see related issues wrt containerd and docker mirroring:
- https://github.com/containerd/containerd/issues/4011
- https://github.com/containerd/cri/issues/1196

**Comment by obeyler** [comment]
https://www.jfrog.com/jira/projects/RTFACT/issues/RTFACT-21534?filter=allissues

**Comment by obeyler** [comment]
Need can be test with switching to the new JCR deployment

**Comment by poblin-orange** [comment]
check with JCR 1.7
- [ ] ops-depls/postgres service uses quay.io with docker bosh release. Ok with nexus, ko avec JCR.
- [ ] on cfcr, change repo

**Comment by poblin-orange** [comment]
ko with JCR 1.7, issue still opened. k8s still uses http proxy as of v46/47

**Comment by obeyler** [comment]
https://stackoverflow.com/questions/62439583/unable-to-pull-k8s-gcr-io-pause-from-jfrog-artifactory-with-my-containerd

**Comment by poblin-orange** [comment]
ok with v48

**Comment by poblin-orange** [comment]
Still ko.

```
    etcd0/272591d8-c4f3-469a-89f6-2dcdd4b7f50c:~$ sudo -i

    etcd0/272591d8-c4f3-469a-89f6-2dcdd4b7f50c:~# docker ps

    CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                      NAMES

    b3d6467617b9        quay.io/coreos/etcd:v3.2.18   "etcd --name=etcd0 -…"   2 days ago          Up 2 days           0.0.0.0:2379-2380->2379-2380/tcp, 0.0.0.0:4001->4001/tcp   etcd

    etcd0/272591d8-c4f3-469a-89f6-2dcdd4b7f50c:~# docker pull quay.io/coreos/etcd

    Using default tag: latest

    Error response from daemon: Get https://quay.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

    etcd0/272591d8-c4f3-469a-89f6-2dcdd4b7f50c:~# 
```

**Comment by poblin-orange** [comment]
Following @ogrand analysis, the issue is related to docker mirroring limitations: 
https://github.com/docker/for-linux/issues/570
