### ISSUE TITLE
vsphere - Control plane CF apps logs missing in master-depls/logsearch-ops

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#686]
### Expected behavior

As a paas-templates operator, in order to have access to logs of control plane components hosted by master-depls/cf (coab brokers, osb-cmdb), I need master-depls/logsearch apps to index master-depls/cf firehose content

Also potentially, centralized log repository for osb-reverse-proxy and osb-cmdb logs cf apps might be useful to support #938 and #940

### Observed behavior

Following #287 in v42, the log-search ops is independent of CF, and the `ingestor_cloudfoundry-firehose` job is not included in log-search-ops

https://github.com/orange-cloudfoundry/paas-templates/blob/76da8377eb56b283bb3c7b938489cac495facd73/master-depls/logsearch-ops/template/9-decouple-from-cf-operators.yml#L1-L9

### Affected release

Reproduced on version 44

/CC @skortobi

**Comment by poblin-orange** [comment]
Short term solution for vsphere
- option 1. activate master-depls/logsearch-apps to collect cf apps logs on vsphere iaas-type (including community cf apps dashboards)
- options 2. for vsphere iaas type, activate bosh ops file to collect logs (firehose) and to load cf apps dashboards.

Mid term solution
- logsearch apps and ops to be unified with a k8S runtime target.

cc @gberche-orange  @skortobi

**Comment by poblin-orange** [comment]
short term: option 1, activate logsearch-apps in a reduced scale for vsphere iaas-type.

**Comment by gberche-orange** [comment]
reopened to proceed with next steps
- [ ] options 2. for vsphere iaas type, in master-depls/logsearch-ops, activate bosh ops file to collect logs (firehose) and to load cf apps dashboards.
   - [ ] production instance is lacking dasboard configuration

Mid term solution
- [ ] logsearch apps and ops to be unified with a k8S runtime target in loki (#1273)
