### ISSUE TITLE
JCR missing helm repo

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#687]
### Expected behavior
helm repository "concourse" with url "https://concourse-charts.storage.googleapis.com/" is missing
I add it manually inside jcr of fe int

**Comment by poblin-orange** [comment]
manual step to add for v46 release note (feature-bumps-for-v46)

**Comment by obeyler** [comment]
As we found a way to create new configuration process this can be close as soon as jcr new deployment will be deployed

**Comment by poblin-orange** [comment]
ok with JCR 1.7 (close when merged)
