### ISSUE TITLE
mariaDB service plan evolutions and needs

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#698]
### Expected behavior
As a service user, i need the mariaDB service plans to be relevant regarding my needs and ensure an evolution.
The purpose is to take into account the customers test and usage feed backs.

### Observed behavior
pre-requisit:
flavors evolution:
https://github.com/orange-cloudfoundry/paas-templates/milestone/15

For all already exiting plans:
parameters evolution:
Tmp_table_size : rise from 16MB to 32MB
Max_heap_table_size: rise from 16MB to 32MB

PLAN MODIFICATIONS
small plan:
flavor from 4GB RAM/1CPU to 4GB RAM/2CPU
max_connections from 100 to 70

large plan:
flavor from 8GB RAM/2CPU to 12GB RAM/2CPU
max_connections from 250 to 200

NEW PLAN:
medium_big_request:
Dedicated MariaDB Galera Cluster 33GB data storage with 8GB RAM/2CPU
max_connections :15 for few users
Tmp_table_size : 256MB for complex sql requests
Max_heap_table_size: 256MB for complex sql requests

**Comment by poblin-orange** [comment]
merged for v46.0.0
