### ISSUE TITLE
containerd config issue

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#700]
### Observerd  behavior

`time="2020-02-20T08:47:41.345483338Z" level=error msg="StopPodSandbox for \"be6f5a9e94e583b428ff687dfc3af2d8ed457a5887018f028a94f4f896a6d356\" failed" error="failed to destroy network for sandbox \"be6f5a9e94e583b428ff687dfc3af2d8ed457a5887018f028a94f4f896a6d356\": invalid version \"\": the version is empty"`

**Comment by obeyler** [comment]
https://github.com/containerd/containerd/issues/4012

**Comment by poblin-orange** [comment]
PR cloudfoundry-incubator/kubo-release#377 merged

**Comment by obeyler** [comment]
Still waiting new CFCR release

**Comment by poblin-orange** [comment]
Remaining issue:
- [ ] monit dependency of kubelet jobs with docker jobs. Must be configurable to be able to switch docker with containerd

**Comment by poblin-orange** [comment]
fixed in v46. waiting for inclusion in community cfcr
