### ISSUE TITLE
micro-bosh recreation failed on docker-bosh-cli whith not enough space to download stemcell/bosh release

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#702]
### Expected behavior
Micro-bosh recreation needs space to download stemcells and bosh releases on file system.
Script `admin/recreate-micro-bosh.sh` which uses bosh create-env identify a directory whith enough space to download components.

### Observed behavior
Target directory for vsphere bosh downloads is defined on `BOSH_PERSISTENT_DIR="/images/bosh"` (used for vsphere jumpbox only).
"/images/bosh" which is associated with "/" file system on docker-bosh-cli is not enough to download components, so micro-bosh recreation failed.

### Affected release
Reproduced on version 44.0.5/45.0.3

**Comment by poblin-orange** [comment]
merged for v46.0.0
