### ISSUE TITLE
v45.0.3 update script fetches last merge commits from next version

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#703]
### Expected behavior

As a paas-templates operator, when installing the v45.0.3 version, I expect the pushed commits to match the v45.0.3 tag 

### Observed behavior

As a paas-templates operator, when installing the v45.0.3 version, I the latest merged commits from the next version get deployed

publish-paas-template-into-local-gitlab-pipeline.sh by default updates paas-templates to the latest version

https://github.com/orange-cloudfoundry/paas-templates/blob/76da8377eb56b283bb3c7b938489cac495facd73/upgrade/publish-paas-template-into-local-gitlab-pipeline.sh#L8-L9

https://github.com/orange-cloudfoundry/paas-templates/blob/76da8377eb56b283bb3c7b938489cac495facd73/upgrade/publish-paas-template-into-local-gitlab-pipeline.sh#L74-L80

```
# upgrade/scripts/common.sh
update_paas_templates(){
    update_git_repo "$HOME/bosh/template"
}
update_git_repo(){
    local repo=$1
    echo "Updating $repo"
    git --git-dir=${repo}/.git --work-tree=${repo}/ pull --rebase --all
    if [[ $? != 0 ]] ; then
        echo "ERROR: failed to update repo"
        git --git-dir=${repo}/.git --work-tree ${repo}/ status
    fi
}
```

### Workaround

Specify -g option to the script

    ```bash
    cd ~/bosh/template/upgrade
    ./publish-paas-template-into-local-gitlab-pipeline.sh -g # tag version is determined using meta-inf.yml, check script option to override
    ```
### Affected release

Reproduced on version 45.0.3

**Comment by o-orand** [comment]
In v46, we keep automatic update of `secrets` repository, (it is still possible to disable this check using `-g`). But we disable `paas-templates` automatic update, (it is possible to force this update using `-u`, see `-h`for details).
To avoid this, we also changed our release pipeline to ensure release metadatas are accurate after a new release.
