### ISSUE TITLE
VPC peering access failure to osb services - missing openstack secgroups for external osb consumers

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#705]
### Expected behavior
As a platform runner, i expect the osb services to be consumed from external client platform (not just paas-templates embedded cloudfoundry)

### Observed behavior
On v45, miss openstack security group to enable remote consumption
- shared service (mysql-osb, rabbit 3.7, redis)
- dedicated services

NB: problem VIP vrrp access issues through vpc peering
- port level security group. not enough
- VPC peering SDN incompatibility. vip IP not announced through VPC peering  ? Might require Flexible Engine Virtual IP ? see https://github.com/cloudfoundry/bosh-openstack-cpi-release/pull/98#issuecomment-529407506 and background documented at https://bosh.io/docs/openstack-vrrp/

cc @pdechamboux

**Comment by gberche-orange** [comment]
VPC peering SDN problems as possibly related to https://github.com/orange-cloudfoundry/paas-templates/issues/556

**Comment by poblin-orange** [comment]
merged for v46
