### ISSUE TITLE
Lacking diagnostic support for failed compilation vms

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#706]
### Expected behavior

As a paas-templates operator, in order to troubleshoot failed compilation, I need to be able to apply the compilation troubleshooting guide documented at https://bosh.io/docs/tips/#unreachable-agent

> This problem can occur due to:
>
>    blocked network connectivity between the Agent on a new VM and NATS (typically the Director VM)
>    bootstrapping problem on the VM and/or wrong configuration of the Agent
>    blocked or slow boot times of the VM
>
>It's recommended to start a deploy again and SSH into one of the VMs and look at the Agent logs while the Director waits for VMs to become accessible. See director.debug.keep_unreachable_vms property to let Director know to leave unreachable VMs for easier debugging.

### Observed behavior

When compilation fail with

```
Task 1181745 | 14:17:05 | Preparing deployment: Preparing deployment (00:00:03)
Task 1181745 | 14:17:08 | Preparing deployment: Rendering templates (00:00:06)
Task 1181745 | 14:17:14 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 1181745 | 14:17:14 | Compiling packages: nginx_prometheus/f48d2bc8e39ca3c9494abe5694e9bdd366a09c2e0698ff8660cef8526d3b3e01
Task 1181745 | 14:17:14 | Compiling packages: grafana_jq/98639c4a59240b5c02386dfcd958aaddb63d46bd63bb8ead8275f1521f62c3e4
Task 1181745 | 14:17:14 | Compiling packages: grafana_plugins/c2462f379ede74946be3c7e5aa5670979cb8eed8cd0df75de32612441e0b086a
Task 1181745 | 14:18:36 | Compiling packages: grafana_jq/98639c4a59240b5c02386dfcd958aaddb63d46bd63bb8ead8275f1521f62c3e4 (00:01:22)
Task 1181745 | 14:19:29 | Compiling packages: nginx_prometheus/f48d2bc8e39ca3c9494abe5694e9bdd366a09c2e0698ff8660cef8526d3b3e01 (00:02:15)
Task 1181745 | 14:28:17 | Compiling packages: grafana_plugins/c2462f379ede74946be3c7e5aa5670979cb8eed8cd0df75de32612441e0b086a (00:11:03)
                     L Error: Timed out pinging to 6618007d-df80-40d1-ac1e-4fc87a042b51 after 600 seconds
Task 1181745 | 14:28:37 | Error: Timed out pinging to 6618007d-df80-40d1-ac1e-4fc87a042b51 after 600 seconds
```

The compilation vms are lacking configuration of vcap password to connect from Iaas console interactive password

https://bosh.io/docs/cloud-config/#compilation
> env [Hash, optional]: Same as env for instance groups.

https://bosh.io/docs/manifest-v2/#instance-groups
```
 env [Hash, optional]: Specifies advanced BOSH Agent configuration for each instance in the group. Read more about the agent.
    bosh [Hash, optional]:
       password [String, optional]: Crypted password for vcap/root user (will be placed into /etc/shadow on Linux).
       authorized_keys [String, optional]: Public key for the vcap user, will be placed in .ssh/authorized_keys. This value can be used to enable SSH access onto VMs in this instance group.
       keep_root_password [Boolean, optional]: Keep password for root and only change password for vcap. Default: false.
```

In addition, the bosh-director may need to have [director.debug.keep_unreachable_vms](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p=director.debug.keep_unreachable_vms) property enabled

This is available in paas-template/micro-depls/bosh-master/template/0-debug-operators-disabled.yml

```yaml
#--- Keep unreachable vms in order to ease debugging
- type: replace
  path: /instance_groups/name=bosh/properties/director/debug?
  value:
    keep_unreachable_vms: true
```` 

### Affected release

Reproduced on version 45.x

**Comment by poblin-orange** [comment]
0-debug-operators-disabled.yml was designed for that purpose. We can activate it with COA 4.3 new profile support (including defining vcap password on cloud-config)

**Comment by poblin-orange** [comment]
TODO:
- [ ] use COA profile to activate director levels per operator
  - 99-debug-master-depls
  - 99-debug-ops-depls
  - 99-debug-coab-depls
  - 99-debug-kubo-depls
  - 99-debug-remote-r2-depls
  - 99-debug-remote-r3-depls
NB: + bosh deploy on directors (no COA level triggering)

- [ ] define compilation pool level vm password
- [ ] add global password secrets + credhub seeding
NB: + bosh update-cloud-config on root deployments + bosh deploy of xx-depls target.

**Comment by poblin-orange** [comment]
first version merged for v46

**Comment by ogrand** [comment]
Introduced with v46 profile management (99-debug-xxx-depls), which integrate `shared-operators/bosh/0-debug-operators.yml` operator
