### ISSUE TITLE
v45 update-pipeline should not disable coab-depls models deployments (breaks coab broker consistency checks)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#708]
### Expected behavior

As a paas-templates operator on vsphere, I expect dedicated services to have passing green smoke tests

### Observed behavior

Coab smoke tests fail with

```
OUT com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.DeploymentException: Model deployment directory doesn't exist at: /home/vcap/tmp/paas-secrets-clone-3606226123705912259/coab-depls/cf-mysql
```

The upgrade pipeline disables all coab deployment models

https://github.com/orange-cloudfoundry/paas-templates/blob/76da8377eb56b283bb3c7b938489cac495facd73/upgrade/releases/v45.0.0/10-pre-upgrade/vsphere/00-enforce-deployment-activations.rb#L91-L99

When the coab-depls/coab-depls-bosh-generated/approve-and-delete-disabled-deployments/30 build passes, it displays

```
Cleanup deployment cf-mysql
Deleting cf-mysql directory as it is empty
````

Then the coab broker (cf-ops-automation-bosh-broker-0.29.0.jar) consistency check fails

See coab [0.29.0 release](https://github.com/orange-cloudfoundry/cf-ops-automation-broker/releases/tag/v0.29.0) which in https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/203 
> Remove checks on meta.yml and secrets.yml files

/CC @skortobi @JCL38-ORANGE @o-orand 

### Workaround

Add a marker file in each coa deployment model secrets deployment to prevent the removal of the directory by approve and delete

### Affected release

Reproduced on version 45.0.3

**Comment by o-orand** [comment]
Fixed on v46, upgrade-v46(deployment-activations): allow coab deployemnts on vsphere (cf-mysql, mongodb, noop and redis)
