### ISSUE TITLE
Support CF CLI Variable Substitution when authoring CF-apps in paas-templates

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#71]
### Expected behavior
As a paas-template author, I want to leverage up to date manifest syntax construct for cf-apps deployments.

* [x] upgrade cf (#83), requires CLI 6.38
* [ ] update CF CLI in COA docker image (https://github.com/orange-cloudfoundry/cf-ops-automation/issues/188)
* [x] update CF CLI in docker bosh-cli

### Observed behavior

- The cf-apps automation emits warning with legacy attributes uses (ie: domains, ...)
- I have to rely on spruce syntax, and not cf cli variable substitution syntax 

### Affected release

Reproduced on version 28

## references

- CF CLI v6.37.0 Released Today: Variable Substitution. https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests and https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#route-attribute

## Solution outline

- [ ] bump cf cli version in cf-ops-automation. align pipeline generation mechanism with variable substitution
- [ ] refactor all cf-apps deployment to use variable substitution instead of spruce templating

**Comment by o-orand** [comment]
cf-cli in bosh-cli is `cf version 6.41.0+dd4c76cdd.2018-11-28`

**Comment by ogrand** [comment]
cf cli updated in 6.44.1 in docker-bosh-cli
