### ISSUE TITLE
use bosh dns facilities between shield server and shield agent on dedicated services

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#711]
### Expected behavior
bosh dns facilities must be used between shield server and shield agents in order to communicate at provisioning time and during backup/restore operations

### Observed behavior
the communication between shield server and shield agents is using ops routing 

Reproduced on version x.y
v40+

**Comment by gberche-orange** [comment]
Background: 
shield server to shield agent communication differ depending on the type of interactions:
* control plane interactions (registration of agent,  jobs) through REST API go through TLS
* data plane interactions (core asking agents for backup command executions) go through ssh, see related intro and planned evolution https://github.com/shieldproject/notebook/blob/master/proposals/active-ssh-fabric.md

**Comment by JCL38-ORANGE** [comment]
Merged in v46
