### ISSUE TITLE
use FQDN for bosh directors

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#712]
### Expected behavior
bosh director certificates must be generated with an alternative name including FQDN (bosh-xxx.internal.paas)

### Observed behavior
bosh director certificates are generated with an alternative name without their FQDN (only IP)

Limitations we want to adress:
- COA config currently reference bosh directors by IP (including dig resolution to translate to IP)
- can not benefit from bosh create-swap-delete on directors
- can not set HA active/passive patterns on directors (direct access from directors client and bosh agents). #364

### solution outline/impact
regenerate certificates (director_ssl) with a FQDN alternative name 

- [ ] micro-bosh bootstrap cert generation
- [ ] bosh-xxx credhub cert generation
- [ ] reconfigure CPI let let bosh agents use FQDN
- [ ] sync COA evolution 

### Affected release
v40+

### Traces and logs
bosh login -e bosh-xxx.internal.paas
Fetching info:
  Performing request GET 'https://bosh-xxx.internal.paas:25555/info':
    Performing GET request:
      Retry: Get https://bosh-xxx.internal.paas:25555/info: x509: certificate is not valid for any names, but wanted to match bosh-xxx.internal.paas
Exit code 1
oorand@fe-int:~$ curl https://bosh-xxx.internal.paas:25555/info
curl: (51) SSL: no alternative certificate subject name matches target host name 'bosh-xxx.internal.paas'

**Comment by gberche-orange** [comment]
relates to #364
