### ISSUE TITLE
separate install element inside each cfcr

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#713]
### Expected behavior
be able to install/remove specific product instead have all product inside cfcr-addon
so on 

create for micro
- cfcr-gitlab
- cfcr-concourse
create for master 
- cfcr-grafana
- cfcr-openldap
- cfcr-metabase
create for serv
- ...
for all cfcr
- cfcr-addon will apply : traefik, openebs, elk, falco, fluentd, prometheus

**Comment by poblin-orange** [comment]
split as COA deployment merged for v46
