### ISSUE TITLE
cf / k8s shared marketplace

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#72]
### Expected behavior
As a platform operator, i want to be able to have a shared marketplace for cloudfoundry, kubo, and compatible OSB clients (e.g. Openshift or vanilla 3rd party K8S deployments using service cat)

Depends on #93 and https://github.com/orange-cloudfoundry/cf-ops-automation/issues/101 and COAB K8S support

### Observed behavior

* The marketplace is built in, only accessible from private zone. 
* Network security based on cf ASG. 
* Inventory based on Cloudfoundry

### Affected release

Reproduced on version x.y

### Traces and logs

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

### references
- https://schd.ws/hosted_files/cfseu18/75/service-manager-cf-summit-eu-2018.pdf
- https://github.com/Peripli/service-broker-proxy
- https://github.com/Peripli/specification
- https://codeengineered.com/blog/2018/kubernetes-helm-related-tools/
- https://fr.slideshare.net/makingx/open-service-broker-apikubernetes-service-catalog-k8sjp-90024385

### solution ouline

- [X] install kubo
- [X] inside kubo, set up service catalog
- [ ] deploy peripli service manager, as a docker bosh deployment, exposed on ops domain
- [ ] deploy peripli proxy for cf
- [x] deploy peripli proxy for k8s in cfcr
- [ ] publish a saas osb api (eg: azure service broker) with service manager. Check the services get exposed in bosh cfar and cfcr

**Comment by obeyler** [comment]
need MR https://github.com/Peripli/service-broker-proxy-k8s/pull/44

**Comment by gberche-orange** [comment]
As of July 2019, peripli is only support central registration of brokers in a single point, which in turns register into multiple osb clients (CF or K8S). It does not yet have an inventory of service instances
* https://github.com/Peripli/service-manager/blob/master/docs/usage/walkthrough.md current feature supported
* https://github.com/Peripli/service-manager-cli/blob/master/docs/README.md current service operator cli

Future peripli version are planning to much extend its scope
* https://github.com/Peripli/specification/blob/sm-ops/api.md (i.e. the `sm-ops` branch)
> The Service Manager API defines a REST interface that allows the management of Platforms, Service Brokers, Service Offerings, Service Plans, service instances and service bindings from a central place. The Service Manager API can be split into three groups:
>
> -   A Service Manager Admin API to manage Service Brokers and attached Platforms.
> -   A Service Controller API that allows the Service Manager to act as an OSB Platform for Service Brokers that are registered in Service Manager ("Service Manager as a Platform").
> -   An OSB API which allows the Service Manager to act as a Service Broker for Platforms that are registered in Service Manager ("Service Manager as a Broker"). The latter implements the Open Service Broker (OSB) API.

The `Service Controller API` plans to include the inventory management features, such as:
* [list/find service instances](https://github.com/Peripli/specification/blob/52bf39f7de453e26abd31607caddd3c65a9a2e5b/api.md#listing-service-instances) with a sophisticated [querying/filtering language](https://github.com/Peripli/specification/blob/52bf39f7de453e26abd31607caddd3c65a9a2e5b/api.md#listing-all-resource-entities-of-a-resource-type) based on entity fields and labels
  * [Labels](https://github.com/Peripli/specification/blob/52bf39f7de453e26abd31607caddd3c65a9a2e5b/api.md#labels-object) are assigned to 
      * osb client platforms when [registering](https://github.com/Peripli/specification/blob/52bf39f7de453e26abd31607caddd3c65a9a2e5b/api.md#registering-a-platform)/updating  them, 
      * service brokers when [registering](https://github.com/Peripli/specification/blob/52bf39f7de453e26abd31607caddd3c65a9a2e5b/api.md#registering-a-service-broker)/updating them
* [list/find service bindings](https://github.com/Peripli/specification/blob/52bf39f7de453e26abd31607caddd3c65a9a2e5b/api.md#listing-service-bindings)

Other features such as:
* service quotas (i.e. enforcing quotas for certain platforms or subentities within these platforms such as CF org/space or K8S namespaces) are not yet planned. See related #264 
* enforcing permissions on OSB api calls w.r.t. service visibility. See related [Auth section](https://github.com/Peripli/specification/blob/52bf39f7de453e26abd31607caddd3c65a9a2e5b/api.md#authentication-an-authorization)
> This specification does not define any permission model. Authorization checks are Service Manager implementation specific. [...]

**Comment by gberche-orange** [comment]
closed with https://github.com/orange-cloudfoundry/paas-templates/issues/492
