### ISSUE TITLE
Prometheus scrape error on concourse db

### ISSUE THREAD

**Issue by JSimon-Orange** [orange-cloudfoundry/paas-templates#720]
### Expected behavior
As an platform operator, i want prometheus to not raise an alarm when component are running fine

### Observed behavior
We observe a Prometheus Scrape Error on Alert Manager because Prometheus failed to scrape the exporter of Concourse db.

The Concourse DB instance use a dynamic network adresse and the prometheus scrape operator fetch a static IP. 

 
### Affected release
45.0.3

**Comment by poblin-orange** [comment]
merged for v46
