### ISSUE TITLE
mariadb binlog backups

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#721]
### Expected behavior
As a platform runner, in order to improve RPO, i need backup for binlogs

### Observed behavior
Only shield based full backup

**Comment by ldangeard-orange** [comment]
Pas implémenté dans release cf-mysql / shield et cela me parait très complexe, avec beaucoup d'opérations manuelles pour restaurer (backup + logbin +applications logbin)

Rappels :
- Les sauvegardes Xtrabackup/MariaBackup sont des FULLS et ne sauvegardent pas les binlog
- Les sauvegardes sont réalisées tous 8h à tours de rôles sur chacun des noeuds
- les binlogs sauvegardés d'un nœud ne sont applicables que sur le nœud sauvegardé
- Les binlog sont purgés par mysql à 7 jours (défaut) via `cf_mysql.mysql.binlog_expire_days` 
- Le RPO Argent/Or est de quelques minutes

Tous les N minutes et sur tous les noeuds: 
- vérifier que la sauvegarde précédente est bien terminée
- flusher pour switcher de logbin
- sauvegarder que les nouveaux logbin et pas le logbin courant

**Comment by poblin-orange** [comment]
use case covered by mysql extended
