### ISSUE TITLE
jcr upgrade/install need 2 deploy to works

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#725]
### Expected behavior
new jcr version install with only one deploy

### Observed behavior
It needs to launch twice deploy to be able to see the JCR admin ui
- work around 
launch the concourse job * 2 :-)

**Comment by o-orand** [comment]
During upgrade, Ops need to manually retrigger JCR deployment
![image](https://user-images.githubusercontent.com/976115/98356243-92934000-2023-11eb-8704-42174124ea01.png)

After bosh deploy has ended, JCR is not fully functionnal
```
failed to fetch digest for image 'docker.jcr.<my-domain>/governmentpaas/bosh-cli-v2:2857fdbaea59594c06cf9c6e32027091b67d4767': 503 Service Unavailable

does the image exist?
```
