### ISSUE TITLE
openstack - multi-region CPI. switch from default az to region az is KO

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#727]
### Expected behavior
As a platform runner, installing v46, i expect cloud-config change from default az to region-1 multi cpi, i expect existing deployment to be updatable (bosh deploy, bosh recreate)

### Observed behavior
On openstack, the az passed for vm updates is incorrect, resulting in disk mount timeout (the vm az doesnt match existing disk az).

**Comment by poblin-orange** [comment]
for v46. disable region 1 cpi to avoid regression

**Comment by poblin-orange** [comment]
rolling back no multi-cpi for z1/z2/z3 is KO

```
11:53:19
	
Task 10399523 | 09:53:17 | Preparing deployment: Preparing deployment (00:00:02)
11:53:21
	
Task 10399523 | 09:53:19 | Preparing deployment: Rendering templates (00:00:02)
11:53:21
	
Task 10399523 | 09:53:21 | Preparing package compilation: Finding packages to compile (00:00:00)
11:53:21
	
Task 10399523 | 09:53:21 | Error: AZ 'z1' must specify a CPI when CPI config is defined.

```

**Comment by poblin-orange** [comment]
issue not reproduced on vpshere integration

**Comment by poblin-orange** [comment]
cant reproduce on vpshere.

**Comment by ogrand** [comment]
**Workaround**
```
switch <deployment>
bosh manifest > <deployment>.yml
bosdh deploy  <deployment>.yml --recreate --fix
```
