### ISSUE TITLE
stratos v3

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#728]
### Expected behavior
https://github.com/cloudfoundry/stratos/releases/tag/3.0.0

### Observed behavior
v46 is stratos v2

**Comment by poblin-orange** [comment]
stratos npm build requires 8Go memory (exceed concourse capacity)

**Comment by poblin-orange** [comment]
target k8s runtime

**Comment by gberche-orange** [comment]
@poblin-orange not sure whether this is related (or linked to cf deployment bump) but the log stream remains empty on the integration environement.

![image](https://user-images.githubusercontent.com/4748380/92010218-d6c74300-ed49-11ea-9994-c2cfdd72c553.png)
