### ISSUE TITLE
dedicated services backups must be monitored

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#737]
### Expected behavior
dedicated services backups must be monitored

### Observed behavior
dedicated services backups are not monitored

### Affected release
v45

**Comment by poblin-orange** [comment]
Seems the prometheus support wont be fixed upstream.
Could leverage shield api / cli to generate a metrics file, served as static file (nginx eg). try to leverage existing grafana dashboard

**Comment by poblin-orange** [comment]
@gcordierOrange do you want to contrib on this scenario with static file + nginx ?

**Comment by gcordierOrange** [comment]
> @gcordierOrange do you want to contrib on this scenario with static file + nginx ?

Why not, but why don't use the static file + node exporter ? In my opinion, it is more simple (the communication with prometheus is already done)

**Comment by poblin-orange** [comment]
We are starting to move the control plane to k8s. Shield CLI/REST API will still be available. Node exporter is bosh specific, probably wont be accessible after k8s migration.

**Comment by gcordierOrange** [comment]
I understand the final goal. 
An better solution is to develop a "stand alone" exporter with is own http server.
Each metric scrabe  query the shield db and return the result.

But my use case is to monitor the coab shield backup.
Actually the coab use bosh and I need some bosh information like deployment name.
Use node exporter add easily this information, which could be useful for linking the backup with the instance.
