### ISSUE TITLE
delete deployment doesn't remove associated K8S resources

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#740]
### Expected behavior
when deleting a K8S deployment install with helm-kubectl-bosh release  the object K8S and helm chart created by this deployment should be removed

### Observed behavior
K8S object and helm chart are not removed from K8S server

### Affected release
46
see https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease/issues/13
Reproduced on version x.y

**Comment by obeyler** [comment]
https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease/issues/13

**Comment by obeyler** [comment]
fix in 47

**Comment by poblin-orange** [comment]
merged for v47
