### ISSUE TITLE
add k8S operator - crunchy/zalando

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#745]
### Expected behavior
The crunchy operator is currently install by ansible
They plan to offer a docker image to package ansible install
see https://github.com/CrunchyData/postgres-operator/releases/tag/v4.3.0-beta.2

### reference
- comparison of k8s operators https://blog.flant.com/comparing-kubernetes-operators-for-postgresql/

**Comment by poblin-orange** [comment]
TBC: list the cfcr features required (typically missing / to adapt on other in house k8S impl)

**Comment by poblin-orange** [comment]
crunchy operator possible architecture

![k8s public lb](https://user-images.githubusercontent.com/5381793/83858576-00f27000-a71d-11ea-94eb-480b70658a91.jpg)
