### ISSUE TITLE
Concourse inside k8s

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#749]
### Expected behavior
Concourse inside CFCR doesn't work anymore
### Observed behavior
Concourse failed has soon as user log either by ldap or by local user with blank screen
http 401 in network exchange
![image](https://user-images.githubusercontent.com/23224162/78978412-00bd6600-7b1a-11ea-8237-9637b017e2b0.png)

### Affected release
46
Reproduced on version x.y

**Comment by poblin-orange** [comment]
see issue trying to bump concourse helm chart https://github.com/concourse/concourse-chart/issues/103
