### ISSUE TITLE
SvCat (K8S service catalog) in k8s

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#751]
### Expected behavior

* As an osb-cmdb contributor
* In order to perform K8S support end-to-end-test (see https://github.com/orange-cloudfoundry/osb-cmdb-spike/issues/17)
* I need to be able to register osb-cmdb in svcat, and create service instance, service binding in svcat, and assert provisionned secrets
   * Svcat server side installed in cfcr
   * Svcat cli installed in bosh-cli

* As a paas-templates service author packaging service in K8S
* In order to leverage services from the bosh/VM based services
* I need to use service catalog to provision OSB service instance/bindings, including svcat cli https://github.com/orange-cloudfoundry/orange-cf-bosh-cli/issues/64

### references
- https://github.com/kubernetes-sigs/service-catalog/issues/2819
- https://kubernetes-sigs.github.io/service-catalog/

### Observed behavior

* Svcat is missing from paas-templates
* Manual testing is performed against orange openshift 3.9 (see https://github.com/orange-cloudfoundry/osb-cmdb-spike/issues/17)

Relates to #72

### Affected release

Reproduced on version 46.x

**Comment by obeyler** [comment]
svc-cat will arrive inside k8s-serv

**Comment by poblin-orange** [comment]
=> should use k8s-master to host service catalog, configured to consume osbcmd-x (must declare a dedicated client platform for k8s-master)

**Comment by obeyler** [comment]
https://github.com/orange-cloudfoundry/paas-templates-private/pull/91

**Comment by obeyler** [comment]
Service catalog project doesn't release since this summer. One of my Pr is merged (but not present in last release) is mandatory.
A workaround is to create a fork to be able to release. need to be discussed
see also that by example kubeapps has removed the support of service catalog they now bet on operator.

**Comment by poblin-orange** [comment]
options:
1 - fork helm chart on github + expose github as helm charts + proxy with micro-depls/jcr
2 - inline the helm chart in paas-templates.

**Comment by obeyler** [comment]
link https://github.com/kubernetes-sigs/service-catalog/issues/2849

**Comment by obeyler** [comment]
Service catalog is released 0.3.1
