### ISSUE TITLE
director-pull-bosh-releases

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#756]
# bosh director pull bosh releases

## Status

> What is the status, such as proposed, accepted, rejected, deprecated, superseded, etc.?

proposed

## Context

> What is the issue that we're seeing that is motivating this decision or change?

* https://github.com/orange-cloudfoundry/cf-ops-automation/issues/264 Refactor offline bosh release management
* Compiled bosh releases

## Decision

> What is the change that we're proposing and/or doing?

Moving 
* from a push model, where coa uploads source bosh releases to bosh directors during bosh deployments
* to a pull model, where bosh director pulls source bosh releases when missing during a bosh deployment

The source of truth for bosh release versions remains in the [x-depls-versions.yml](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/master/docs/reference_dataset/template_repository/hello-world-root-depls/hello-world-root-depls-versions.yml) file
   * source release SHA1 gets optionally added by authors in `x-depls-versions.yml`
   
COA performs bosh manifest transformation (possibly by generating a bosh operation file) to replace version of each managed release with content specified in `x-depls-versions.yml` according to:
* bosh source release url form https://bosh.io/docs/release-urls/ specified in https://bosh.io/docs/manifest-v2/#releases
* bosh compiled release specified in https://bosh.io/docs/locking-compiled-releases/#usage

## Consequences

> What becomes easier or more difficult to do because of this change?

Easier:
  * Removed S3 resource holding release TGZ in bosh deployment pipelines. Implies hardward resource gains, and improved concourse pipelines UX
  * Bosh director can still download bosh release source code when/if a compiled release is missing
  * Avoids race condition and associated workaround for uploading bosh releases to directors

**Comment by poblin-orange** [comment]
applied as of v48, with COA 5 release management

**Comment by gberche-orange** [comment]
@o-orand do you confirm bosh director is now pulling bosh releases from their url in the deployment manifest ?

I'm confused because I still see generated pipeline load release tar.gz for use by the concourse bosh release resource

![image](https://user-images.githubusercontent.com/4748380/97230398-22dab500-17da-11eb-9bc5-af70e3d68e45.png)

![image](https://user-images.githubusercontent.com/4748380/97230438-34bc5800-17da-11eb-926c-f4d34e09fa6e.png)

@poblin-orange did you mean instead that https://github.com/orange-cloudfoundry/paas-templates/issues/757 is applied as of v48, with COA 5 release management

**Comment by o-orand** [comment]
@gberche-orange currently COA 5 still use push mechanism. But no bosh-release are uploaded during bosh deploy. Theses resources are used to detect changes on bosh-releases version.
