### ISSUE TITLE
Use samples from cloudfoundry-samples instead of swisscom samples

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#76]
### Expected behavior
We should consider to replace our samples by [cloudfoundry-samples](https://github.com/cloudfoundry-samples/) referenced in the [Cf buildpack documentation](https://github.com/cloudfoundry/docs-buildpacks/search?q=cloudfoundry-samples%2F&unscoped_q=cloudfoundry-samples%2F) and tested by the buildpacks team CI (see https://www.pivotaltracker.com/story/show/128896127) . It seems that we can find more samples.

### Observed behavior

Our sample apps complement cf smoke and cf acceptance tests.

### Affected release

Reproduced on version v30 and before

**Comment by poblin-orange** [comment]
close, wont fix
