### ISSUE TITLE
Github Private repo for paas-templates contribs

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#765]
## Status

> What is the status, such as proposed, discussed, accepted, rejected, deprecated, superseded, etc.?

discussed

Waiting on spike GH "Assess" #766 

## Context

> What is the issue that we're seeing that is motivating this decision or change?

* Need to be able to cross reference paas-templates public issues in related contributions
* Need to automatically close GH issues when related contributions are merged
* Need to automate release notes content from PR content
* Need to leverage "automated rebase" of branches before merging.

## Decision

> What is the change that we're proposing and/or doing?

* fe-dev/preprod/prod platforms don't get any changes

For integration env:
* Copy gitlab-fe-int/paas-templates over to https://github.com/orange-cloudfoundry/paas-templates-private
  * switch gitlab-fe-int/paas-templates read-only
   * only accept contributions as Pull Requests on paas-templates-private (although unable to enforce protected branch with github free)
   * migrate MR template to PR template
   * current MR migrated to PR (50 opened)
   * PRs will be used to generate automatically release notes, e.g. with https://github.com/github-changelog-generator/github-changelog-generator
* github.com/orange-cloudfoundry/paas-templates-private does not accept issues 
* disallow PRs and pushes on github.com/orange-cloudfoundry/paas-templates (public) other than from coa user as to avoid human errors and triggering leaks

Potentially for a future ADR 
* Gitlab-fe-int/paas-templates get a restricted list of branch which can be pushed to. Relates to https://github.com/orange-cloudfoundry/cf-ops-automation/issues/62
   * wip branch 
   * coab service instance branches

## Consequences

> What becomes easier or more difficult to do because of this change?

Easier:
* Less load on gitlab fe-int, implies less errors 
* Automated github issue closing + cross reference
* Automated release notes generation from github PRs
* Automated branch rebase
* Provides access to Saas tooling working on github private repos (TBC)

More Difficult (ordered by risk, higuest risk first, lowest risks last):
* More traffic to internet on integration platform for git clone/ git push
   * github rate limiting ? Assuming no rate limit on github git traffic according to https://github.community/t5/GitHub-API-Development-and/Git-clone-limits-using-git-commands-vs-the-API-what-are-they/td-p/33623
   * internet proxy scalability limits (proxy usage should be less than when docker images were downloaded)
* Slightly more risks that a loss of a github account leaks sensitive information from paas-templates-private. Mitigated with
   * Restrict paas-templates-private with a team with 2FA enables accounts
   * Be careful when granting apps access to paas-templates-private (circle ci/travis/coverity)

* Potential restrictions from usage of github free https://github.com/pricing
   * paas-templates/develop is not protected against force pushes: github free does not allow protected branch on private repos.
      * human errors on default branch (develop) is possible
* ultimately requires operators to learn about multi remotes in their git clone: 
   * gitlab-fe-int to check wip-merge branch
   * github-paas-templates-private to submit feature branches

* Potential security governance risks even though paas-templates repo should not contain sensitive data
* Conflicts with integration platform offline strategy unless the current local gitlab clone is preserved.

**Comment by poblin-orange** [comment]
applied with v46
