### ISSUE TITLE
MySQLdExporterScrapeError on mysql shared

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#769]
### Expected behavior

* As a paas-templates operator 
* In order to collect mysql metrics from mysqld_exporter from the shared instane
* I need to have a result OK from the exporter with all the metics

### Observed behavior
I get a alert : MySQLdExporterScrapeError for instance shared
Sometimes, The next pooling is ok and the alert disapers
 
### Affected releases
* 45.0.3
* earlier versions

### Traces and logs
into : /var/vcap/sys/log/mysqld_exporter/mysqld_exporter.stderr.log
time="2020-04-22T13:14:50Z" level=debug msg="collect query: []" source="mysqld_exporter.go:193"
time="2020-04-22T13:14:50Z" level=debug msg="Query response time distribution is not present." source="info_schema_query_response_time.go:125"
time="2020-04-22T13:15:04Z" level=error msg="**Error scraping for collect.info_schema.tables: context deadline exceeded**" source="exporter.go:171"
time="2020-04-22T13:15:20Z" level=debug msg="collect query: []" source="mysqld_exporter.go:193"
time="2020-04-22T13:15:20Z" level=debug msg="Query response time distribution is not present." source="info_schema_query_response_time.go:125"

### bypass
We can bypass the error by disabling the collect (--no-collect.info_schema.tables), the scrape is OK

**Comment by poblin-orange** [comment]
https://github.com/bosh-prometheus/prometheus-boshrelease/pull/302

**Comment by ldangeard-orange** [comment]
I add to not `collect.info_schema.query_response_time`.
I need ro report on dedicated also

Correction in branch` feature-mariadb10-3-shared`

**Comment by JCL38-ORANGE** [comment]
merged in v47
