### ISSUE TITLE
cloudfoundry blobstore minio tuning (scale up)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#77]
### Expected behavior

* [x] improve observability of minio performance to measure response times: https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md
* [ ] benchmark minio through a scenario of "diego-cells recreation" that make mostly non-cacheable parallelized downloads. Increase load by increasing parallelization
   * [ ] confirm bottleneck (suspecting persistent disk response time, but also observed some swap spikes)
* Tune minio performance through:
   * [x]  scale out though cluster set up:
   * [ ]  ~~set up transient new members with SSD local system disks => KO, minio is not horizontally scalable once sized~~
   * [ ] define openstack server group with anti affinity rules to spread out members across distinct hypervisors

### Observed behavior

* During current diego cells recreations with max-in-flight=1 we observe approx 60% CPU wait peaks, suspecting IO limitations and degraded minio HTTP response times

### Affected release

Reproduced on version 30.0.0

**Comment by gberche-orange** [comment]
Lowering priority following cf-deployment transition and related #87

**Comment by poblin-orange** [comment]
see related #481

**Comment by gberche-orange** [comment]
see previously related https://github.com/orange-cloudfoundry/paas-templates/issues/86 `Handle cold start CC capacity issue (with undercapacity minio as a blobstore)`

**Comment by poblin-orange** [comment]
bump for v42.  still missing a framework to load the platform with representative load

**Comment by gberche-orange** [comment]
closed because targetting to K8S minio deployment
