### ISSUE TITLE
drain failure with containerd

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#777]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | paas-templates author | paas-templates maintainer
* In order to 
* I need 

### Observed behavior

```
Task 5638622 | 15:23:09 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 5638622 | 15:23:11 | Updating instance worker: worker/f532de55-5806-4f9c-b017-23b22618b36e (0) (canary) (00:10:06)
                     L Error: Action Failed get_task: Task a79418e1-23df-49c2-57dc-f2db647f1319 result: Unmounting persistent disk: Running command: 'umount /dev/vdb1', stdout: '', stderr: 'umount: /var/vcap/store: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)

```
 
### Affected releases

* x.y
* earlier versions

**Comment by obeyler** [comment]
Link with the branch feature-rook-ceph not yet inside main branch

**Comment by poblin-orange** [comment]
fixed on cfcr, but not on k8s bosh release

**Comment by poblin-orange** [comment]
Once we reach 80% disk usage, k8s switch nodes to "disk pressure", preventing proper use of storage.
In that case, bosh resizing the disk gives issues (disk busy when bosh tries to unmount the disk  due to remainging pods running after containerd bosh stop / drain).

We have to use differents items to unlock proper bosh disk resizing
- bosh stop node_persistent/0
- bosh ssh +  reboot, in order to have a fresh vm with no ghost pod
- bosh deploy -d k8s --skip-drain=node_persistent k8s-deployment-failure.yml

- use kubectl / or k9s  to cordon, then drain the node

**Comment by poblin-orange** [comment]
fixed with orange bosh release k8S https://github.com/orange-cloudfoundry/k8s-boshrelease/releases/tag/1.18.8-orange-3
