### ISSUE TITLE
Having a free mariadb shared plan

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#778]
### Expected behavior

* As a marketplace user 
* In order to use mariadb shared plan 10mb with the aerofoundry sandboox org
* I need ti have this plan free

### Observed behavior
 this plan is paid
### Affected releases
* v45
* earlier versions

Ops file for doing the job into deploiement cloudfoundry-mysql-osb :
- type: replace
  path: /instance_groups/name=broker/jobs/name=cf-mysql-broker/properties/cf_mysql/broker/services/0/plans/name=10mb/free
  value: true

**Comment by JCL38-ORANGE** [comment]
merged in v46.0.1
