### ISSUE TITLE
COA profile for external / provided k8S runtime

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#780]
### Expected behavior

* As a paas-templates operator 
* In order to use paas-templates market place with provided k8S runtime
* I need to be able to choose with a COA profile between different k8S configuration

eg:
- 10-embedded-cfcr-k8s
- 10-external-kops-k8s 
- 10-external-hws-cce-k8s
- 10-external-openshift-k8s

These profile will help capture the differences between various runtime, while keeping/sharing common marketplace control plane

### Affected releases

* x.y
* earlier versions

**Comment by obeyler** [comment]
Externalize the url of kubernetes: the Kubernetes url must be inside the passtemplate but must be read in secret to allow choise between CFCR/RKE/Metalikaas/CCE...

**Comment by poblin-orange** [comment]
@obeyler i think credentials are not enough.
Depending on target k8S, paas-templates should rely on / install:
- k8s loadbalancer (eg: CCE provides openstack LB)
- k8s storage class 
- RBAC right
...

Following the logic we have with multiple iaas, we must be able to adapt to the different context (and share the most generic / valuable control plane component with this different targets)

**Comment by obeyler** [comment]
I propose to have only 2 profiles: 
- embeded-k8s (ie look credential in credhub assuming they are created by cfcr and managed by credhub/bosh)
- external-k8s (ie look credential inside secrets)

**Comment by poblin-orange** [comment]
merged for v47
