### ISSUE TITLE
bosh_exporter failed when recreate bosh-director due to uaa jobs slow deployment

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#799]
### Expected behavior

* As a paas-templates operator I expect bosh-directors concourse jobs to  deploy without any errors.

### Observed behavior

* When first deploy ou recreate bosh-directors, uaa job start slowly and is not available for `bosh-exporter` job which try to authenticate with uaa (5 attempts in a minute)

### Affected releases

* `46.0.2` and earlier versions

### Traces and logs
 ```
[httpClient] 2020/05/26 07:40:58 DEBUG - Sending GET request to endpoint 'https://xxx.xxx.xxx.xxx:25555/info'
[httpClient] 2020/05/26 07:40:58 DEBUG - Sending POST request to endpoint 'https://xxx.xxx.xxx.xxx:8443/oauth/token'
[attemptRetryStrategy] 2020/05/26 07:40:58 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2020/05/26 07:40:58 DEBUG - [requestID=0e1c57c6-0422-4eb0-44e1-bcbc07e0764e] Requesting (attempt=1): Request{ Method: 'POST', URL: 'https://xxx.xxx.xxx.xxx:8443/oauth/token' }
[attemptRetryStrategy] 2020/05/26 07:40:59 DEBUG - Making attempt #1 for *httpclient.RequestRetryable
[clientRetryable] 2020/05/26 07:40:59 DEBUG - [requestID=0e1c57c6-0422-4eb0-44e1-bcbc07e0764e] Requesting (attempt=2): Request{ Method: 'POST', URL: 'https://xxx.xxx.xxx.xxx:8443/oauth/token' }
[attemptRetryStrategy] 2020/05/26 07:40:59 DEBUG - Making attempt #2 for *httpclient.RequestRetryable
[clientRetryable] 2020/05/20 18:05:02 DEBUG - [requestID=77b86625-d73f-4022-5182-99b2bede5948] Requesting (attempt=3): Request{ Method: 'POST', URL: 'https://xxx.xxx.xxx.xxx:8443/oauth/token' }
[attemptRetryStrategy] 2020/05/20 18:05:03 DEBUG - Making attempt #3 for *httpclient.RequestRetryable
[clientRetryable] 2020/05/26 07:41:00 DEBUG - [requestID=0e1c57c6-0422-4eb0-44e1-bcbc07e0764e] Requesting (attempt=4): Request{ Method: 'POST', URL: 'https://xxx.xxx.xxx.xxx:8443/oauth/token' }
[attemptRetryStrategy] 2020/05/26 07:41:00 DEBUG - Making attempt #4 for *httpclient.RequestRetryable
[clientRetryable] 2020/05/26 07:41:00 DEBUG - [requestID=0e1c57c6-0422-4eb0-44e1-bcbc07e0764e] Requesting (attempt=5): Request{ Method: 'POST', URL: 'https://xxx.xxx.xxx.xxx:8443/oauth/token' }
time="2020-05-26T07:41:01Z" level=error msg="Error reading BOSH Info: Fetching info: Performing request GET 'https://xxx.xxx.xxx.xxx:25555/info': 
Performing GET request: Requesting token via client credentials grant: Performing request POST 'https://xxx.xxx.xxx.xxx:8443/oauth/token': 
Performing POST request: Retry: Post https://xxx.xxx.xxx.xxx:8443/oauth/token: dial tcp xxx.xxx.xxx.xxx:8443: connect: connection refused" source="bosh_exporter.go:288"
 ```

### Potential solutions

- [x] Use bosh syntax `after` => usefull between instances, not for jobs
- [x] Use `/dev/urandom` with uaa catalina_opts to increase Random Number Generator  entropy pool seeding => already enable on bosh-directors
 ```
catalina_opts: -Xmx768m -XX:MaxMetaspaceSize=256m -Djava.security.egd=file:///dev/urandom
 ```
- [x] Look at cpu option =>  `/dev/urandom` uses software algorithm without hardware cpu flags
- [x] Increase vm vertical scaling => Vm is 4 cpu/ 8 Go which is enough on day-to-day running
- [ ] Introduce a monit dependency between `uaa` and `bosh_exporter` jobs to let `uaa` start before consuming its api
- [ ] Use `bosh-exporter` docker image instead of bosh release to easily manage scheduling
  - https://github.com/bosh-prometheus/bosh_exporter#docker

**Comment by gberche-orange** [comment]
The retry configuration is hard coded in bosh cli and thus can't be configured before launching the exporter to retry longer.

    https://github.com/bosh-prometheus/bosh_exporter/blob/1a8ba31c13e2c9144bce0b716b60a25a599afe3e/vendor/github.com/cloudfoundry/bosh-cli/uaa/factory.go#L55 
> retryClient := httpclient.NewNetworkSafeRetryClient(rawClient, 5, 500*time.Millisecond, f.logger)

**Comment by ogrand** [comment]
Solution using following items have been implemented with `bosh-remote-r2` and `bosh-remote-r3` bosh directors. Need now to extend this solution to:
* `bosh-master`
* `bosh-ops`
* `bosh-coab`

- [x] Introduce a monit dependency between uaa and bosh_exporter jobs to let uaa start before consuming its api
- [x] Use bosh-exporter docker image instead of bosh release to easily manage scheduling

**Comment by poblin-orange** [comment]
applied and merged for v47 in bosh-remote-r2 / bosh remote-r3 and bosh-coab
TODO:
- [ ] bosh-master
-  [ ] bosh-ops
