### ISSUE TITLE
update redis shared - tcpkeepalive value

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#801]
### Expected behavior

* As a paas-templates marketplace user
* In order to have the same behaviour between the redis shared and redis dedicated
* I need to have the same velue for tcpkeepalive = 300 into redis.conf 

### Observed behavior
The TCP connexion are closed unexpectedly.

### Affected releases
* 445/46
* earlier versions

**Comment by JCL38-ORANGE** [comment]
merged in v47.
