### ISSUE TITLE
embedded k8S log access for operator

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#802]
### Expected behavior

* As a paas-templates operator
* In order to operate k8s component in paas-templates
* I need a ELK access including k8s logs

### Affected releases

* 46.0.0
* earlier versions

**Comment by obeyler** [comment]
Current elastiksearch installed with kibana and fluent bit are installed on each K8S
there is still some pb : all container logs are not present. If we create an index inside Kibana and have a look about namespace, only few of them are present.
