### ISSUE TITLE
Cassandra services lack scheduled backup

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#81]
### Expected behavior

The cassandra service should have an associated shield job scheduled, just like the mysql, or redis services do.

### Observed behavior

Cassandra shared clusters don't yet back scheduled backups, where as the shield plugin support seems to be compatible with the cassandra bosh release, according to https://github.com/orange-cloudfoundry/cassandra-boshrelease/pull/28

/CC @bgandon @OMI69-orange 

### Affected release

Reproduced on version 29.5

**Comment by poblin-orange** [comment]
merge in v37
