### ISSUE TITLE
enable reduced network sizes on non prod environnement

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#812]
### Expected behavior

* As a paas-templates operator 
* In order to be able to provision paas-templates on non prod / reduced subnets size environnement
* I need to be able to configure the network specific sizing (secrets / COA profile)

### Observed behavior
Need to develop a custom environment branch to workaround  

### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
Maybe it will be closed with : 
https://github.com/orange-cloudfoundry/paas-templates/issues/969
