### ISSUE TITLE
Replace CFCR by another K8S distrib

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#816]
### Expected behavior

Bump K8S version to 18.x and leave CFCR dead project

[ ] use https://github.com/jhunt/k8s-boshrelease
[ ] use rke https://github.com/orange-cloudfoundry/rke-boshrelease

**Comment by poblin-orange** [comment]
As of v47, we choose to leverage S&W k8s bosh release for internal use (micro and master k8s).
Target still to be defined (conformance with Orange internal k8s distritribution. RKE / Openshift)
