### ISSUE TITLE
database level backup for k8S (e.g. shield in k8s / k8up / kanister+kopia )

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#820]
### Expected behavior

* As a paas-templates  author
* In order to backup k8s hosted, i need a backup solution leveraging k8s

### reference
- https://github.com/orange-cloudfoundry/helm-shield 

### Observed behavior
 
We could leveage shield helm chart

### Affected releases

* x.y
* earlier versions

**Comment by gberche-orange** [comment]
K8S master node data stored in etcd seem to require an etcd builtin backup see https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster

Quick overview of apparent opensource automation of etcd backup and restore
* coreos [etcd operator](https://github.com/coreos/etcd-operator), [docs](https://coreos.com/operators/etcd/docs/latest/user/walkthrough/backup-operator.html), [has been archived](https://github.com/coreos/etcd-operator/pull/2169)
* [Kops - Kubernetes Operations](https://kops.sigs.k8s.io/) has built in support for [etcd backup and restore](https://kops.sigs.k8s.io/operations/etcd_backup_restore_encryption/) to S3. This seems however to require installation of ectd through [etcd-manager](https://github.com/kopeio/etcd-manager). See [usage of etcd-manager within kops for etcd backup & restore](https://kops.sigs.k8s.io/operations/etcd_backup_restore_encryption/)

**Comment by gberche-orange** [comment]
Velero was integrated as part of v44. 

Currently apparently fails in v47.0.2 with restic pods failing to reach K8S API

> Get "https://10.245.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3D1ae93daf-fbbd-47bf-bf79-6d0f440d2684.k8s%2Cstatus.phase%3DRunning": Service Unavailable                         │
│ stream closed          

No backup resources are available in K8S inventory.
Since prometheus metrics are enabled, might be worth checking failed backup metrics, and set up alerting

**Comment by obeyler** [comment]
I put an issue to K8S bosh release to see if shield can be embedded inside the JHunt k8s-boshrelease.
https://github.com/jhunt/k8s-boshrelease/issues/61
note: It also can be done by etcdctl cron job.

**Comment by obeyler** [comment]
I put an issue to K8S bosh release to see if shield can be embedded inside the JHunt k8s-boshrelease.
k8s-boshrelease/issues/61
note: It also can be done by etcdctl cron job.

see result of ADR to see good chose.

**Comment by gberche-orange** [comment]
k8up is a promising operator wrapping the [restic opensource backup library](https://restic.readthedocs.io/en/stable/), identified by @poblin-orange 
   * https://k8up.io/k8up/2.5/index.html
      * https://k8up.io/k8up/2.5/about/community.html
      * > The project is sponsored by [VSHN AG](https://vshn.ch/).
   * https://github.com/k8up-io/k8up
      * https://github.com/k8up-io/k8up/graphs/contributors
        * mostly contribs from VSHN plus some others
        * 10 commits SRE at apple https://github.com/srueg
        * 7 commits https://github.com/dns2utf8
   *  https://github.com/k8up-io/k8up/discussions/467
     > It looks like something that could replace our whole prebackup pod management. It supports various methods to execute commands at various stages of a backup. For instance pre/post backup but also pre/post restore.

**Comment by gberche-orange** [comment]
Kanister is an opensource project backed by the veam major backup company as part of its commercial kasten product: https://www.kasten.io/

Kanister is focusing on custom blueprints (such as database specific data export and imports)

https://kanister.io/
https://github.com/kanisterio/kanister

https://github.com/kanisterio/kanister/blob/master/design/kanister-kopia-integration.md

> Kopia is a powerful, cross-platform tool for managing encrypted backups in the cloud. It provides fast and secure backups, using compression, data deduplication, and client-side end-to-end encryption. It supports a variety of backup storage targets, including object stores, which allows users to choose the storage provider that better addresses their needs.

https://kopia.io/

https://www.youtube.com/watch?v=hN8sn3A_oEs Kanister & Kopia: An Open-Source Data Protection Match Made in Heaven 


https://github.com/kanisterio/kanister/blob/5c2302420309a1beb5026f9039a1abc5f3021644/design/progress-tracking.md?plain=1#L139

> Currently, Kanister Functions do not utilize Kopia to perform their underlying work. Once the work to integrate Kopia into Kanister is completed, we can extract the progress status directly from the log outputs.

>Here's a sample log output of the Kopia create snapshot function:

> ```sh
> 
> $ kopia snapshot create kanister
> 
> Snapshotting isim@pop-os:/home/isim/workspace/kanisterio/kanister ...
> 
> - 5 hashing, 4186 hashed (329.1 MB), 0 cached (0 B), uploaded 309.8 MB, estimated 2 GB (16.3%) 3m38s left
> 
> ```
> 
> 
> Kanister Functions that are currently using Restic already have a set of library functions that can be used to extract progress status from the Restic logs. See e.g., the `restic.SnapshotStatsFromBackupLog()` function in
> 
> [`pkg/restic/restic.go`](https://github.com/kanisterio/kanister/blob/c5acaac88a60c22faeadd59c49b20942f662331d/pkg/restic/restic.go#L362)
>
