### ISSUE TITLE
cfcr - dns forwarding to platform dns

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#823]
### Expected behavior

* As a paas-templates author 
* In order to 
  - be able to use platform provided dns (eg: bosh-dns aliases)
* I need 
  - the k8s distro to be able to recurse/forward to bosh-dns node /etc/resolv.conf

### Observed behavior

index bosh dns are not resolved from bosh-dns daemon see upstream issue https://github.com/cloudfoundry/bosh-dns-release/issues/25

### References
- https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
- https://kubernetes.io/docs/tasks/debug-application-cluster/dns-debugging-resolution/#known-issues

- https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#example
- https://coredns.io/plugins/forward/
- https://coredns.io/plugins/hosts/

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
Using coredns plugins:
- hosts plugin, with a volume mounted from node VM /etc/hosts. This will enable director level dns lookup
- forward plugin, to resolv to platform level dns servers (as host vm /etc/resolv.conf)

```
     forward internal.paas. /etc/resolv.conf {                                                                                                                                         │
         policy sequential                                                                                                                                                             │
     }                                                                                                                                                                                 │
     hosts bosh.  /etc/hostsFromNode                                                                                                                                                   │

```

**Comment by poblin-orange** [comment]
Issue was fixed on cfcr. But same problem following migration to S&W k8s bosh release : coredns is preinstalled, with no way to override  ? @obeyler

**Comment by obeyler** [comment]
see https://github.com/jhunt/k8s-boshrelease/issues/62

**Comment by jhunt** [comment]
How did CFCR do it, @poblin-orange ?

**Comment by obeyler** [comment]
I do that by not enabling Core-dns and replacing it it by deployment of helm chart who allows to specified pluging

**Comment by obeyler** [comment]
solved by disabling core-dns inside K8S bosh release, move clusterip adress of coredns service to an unused Ip and deploy coredns by helm kubectl bosh release as an helm chart. This issue is fixed in feature-k8s-fixes-for-v48
