### ISSUE TITLE
Terraform 0.13

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#832]
### Expected behavior

* As a paas-templates operator , paas-templates author,  paas-templates maintainer
* In order to 
  - benefit from up to date terraform plugins
* I need 
  - a way to apply terraform 12 constructs

### Observed behavior
As of paas-templates v47 COA 4, only terraform 11 is available, as a COA construct

### references

- see ADR #258 (decouple terraform from COA)

### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
We can bump terraform to 0.12, in a COA version and use upgrade pipeline to convert tf_state to 0.12. I think the most difficult part is to upgrade providers, as I'm not sure all providers provide helper to ease migration.

**Comment by poblin-orange** [comment]
terraform-release 1 support bosh deployment level terraform 0.13.3.
