### ISSUE TITLE
dedicated redis -sentinel in HA mode with 3 regions

### ISSUE THREAD

**Issue by regismarg** [orange-cloudfoundry/paas-templates#839]
### Expected behavior

* As a  marketplace user 
a need a redis service available in HA mode with 2 or 3 AZ
* In order to 
be able to have a resilient service even if an AZ is down
* I need 
to keep alive and accessible my data when i lose an AZ

### Observed behavior
in an Orange France use case way, i need a solution that is resilient, using redis and sentinel
how the service  must be designed to feet a HA mode in an Orange France contexts ?

### Affected releases

* x.y
* earlier versions

**Comment by JCL38-ORANGE** [comment]
in progress for v49.
