### ISSUE TITLE
add alerting on credhub hosted certs expiration

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#84]
### Expected behavior

Any credhub-stored certificate that is close to expiration triggers a prometheus alert (this includes internal CA for CF control plane, such as diego)

Potentially, contribute a prometheus exporter which uses the credhub api to search and inspect certs for close expirations. credhub clients exist in go-lang and in java.

### Observed behavior

Only certs for external routes are currently monitored for expiration.
We also have a blackbox expoter scanning credhub.internal.paas endpoint. We could extend to all http/https internal endpoint. Still missing out of the box solution for certs like etcd/consul and https client certs

### references:
- https://github.com/orange-cloudfoundry/credhub_exporter

### Affected release

Reproduced on version from July 2018

/CC @psycofdj

**Comment by gberche-orange** [comment]
Possible 1st step is to actively monitor TLS endpoint for cert expiration

Pseudo code (potentially in Java) for credhub exporter based approach
* find all keys of type certificate
* load cert and extract expiration date
* export expiration date

**Comment by psycofdj** [comment]
would this help ? https://github.com/orange-cloudfoundry/credhub_exporter

**Comment by poblin-orange** [comment]
initial support included in v37
