### ISSUE TITLE
multi-region : hm resurector issues (policy + bosh cck issue)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#840]
### Expected behavior

* As a paas-templates operator 
* In order to 
  - be able to repair multi-region deployment like coab-depls/cf-mysql-extended

* I need 

- the bosh hm resurrector to fix vms consistently (such as vms with unresponsive agents)

### Observed behavior

- testing r3 failure (bosh stop on remote-r3-depls/00-bootstrap vpn vm)
  - bosh coab detects the remote vm connectivity issue (unresponsive vm, arbitrator)
  - bosh hm delete the unresponsive vm, and tries to recreate all arbitrators
 -  later, once vpn is restarted, bosh hm finally manages to recreate all arbitrators

- testing r2 failure (bosh stop on remote-r2-depls/00-bootstrap vpn vm)
  - bosh coab detects the remote vm connectivity issue (unresponsive vms, mysql and proxy)
  - bosh hm delete the unresponsive vm, and tries to recreate.
 -  later, once vpn is restarted, bosh hm finally fails  to recreate all mysql and proxy in R2, with a stemcell mismatch error:

```
Task 1858220 | 13:58:58 | Applying problem resolutions: VM for 'mysql/fe42cdd0-5d9a-4ba9-a533-2a73d8d0c321 (0)' missing. (missing_vm 1690): Recreate VM and wait for processes to start (00:00:01)
                     L Error: Required stemcell {"name"=>"bosh-openstack-kvm-ubuntu-xenial-go_agent", "version"=>"621.69"} not found for cpi region-2, please upload again
Task 1858220 | 13:58:59 | Applying problem resolutions: VM for 'proxy/069c57ef-a4a8-469f-9d37-84870f6bb7fc (0)' missing. (missing_vm 1693): Recreate VM and wait for processes to start (00:00:01)
                     L Error: Required stemcell {"name"=>"bosh-openstack-kvm-ubuntu-xenial-go_agent", "version"=>"621.69"} not found for cpi region-2, please upload again
T
```

### references
- upstream  bosh issue https://github.com/cloudfoundry/bosh/issues/2287

 
### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
short term:
- [ ] disable resurrection for remote r2 / remote r3. avoid vpn cascade failure. v47
- [ ] for extended services, should disable resurection. resurector-config. v48

**Comment by poblin-orange** [comment]
Possible woraround: use deploy.sh to disable resurector for mysql extended deployment.

**Comment by poblin-orange** [comment]
workaround in deploy.sh, generating resurrection-config.yml on the fly for extended (bosh update-resurrection on first, apply globally)

**Comment by JCL38-ORANGE** [comment]
### unresponsive-agent case : 
bosh -d 01-cf-mysql-extended.yml manifest > 01-cf-mysql-extended.yml
bosh deploy 01-cf-mysql-extended.yml --recreate --fix

**Comment by JCL38-ORANGE** [comment]
quickest workaround example : 
    depl="20-strimzi-kafka" ; instance="worker/4e92e0cc-1118-46a7-bfa0-8507a9b1294f"
    bosh -d ${depl} -n recreate ${instance} --skip-drain --fix

**Comment by gberche-orange** [comment]
`feature-multi-cpi-stemcell-stopgap` planned in v51.0.4 provides a partial fix for https://github.com/orange-cloudfoundry/paas-templates/issues/840 `multi-region : hm resurector issues (policy + bosh cck issue)`: coab deployments (and potentially all deployments with a director configured with stemcells from multiple cpis) can't have `bosh cloud-check`or health manager on vsphere instances, only openstack instances can be repaired.

Once this branch is applied, and bosh instances are recreated (e.g. following a stemcell bump), then the `bosh cloud-check` or health manager are successfully applied on vsphere instances but will fail on openstack instances 

A more complete non trivial fix is being worked in https://github.com/cloudfoundry/bosh/issues/2287

**Comment by gberche-orange** [comment]
FYI: potentially interesting bosh director console for interactive debugging using bosh code available at https://github.com/cloudfoundry/bosh/blob/83813f6323c07d49a3af62fcff8e6a94209fadfc/docs/director-console-debugging.md

**Comment by gberche-orange** [comment]
https://github.com/cloudfoundry/bosh/issues/2287 is now fixed, waiting for a related bosh release
* [ ] bump bosh release
