### ISSUE TITLE
Bump CF-deployment to meet CF CLI C7 min V3 API version 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#842]
### Expected behavior

* As a paas-templates paas-templates maintainer
* In order to leverage CF V7 features ( #773)
* I need Cf deployment bump to meet minimum V3 API, (cf deployment 13 or more)
   * cloudfoundry/cli#2001 CF7 marketplace fails with CF deployment version v12.42.0
   * cloudfoundry/cli#2008 Clarify supported API version for v7

### Observed behavior
 
   * cloudfoundry/cli#2001 CF7 marketplace fails with

### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
Cf-deployment 14.0.0 is out: https://github.com/cloudfoundry/cf-deployment/releases/tag/v14.0.0
This  is include changes updating certificates generation induce by Go 1.15 Certificates must have subject alternative names (SAN) that at least includes the common name. See release notes for details

**Comment by o-orand** [comment]
Cf 7 bump is included in https://github.com/orange-cloudfoundry/cf-ops-automation/pull/337.
It should be available with COA [5.1](https://github.com/orange-cloudfoundry/cf-ops-automation/milestone/19?closed=1)

**Comment by o-orand** [comment]
We have already moved to cf-deployment 13.x in v49, we are ready to move forward, see #1000 

@poblin-orange @gberche-orange I think we can close this one, as usage of cf cli v7 is already referenced by other issues (see #301 and #773 ).
