### ISSUE TITLE
multi-region - COA mixed iaas-type stemcell upload

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#843]
### Expected behavior

* As a paas-templates operator 
* In order to 
  - be able to upload multiple stemcell when targeting different iaas

* I need 
  - to be able to configure COA 4 to upload stemcells with different iaas types (eg: openstack stemcell, for remote r3 root deployment)
  - to load bosh coab with the required stemcells

### Observed behavior

with R1/R2 iaas type vsphere, R3 openstack, we configure the following override in coa/config/credentials-remote-r3-depls-bosh-pipeline.yml :

```
---
bosh-target: 192.168.99.156
bosh-username: xx
bosh-password: yy

#OVERIDE default COA stemcell and iaas type for bosh-remote-r3 (openstack)
stemcell-main-name: openstack-kvm-ubuntu-xenial-go_agent
iaas-type: openstack-hws

```

When bumping stemcell
  - the remote-r3-depls/00-bootstrap is blocked, due to missing openstack stemcell in minio-s3
  - the remote-r3 stemcell upload pipeline has uploaded the vpshere stemcell (iaas-type stemcell). The overrides in coa-config didnt manage to force openstack stemcell.

### Workaround
- Manually upload required stemcell in minio-s3 bucket and bosh-coab director:

```
#--- Get stemcell locally
proxy
STEMCELL_VERSION="1.10" ; STEMCELL_NAME="bosh-openstack-kvm-ubuntu-bionic-go_agent"
STEMCELL_TGZ=~/.bosh/downloads/bosh-stemcell-${STEMCELL_VERSION}-openstack-kvm-ubuntu-bionic-go_agent.tgz
curl https://bosh.io/d/stemcells/${STEMCELL_NAME}?v=${STEMCELL_VERSION} -L -s -o ${STEMCELL_TGZ}
ll ${STEMCELL_TGZ}
proxy

#--- Upload stemcell in minio
~/bosh/template/admin/init-mc.sh
mc cp ${STEMCELL_TGZ} minio/stemcells/bosh-openstack-kvm-ubuntu-bionic-go_agent/

#--- Upload stemcell in bosh-coab
log-bosh (select "coab" director)
bosh upload-stemcell --fix ${STEMCELL_TGZ}
rm ${STEMCELL_TGZ}
```

### Affected releases

* 47.0.2
* COA 4.3.2
* earlier versions

**Comment by poblin-orange** [comment]
Issue should be solved with COA 5 (v48) new stemcell/bosh release mechanism. An an additionnal override config will be required for pre-compile pipeline.

**Comment by poblin-orange** [comment]
possible automated workaround: use deploy.sh

**Comment by o-orand** [comment]
I think this is working with COA 5.0.3, as in v49, we didn't upload manually stemcells to bosh directors. To be confirmed by @JCL38-ORANGE

**Comment by gberche-orange** [comment]
@o-orand will be checking in v50 tests

**Comment by o-orand** [comment]
The part about specific stemcell upload for remote-r3, is handled by COA.
However, the multi-upload required by COAB multi-region mode is not supported, yet.

**Comment by o-orand** [comment]
Stating with v50.0.5, as workaround, upgrade pipeline upload openstack stemcell. But this is not handled properly.

**Comment by ogrand** [comment]
Updated workaround:

```
proxy
STEMCELL_URL=https://bosh-core-stemcells.s3-accelerate.amazonaws.com/<stemcell_version>/bosh-stemcell-<stemcell_version>-openstack-kvm-ubuntu-xenial-go_agent.tgz
TGZ_NAME=~/.bosh/downloads/bosh-stemcell-<stemcell_version>-openstack-kvm-ubuntu-xenial-go_agent.tgz
curl -SsL "${STEMCELL_URL}" > ${TGZ_NAME}
proxy

~/bosh/template/admin/init-mc.sh
mc cp ${TGZ_NAME} minio/stemcells/bosh-openstack-kvm-ubuntu-xenial-go_agent/
rm ${TGZ_NAME}
```

**Comment by o-orand** [comment]
Workaround fixed in v52, we download from bosh.io and follow redirect, instead of direct download on aws. Starting with stemcell bionic 1.13, stemcells are published on google storage (previously published on aws).

**Comment by o-orand** [comment]
Closing after been merged
