### ISSUE TITLE
HTTP routing for internal traffic only

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#846]
### Expected behavior

* As a paas-templates maintainer
* In order to route http traffic to internal workarounds without exposing it on intranet/internet (e.g. https://github.com/orange-cloudfoundry/osb-cmdb/issues/48 which fronts user-facing authN/authZ)
* I need an internal http routing layer 
   * for coab-depls workloads
   * reacheable from master-depls/cf

### Observed behavior
 
Previous fake domain *.apps.internal.paas was removed in #446

### Affected releases

* 47.0.3

**Comment by gberche-orange** [comment]
ADR session on aug 6th, 2020

# HTTP routing for internal traffic only

## Status

> What is the status, such as proposed, discussed, accepted, rejected, deprecated, superseded, etc.?

## Context

> What is the issue that we're seeing that is motivating this decision or change?

### Expected behavior

* As a paas-templates maintainer
* In order to route http traffic to internal workloads without exposing it on intranet/internet (e.g. https://github.com/orange-cloudfoundry/osb-cmdb/issues/48 which fronts user-facing authN/authZ)
* I need an internal http routing layer 
   * for coab-depls workloads (e.g. dedicated coab dashboards such as shield or grafana) 
   * reacheable from master-depls/cf (where osb-cmdb proxy would be deployed to)
   * possibly with client agent authentication to restrict clients to osb-cmdb-proxy (e.g. mTLS, or basic auth)

### Observed behavior
 
Previous fake domain *.apps.internal.paas was removed in #446
   * based on: Relay TCP + proxy protocol

bosh-dns is installed on client side (alls vms, pods on k8s on vms)
   * can be set statically (eg: dns-recursor) at bosh-dns agent deployment time
   * dynamic for same directors vms


route registrar
   * can register vm internal ips dynamically, for external expositions only (ops/api/osb, with wildcard + PKI )

gorouters
   * per isolation segment, dedicated relay (isolation segment intranet: apps-relay  - is internet, internet relay)
   * https://bosh.io/jobs/gorouter?source=github.com/cloudfoundry/routing-release&version=0.204.0#p%3drouter.isolation_segments


Also relates to https://github.com/orange-cloudfoundry/paas-templates/issues/171 `Reduce service broker endpoints visibility`

### Option 0: new isolation segment "internal" with dedicated gorouter

   * New isolation segment "internal-control-plane"
   * New non-shared domain "internal-control-plane.paas"
   * New internal relay 192.168.xx
   * New small diego cells 

Diagram exported from board https://miro.com/app/board/o9J_krEBr-4=/:
![image](https://user-images.githubusercontent.com/4748380/89550440-e7979e00-d809-11ea-863e-25df39fce94e.png)

Potentially configured to verify backing service (e.g. shield) TLS cert:

https://github.com/cloudfoundry/routing-release/blob/56f9b8630ebf785a6f7190138f61a92ab74e285d/jobs/route_registrar/spec#L94-L107
>  Gorouter will validate that the TLS certificate presented by the destination host contains this as a Subject Alternative Name (SAN).  
>     server_cert_domain_san (conditional, string, for http routes): Required if tls_port is present.                    


### Option 1: New DNS service 

   * each service VM has a "dns registrar' agent
      * consul (anynines, cf 1.x)
      * bosh-agent (with associated limitations)
      * dns client (such as dynamic DNS client)
    * each internal cf apps (e.g. coab) can't have a DNS registrar agent (their container networking IP is not routeable)
       * => configure instead container networking to make them reachable from osbcmdb
            * requires to set up container networking policies across spaces in system-domain.
            * limited to cfapps clients (e.g. concourse/prometheus is unable to reach coab brokers)


### Option 2: CF default isolation segment recurses to coab-depls bosh director dns

The default isolation segment (where system_domain org is hoste), is configured to recurse to a DNS server exposed by the coab-depl bosh director 

This is similar to pivotal mysql in which cf apps are resolving mysql proxy through bosh dns
https://github.com/orange-cloudfoundry/paas-templates/issues/716

Limitations:
   * bosh dns queries always have domain `.bosh`
      * this implies that DNS queries documented at [https://bosh.io/docs/dns/#constructing-queries](https://bosh.io/docs/dns/#constructing-queries) (e.g. `0.instance_group.network.y_zzzzzzz.bosh` 
can't be easily recursed across bosh directors, since their .bosh domain conflicts with local dns resolution
      * reexposing these queries with a distinct domain (altough [dnsmasq manual](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) does not make this obvious)  
   * except for aliases which are defined at deployment time, see https://github.com/cloudfoundry/bosh-dns-release/issues/2#issuecomment-327224553
    ```yaml
      aliases:
            _.bosh-dns-sl-cpi.bluemix.net:           [q-s0.ha-proxy.default.bosh-dns-sl-cpi.bosh]
            special_app.bosh-dns-sl-cpi.bluemix.net: [q-s0.ha-proxy222.default.bosh-dns-sl-cpi.bosh]
    ```
      * See https://bosh.io/docs/dns/#using-aliases  Defining such an alias with deployment name could address the issue.

> Jobs which provide services can be configured to be addressable via a static alias. A job that currently provides a link can be aliased directly by updating the manifest to add the alias in the provides configuration of the job. Here is an example:
> domain: 'my-custom-alias.example.com'
> domain: '((coab-deployment-name)).example.com'

https://bosh.io/docs/dns/#more-on-recursor_selection (1.12) details the smart mode to round-robin recursors on FQDN lookup failures.

  * Implementation
      * need to add 2 vms in coab-depls to be able to expose DNS alias/index records (/etc/hosts records with index are not resolvable from bosh-dns agent 169.xxx )

Pros:
   * a bit less latency
   * less resource consumption 

Cons:
   * inability to support load balancing or health DNS queries, hence to provide HA.
   * risk on dns recursion (no way to define different recursion policy for bosh-master or bosh-coab, both are .bosh)
   https://github.com/cloudfoundry/bosh-dns-release/blob/master/jobs/bosh-dns/spec#L106
      * higher DNS resolution times for downstream DNS recursors

## Decision

> What is the change that we're proposing and/or doing?

Spike option 0

## Consequences

> What becomes easier or more difficult to do because of this change?

Easier:
* brokers more secure
* clarify internal broker manageemnt (internal org/internal domain)

More Difficult:
* more resource consumption. Can be mitigated by reducing/removing Intranet isolation segment in the ACDC (marketplace) profile.
* additional latency (due to one addtional HTTP routing layer) for dashboard. Acceptable for dashboards.

**Comment by poblin-orange** [comment]
option 0 has been implemened in v48.

**Comment by poblin-orange** [comment]
Of interest for option 2 (dns recursion) https://github.com/cloudfoundry-community/merge-bosh-dns-release
