### ISSUE TITLE
multi-region - upgrade pipelines should avoid vpn deployments concurrent update

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#848]
### Expected behavior

* As a paas-templates operator 
* In order to 
  - have a smooth upgrade with multi-region deployments
  - not have cascade failures during upgrades

* I need 
  - the upgrade pipeline to process separatly the following deployments:
   - master-depls/r1-vpn
   - remote-r2-depls/00-bootstrap
   - remote-r3-depls/00-bootstrap
 

### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
We also need to update admin script (like pause & unpause) to ignore theses deployments.
