### ISSUE TITLE
multi-region - remote-r2 / r3 prometheus scrape error

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#856]
### Expected behavior

* As a paas-templates operator
* In order to 
  - be able to use remote-r2 / r3 prometheus metrics
* I need 
  - remote-r2 / r3 prometheus scrap works
### Observed behavior
Remote-r2 and remote-r3 grafana dashboards are empty 
### Affected releases

* 47.0.3

**Comment by poblin-orange** [comment]
Scraping has been fixed for v48.
Dashboard do not show all metrics though (related to 10min granularity?)
