### ISSUE TITLE
multi-region - ssh to vsphere r2-vpn  VM failed

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#857]
### Expected behavior

* As a paas-templates operator
* In order to 
  - be able to operate and troubleshoot Wireguard on vpn r2 VM
* I need 
  - ssh connect with ssh key from secrets

### Observed behavior

Password is asked.
 
### Affected releases

* 47.0.3

**Comment by poblin-orange** [comment]
```
    ssh  -i ~/bosh/secrets/shared/keypair/bosh.pem vcap@192.168.117.41 (R2 KO)
    ssh  -i ~/bosh/secrets/shared/keypair/bosh.pem vcap@192.168.118.41 (R3 OK)
```

Password is in shared-secrets/secrets.yml

``` yaml
secrets:
  ...
  bosh:
    root:
      decoded_password: <redacted>
```
on openstack, access as vcap is direct (need a sudo -i + bosh secret decoded password)
on vpshere, a password is required use at ssh connection time (with bosh secret decoded password)

**Comment by gberche-orange** [comment]
Starting with v54 and feature [feature-add-user-to-vms](https://github.com/orange-cloudfoundry/paas-templates-private/pull/1137), a guest account is available on bosh vms with the password available in credhub (`credhub-get /secrets/bosh_root_decoded_password`) the procedure to connect to vpn r2 is therefore

```bash
ssh -o ServerAliveInterval=30 guest@192.168.117.41
# type in password obtained through `credhub-get /secrets/bosh_root_decoded_password`
```

/CC @ogrand
