### ISSUE TITLE
Handle cold start CC capacity issue (with undercapacity minio as a blobstore)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#86]
### Expected behavior

CloudController capacity should be better instrumented so that we get an alert when we run out of CC capacity, we should contribute to https://github.com/bosh-prometheus/prometheus-boshrelease/issues/226 . Similarly high rate of apps in unhealthy/crashed should trigger alert, see #92

We should contribute prometheus monitoring and alerting:
* dashboard for minio to leverage existing [built-in minio capacity metrics](https://github.com/minio/cookbook/blob/master/docs/how-to-monitor-minio-with-prometheus.md) to be able to better diagnose capacity issues earlier, 
* triggering an alert on the minio goroutines threshold larger than 100 (value used by the [readiness proble](https://github.com/minio/minio/blob/master/docs/metrics/healthcheck/README.md#readiness-probe)), 
* add a blackbox exporter against the [minio healthcheck endpoints](https://github.com/minio/minio/blob/master/docs/metrics/healthcheck/README.md) (Liveness and Readiness probes)

Minio could be improved to support easier capacity upgrades and tuning, see https://github.com/minio/minio-boshrelease/issues/84

CloudController capacity should not be affected by slow blobstore responses. We likely need to enable the bits service, see background in the [Bits service proposal](https://docs.google.com/document/d/1kIjBuJJ0ZiJRPzMJW8dtce26jhAHbK7KotY9416YMEI/edit#)

Cf-deployment does have experimental support for bits service, see https://github.com/cloudfoundry/cf-deployment/tree/master/operations/experimental#cf-deployment-experimental-ops-files

See also [bits related merged prs and opened issues in cf-deployment](https://github.com/cloudfoundry/cf-deployment/issues?utf8=%E2%9C%93&q=bits) including https://github.com/cloudfoundry/cf-deployment/pull/132 which [seems to configure diego to download from minio using certs](https://github.com/cloudfoundry/cf-deployment/pull/132/files#diff-105dd7049a0f07e66f389f16aaac6582R66)

Additionally, diego supports limiting the number of concurrent starting containers, see https://docs.cloudfoundry.org/adminguide/diego-cell-upgrade.html#limitations-considerations and [diego property documentation](http://bosh.io/jobs/auctioneer?source=github.com/cloudfoundry/diego-release&version=2.12.0#p%3ddiego.auctioneer.starting_container_count_maximum)
> starting_container_count_maximum
> Maximum number of inflight container starts allowed globally. Value of 0 or less indicates no limit.
> Default 0

We should assign a limit (currently unlimited)

Also, we should be able to test cold start on non-prod environment with similar workload/capacity ratio than production.
   * create large number of apps
   * stop all diego cells
   * start all diego cells
   * check concurrent number of starting containers (see https://github.com/cloudfoundry/cfdot#basic-examples )  respects configured limit
   * check load on CC and blobstore minio

### Observed behavior

CloudController threads stack up, waiting for minio blobstore responses, api endpoint eventually timeout, and get restarted by monit health checks. A a result diego cells fail to download droplet, failing to start apps that enter a crashed state. 

Diego start retries over apps in a crashed state then come all in concurrent after the crashed state wait time kicks in.

### Affected release

Reproduced on version 30.0

**Comment by gberche-orange** [comment]
Refined Diego documentation w.r.t. starting container rate limit at https://github.com/cloudfoundry/docs-cf-admin/issues/126

**Comment by poblin-orange** [comment]
start rate limiting has been set. closing

**Comment by gberche-orange** [comment]
Bits service is now deprecated until cloud-native buildpacks use OCI image registry instead. See related announcement at https://lists.cloudfoundry.org/g/cf-dev/topic/discontinuation_of_the/32295676?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,32295676
