### ISSUE TITLE
Ops portal: rename JFrog into JCR 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#873]
### Expected behavior

* As a paas-templates operator
* in order to access JCR
* I need JCR to be linked in ops portal

### Observed behavior
 
![image](https://user-images.githubusercontent.com/4748380/91319130-4d999480-e7bc-11ea-8e89-7f79984ea19a.png)

### Affected releases

* 47.0.3
* earlier versions

**Comment by poblin-orange** [comment]
suggesting renaming Jfrog => JCR ?

**Comment by gberche-orange** [comment]
yes, sorry, updated the issue name

**Comment by poblin-orange** [comment]
done for v48
