### ISSUE TITLE
security filter brokers incompatible with  java buildpack 4.32.1

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#876]
### Expected behavior

* As a paas-template author
* In order to 
  * maintain the legacy OSB brokers, like static cred brokers.
* I need 
  * to assess JDK compatibilty as provided by cf 13.13.0 java buildpack

### Observed behavior
Impacted cf apps:
- intranet-proxy-sec-group-broker-filter
- internet-sec-group-broker-filter

Stacktrace when spring boot starts

```
   2020-08-26T17:02:07.30+0000 [APP/PROC/WEB/0] OUT 	... 70 common frames omitted
   2020-08-26T17:02:07.30+0000 [APP/PROC/WEB/0] OUT Caused by: java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
   2020-08-26T17:02:07.30+0000 [APP/PROC/WEB/0] OUT 	at okhttp3.internal.Jdk9Platform.trustManager(Jdk9Platform.java:78) ~[okhttp-3.3.1.jar!/:na]
   2020-08-26T17:02:07.30+0000 [APP/PROC/WEB/0] OUT 	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:554) ~[okhttp-3.3.1.jar!/:na]
   2020-08-26T17:02:07.30+0000 [APP/PROC/WEB/0] OUT 	at com.orange.cloud.servicebroker.filter.core.config.OkHttpClientConfig.squareHttpClient(OkHttpClientConfig.java:92) ~[service-br

```
 
### references
- 
- https://stackoverflow.com/questions/61458197/clientbuilder-sslsocketfactorysslsocketfactory-not-supported-on-jdk-9
- https://github.com/square/okhttp/issues/5970  seems the issue is in recent openjdk 8 with jdk 9 backport ...
- upstream issue https://github.com/orange-cloudfoundry/sec-group-broker-filter/issues/197
### Affected releases

* 48 dev
* 47.0.3 ?

### Workaround

short term:, force openjdk 8 with buildpacks:

- see https://github.com/cloudfoundry/java-buildpack#configuration-and-extension

**Comment by poblin-orange** [comment]
also affects 47.0.3 with Java Buildpack v4.29.1 (offline) ?

**Comment by gberche-orange** [comment]
Seems jdk8 is a LTS whose EOL varies among vendors according to https://en.wikipedia.org/wiki/Java_version_history


Version | Releasedate | End of FreePublic Updates[5][6] | ExtendedSupport Until
-- | -- | -- | --
[...]
Java SE 8 (LTS) | March 2014 | January 2019 for Oracle (commercial)December 2020 for Oracle (personal use)At least May 2026 for AdoptOpenJDKAt least May 2026[7] for Amazon Corretto | December 2030
Java SE 9 | September 2017 | March 2018 for OpenJDK | N/A
Java SE 10 | March 2018 | September 2018 for OpenJDK | N/A
Java SE 11 (LTS) | September 2018 | At least September 2027[7] for Amazon CorrettoOctober 2024 for AdoptOpenJDK | September 2026
Java SE 12 | March 2019 | September 2019 for OpenJDK | N/A
Java SE 13 | September 2019 | March 2020 for OpenJDK | N/A
Java SE 14 | March 2020 | September 2020 for OpenJDK | N/A
Java SE 15 | September 2020 | March 2021 for OpenJDK | N/A
Java SE 16 | March 2021 | September 2021 for OpenJDK | N/A
Java SE 17 (LTS) | September 2021 | TBA | TBA
Legend:


The java buildpack v4.29.1 outputs the following supported jdk versions
```
    Open Jdk JRE error: No version resolvable for '8.+' in 1.8.0_172, 1.8.0_181, 1.8.0_191, 1.8.0_192, 1.8.0_201, 1.8.0_202, 1.8.0_212, 1.8.0_222, 1.8.0_232, 1.8.0_242, 1.8.0_252, 1.8.0_262, 1.8.0_265, 10.0.1_10, 10.0.2_13, 11.0.0_28, 11.0.1_13, 11.0.2_07, 11.0.2_09, 11.0.3_07, 11.0.4_11, 11.0.5_10, 11.0.6_10, 11.0.7_10, 11.0.8_10, 12.0.0_33, 12.0.1_12, 12.0.2_10, 13.0.0_33, 13.0.1_09, 13.0.2_08, 14.0.0_36, 14.0.1_8, 14.0.2_13>
```
