### ISSUE TITLE
dockerhub policy update impact

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#879]
### Expected behavior

* As a paas-templates paas-templates author 
* In order to 
  * ensure no regression with dockerhub image
* I need 
  * to check the new dockerhub policy causes no issue, see https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/

### Affected releases

* x.y
* earlier versions

**Comment by poblin-orange** [comment]
Prometheus exporter https://gitlab.com/gitlab-com/marketing/corporate_marketing/developer-evangelism/code/docker-hub-limit-exporter

**Comment by obeyler** [comment]
![Uploading image.png…]()

**Comment by poblin-orange** [comment]
closing as we use generally jcr to corporate artifactory
