### ISSUE TITLE
kubeopsview multicluster

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#883]
### Expected behavior
allow from one kubeopsview to see others cluster in only one page
https://kubernetes-operational-view.readthedocs.io/en/latest/multiple-clusters.html#static-list-of-api-server-urls
### Observed behavior
Now we have one kubeopsview per cluster the idea is to have only one for each cluster
### Affected releases

all release

**Comment by poblin-orange** [comment]
implemented in 00-shared-services
