### ISSUE TITLE
SEC_ERROR_PKCS11_GENERAL_ERROR error with Firefox entreprise strategy

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#891]
### Expected behavior

* As a paas-templates operator and user
* In order to use portals and web ui components with Firefox browser
* I need to adapt web access to entreprise strategy

### Observed behavior
Since Firefox upgrade to release75, mozilla use a new feature that allow to keep client certificat in storage provided by the operating system.

Entreprise strategy defined on eBuro Firefox configuration set `security.osclientcerts.autoload` to `true` in Windows 10 registry.
(You can see this configuration by typing `about:policies` in your Firefox browser uri bar)

References:
- https://blog.mozilla.org/security/2020/04/14/expanding-client-certificates-in-firefox-75/

Combination of using >75 Firefox release with entreprise strategy generate a `SEC_ERROR_PKCS11_GENERAL_ERROR` error on browser when trying to reach uri from our pki domains.

### Analysis

By default, the Gorouter requests but does not require client certificates in TLS handshakes.
Operators may change this behavior with the property `router.client_cert_validation` by setting it to `none`.

From our use-cases, we don't need to use mutual authent on distribution websites, so we can try to deactivate this propertie.

References:
- https://docs.cloudfoundry.org/adminguide/securing-traffic.html#gorouter_mutual_auth

**Comment by ogrand** [comment]
Workaround to disable firefox autoload personal certificate :
- Set Windows registry with `regedit` key `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Preferences\security.osclientcerts.autoload` to `0`

**Comment by distortedsignal** [comment]
I fixed this issue by changing the `security.osclientcerts.autoload` value to `false` in `about:config`, but this worked great for me! Thanks for the help!
