### ISSUE TITLE
scale bosh-coab for large scale dedicated services

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#897]
### Expected behavior

* As a paas-templates operator
* In order to 
  * be able to manage more than 100 complex dedicated service (~500vm)
* I need 
  * the bosh-coab architecture to be adapted for scaling

### Observed behavior

As of v47.0.3, with a marketplace of ~60 services (each with ~4 vms), we experience cpu saturation alerts on master-depls/bosh-coab
 
### Affected releases

* 47.0.3

**Comment by gberche-orange** [comment]
@ogrand diagnosed that load is related to prometheus scrapes of the bosh exporter.

Mitigation steps:

1. reduce scrape frequency and increase scrape timeout 
1. tune bosh_exporter to reduce load on bosh director
   * measure latency and cpu impact of bosh exporter scrapes and its variants:  Deployments, Jobs, ServiceDiscovery
      * use bosh exporter metrics (possibly in a new dahsboard)
         *  bosh_scrape_errors_total
         *  bosh_last_deployments_scrape_duration_seconds
         *  bosh_last_jobs_scrape_duration_seconds
         *  bosh_last_service_discovery_scrape_duration_seconds
   * focus on vm discovery and use node exporter to scrape os metrics. See https://github.com/bosh-prometheus/bosh_exporter/blob/master/FAQ.md

> In order to get the metrics, the exporter calls the BOSH Director Instance details endpoint. This request result in potentially long running operations against each BOSH Agent, so such requests start a Director Task. Therefore, each exporter scrape will generate a new Director Task per deployment. This will NOT hurt your BOSH performance, but has the nasty effect that generates thousand of tasks per scrape (i.e. scrapping each minute will generate 1440 tasks per deployment per day).
> A longer scrape interval means less real time metrics, but for most use cases, this will be enough, specially when combined with the Node Exporter.

> How can I enable only a particular collector?
>
>The filter.collectors command flag allows you to filter what collectors will be enabled (if not set, all collectors will be enabled by default). Possible values are Deployments, Jobs, ServiceDiscovery (or a combination of them).


 * Try to limit collectors to ServiceDiscovety and Deployments in https://github.com/bosh-prometheus/prometheus-boshrelease/blob/5cc2ed7cf08f0356ff3c8245f70cd3ff52159a26/jobs/bosh_exporter/spec#L32-L33
