### ISSUE TITLE
bump gitlab ce 13.x

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#899]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to 
* I need 

### reference
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/CHANGELOG.md
- https://docs.gitlab.com/ee/update/#upgrading-to-a-new-major-version
- https://docs.gitlab.com/ee/update/#1200
- https://docs.gitlab.com/ee/update/#upgrade-paths

### Affected releases
48.x

**Comment by ogrand** [comment]
Migration to gitlab-k8s manage this item
