### ISSUE TITLE
K8S node are not stable

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#916]
### Expected behavior
K8S node need to stay enabled

### Observed behavior
some K8S node are not ready after few days (I dont know yet the reason and when). 
if we go on VM who says node not ready
monit summary say every thing is running

monit restart kubelet 
after that the node come back to ready

### Affected releases

V48

**Comment by obeyler** [comment]
The stability is also link to the bug on longhorn backup

**Comment by obeyler** [comment]
linked to issue #976

**Comment by poblin-orange** [comment]
switched to k3s bosh release, and disable longhorn as of v50.
