### ISSUE TITLE
Add script to disable a branch

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#919]
### Expected behavior

We frequently have to rename a branch feature-xxxx  to disable-feature-xxxx in order to disable this branch for coa.
Important note:  if the disable-feature-xxxx already exist this branch need to be destroyed before renaming the branch feature.
an utility script can help us to do that in both way (disable and enable branch)
the last arg will be used to specified who disable the branch

This script needs to be present on bosh cli
```disable-branch.sh feature-xxx ols```

```
git pull feature-xxx
git push origin --delete disable-ols-feature-xxx
git branch -M feature-xxx  disable-ols-feature-xxxx
git push --set-upstream  origin disable-ols-feature-xxxx
```

```enable-branch.sh  feature-xxx ols```

```
git pull disabled-ols-feature-xxx
git branch -M disable-ols-feature-xxxx feature-xxx
git push --set-upstream  origin feature-xxxx
git push origin --delete disable-ols-feature-xxx
```

**Comment by ogrand** [comment]
Add in `develop` branch for paas-template v48.0.2
