### ISSUE TITLE
Enable CF-exporter in prometheus to get CF CFAppCrashed and CFAppUnhealthy alerts

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#92]
### Expected behavior

As a paas-ops, I expect to be alerted when more than x percent of apps are in crashed state (as this likely indicates an issue on the platform).
As a paas-ops, I expect to not be alerted when than than x percent of apps are in crashed state (as this likely seldom application issue, such as an application bug or configuration issue).

cf-exporter exports metrics related to number of apps, orgs, route, services, service bindinds, spaces, security-groups, stacks

prometheus provides CF-apps state related alerts: [CFAppCrashed and CFAppUnhealthy](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/01c0c81b6cc79a853e8d54273d4882983844d4ca/jobs/cloudfoundry_alerts/templates/cf_apps.alerts.yml)

### Observed behavior

Seems we're missing the inclusion of the [monitor-cf](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/monitor-cf.yml) operator, as documented into https://github.com/bosh-prometheus/prometheus-boshrelease#monitoring-cloud-foundry

### Affected release

Reproduced on version 30.0.0

**Comment by poblin-orange** [comment]
the cf apps down alerting has been activated in v37, only for system_domain org

**Comment by poblin-orange** [comment]
no more cfar end usage.
should remove monitor cf customization and alert on all failing cf apps (if not already set)
