### ISSUE TITLE
COAB mysql MVP

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#94]
### Expected behavior

Cf-mysql with COAB 0.26 features 

### Affected release

Reproduced on version x.y

### Traces and logs

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by poblin-orange** [comment]
delivered in v37
