### ISSUE TITLE
Job ops-depls-bosh-generated / deploy-cf-redis-osb failed

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#942]
### Expected behavior

* As a paas-templates operator 
concourse job not failed
### Observed behavior
ops-depls-bosh-generated/deploy-cf-redis-osb concourse job failed

definition is missing inside:
paas-templates-private/ops-depls/template/vsphere/network-osb-cloud-operators.yml 
and vsphere/network-osb-cloud-vars-tpl.yml

### Affected releases
v48.0.1

### Traces and logs

`Task 375387 | 14:13:02 | Error: Instance group 'cf-redis-broker' references an unknown network 'tf-net-osb-data-plane-shared-pub2'  
`

**Comment by JCL38-ORANGE** [comment]
tf-net-osb-data-plane-shared-pub2 is not included in paas-templates. it is related to a custom branch.
