### ISSUE TITLE
get easily the token for kube-dashboard

### ISSUE THREAD

**Issue by obeyler** [orange-cloudfoundry/paas-templates#945]
### Expected behavior
get easily the token for kube-dashboard
add at the end of log-k8s this command
`kubectl describe secret -n kube-system $(kubectl get secret -n kube-system |grep admin|cut -d' ' -f1)|grep token:`

### Affected releases

v48.0.1

**Comment by ogrand** [comment]
Will be available in bosh-cli 2.1.44
