### ISSUE TITLE
k3s opensource community assessment

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#975]
### Expected behavior

* As a paas-templates maintainer
* In order to invest onto using k3S
* I need to assess its opensource community and quality

relates to #972 #973 #974

### Observed behavior

* [ ] k3s use cases matching paas-templates use-cases ?
* [ ] quality evaluation 
   * [ ] assess automated test coverage 
   * [ ] code review practice
* [ ] openness / community health evaluation 
   * examples of happy non paying users/contributors to k3s ?
   * public test results
   * public roadmap
   * contributing guidelines
* [ ] business model in Rancher/K3S / commercial figures 
   * marketshare
   * financials

### Affected releases

* 48.x
* earlier versions

**Comment by gberche-orange** [comment]
initial quick automated test coverage assessment as of Oct 15 2020: apparently traditional manual QA and did not yet find signs of opensource automated tests.

* https://github.com/rancher/k3s/blob/master/CONTRIBUTING.md no mention of tests
* https://drone-publish.rancher.io/rancher/k3s/890/2/3 CI runs 2 mins tests
* https://github.com/rancher/k3s/pull/2382 Update Kubernetes to v1.19.3-k3s1
* https://github.com/rancher/k3s/issues/2225
   * PM and QA review changes and understand testing efforts
* https://github.com/rancher/k3s/blob/f26785c0e21567148d6321408fe557caab928b69/.github/PULL_REQUEST_TEMPLATE.md
   * `A functional example will greatly help QA with verifying/reproducing a bug or testing new features`
* manual testing activities ???
   * https://github.com/rancher/k3s/issues/2079
   * https://github.com/rancher/k3s/labels/%5Bzube%5D%3A%20To%20Test
* Upcoming investments in test automation (possibly not yet integrated in core contributor role but as separate role)
   * https://rancher.com/careers/software-engineer-automation/
      > As an QA Automation Engineer, you will be part of a world-class engineering team. You will help improve the quality, performance, and resiliency of products like Rancher and RancherOS. You will develop comprehensive test suites and strive for full automation coverage of key product features. You will push the envelope of the technology in multiple fronts.
      > 
      > You must be knowledgeable and passionate about quality and automation. You must be well versed in dynamic languages like Python. Experience with DevOps practices and continuous integration environments will be helpful. You must be a quick learner and can get up to speed with latest Docker and Kubernetes container technologies.

**Comment by poblin-orange** [comment]
k3s now cncf graduated
