### ISSUE TITLE
Multi-level credhub ssl certs - bosh director ssl

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#98]
### Expected behavior
As a platform operator, i want to use credhub for all internal certificates

### Observed behavior
Due to credhub issue, multi-level cert are not valid, and not usable for bosh-director api ssl certs.
We dont have the issue when certs are generated by bosh cli (eg: bootstrap certs).

The fix will be provided in credhub 2 see https://github.com/pivotal-cf/credhub-release/releases/tag/2.0.0
Note: also solved on credhub 1.9.x line https://github.com/pivotal-cf/credhub-release/releases/tag/1.9.5

> Resolves an error where CredHub was creating RFC-noncompliant certs such that OpenSSL would fail to verify a leaf certificate in a three-tier or longer cert chain managed by CredHub.

As a workaround, we use custom shells for generating bosh directors TLS certs (and not credhub)

### Affected release

Reproduced on version 33.0

**Comment by poblin-orange** [comment]
bump 1.9.6 in v35. Need to test multi-level cert gen, then switch director ssl to credhub

**Comment by JCL38-ORANGE** [comment]
Tested with success on BOSH-EXPE

**Comment by poblin-orange** [comment]
generalized and merged for v41
