### ISSUE TITLE
vms/workloads on remote region (openstack-hws) take time to be updated or fail on HA/extended services

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#980]
### Expected behavior
* As a marketplace user
* In order to use quickly my dedicated HA service 
* I need a quick provisioning of my dedicated HA service 

### Observed behavior
In some cases the vms deployed in the remote region (openstack-hws) take many time to be updated and in some cases the update fails. A redeploy seems to solve the problem.

### Affected releases
v48.0.2

### Traces and logs on redis
Task 2758272 | 14:21:40 | Updating instance redis-sentinel: redis-sentinel/6339300f-4159-4c3d-84f9-36a3edde516e (0) (canary) (00:37:20)
Task 2758272 | 14:59:00 | Updating instance redis-sentinel: redis-sentinel/2612521e-abcd-4bf1-994c-ebaea5665027 (1) (00:49:45)

Task 2757604 | 12:45:01 | Updating instance redis-sentinel: redis-sentinel/b98a29e3-384a-451d-81de-8f7f994ad8b7 (0) (canary) (00:45:02)

Task 2757604 | 13:30:03 | Updating instance redis-sentinel: redis-sentinel/fc78ab37-3e62-43dd-93da-922eaae0e638 (1) (00:39:05)

                     L Error: Action Failed get_task: Task 5068ab25-18b0-4670-589e-b2302108e60a result: Preparing apply spec: Preparing package bosh-dns: Fetching package blob: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-dav cli: Running command: 'bosh-blobstore-dav -c /var/vcap/bosh/etc/blobstore-dav.json get df58484e-c24e-446e-6628-b32b5382847a /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get623585052', stdout: 'Error running app - read tcp 192.168.68.32:38202->192.168.99.155:25250: read: connection timed out', stderr: '': exit status 1

Task 2757604 | 14:09:08 | Error: Action Failed get_task: Task 5068ab25-18b0-4670-589e-b2302108e60a result: Preparing apply spec: Preparing package bosh-dns: Fetching package blob: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-dav cli: Running command: 'bosh-blobstore-dav -c /var/vcap/bosh/etc/blobstore-dav.json get df58484e-c24e-446e-6628-b32b5382847a /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get623585052', stdout: 'Error running app - read tcp 192.168.68.32:38202->192.168.99.155:25250: read: connection timed out', stderr: '': exit status 1

### Traces and logs on mysql
Task 2721873 | 15:18:40 | Updating instance arbitrator: arbitrator/a3d691ec-e625-4eff-9d1a-4f6a95711d3e (0) (canary) (00:03:00)

                     L Error: Timed out sending 'upload_blob' to instance: 'arbitrator/a3d691ec-e625-4eff-9d1a-4f6a95711d3e', agent-id: '0c8dc1ed-6924-41c7-a582-b8899f55f615' after 45 seconds

Task 2721873 | 15:21:40 | Error: Timed out sending 'upload_blob' to instance: 'arbitrator/a3d691ec-e625-4eff-9d1a-4f6a95711d3e', agent-id: '0c8dc1ed-6924-41c7-a582-b8899f55f615' after 45 seconds

**Comment by poblin-orange** [comment]
this issue was induced by activation of traffic limiting on non prod environment (1mbits).
Need to raise traffic to 10 mbits (ongoing hotfix from @ogrand )
