### ISSUE TITLE
mariadb shared service backups nodes frequently fail with mysql shield plugin

### ISSUE THREAD

**Issue by CDallosto-orange** [orange-cloudfoundry/paas-templates#986]
### Expected behavior

* I need to have consistent mariadb shared service backups

### Observed behavior

Shield backups with mysql plugin frequently fail because of the large data volume and structure changes during the generation of the MySQL dump

### Affected releases

47

**Comment by ldangeard-orange** [comment]
No solution (mylsqldump setting).
So
  - Do not make mysqldump backups during MDL operations (not possible)
  - use Xtrabackup (10.1) or MariaBackup (10.3)
