### ISSUE TITLE
harden built-in openldap (has SPOF and downtime during upgrades)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#99]
### Expected behavior
As a platform operator, i need
- a secured, up-to-date version of openldap
- industrial backup
- tls support
- possibly clustering and HA

### Observed behavior

As of v32, we rely on community openldap bosh release, with little community activity.
Shield backup of the file system and not a ldiff export (likely harder to restore backups)

### Affected release

32.0.0

### Solution outline
- [x] evaluate active community options
* https://github.com/helm/charts/tree/master/stable/openldap
* https://github.com/osixia/docker-openldap
- [ ] set up a dual configuration (bosh release AND docker service)
- [x] define migration path
 
## references
- #219 

### Traces and logs

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)

**Comment by poblin-orange** [comment]
also fix    #219

**Comment by poblin-orange** [comment]
targeting kubernetes openldap helm chart

**Comment by gberche-orange** [comment]
symptoms when openldap fails, or is stopped:
* bosh directors can't be accessed interactively by named accounts.
* gitlab git clones by concourse fail

```
Cloning into '/tmp/build/get'...
	
fatal: unable to access 'https://redacted-user:redacted-password@elpaaso-gitlab.ops-data-services.itn.intraorange/paas-template/paas-templates.git/': The requested URL returned error: 500
```

Workarounds:

* bosh directors access: use their admin accounts instead of named account

```sh
credhub api -s https://credhub.internal.paas:8844
credhub login --client-name=director_to_credhub  --client-secret=<in shared/secrets.yml#bosh_credhub_secrets)
```

**Comment by gberche-orange** [comment]
## symptoms when openldap fails, or is stopped

* bosh directors can't be accessed interactively by named accounts.

```
$ log-bosh
[...]
Failed to authenticate with UAA
```

* gitlab git clones by concourse fail

```
Cloning into '/tmp/build/get'...
	
fatal: unable to access 'https://redacted-user:redacted-password@elpaaso-gitlab.ops-data-services.redacted-domain.com/paas-template/paas-templates.git/': The requested URL returned error: 500
```

* credhub can't be accessed through UAA ldap account

## workarounds:

* credhub: connect using client id/client-secrets assigned to bosh directors:
```sh
credhub api -s https://credhub.internal.paas:8844
credhub login --client-name=director_to_credhub  --client-secret=<in shared/secrets.yml#bosh_credhub_secrets)
```

* bosh directors access: use their admin accounts instead of named account (fetching admin account from credhub)

**Comment by poblin-orange** [comment]
Reopen to see if a cluster solution could help

**Comment by poblin-orange** [comment]
as of v51, replacing bosh release wth k8s deployment
