### ISSUE TITLE
rotate expired tls certs exposed in coab service bindings 

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#993]
### Expected behavior

* As a paas-templates operator

* In order to update exposed certifcat for coab instance
- impacted services (broker provided credhub generated cert in binding)
  - mysql shared
  - mysql dedicated
  - mysql extended

NB: as of v48
 - most client do not use tls
 - mariab db jdbc drivers requires explicit fqdn check skip
 - client do skip ssl validation (global skip, just FQDN validation skip)

* I need to have a procédure for making this update. This might imply providing a single intranet PKI signed certificate in all service instances (based on a wildcard, expecting future intranet DNS use for service endpoints) 

### Observed behavior
I want also know the impact for the client when the certificat expire.

### Affected releases

* earlier versions

### references
- #203 
- #676

**Comment by JCL38-ORANGE** [comment]
will be closed with #1206
