### ISSUE TITLE
syslog_forwarder / blackbox out of memory

### ISSUE THREAD

**Issue by gcordierOrange** [orange-cloudfoundry/paas-templates#995]
### Expected behavior

* As a paas-templates operator | paas-templates maintainer
* In order to reduce the number of alarm
* I need to do not have out of memory from the blackbox process

### Observed behavior
When the log files are very large (more than 2Gb), syslog_forwarder / blackbox get a out of memory every 10 minutes.
The process is automatically restart by bosh, but it is not a good behaviour.
The issue is visible on deployment :
* prometheus / minio-s3-thanos (haproxy/sdtout.log size = 30G !!!)
* intranet-interco-relay / ops-relay (haproxy/sdtout.log size = 2G !)

### Affected releases

* 47.0.3
* earlier versions

**Comment by gcordierOrange** [comment]
An other question is why the haproxy log is too big (30G!!)
My feeling is that the log rotate process not working correctly and the file grow unlimited.

**Comment by gcordierOrange** [comment]
In addition, about the strange behaviour of le log file :
With different tools, I don't have the same result for the file size

```
minio-s3-thanos/b47d1c5c-d543-450b-b99d-e818f501bec4:/var/vcap/sys/log/haproxy$ du -h haproxy.stdout.log
2.1M	haproxy.stdout.log
minio-s3-thanos/b47d1c5c-d543-450b-b99d-e818f501bec4:/var/vcap/sys/log/haproxy$ ls -lh haproxy.stdout.log
-rw------- 1 vcap vcap 1.1G Nov  5 08:58 haproxy.stdout.log
```

**Comment by poblin-orange** [comment]
same on 48.0.2.
Thanos should be solved when removing built in minio s3 (leveraging corporate s3 for long term metrics)
Intranet interco relay might be solved by reducing verbosity level on haproxy bosh release.

**Comment by ogrand** [comment]
- [x] Thanos has be done in v50
- [] `intranet-interco-relay/ops-relay`
