### ISSUE TITLE
Mysql smoke tests should use and test TLS with java probe (maria/mysql jdbc drivers)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#997]
### Expected behavior

* As a paas-templates operator and paas-templates maintainer
* In order to make sure that mysql over TLS (see #203) is properly behaving 
* I need mysql smoke tests to use TLS 

### Observed behavior

Mysql smoke test leverage https://github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests for mysql tests however it does not yet leverage TLSs-specifics in mysql service binding:

https://github.com/cloudfoundry-attic/cf-mysql-acceptance-tests/blob/526ea62fdbd8fb4186f71cf2443b2b8fd24def65/assets/sinatra_app/main.rb#L158-L166

### references
- #993 

### Affected releases

* 49.0.x

**Comment by poblin-orange** [comment]
@gcordierOrange could you contribute the probe developped for cf

**Comment by JCL38-ORANGE** [comment]
done in https://github.com/orange-cloudfoundry/cf-mysql-acceptance-tests (tag = ssl-server)
dedicated mariadb will use this forked app with ssl-server tag in v53
